# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import Dict, Any, List

from darabonba.model import DaraModel

class ImportStacksToStackGroupRequest(DaraModel):
    def __init__(
        self,
        client_token: str = None,
        operation_description: str = None,
        operation_preferences: Dict[str, Any] = None,
        region_id: str = None,
        resource_directory_folder_ids: List[str] = None,
        stack_arns: List[str] = None,
        stack_group_name: str = None,
    ):
        # Ensures the idempotence of the request. This value is generated by the client and must be globally unique. 
        # It cannot exceed 64 characters and can include letters, numbers, hyphens (-), and underscores (_). 
        # For more information, see [How to Ensure Idempotence](https://help.aliyun.com/document_detail/134212.html).
        self.client_token = client_token
        # Description of the operation.
        self.operation_description = operation_description
        # Operation settings for importing stacks into the stack group.
        # 
        # Includes the following parameters:
        # 
        # - {"FailureToleranceCount": N}
        # 
        #   Failure tolerance count. The number of accounts in which the stack can fail in each region. If this number is exceeded, the operation in that region will stop. If the operation in one region stops, it will not continue in other regions.
        #   
        #    The range of N: 0~20.
        # 
        #    If FailureToleranceCount is not specified, the default value is 0.
        # 
        # - {"FailureTolerancePercentage": N}
        # 
        #    Failure tolerance percentage. The percentage of total accounts in which the stack can fail in each region. If this percentage is exceeded, the operation in that region will stop.
        # 
        #    The range of N: 0~100. If the percentage is not an integer, ROS will round down.
        # 
        #    If FailureTolerancePercentage is not specified, the default value is 0.
        # 
        # - {"MaxConcurrentCount": N}
        # 
        #    Maximum concurrent account count. The number of accounts in which the stack can be deployed simultaneously in each region.
        # 
        #    The range of N: 1~20.
        # 
        #    If MaxConcurrentCount is not specified, the default value is 1.
        # 
        # - {"MaxConcurrentPercentage": N} Maximum concurrent account percentage.
        # 
        #    The percentage of total accounts in which the stack can be deployed simultaneously in each region.
        # 
        #    The range of N: 1~100. If the percentage is not an integer, ROS will round down.
        # 
        #    If MaxConcurrentPercentage is not specified, the default value is 1.
        # - {"RegionConcurrencyType": N}
        # Region-level concurrency type for deploying stack instances, values:
        #      - SEQUENTIAL (default): Deploy sequentially in each specified region, only one region at a time.
        # 
        #      - PARALLEL: Deploy in parallel across all specified regions.
        # 
        # Multiple parameters are separated by commas (,).
        # 
        # > - Do not specify both MaxConcurrentCount and MaxConcurrentPercentage.  
        # >- Do not specify both FailureToleranceCount and FailureTolerancePercentage.
        self.operation_preferences = operation_preferences
        # The region ID of the stack group. You can call [DescribeRegions](https://help.aliyun.com/document_detail/131035.html) to view the latest list of Alibaba Cloud regions.
        # 
        # This parameter is required.
        self.region_id = region_id
        # A list of resource directory folder IDs for the stacks to be imported. A maximum of 10 folders can be added.
        self.resource_directory_folder_ids = resource_directory_folder_ids
        # A list of ARNs for the stacks to be imported into the stack group, in the format `acs:ros:${RegionId}:${AccountId}:stack/${StackId}`. A maximum of 10 stacks can be added.
        # 
        # This parameter is required.
        self.stack_arns = stack_arns
        # The name of the stack group. The name must be unique within a single region. It cannot exceed 255 characters and must start with a letter or number, and can include letters, numbers, hyphens (-), and underscores (_).
        # 
        # This parameter is required.
        self.stack_group_name = stack_group_name

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.client_token is not None:
            result['ClientToken'] = self.client_token

        if self.operation_description is not None:
            result['OperationDescription'] = self.operation_description

        if self.operation_preferences is not None:
            result['OperationPreferences'] = self.operation_preferences

        if self.region_id is not None:
            result['RegionId'] = self.region_id

        if self.resource_directory_folder_ids is not None:
            result['ResourceDirectoryFolderIds'] = self.resource_directory_folder_ids

        if self.stack_arns is not None:
            result['StackArns'] = self.stack_arns

        if self.stack_group_name is not None:
            result['StackGroupName'] = self.stack_group_name

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ClientToken') is not None:
            self.client_token = m.get('ClientToken')

        if m.get('OperationDescription') is not None:
            self.operation_description = m.get('OperationDescription')

        if m.get('OperationPreferences') is not None:
            self.operation_preferences = m.get('OperationPreferences')

        if m.get('RegionId') is not None:
            self.region_id = m.get('RegionId')

        if m.get('ResourceDirectoryFolderIds') is not None:
            self.resource_directory_folder_ids = m.get('ResourceDirectoryFolderIds')

        if m.get('StackArns') is not None:
            self.stack_arns = m.get('StackArns')

        if m.get('StackGroupName') is not None:
            self.stack_group_name = m.get('StackGroupName')

        return self

