# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from alibabacloud_ecd20200930 import models as main_models
from darabonba.model import DaraModel

class GetAsyncTaskResponseBody(DaraModel):
    def __init__(
        self,
        code: str = None,
        data: main_models.GetAsyncTaskResponseBodyData = None,
        request_id: str = None,
        success: str = None,
    ):
        # The operation result. If the request was successful, a success message is returned. If the request failed, an error message is returned.
        self.code = code
        # The data information.
        self.data = data
        # The request ID.
        self.request_id = request_id
        # Indicates whether the request was successful. Valid values:
        self.success = success

    def validate(self):
        if self.data:
            self.data.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.code is not None:
            result['Code'] = self.code

        if self.data is not None:
            result['Data'] = self.data.to_map()

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.success is not None:
            result['Success'] = self.success

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Code') is not None:
            self.code = m.get('Code')

        if m.get('Data') is not None:
            temp_model = main_models.GetAsyncTaskResponseBodyData()
            self.data = temp_model.from_map(m.get('Data'))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Success') is not None:
            self.success = m.get('Success')

        return self

class GetAsyncTaskResponseBodyData(DaraModel):
    def __init__(
        self,
        async_task_id: str = None,
        consumed_process: str = None,
        err_code: int = None,
        message: str = None,
        status: str = None,
        total_process: int = None,
        url: str = None,
    ):
        # The asynchronous task ID.
        self.async_task_id = async_task_id
        # The total number of asynchronous tasks that are processed. Example: the number of files that are packaged and downloaded on the server.
        self.consumed_process = consumed_process
        # The error code of the asynchronous task.
        self.err_code = err_code
        # The error message of the asynchronous task.
        self.message = message
        # The task status.
        # 
        # Valid values:
        # 
        # *   Failed: The task failed.
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        # *   Running: The task was running.
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        # *   PartialSucceed: The task did not completely succeed.
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        # *   Succeed: The task succeeded.
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        # 
        #     <!-- -->
        self.status = status
        # The total number of asynchronous tasks to be processed, such as the amount of files to be downloaded and packaged on the server.
        self.total_process = total_process
        # The URL to download data generated by the asynchronous task. Example: the URL to package and download tasks on the server.
        self.url = url

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.async_task_id is not None:
            result['AsyncTaskId'] = self.async_task_id

        if self.consumed_process is not None:
            result['ConsumedProcess'] = self.consumed_process

        if self.err_code is not None:
            result['ErrCode'] = self.err_code

        if self.message is not None:
            result['Message'] = self.message

        if self.status is not None:
            result['Status'] = self.status

        if self.total_process is not None:
            result['TotalProcess'] = self.total_process

        if self.url is not None:
            result['Url'] = self.url

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AsyncTaskId') is not None:
            self.async_task_id = m.get('AsyncTaskId')

        if m.get('ConsumedProcess') is not None:
            self.consumed_process = m.get('ConsumedProcess')

        if m.get('ErrCode') is not None:
            self.err_code = m.get('ErrCode')

        if m.get('Message') is not None:
            self.message = m.get('Message')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('TotalProcess') is not None:
            self.total_process = m.get('TotalProcess')

        if m.get('Url') is not None:
            self.url = m.get('Url')

        return self

