# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from ._add_user_to_vpc_endpoint_service_request import AddUserToVpcEndpointServiceRequest
from ._add_user_to_vpc_endpoint_service_response_body import AddUserToVpcEndpointServiceResponseBody
from ._add_user_to_vpc_endpoint_service_response import AddUserToVpcEndpointServiceResponse
from ._add_zone_to_vpc_endpoint_request import AddZoneToVpcEndpointRequest
from ._add_zone_to_vpc_endpoint_response_body import AddZoneToVpcEndpointResponseBody
from ._add_zone_to_vpc_endpoint_response import AddZoneToVpcEndpointResponse
from ._attach_resource_to_vpc_endpoint_service_request import AttachResourceToVpcEndpointServiceRequest
from ._attach_resource_to_vpc_endpoint_service_response_body import AttachResourceToVpcEndpointServiceResponseBody
from ._attach_resource_to_vpc_endpoint_service_response import AttachResourceToVpcEndpointServiceResponse
from ._attach_security_group_to_vpc_endpoint_request import AttachSecurityGroupToVpcEndpointRequest
from ._attach_security_group_to_vpc_endpoint_response_body import AttachSecurityGroupToVpcEndpointResponseBody
from ._attach_security_group_to_vpc_endpoint_response import AttachSecurityGroupToVpcEndpointResponse
from ._change_resource_group_request import ChangeResourceGroupRequest
from ._change_resource_group_response_body import ChangeResourceGroupResponseBody
from ._change_resource_group_response import ChangeResourceGroupResponse
from ._check_product_open_response_body import CheckProductOpenResponseBody
from ._check_product_open_response import CheckProductOpenResponse
from ._create_vpc_endpoint_request import CreateVpcEndpointRequest
from ._create_vpc_endpoint_response_body import CreateVpcEndpointResponseBody
from ._create_vpc_endpoint_response import CreateVpcEndpointResponse
from ._create_vpc_endpoint_service_request import CreateVpcEndpointServiceRequest
from ._create_vpc_endpoint_service_response_body import CreateVpcEndpointServiceResponseBody
from ._create_vpc_endpoint_service_response import CreateVpcEndpointServiceResponse
from ._delete_vpc_endpoint_request import DeleteVpcEndpointRequest
from ._delete_vpc_endpoint_response_body import DeleteVpcEndpointResponseBody
from ._delete_vpc_endpoint_response import DeleteVpcEndpointResponse
from ._delete_vpc_endpoint_service_request import DeleteVpcEndpointServiceRequest
from ._delete_vpc_endpoint_service_response_body import DeleteVpcEndpointServiceResponseBody
from ._delete_vpc_endpoint_service_response import DeleteVpcEndpointServiceResponse
from ._describe_regions_request import DescribeRegionsRequest
from ._describe_regions_response_body import DescribeRegionsResponseBody
from ._describe_regions_response import DescribeRegionsResponse
from ._describe_zones_request import DescribeZonesRequest
from ._describe_zones_response_body import DescribeZonesResponseBody
from ._describe_zones_response import DescribeZonesResponse
from ._detach_resource_from_vpc_endpoint_service_request import DetachResourceFromVpcEndpointServiceRequest
from ._detach_resource_from_vpc_endpoint_service_response_body import DetachResourceFromVpcEndpointServiceResponseBody
from ._detach_resource_from_vpc_endpoint_service_response import DetachResourceFromVpcEndpointServiceResponse
from ._detach_security_group_from_vpc_endpoint_request import DetachSecurityGroupFromVpcEndpointRequest
from ._detach_security_group_from_vpc_endpoint_response_body import DetachSecurityGroupFromVpcEndpointResponseBody
from ._detach_security_group_from_vpc_endpoint_response import DetachSecurityGroupFromVpcEndpointResponse
from ._disable_vpc_endpoint_connection_request import DisableVpcEndpointConnectionRequest
from ._disable_vpc_endpoint_connection_response_body import DisableVpcEndpointConnectionResponseBody
from ._disable_vpc_endpoint_connection_response import DisableVpcEndpointConnectionResponse
from ._disable_vpc_endpoint_zone_connection_request import DisableVpcEndpointZoneConnectionRequest
from ._disable_vpc_endpoint_zone_connection_response_body import DisableVpcEndpointZoneConnectionResponseBody
from ._disable_vpc_endpoint_zone_connection_response import DisableVpcEndpointZoneConnectionResponse
from ._enable_vpc_endpoint_connection_request import EnableVpcEndpointConnectionRequest
from ._enable_vpc_endpoint_connection_response_body import EnableVpcEndpointConnectionResponseBody
from ._enable_vpc_endpoint_connection_response import EnableVpcEndpointConnectionResponse
from ._enable_vpc_endpoint_zone_connection_request import EnableVpcEndpointZoneConnectionRequest
from ._enable_vpc_endpoint_zone_connection_response_body import EnableVpcEndpointZoneConnectionResponseBody
from ._enable_vpc_endpoint_zone_connection_response import EnableVpcEndpointZoneConnectionResponse
from ._get_vpc_endpoint_attribute_request import GetVpcEndpointAttributeRequest
from ._get_vpc_endpoint_attribute_response_body import GetVpcEndpointAttributeResponseBody
from ._get_vpc_endpoint_attribute_response import GetVpcEndpointAttributeResponse
from ._get_vpc_endpoint_service_attribute_request import GetVpcEndpointServiceAttributeRequest
from ._get_vpc_endpoint_service_attribute_response_body import GetVpcEndpointServiceAttributeResponseBody
from ._get_vpc_endpoint_service_attribute_response import GetVpcEndpointServiceAttributeResponse
from ._list_tag_resources_request import ListTagResourcesRequest
from ._list_tag_resources_response_body import ListTagResourcesResponseBody
from ._list_tag_resources_response import ListTagResourcesResponse
from ._list_vpc_endpoint_connections_request import ListVpcEndpointConnectionsRequest
from ._list_vpc_endpoint_connections_response_body import ListVpcEndpointConnectionsResponseBody
from ._list_vpc_endpoint_connections_response import ListVpcEndpointConnectionsResponse
from ._list_vpc_endpoint_security_groups_request import ListVpcEndpointSecurityGroupsRequest
from ._list_vpc_endpoint_security_groups_response_body import ListVpcEndpointSecurityGroupsResponseBody
from ._list_vpc_endpoint_security_groups_response import ListVpcEndpointSecurityGroupsResponse
from ._list_vpc_endpoint_service_resources_request import ListVpcEndpointServiceResourcesRequest
from ._list_vpc_endpoint_service_resources_response_body import ListVpcEndpointServiceResourcesResponseBody
from ._list_vpc_endpoint_service_resources_response import ListVpcEndpointServiceResourcesResponse
from ._list_vpc_endpoint_service_users_request import ListVpcEndpointServiceUsersRequest
from ._list_vpc_endpoint_service_users_response_body import ListVpcEndpointServiceUsersResponseBody
from ._list_vpc_endpoint_service_users_response import ListVpcEndpointServiceUsersResponse
from ._list_vpc_endpoint_services_request import ListVpcEndpointServicesRequest
from ._list_vpc_endpoint_services_response_body import ListVpcEndpointServicesResponseBody
from ._list_vpc_endpoint_services_response import ListVpcEndpointServicesResponse
from ._list_vpc_endpoint_services_by_end_user_request import ListVpcEndpointServicesByEndUserRequest
from ._list_vpc_endpoint_services_by_end_user_response_body import ListVpcEndpointServicesByEndUserResponseBody
from ._list_vpc_endpoint_services_by_end_user_response import ListVpcEndpointServicesByEndUserResponse
from ._list_vpc_endpoint_zones_request import ListVpcEndpointZonesRequest
from ._list_vpc_endpoint_zones_response_body import ListVpcEndpointZonesResponseBody
from ._list_vpc_endpoint_zones_response import ListVpcEndpointZonesResponse
from ._list_vpc_endpoints_request import ListVpcEndpointsRequest
from ._list_vpc_endpoints_response_body import ListVpcEndpointsResponseBody
from ._list_vpc_endpoints_response import ListVpcEndpointsResponse
from ._open_private_link_service_request import OpenPrivateLinkServiceRequest
from ._open_private_link_service_response_body import OpenPrivateLinkServiceResponseBody
from ._open_private_link_service_response import OpenPrivateLinkServiceResponse
from ._remove_user_from_vpc_endpoint_service_request import RemoveUserFromVpcEndpointServiceRequest
from ._remove_user_from_vpc_endpoint_service_response_body import RemoveUserFromVpcEndpointServiceResponseBody
from ._remove_user_from_vpc_endpoint_service_response import RemoveUserFromVpcEndpointServiceResponse
from ._remove_zone_from_vpc_endpoint_request import RemoveZoneFromVpcEndpointRequest
from ._remove_zone_from_vpc_endpoint_response_body import RemoveZoneFromVpcEndpointResponseBody
from ._remove_zone_from_vpc_endpoint_response import RemoveZoneFromVpcEndpointResponse
from ._tag_resources_request import TagResourcesRequest
from ._tag_resources_response_body import TagResourcesResponseBody
from ._tag_resources_response import TagResourcesResponse
from ._untag_resources_request import UntagResourcesRequest
from ._untag_resources_response_body import UntagResourcesResponseBody
from ._untag_resources_response import UntagResourcesResponse
from ._update_vpc_endpoint_attribute_request import UpdateVpcEndpointAttributeRequest
from ._update_vpc_endpoint_attribute_response_body import UpdateVpcEndpointAttributeResponseBody
from ._update_vpc_endpoint_attribute_response import UpdateVpcEndpointAttributeResponse
from ._update_vpc_endpoint_connection_attribute_request import UpdateVpcEndpointConnectionAttributeRequest
from ._update_vpc_endpoint_connection_attribute_response_body import UpdateVpcEndpointConnectionAttributeResponseBody
from ._update_vpc_endpoint_connection_attribute_response import UpdateVpcEndpointConnectionAttributeResponse
from ._update_vpc_endpoint_service_attribute_request import UpdateVpcEndpointServiceAttributeRequest
from ._update_vpc_endpoint_service_attribute_response_body import UpdateVpcEndpointServiceAttributeResponseBody
from ._update_vpc_endpoint_service_attribute_response import UpdateVpcEndpointServiceAttributeResponse
from ._update_vpc_endpoint_service_resource_attribute_request import UpdateVpcEndpointServiceResourceAttributeRequest
from ._update_vpc_endpoint_service_resource_attribute_response_body import UpdateVpcEndpointServiceResourceAttributeResponseBody
from ._update_vpc_endpoint_service_resource_attribute_response import UpdateVpcEndpointServiceResourceAttributeResponse
from ._update_vpc_endpoint_zone_connection_resource_attribute_request import UpdateVpcEndpointZoneConnectionResourceAttributeRequest
from ._update_vpc_endpoint_zone_connection_resource_attribute_response_body import UpdateVpcEndpointZoneConnectionResourceAttributeResponseBody
from ._update_vpc_endpoint_zone_connection_resource_attribute_response import UpdateVpcEndpointZoneConnectionResourceAttributeResponse
from ._create_vpc_endpoint_request import CreateVpcEndpointRequestTag
from ._create_vpc_endpoint_request import CreateVpcEndpointRequestZone
from ._create_vpc_endpoint_service_request import CreateVpcEndpointServiceRequestResource
from ._create_vpc_endpoint_service_request import CreateVpcEndpointServiceRequestTag
from ._create_vpc_endpoint_service_response_body import CreateVpcEndpointServiceResponseBodySupportedRegionSet
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegionsRegionServiceResourceTypes
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegionsRegion
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegions
from ._describe_zones_response_body import DescribeZonesResponseBodyZonesZone
from ._describe_zones_response_body import DescribeZonesResponseBodyZones
from ._get_vpc_endpoint_service_attribute_response_body import GetVpcEndpointServiceAttributeResponseBodySupportedRegionSet
from ._list_tag_resources_request import ListTagResourcesRequestTag
from ._list_tag_resources_response_body import ListTagResourcesResponseBodyTagResources
from ._list_vpc_endpoint_connections_response_body import ListVpcEndpointConnectionsResponseBodyConnectionsZones
from ._list_vpc_endpoint_connections_response_body import ListVpcEndpointConnectionsResponseBodyConnections
from ._list_vpc_endpoint_security_groups_response_body import ListVpcEndpointSecurityGroupsResponseBodySecurityGroups
from ._list_vpc_endpoint_service_resources_response_body import ListVpcEndpointServiceResourcesResponseBodyResources
from ._list_vpc_endpoint_service_users_response_body import ListVpcEndpointServiceUsersResponseBodyUserARNs
from ._list_vpc_endpoint_service_users_response_body import ListVpcEndpointServiceUsersResponseBodyUsers
from ._list_vpc_endpoint_services_request import ListVpcEndpointServicesRequestTag
from ._list_vpc_endpoint_services_response_body import ListVpcEndpointServicesResponseBodyServicesSupportedRegionSet
from ._list_vpc_endpoint_services_response_body import ListVpcEndpointServicesResponseBodyServicesTags
from ._list_vpc_endpoint_services_response_body import ListVpcEndpointServicesResponseBodyServices
from ._list_vpc_endpoint_services_by_end_user_request import ListVpcEndpointServicesByEndUserRequestTag
from ._list_vpc_endpoint_services_by_end_user_response_body import ListVpcEndpointServicesByEndUserResponseBodyServicesTags
from ._list_vpc_endpoint_services_by_end_user_response_body import ListVpcEndpointServicesByEndUserResponseBodyServices
from ._list_vpc_endpoint_zones_response_body import ListVpcEndpointZonesResponseBodyZones
from ._list_vpc_endpoints_request import ListVpcEndpointsRequestTag
from ._list_vpc_endpoints_response_body import ListVpcEndpointsResponseBodyEndpointsTags
from ._list_vpc_endpoints_response_body import ListVpcEndpointsResponseBodyEndpoints
from ._tag_resources_request import TagResourcesRequestTag

__all__ = [
    AddUserToVpcEndpointServiceRequest,
    AddUserToVpcEndpointServiceResponseBody,
    AddUserToVpcEndpointServiceResponse,
    AddZoneToVpcEndpointRequest,
    AddZoneToVpcEndpointResponseBody,
    AddZoneToVpcEndpointResponse,
    AttachResourceToVpcEndpointServiceRequest,
    AttachResourceToVpcEndpointServiceResponseBody,
    AttachResourceToVpcEndpointServiceResponse,
    AttachSecurityGroupToVpcEndpointRequest,
    AttachSecurityGroupToVpcEndpointResponseBody,
    AttachSecurityGroupToVpcEndpointResponse,
    ChangeResourceGroupRequest,
    ChangeResourceGroupResponseBody,
    ChangeResourceGroupResponse,
    CheckProductOpenResponseBody,
    CheckProductOpenResponse,
    CreateVpcEndpointRequest,
    CreateVpcEndpointResponseBody,
    CreateVpcEndpointResponse,
    CreateVpcEndpointServiceRequest,
    CreateVpcEndpointServiceResponseBody,
    CreateVpcEndpointServiceResponse,
    DeleteVpcEndpointRequest,
    DeleteVpcEndpointResponseBody,
    DeleteVpcEndpointResponse,
    DeleteVpcEndpointServiceRequest,
    DeleteVpcEndpointServiceResponseBody,
    DeleteVpcEndpointServiceResponse,
    DescribeRegionsRequest,
    DescribeRegionsResponseBody,
    DescribeRegionsResponse,
    DescribeZonesRequest,
    DescribeZonesResponseBody,
    DescribeZonesResponse,
    DetachResourceFromVpcEndpointServiceRequest,
    DetachResourceFromVpcEndpointServiceResponseBody,
    DetachResourceFromVpcEndpointServiceResponse,
    DetachSecurityGroupFromVpcEndpointRequest,
    DetachSecurityGroupFromVpcEndpointResponseBody,
    DetachSecurityGroupFromVpcEndpointResponse,
    DisableVpcEndpointConnectionRequest,
    DisableVpcEndpointConnectionResponseBody,
    DisableVpcEndpointConnectionResponse,
    DisableVpcEndpointZoneConnectionRequest,
    DisableVpcEndpointZoneConnectionResponseBody,
    DisableVpcEndpointZoneConnectionResponse,
    EnableVpcEndpointConnectionRequest,
    EnableVpcEndpointConnectionResponseBody,
    EnableVpcEndpointConnectionResponse,
    EnableVpcEndpointZoneConnectionRequest,
    EnableVpcEndpointZoneConnectionResponseBody,
    EnableVpcEndpointZoneConnectionResponse,
    GetVpcEndpointAttributeRequest,
    GetVpcEndpointAttributeResponseBody,
    GetVpcEndpointAttributeResponse,
    GetVpcEndpointServiceAttributeRequest,
    GetVpcEndpointServiceAttributeResponseBody,
    GetVpcEndpointServiceAttributeResponse,
    ListTagResourcesRequest,
    ListTagResourcesResponseBody,
    ListTagResourcesResponse,
    ListVpcEndpointConnectionsRequest,
    ListVpcEndpointConnectionsResponseBody,
    ListVpcEndpointConnectionsResponse,
    ListVpcEndpointSecurityGroupsRequest,
    ListVpcEndpointSecurityGroupsResponseBody,
    ListVpcEndpointSecurityGroupsResponse,
    ListVpcEndpointServiceResourcesRequest,
    ListVpcEndpointServiceResourcesResponseBody,
    ListVpcEndpointServiceResourcesResponse,
    ListVpcEndpointServiceUsersRequest,
    ListVpcEndpointServiceUsersResponseBody,
    ListVpcEndpointServiceUsersResponse,
    ListVpcEndpointServicesRequest,
    ListVpcEndpointServicesResponseBody,
    ListVpcEndpointServicesResponse,
    ListVpcEndpointServicesByEndUserRequest,
    ListVpcEndpointServicesByEndUserResponseBody,
    ListVpcEndpointServicesByEndUserResponse,
    ListVpcEndpointZonesRequest,
    ListVpcEndpointZonesResponseBody,
    ListVpcEndpointZonesResponse,
    ListVpcEndpointsRequest,
    ListVpcEndpointsResponseBody,
    ListVpcEndpointsResponse,
    OpenPrivateLinkServiceRequest,
    OpenPrivateLinkServiceResponseBody,
    OpenPrivateLinkServiceResponse,
    RemoveUserFromVpcEndpointServiceRequest,
    RemoveUserFromVpcEndpointServiceResponseBody,
    RemoveUserFromVpcEndpointServiceResponse,
    RemoveZoneFromVpcEndpointRequest,
    RemoveZoneFromVpcEndpointResponseBody,
    RemoveZoneFromVpcEndpointResponse,
    TagResourcesRequest,
    TagResourcesResponseBody,
    TagResourcesResponse,
    UntagResourcesRequest,
    UntagResourcesResponseBody,
    UntagResourcesResponse,
    UpdateVpcEndpointAttributeRequest,
    UpdateVpcEndpointAttributeResponseBody,
    UpdateVpcEndpointAttributeResponse,
    UpdateVpcEndpointConnectionAttributeRequest,
    UpdateVpcEndpointConnectionAttributeResponseBody,
    UpdateVpcEndpointConnectionAttributeResponse,
    UpdateVpcEndpointServiceAttributeRequest,
    UpdateVpcEndpointServiceAttributeResponseBody,
    UpdateVpcEndpointServiceAttributeResponse,
    UpdateVpcEndpointServiceResourceAttributeRequest,
    UpdateVpcEndpointServiceResourceAttributeResponseBody,
    UpdateVpcEndpointServiceResourceAttributeResponse,
    UpdateVpcEndpointZoneConnectionResourceAttributeRequest,
    UpdateVpcEndpointZoneConnectionResourceAttributeResponseBody,
    UpdateVpcEndpointZoneConnectionResourceAttributeResponse,
    CreateVpcEndpointRequestTag,
    CreateVpcEndpointRequestZone,
    CreateVpcEndpointServiceRequestResource,
    CreateVpcEndpointServiceRequestTag,
    CreateVpcEndpointServiceResponseBodySupportedRegionSet,
    DescribeRegionsResponseBodyRegionsRegionServiceResourceTypes,
    DescribeRegionsResponseBodyRegionsRegion,
    DescribeRegionsResponseBodyRegions,
    DescribeZonesResponseBodyZonesZone,
    DescribeZonesResponseBodyZones,
    GetVpcEndpointServiceAttributeResponseBodySupportedRegionSet,
    ListTagResourcesRequestTag,
    ListTagResourcesResponseBodyTagResources,
    ListVpcEndpointConnectionsResponseBodyConnectionsZones,
    ListVpcEndpointConnectionsResponseBodyConnections,
    ListVpcEndpointSecurityGroupsResponseBodySecurityGroups,
    ListVpcEndpointServiceResourcesResponseBodyResources,
    ListVpcEndpointServiceUsersResponseBodyUserARNs,
    ListVpcEndpointServiceUsersResponseBodyUsers,
    ListVpcEndpointServicesRequestTag,
    ListVpcEndpointServicesResponseBodyServicesSupportedRegionSet,
    ListVpcEndpointServicesResponseBodyServicesTags,
    ListVpcEndpointServicesResponseBodyServices,
    ListVpcEndpointServicesByEndUserRequestTag,
    ListVpcEndpointServicesByEndUserResponseBodyServicesTags,
    ListVpcEndpointServicesByEndUserResponseBodyServices,
    ListVpcEndpointZonesResponseBodyZones,
    ListVpcEndpointsRequestTag,
    ListVpcEndpointsResponseBodyEndpointsTags,
    ListVpcEndpointsResponseBodyEndpoints,
    TagResourcesRequestTag
]
