# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from alibabacloud_agentcore20260804 import models as main_models
from darabonba.model import DaraModel

class CreateUserResponseBody(DaraModel):
    def __init__(
        self,
        code: str = None,
        data: main_models.CreateUserResponseBodyData = None,
        http_status_code: int = None,
        message: str = None,
        request_id: str = None,
        success: bool = None,
    ):
        # The business status code.
        self.code = code
        # The information about the created user.
        self.data = data
        # The HTTP status code.
        self.http_status_code = http_status_code
        # The response message. An error description is returned if the request fails.
        self.message = message
        # The request ID.
        self.request_id = request_id
        # Indicates whether the request was successful.
        self.success = success

    def validate(self):
        if self.data:
            self.data.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.code is not None:
            result['code'] = self.code

        if self.data is not None:
            result['data'] = self.data.to_map()

        if self.http_status_code is not None:
            result['httpStatusCode'] = self.http_status_code

        if self.message is not None:
            result['message'] = self.message

        if self.request_id is not None:
            result['requestId'] = self.request_id

        if self.success is not None:
            result['success'] = self.success

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('code') is not None:
            self.code = m.get('code')

        if m.get('data') is not None:
            temp_model = main_models.CreateUserResponseBodyData()
            self.data = temp_model.from_map(m.get('data'))

        if m.get('httpStatusCode') is not None:
            self.http_status_code = m.get('httpStatusCode')

        if m.get('message') is not None:
            self.message = m.get('message')

        if m.get('requestId') is not None:
            self.request_id = m.get('requestId')

        if m.get('success') is not None:
            self.success = m.get('success')

        return self

class CreateUserResponseBodyData(DaraModel):
    def __init__(
        self,
        agent_core_user_id: str = None,
        auth_method: str = None,
        created_at: str = None,
        display_name: str = None,
        email: str = None,
        initial_password: str = None,
        name: str = None,
        note: str = None,
        region_id: str = None,
        status: str = None,
        updated_at: str = None,
        workspace_id: str = None,
    ):
        # The user ID.
        self.agent_core_user_id = agent_core_user_id
        # The authentication method of the user. A value of password indicates local password authentication within the workspace. Values of dingtalk and feishu indicate that the user is synchronized and authenticated by the corresponding external identity provider.
        self.auth_method = auth_method
        # The time when the user was created, in UTC and RFC 3339 format.
        self.created_at = created_at
        # The display name of the user. The display name must be 1 to 32 characters in length.
        self.display_name = display_name
        # The email address of the user. The email address can be up to 256 characters in length.
        self.email = email
        # The initial password of the user. If password was specified during creation, the specified password is returned. If password was not specified, a random password generated by the server is returned.
        self.initial_password = initial_password
        # The username. The username is unique within the workspace and can contain only lowercase letters, digits, and hyphens. It must start and end with a lowercase letter or digit and be 1 to 32 characters in length.
        self.name = name
        # The remarks of the user. The remarks can be up to 1024 characters in length.
        self.note = note
        # The region ID of the resource.
        self.region_id = region_id
        # The user status. Valid values: Creating, Active, Updating, Deleting, Failed, and DeleteFailed.
        self.status = status
        # The time when the user was last modified, in UTC and RFC 3339 format.
        self.updated_at = updated_at
        # The workspace ID.
        self.workspace_id = workspace_id

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.agent_core_user_id is not None:
            result['agentCoreUserId'] = self.agent_core_user_id

        if self.auth_method is not None:
            result['authMethod'] = self.auth_method

        if self.created_at is not None:
            result['createdAt'] = self.created_at

        if self.display_name is not None:
            result['displayName'] = self.display_name

        if self.email is not None:
            result['email'] = self.email

        if self.initial_password is not None:
            result['initialPassword'] = self.initial_password

        if self.name is not None:
            result['name'] = self.name

        if self.note is not None:
            result['note'] = self.note

        if self.region_id is not None:
            result['regionId'] = self.region_id

        if self.status is not None:
            result['status'] = self.status

        if self.updated_at is not None:
            result['updatedAt'] = self.updated_at

        if self.workspace_id is not None:
            result['workspaceId'] = self.workspace_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('agentCoreUserId') is not None:
            self.agent_core_user_id = m.get('agentCoreUserId')

        if m.get('authMethod') is not None:
            self.auth_method = m.get('authMethod')

        if m.get('createdAt') is not None:
            self.created_at = m.get('createdAt')

        if m.get('displayName') is not None:
            self.display_name = m.get('displayName')

        if m.get('email') is not None:
            self.email = m.get('email')

        if m.get('initialPassword') is not None:
            self.initial_password = m.get('initialPassword')

        if m.get('name') is not None:
            self.name = m.get('name')

        if m.get('note') is not None:
            self.note = m.get('note')

        if m.get('regionId') is not None:
            self.region_id = m.get('regionId')

        if m.get('status') is not None:
            self.status = m.get('status')

        if m.get('updatedAt') is not None:
            self.updated_at = m.get('updatedAt')

        if m.get('workspaceId') is not None:
            self.workspace_id = m.get('workspaceId')

        return self

