# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class DeletePipelinesRequest(DaraModel):
    def __init__(
        self,
        client_token: str = None,
        pipeline_ids: str = None,
    ):
        # A client token that is used to ensure the idempotence of the request. The value is generated by the client and must be unique among different requests. The value can contain up to 64 ASCII characters.
        self.client_token = client_token
        # The pipeline ID.
        self.pipeline_ids = pipeline_ids

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.client_token is not None:
            result['ClientToken'] = self.client_token

        if self.pipeline_ids is not None:
            result['pipelineIds'] = self.pipeline_ids

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ClientToken') is not None:
            self.client_token = m.get('ClientToken')

        if m.get('pipelineIds') is not None:
            self.pipeline_ids = m.get('pipelineIds')

        return self

