# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from alibabacloud_elasticsearch20170613 import models as main_models
from darabonba.model import DaraModel

class UpdateInstanceChargeTypeRequest(DaraModel):
    def __init__(
        self,
        payment_info: main_models.UpdateInstanceChargeTypeRequestPaymentInfo = None,
        payment_type: str = None,
        client_token: str = None,
    ):
        self.payment_info = payment_info
        self.payment_type = payment_type
        # A unique token generated by the client to guarantee the idempotency of the request. You can use the client to generate the value, but you must ensure that it is unique among different requests. The token can only contain ASCII characters and cannot exceed 64 characters in length.
        self.client_token = client_token

    def validate(self):
        if self.payment_info:
            self.payment_info.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.payment_info is not None:
            result['paymentInfo'] = self.payment_info.to_map()

        if self.payment_type is not None:
            result['paymentType'] = self.payment_type

        if self.client_token is not None:
            result['clientToken'] = self.client_token

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('paymentInfo') is not None:
            temp_model = main_models.UpdateInstanceChargeTypeRequestPaymentInfo()
            self.payment_info = temp_model.from_map(m.get('paymentInfo'))

        if m.get('paymentType') is not None:
            self.payment_type = m.get('paymentType')

        if m.get('clientToken') is not None:
            self.client_token = m.get('clientToken')

        return self

class UpdateInstanceChargeTypeRequestPaymentInfo(DaraModel):
    def __init__(
        self,
        duration: int = None,
        pricing_cycle: str = None,
    ):
        self.duration = duration
        self.pricing_cycle = pricing_cycle

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.duration is not None:
            result['duration'] = self.duration

        if self.pricing_cycle is not None:
            result['pricingCycle'] = self.pricing_cycle

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('duration') is not None:
            self.duration = m.get('duration')

        if m.get('pricingCycle') is not None:
            self.pricing_cycle = m.get('pricingCycle')

        return self

