# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class UpdatePipelinesRequest(DaraModel):
    def __init__(
        self,
        body: str = None,
        client_token: str = None,
        trigger: bool = None,
    ):
        self.body = body
        # A unique token used to ensure idempotence. This parameter value is generated by the client and must be unique across different requests. The value can be up to 64 ASCII characters in length.
        self.client_token = client_token
        # Specifies whether to immediately deploy the pipeline.
        self.trigger = trigger

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.body is not None:
            result['body'] = self.body

        if self.client_token is not None:
            result['clientToken'] = self.client_token

        if self.trigger is not None:
            result['trigger'] = self.trigger

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('body') is not None:
            self.body = m.get('body')

        if m.get('clientToken') is not None:
            self.client_token = m.get('clientToken')

        if m.get('trigger') is not None:
            self.trigger = m.get('trigger')

        return self

