# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_outboundbot20191226 import models as main_models
from darabonba.model import DaraModel

class ListJobsResponseBody(DaraModel):
    def __init__(
        self,
        code: str = None,
        http_status_code: int = None,
        jobs: List[main_models.ListJobsResponseBodyJobs] = None,
        message: str = None,
        request_id: str = None,
        success: bool = None,
    ):
        # API status code
        self.code = code
        # HTTP status code
        self.http_status_code = http_status_code
        # Job array
        self.jobs = jobs
        # API message
        self.message = message
        # Request ID
        self.request_id = request_id
        # Indicates whether the request succeeded
        self.success = success

    def validate(self):
        if self.jobs:
            for v1 in self.jobs:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.code is not None:
            result['Code'] = self.code

        if self.http_status_code is not None:
            result['HttpStatusCode'] = self.http_status_code

        result['Jobs'] = []
        if self.jobs is not None:
            for k1 in self.jobs:
                result['Jobs'].append(k1.to_map() if k1 else None)

        if self.message is not None:
            result['Message'] = self.message

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.success is not None:
            result['Success'] = self.success

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Code') is not None:
            self.code = m.get('Code')

        if m.get('HttpStatusCode') is not None:
            self.http_status_code = m.get('HttpStatusCode')

        self.jobs = []
        if m.get('Jobs') is not None:
            for k1 in m.get('Jobs'):
                temp_model = main_models.ListJobsResponseBodyJobs()
                self.jobs.append(temp_model.from_map(k1))

        if m.get('Message') is not None:
            self.message = m.get('Message')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Success') is not None:
            self.success = m.get('Success')

        return self

class ListJobsResponseBodyJobs(DaraModel):
    def __init__(
        self,
        calling_numbers: List[str] = None,
        contacts: List[main_models.ListJobsResponseBodyJobsContacts] = None,
        extras: List[main_models.ListJobsResponseBodyJobsExtras] = None,
        failure_reason: str = None,
        job_group_id: str = None,
        job_id: str = None,
        priority: int = None,
        reference_id: str = None,
        scenario_id: str = None,
        status: str = None,
        strategy_id: str = None,
        summary: List[main_models.ListJobsResponseBodyJobsSummary] = None,
        system_priority: int = None,
        tasks: List[main_models.ListJobsResponseBodyJobsTasks] = None,
    ):
        # Calling number list
        self.calling_numbers = calling_numbers
        # Contact list
        self.contacts = contacts
        # Business parameter list.
        # 
        # > TenantId and ServiceId are generated by the system. All other parameters are custom.
        self.extras = extras
        # Failure reason
        self.failure_reason = failure_reason
        # Job group ID
        self.job_group_id = job_group_id
        # Job ID
        self.job_id = job_id
        # Job priority
        self.priority = priority
        # Business ID for the job. Defined by the business party.
        # 
        # > This is the uploaded ContactId value.
        self.reference_id = reference_id
        # Business ID
        self.scenario_id = scenario_id
        # Job status. Valid values:
        # 
        # - **Scheduling**: Scheduling.
        # 
        # - **Executing**: Running.
        # 
        # - **Succeeded**: Succeeded.
        # 
        # - **Paused**: Suspended.
        # 
        # - **Failed**: Failed.
        # 
        # - **Cancelled**: Cancelled.
        # 
        # - **Drafted**: Draft.
        self.status = status
        # Strategy ID
        self.strategy_id = strategy_id
        # Conversation business tag data:
        # 
        # In Large Language Model (LLM) scenarios: Tag hit data after conversation ends.
        # 
        # In small model scenarios: Variable values after conversation ends.
        self.summary = summary
        # System priority
        self.system_priority = system_priority
        # Task list
        self.tasks = tasks

    def validate(self):
        if self.contacts:
            for v1 in self.contacts:
                 if v1:
                    v1.validate()
        if self.extras:
            for v1 in self.extras:
                 if v1:
                    v1.validate()
        if self.summary:
            for v1 in self.summary:
                 if v1:
                    v1.validate()
        if self.tasks:
            for v1 in self.tasks:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.calling_numbers is not None:
            result['CallingNumbers'] = self.calling_numbers

        result['Contacts'] = []
        if self.contacts is not None:
            for k1 in self.contacts:
                result['Contacts'].append(k1.to_map() if k1 else None)

        result['Extras'] = []
        if self.extras is not None:
            for k1 in self.extras:
                result['Extras'].append(k1.to_map() if k1 else None)

        if self.failure_reason is not None:
            result['FailureReason'] = self.failure_reason

        if self.job_group_id is not None:
            result['JobGroupId'] = self.job_group_id

        if self.job_id is not None:
            result['JobId'] = self.job_id

        if self.priority is not None:
            result['Priority'] = self.priority

        if self.reference_id is not None:
            result['ReferenceId'] = self.reference_id

        if self.scenario_id is not None:
            result['ScenarioId'] = self.scenario_id

        if self.status is not None:
            result['Status'] = self.status

        if self.strategy_id is not None:
            result['StrategyId'] = self.strategy_id

        result['Summary'] = []
        if self.summary is not None:
            for k1 in self.summary:
                result['Summary'].append(k1.to_map() if k1 else None)

        if self.system_priority is not None:
            result['SystemPriority'] = self.system_priority

        result['Tasks'] = []
        if self.tasks is not None:
            for k1 in self.tasks:
                result['Tasks'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('CallingNumbers') is not None:
            self.calling_numbers = m.get('CallingNumbers')

        self.contacts = []
        if m.get('Contacts') is not None:
            for k1 in m.get('Contacts'):
                temp_model = main_models.ListJobsResponseBodyJobsContacts()
                self.contacts.append(temp_model.from_map(k1))

        self.extras = []
        if m.get('Extras') is not None:
            for k1 in m.get('Extras'):
                temp_model = main_models.ListJobsResponseBodyJobsExtras()
                self.extras.append(temp_model.from_map(k1))

        if m.get('FailureReason') is not None:
            self.failure_reason = m.get('FailureReason')

        if m.get('JobGroupId') is not None:
            self.job_group_id = m.get('JobGroupId')

        if m.get('JobId') is not None:
            self.job_id = m.get('JobId')

        if m.get('Priority') is not None:
            self.priority = m.get('Priority')

        if m.get('ReferenceId') is not None:
            self.reference_id = m.get('ReferenceId')

        if m.get('ScenarioId') is not None:
            self.scenario_id = m.get('ScenarioId')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('StrategyId') is not None:
            self.strategy_id = m.get('StrategyId')

        self.summary = []
        if m.get('Summary') is not None:
            for k1 in m.get('Summary'):
                temp_model = main_models.ListJobsResponseBodyJobsSummary()
                self.summary.append(temp_model.from_map(k1))

        if m.get('SystemPriority') is not None:
            self.system_priority = m.get('SystemPriority')

        self.tasks = []
        if m.get('Tasks') is not None:
            for k1 in m.get('Tasks'):
                temp_model = main_models.ListJobsResponseBodyJobsTasks()
                self.tasks.append(temp_model.from_map(k1))

        return self

class ListJobsResponseBodyJobsTasks(DaraModel):
    def __init__(
        self,
        actual_time: int = None,
        brief: str = None,
        call_id: str = None,
        called_number: str = None,
        calling_number: str = None,
        chatbot_id: str = None,
        contact: main_models.ListJobsResponseBodyJobsTasksContact = None,
        conversation: List[main_models.ListJobsResponseBodyJobsTasksConversation] = None,
        duration: int = None,
        job_id: str = None,
        planed_time: int = None,
        scenario_id: str = None,
        status: str = None,
        task_id: str = None,
    ):
        # Actual execution time
        self.actual_time = actual_time
        # Business result. Legacy parameter. Deprecated.
        self.brief = brief
        # Call ID
        self.call_id = call_id
        # Called number
        self.called_number = called_number
        # Calling number
        self.calling_number = calling_number
        # Chatbot ID
        self.chatbot_id = chatbot_id
        # Contact for the task
        self.contact = contact
        # Conversation list
        self.conversation = conversation
        # The duration of the task.
        self.duration = duration
        # Job ID
        self.job_id = job_id
        # Scheduled execution time
        self.planed_time = planed_time
        # Scenario ID. Legacy parameter. Deprecated.
        self.scenario_id = scenario_id
        # Note: The **Succeeded** status is now split into specific reasons. The generic **Succeeded**: 1 (Connected) status is no longer returned. Instead, specific reason types are returned.
        # 
        # - **Executing**: 0 (Dialing).
        # 
        # - **Succeeded**: 1 (Connected).
        # 
        # - **NoAnswer**: 2 (Not connected — No answer).
        # 
        # - **NotExist**: 3 (Not connected — Nonexistent number).
        # 
        # - **Busy**: 4 (Not connected — Busy).
        # 
        # - **Cancelled**: 5 (Not dialed — Task stopped).
        # 
        # - **Failed**: 6 (Failed).
        # 
        # - **NotConnected**: 7 (Not connected — Unreachable).
        # 
        # - **PoweredOff**: 8 (Not connected — Powered off).
        # 
        # - **OutOfService**: 9 (Not connected — Out of service).
        # 
        # - **InArrears**: 10 (Not connected — Overdue payment).
        # 
        # - **EmptyNumber**: 11 (Not dialed — Empty number).
        # 
        # - **PerDayCallCountLimit**: 12 (Not dialed — Daily call limit exceeded).
        # 
        # - **ContactBlockList**: 13 (Not dialed — Blacklisted).
        # 
        # - **CallerNotRegistered**: 14 (Not dialed — Caller number not registered).
        # 
        # - **Terminated**: 15 (Not dialed — Terminated).
        # 
        # - **VerificationCancelled**: 16 (Not dialed — Verification failed before call).
        # 
        # - **OutOfServiceNoCall**: 17 (Not dialed — Out of service).
        # 
        # - **InArrearsNoCall**: 18 (Not dialed — Overdue payment).
        # 
        # - **CallingNumberNotExist**: 19 (Not dialed — Caller number does not exist).
        # 
        # - **SucceededFinish**: 20 (Connected — Normal end).
        # 
        # - **SucceededChatbotHangUpAfterNoAnswer**: 21 (Connected — Bot hung up after no recognition).
        # 
        # - **SucceededChatbotHangUpAfterSilence**: 22 (Connected — Bot hung up after silence timeout).
        # 
        # - **SucceededClientHangUpAfterNoAnswer**: 23 (Connected — User hung up after no recognition).
        # 
        # - **SucceededClientHangUp**: 24 (Connected — User hung up without reason).
        # 
        # - **SucceededTransferByIntent**: 25 (Connected — Transferred to agent after intent match).
        # 
        # - **SucceededTransferAfterNoAnswer**: 26 (Connected — Transferred to agent after no recognition).
        # 
        # - **SucceededInoInterAction**: 27 (Connected — No interaction from user side).
        # 
        # - **SucceededError**: 28 (Connected — System error interrupted).
        # 
        # - **SucceededSpecialInterceptVoiceAssistant**: 29 (Connected — Intercepted for special case — Voice assistant).
        # 
        # - **SucceededSpecialInterceptExtensionNumberTransfer**: 30 (Connected — Intercepted for special case — Extension transfer).
        # 
        # - **SucceededSpecialInterceptCustomSpecialIntercept**: 31 (Connected — Intercepted for special case — Custom interception).
        # 
        # - **HighRiskSipCode**: 32 (Not dialed — High risk).
        self.status = status
        # Task ID
        self.task_id = task_id

    def validate(self):
        if self.contact:
            self.contact.validate()
        if self.conversation:
            for v1 in self.conversation:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.actual_time is not None:
            result['ActualTime'] = self.actual_time

        if self.brief is not None:
            result['Brief'] = self.brief

        if self.call_id is not None:
            result['CallId'] = self.call_id

        if self.called_number is not None:
            result['CalledNumber'] = self.called_number

        if self.calling_number is not None:
            result['CallingNumber'] = self.calling_number

        if self.chatbot_id is not None:
            result['ChatbotId'] = self.chatbot_id

        if self.contact is not None:
            result['Contact'] = self.contact.to_map()

        result['Conversation'] = []
        if self.conversation is not None:
            for k1 in self.conversation:
                result['Conversation'].append(k1.to_map() if k1 else None)

        if self.duration is not None:
            result['Duration'] = self.duration

        if self.job_id is not None:
            result['JobId'] = self.job_id

        if self.planed_time is not None:
            result['PlanedTime'] = self.planed_time

        if self.scenario_id is not None:
            result['ScenarioId'] = self.scenario_id

        if self.status is not None:
            result['Status'] = self.status

        if self.task_id is not None:
            result['TaskId'] = self.task_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ActualTime') is not None:
            self.actual_time = m.get('ActualTime')

        if m.get('Brief') is not None:
            self.brief = m.get('Brief')

        if m.get('CallId') is not None:
            self.call_id = m.get('CallId')

        if m.get('CalledNumber') is not None:
            self.called_number = m.get('CalledNumber')

        if m.get('CallingNumber') is not None:
            self.calling_number = m.get('CallingNumber')

        if m.get('ChatbotId') is not None:
            self.chatbot_id = m.get('ChatbotId')

        if m.get('Contact') is not None:
            temp_model = main_models.ListJobsResponseBodyJobsTasksContact()
            self.contact = temp_model.from_map(m.get('Contact'))

        self.conversation = []
        if m.get('Conversation') is not None:
            for k1 in m.get('Conversation'):
                temp_model = main_models.ListJobsResponseBodyJobsTasksConversation()
                self.conversation.append(temp_model.from_map(k1))

        if m.get('Duration') is not None:
            self.duration = m.get('Duration')

        if m.get('JobId') is not None:
            self.job_id = m.get('JobId')

        if m.get('PlanedTime') is not None:
            self.planed_time = m.get('PlanedTime')

        if m.get('ScenarioId') is not None:
            self.scenario_id = m.get('ScenarioId')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('TaskId') is not None:
            self.task_id = m.get('TaskId')

        return self

class ListJobsResponseBodyJobsTasksConversation(DaraModel):
    def __init__(
        self,
        script: str = None,
        speaker: str = None,
        summary: List[main_models.ListJobsResponseBodyJobsTasksConversationSummary] = None,
        timestamp: int = None,
    ):
        # Conversation text
        self.script = script
        # Who spoke: Robot or Contact
        self.speaker = speaker
        # Summary information. Deprecated.
        self.summary = summary
        # Timestamp when the conversation text was stored
        self.timestamp = timestamp

    def validate(self):
        if self.summary:
            for v1 in self.summary:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.script is not None:
            result['Script'] = self.script

        if self.speaker is not None:
            result['Speaker'] = self.speaker

        result['Summary'] = []
        if self.summary is not None:
            for k1 in self.summary:
                result['Summary'].append(k1.to_map() if k1 else None)

        if self.timestamp is not None:
            result['Timestamp'] = self.timestamp

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Script') is not None:
            self.script = m.get('Script')

        if m.get('Speaker') is not None:
            self.speaker = m.get('Speaker')

        self.summary = []
        if m.get('Summary') is not None:
            for k1 in m.get('Summary'):
                temp_model = main_models.ListJobsResponseBodyJobsTasksConversationSummary()
                self.summary.append(temp_model.from_map(k1))

        if m.get('Timestamp') is not None:
            self.timestamp = m.get('Timestamp')

        return self

class ListJobsResponseBodyJobsTasksConversationSummary(DaraModel):
    def __init__(
        self,
        category: str = None,
        content: str = None,
        summary_name: str = None,
    ):
        # Category
        self.category = category
        # Summary content
        self.content = content
        # Summary name
        self.summary_name = summary_name

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.category is not None:
            result['Category'] = self.category

        if self.content is not None:
            result['Content'] = self.content

        if self.summary_name is not None:
            result['SummaryName'] = self.summary_name

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Category') is not None:
            self.category = m.get('Category')

        if m.get('Content') is not None:
            self.content = m.get('Content')

        if m.get('SummaryName') is not None:
            self.summary_name = m.get('SummaryName')

        return self

class ListJobsResponseBodyJobsTasksContact(DaraModel):
    def __init__(
        self,
        contact_id: str = None,
        contact_name: str = None,
        honorific: str = None,
        job_id: str = None,
        phone_number: str = None,
        reference_id: str = None,
        role: str = None,
        state: str = None,
    ):
        # Contact ID
        self.contact_id = contact_id
        # Contact name
        self.contact_name = contact_name
        # Honorific. If empty, defaults to the contact name.
        self.honorific = honorific
        # Job ID. Deprecated.
        self.job_id = job_id
        # Phone number
        self.phone_number = phone_number
        # Third-party system ID for the contact
        self.reference_id = reference_id
        # Role
        self.role = role
        # Status
        self.state = state

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.contact_id is not None:
            result['ContactId'] = self.contact_id

        if self.contact_name is not None:
            result['ContactName'] = self.contact_name

        if self.honorific is not None:
            result['Honorific'] = self.honorific

        if self.job_id is not None:
            result['JobId'] = self.job_id

        if self.phone_number is not None:
            result['PhoneNumber'] = self.phone_number

        if self.reference_id is not None:
            result['ReferenceId'] = self.reference_id

        if self.role is not None:
            result['Role'] = self.role

        if self.state is not None:
            result['State'] = self.state

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ContactId') is not None:
            self.contact_id = m.get('ContactId')

        if m.get('ContactName') is not None:
            self.contact_name = m.get('ContactName')

        if m.get('Honorific') is not None:
            self.honorific = m.get('Honorific')

        if m.get('JobId') is not None:
            self.job_id = m.get('JobId')

        if m.get('PhoneNumber') is not None:
            self.phone_number = m.get('PhoneNumber')

        if m.get('ReferenceId') is not None:
            self.reference_id = m.get('ReferenceId')

        if m.get('Role') is not None:
            self.role = m.get('Role')

        if m.get('State') is not None:
            self.state = m.get('State')

        return self

class ListJobsResponseBodyJobsSummary(DaraModel):
    def __init__(
        self,
        category: str = None,
        content: str = None,
        summary_name: str = None,
    ):
        # Conversation summary category
        self.category = category
        # Tag value
        self.content = content
        # Tag name
        self.summary_name = summary_name

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.category is not None:
            result['Category'] = self.category

        if self.content is not None:
            result['Content'] = self.content

        if self.summary_name is not None:
            result['SummaryName'] = self.summary_name

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Category') is not None:
            self.category = m.get('Category')

        if m.get('Content') is not None:
            self.content = m.get('Content')

        if m.get('SummaryName') is not None:
            self.summary_name = m.get('SummaryName')

        return self

class ListJobsResponseBodyJobsExtras(DaraModel):
    def __init__(
        self,
        key: str = None,
        value: str = None,
    ):
        # Business parameter key
        self.key = key
        # Business parameter value
        self.value = value

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.key is not None:
            result['Key'] = self.key

        if self.value is not None:
            result['Value'] = self.value

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Key') is not None:
            self.key = m.get('Key')

        if m.get('Value') is not None:
            self.value = m.get('Value')

        return self

class ListJobsResponseBodyJobsContacts(DaraModel):
    def __init__(
        self,
        contact_id: str = None,
        contact_name: str = None,
        honorific: str = None,
        job_id: str = None,
        phone_number: str = None,
        reference_id: str = None,
        role: str = None,
        state: str = None,
    ):
        # Contact ID. Generated by the system.
        self.contact_id = contact_id
        # Contact name
        self.contact_name = contact_name
        # Honorific. Same as the contact name.
        self.honorific = honorific
        # Job ID. Deprecated.
        self.job_id = job_id
        # Phone number
        self.phone_number = phone_number
        # Third-party system ID for the contact
        self.reference_id = reference_id
        # Contact role. Deprecated.
        self.role = role
        # Status. Deprecated.
        self.state = state

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.contact_id is not None:
            result['ContactId'] = self.contact_id

        if self.contact_name is not None:
            result['ContactName'] = self.contact_name

        if self.honorific is not None:
            result['Honorific'] = self.honorific

        if self.job_id is not None:
            result['JobId'] = self.job_id

        if self.phone_number is not None:
            result['PhoneNumber'] = self.phone_number

        if self.reference_id is not None:
            result['ReferenceId'] = self.reference_id

        if self.role is not None:
            result['Role'] = self.role

        if self.state is not None:
            result['State'] = self.state

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ContactId') is not None:
            self.contact_id = m.get('ContactId')

        if m.get('ContactName') is not None:
            self.contact_name = m.get('ContactName')

        if m.get('Honorific') is not None:
            self.honorific = m.get('Honorific')

        if m.get('JobId') is not None:
            self.job_id = m.get('JobId')

        if m.get('PhoneNumber') is not None:
            self.phone_number = m.get('PhoneNumber')

        if m.get('ReferenceId') is not None:
            self.reference_id = m.get('ReferenceId')

        if m.get('Role') is not None:
            self.role = m.get('Role')

        if m.get('State') is not None:
            self.state = m.get('State')

        return self

