# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class ModifyDeviceInfoRequest(DaraModel):
    def __init__(
        self,
        biz_type: str = None,
        device_id: str = None,
        duration: str = None,
        expired_day: str = None,
        user_device_id: str = None,
    ):
        # The updated business type. The value can be up to 64 characters in length. This parameter is defined by the requester and can be used to add remarks for specific business scenarios, such as different facial recognition usage scenarios or customer identifiers for pending deliveries.
        self.biz_type = biz_type
        # The unique ID generated by the ID Verification server for the device of the requester. This ID is generated only after the device is successfully activated. You can obtain this ID by calling the getLicenseExtraInfo function in the offline facial recognition SDK.
        # 
        # This parameter is required.
        self.device_id = device_id
        # The period by which to extend the device expiration time. Unit: years. Valid values: 1 to 100. A value of 100 indicates permanent use. One year is calculated as 365 days.
        self.duration = duration
        # The expiration time of the current device. An error is returned if the expiration date is incorrect (differs from the expiration time recorded on the ID Verification server by more than one week).
        # > You can query the expiration time by calling the DescribeDeviceInfo operation. An error is returned if the expiration date is incorrect. This validation ensures that the requester does not accidentally reactivate a device due to misoperations, which would unnecessarily consume authorization quotas.
        self.expired_day = expired_day
        # The updated user device ID. The value can be up to 64 characters in length. This parameter is defined by the requester and can be used to identify a specific device. We recommend that you use the physical device number.
        self.user_device_id = user_device_id

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.biz_type is not None:
            result['BizType'] = self.biz_type

        if self.device_id is not None:
            result['DeviceId'] = self.device_id

        if self.duration is not None:
            result['Duration'] = self.duration

        if self.expired_day is not None:
            result['ExpiredDay'] = self.expired_day

        if self.user_device_id is not None:
            result['UserDeviceId'] = self.user_device_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('BizType') is not None:
            self.biz_type = m.get('BizType')

        if m.get('DeviceId') is not None:
            self.device_id = m.get('DeviceId')

        if m.get('Duration') is not None:
            self.duration = m.get('Duration')

        if m.get('ExpiredDay') is not None:
            self.expired_day = m.get('ExpiredDay')

        if m.get('UserDeviceId') is not None:
            self.user_device_id = m.get('UserDeviceId')

        return self

