# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from ._create_config_request import CreateConfigRequest
from ._create_config_response_body import CreateConfigResponseBody
from ._create_config_response import CreateConfigResponse
from ._create_data_limit_request import CreateDataLimitRequest
from ._create_data_limit_response_body import CreateDataLimitResponseBody
from ._create_data_limit_response import CreateDataLimitResponse
from ._create_rule_request import CreateRuleRequest
from ._create_rule_response_body import CreateRuleResponseBody
from ._create_rule_response import CreateRuleResponse
from ._create_scan_task_request import CreateScanTaskRequest
from ._create_scan_task_response_body import CreateScanTaskResponseBody
from ._create_scan_task_response import CreateScanTaskResponse
from ._create_slr_role_request import CreateSlrRoleRequest
from ._create_slr_role_response_body import CreateSlrRoleResponseBody
from ._create_slr_role_response import CreateSlrRoleResponse
from ._delete_data_limit_request import DeleteDataLimitRequest
from ._delete_data_limit_response_body import DeleteDataLimitResponseBody
from ._delete_data_limit_response import DeleteDataLimitResponse
from ._delete_rule_request import DeleteRuleRequest
from ._delete_rule_response_body import DeleteRuleResponseBody
from ._delete_rule_response import DeleteRuleResponse
from ._describe_audit_logs_request import DescribeAuditLogsRequest
from ._describe_audit_logs_response_body import DescribeAuditLogsResponseBody
from ._describe_audit_logs_response import DescribeAuditLogsResponse
from ._describe_category_template_list_request import DescribeCategoryTemplateListRequest
from ._describe_category_template_list_response_body import DescribeCategoryTemplateListResponseBody
from ._describe_category_template_list_response import DescribeCategoryTemplateListResponse
from ._describe_category_template_rule_list_request import DescribeCategoryTemplateRuleListRequest
from ._describe_category_template_rule_list_response_body import DescribeCategoryTemplateRuleListResponseBody
from ._describe_category_template_rule_list_response import DescribeCategoryTemplateRuleListResponse
from ._describe_columns_request import DescribeColumnsRequest
from ._describe_columns_response_body import DescribeColumnsResponseBody
from ._describe_columns_response import DescribeColumnsResponse
from ._describe_columns_v2request import DescribeColumnsV2Request
from ._describe_columns_v2response_body import DescribeColumnsV2ResponseBody
from ._describe_columns_v2response import DescribeColumnsV2Response
from ._describe_configs_request import DescribeConfigsRequest
from ._describe_configs_response_body import DescribeConfigsResponseBody
from ._describe_configs_response import DescribeConfigsResponse
from ._describe_data_assets_request import DescribeDataAssetsRequest
from ._describe_data_assets_response_body import DescribeDataAssetsResponseBody
from ._describe_data_assets_response import DescribeDataAssetsResponse
from ._describe_data_limit_detail_request import DescribeDataLimitDetailRequest
from ._describe_data_limit_detail_response_body import DescribeDataLimitDetailResponseBody
from ._describe_data_limit_detail_response import DescribeDataLimitDetailResponse
from ._describe_data_limit_set_request import DescribeDataLimitSetRequest
from ._describe_data_limit_set_response_body import DescribeDataLimitSetResponseBody
from ._describe_data_limit_set_response import DescribeDataLimitSetResponse
from ._describe_data_limits_request import DescribeDataLimitsRequest
from ._describe_data_limits_response_body import DescribeDataLimitsResponseBody
from ._describe_data_limits_response import DescribeDataLimitsResponse
from ._describe_data_masking_run_history_request import DescribeDataMaskingRunHistoryRequest
from ._describe_data_masking_run_history_response_body import DescribeDataMaskingRunHistoryResponseBody
from ._describe_data_masking_run_history_response import DescribeDataMaskingRunHistoryResponse
from ._describe_data_masking_tasks_request import DescribeDataMaskingTasksRequest
from ._describe_data_masking_tasks_response_body import DescribeDataMaskingTasksResponseBody
from ._describe_data_masking_tasks_response import DescribeDataMaskingTasksResponse
from ._describe_data_object_column_detail_request import DescribeDataObjectColumnDetailRequest
from ._describe_data_object_column_detail_response_body import DescribeDataObjectColumnDetailResponseBody
from ._describe_data_object_column_detail_response import DescribeDataObjectColumnDetailResponse
from ._describe_data_object_column_detail_v2request import DescribeDataObjectColumnDetailV2Request
from ._describe_data_object_column_detail_v2response_body import DescribeDataObjectColumnDetailV2ResponseBody
from ._describe_data_object_column_detail_v2response import DescribeDataObjectColumnDetailV2Response
from ._describe_data_objects_request import DescribeDataObjectsRequest
from ._describe_data_objects_response_body import DescribeDataObjectsResponseBody
from ._describe_data_objects_response import DescribeDataObjectsResponse
from ._describe_doc_types_request import DescribeDocTypesRequest
from ._describe_doc_types_response_body import DescribeDocTypesResponseBody
from ._describe_doc_types_response import DescribeDocTypesResponse
from ._describe_event_detail_request import DescribeEventDetailRequest
from ._describe_event_detail_response_body import DescribeEventDetailResponseBody
from ._describe_event_detail_response import DescribeEventDetailResponse
from ._describe_event_types_request import DescribeEventTypesRequest
from ._describe_event_types_response_body import DescribeEventTypesResponseBody
from ._describe_event_types_response import DescribeEventTypesResponse
from ._describe_events_request import DescribeEventsRequest
from ._describe_events_response_body import DescribeEventsResponseBody
from ._describe_events_response import DescribeEventsResponse
from ._describe_identify_task_status_request import DescribeIdentifyTaskStatusRequest
from ._describe_identify_task_status_response_body import DescribeIdentifyTaskStatusResponseBody
from ._describe_identify_task_status_response import DescribeIdentifyTaskStatusResponse
from ._describe_instance_sources_request import DescribeInstanceSourcesRequest
from ._describe_instance_sources_response_body import DescribeInstanceSourcesResponseBody
from ._describe_instance_sources_response import DescribeInstanceSourcesResponse
from ._describe_instances_request import DescribeInstancesRequest
from ._describe_instances_response_body import DescribeInstancesResponseBody
from ._describe_instances_response import DescribeInstancesResponse
from ._describe_oss_object_detail_request import DescribeOssObjectDetailRequest
from ._describe_oss_object_detail_response_body import DescribeOssObjectDetailResponseBody
from ._describe_oss_object_detail_response import DescribeOssObjectDetailResponse
from ._describe_oss_object_detail_v2request import DescribeOssObjectDetailV2Request
from ._describe_oss_object_detail_v2response_body import DescribeOssObjectDetailV2ResponseBody
from ._describe_oss_object_detail_v2response import DescribeOssObjectDetailV2Response
from ._describe_oss_objects_request import DescribeOssObjectsRequest
from ._describe_oss_objects_response_body import DescribeOssObjectsResponseBody
from ._describe_oss_objects_response import DescribeOssObjectsResponse
from ._describe_packages_request import DescribePackagesRequest
from ._describe_packages_response_body import DescribePackagesResponseBody
from ._describe_packages_response import DescribePackagesResponse
from ._describe_parent_instance_request import DescribeParentInstanceRequest
from ._describe_parent_instance_response_body import DescribeParentInstanceResponseBody
from ._describe_parent_instance_response import DescribeParentInstanceResponse
from ._describe_risk_levels_request import DescribeRiskLevelsRequest
from ._describe_risk_levels_response_body import DescribeRiskLevelsResponseBody
from ._describe_risk_levels_response import DescribeRiskLevelsResponse
from ._describe_rules_request import DescribeRulesRequest
from ._describe_rules_response_body import DescribeRulesResponseBody
from ._describe_rules_response import DescribeRulesResponse
from ._describe_tables_request import DescribeTablesRequest
from ._describe_tables_response_body import DescribeTablesResponseBody
from ._describe_tables_response import DescribeTablesResponse
from ._describe_template_all_rules_request import DescribeTemplateAllRulesRequest
from ._describe_template_all_rules_response_body import DescribeTemplateAllRulesResponseBody
from ._describe_template_all_rules_response import DescribeTemplateAllRulesResponse
from ._describe_user_status_request import DescribeUserStatusRequest
from ._describe_user_status_response_body import DescribeUserStatusResponseBody
from ._describe_user_status_response import DescribeUserStatusResponse
from ._disable_user_config_request import DisableUserConfigRequest
from ._disable_user_config_response_body import DisableUserConfigResponseBody
from ._disable_user_config_response import DisableUserConfigResponse
from ._exec_datamask_request import ExecDatamaskRequest
from ._exec_datamask_response_body import ExecDatamaskResponseBody
from ._exec_datamask_response import ExecDatamaskResponse
from ._manual_trigger_masking_process_request import ManualTriggerMaskingProcessRequest
from ._manual_trigger_masking_process_response_body import ManualTriggerMaskingProcessResponseBody
from ._manual_trigger_masking_process_response import ManualTriggerMaskingProcessResponse
from ._mask_oss_image_request import MaskOssImageRequest
from ._mask_oss_image_response_body import MaskOssImageResponseBody
from ._mask_oss_image_response import MaskOssImageResponse
from ._modify_data_limit_request import ModifyDataLimitRequest
from ._modify_data_limit_response_body import ModifyDataLimitResponseBody
from ._modify_data_limit_response import ModifyDataLimitResponse
from ._modify_default_level_request import ModifyDefaultLevelRequest
from ._modify_default_level_response_body import ModifyDefaultLevelResponseBody
from ._modify_default_level_response import ModifyDefaultLevelResponse
from ._modify_event_status_request import ModifyEventStatusRequest
from ._modify_event_status_response_body import ModifyEventStatusResponseBody
from ._modify_event_status_response import ModifyEventStatusResponse
from ._modify_event_type_status_request import ModifyEventTypeStatusRequest
from ._modify_event_type_status_response_body import ModifyEventTypeStatusResponseBody
from ._modify_event_type_status_response import ModifyEventTypeStatusResponse
from ._modify_report_task_status_request import ModifyReportTaskStatusRequest
from ._modify_report_task_status_response_body import ModifyReportTaskStatusResponseBody
from ._modify_report_task_status_response import ModifyReportTaskStatusResponse
from ._modify_rule_request import ModifyRuleRequest
from ._modify_rule_response_body import ModifyRuleResponseBody
from ._modify_rule_response import ModifyRuleResponse
from ._modify_rule_status_request import ModifyRuleStatusRequest
from ._modify_rule_status_response_body import ModifyRuleStatusResponseBody
from ._modify_rule_status_response import ModifyRuleStatusResponse
from ._restore_oss_image_request import RestoreOssImageRequest
from ._restore_oss_image_response_body import RestoreOssImageResponseBody
from ._restore_oss_image_response import RestoreOssImageResponse
from ._scan_oss_object_v1request import ScanOssObjectV1Request
from ._scan_oss_object_v1shrink_request import ScanOssObjectV1ShrinkRequest
from ._scan_oss_object_v1response_body import ScanOssObjectV1ResponseBody
from ._scan_oss_object_v1response import ScanOssObjectV1Response
from ._stop_masking_process_request import StopMaskingProcessRequest
from ._stop_masking_process_response_body import StopMaskingProcessResponseBody
from ._stop_masking_process_response import StopMaskingProcessResponse
from ._describe_audit_logs_response_body import DescribeAuditLogsResponseBodyItems
from ._describe_category_template_list_response_body import DescribeCategoryTemplateListResponseBodyItems
from ._describe_category_template_rule_list_response_body import DescribeCategoryTemplateRuleListResponseBodyItems
from ._describe_columns_response_body import DescribeColumnsResponseBodyItemsModelTags
from ._describe_columns_response_body import DescribeColumnsResponseBodyItems
from ._describe_columns_v2response_body import DescribeColumnsV2ResponseBodyItemsModelTags
from ._describe_columns_v2response_body import DescribeColumnsV2ResponseBodyItems
from ._describe_configs_response_body import DescribeConfigsResponseBodyConfigList
from ._describe_data_assets_response_body import DescribeDataAssetsResponseBodyItems
from ._describe_data_limit_detail_response_body import DescribeDataLimitDetailResponseBodyDataLimit
from ._describe_data_limit_set_response_body import DescribeDataLimitSetResponseBodyDataLimitSetDataLimitList
from ._describe_data_limit_set_response_body import DescribeDataLimitSetResponseBodyDataLimitSetOssBucketList
from ._describe_data_limit_set_response_body import DescribeDataLimitSetResponseBodyDataLimitSetRegionList
from ._describe_data_limit_set_response_body import DescribeDataLimitSetResponseBodyDataLimitSet
from ._describe_data_limits_response_body import DescribeDataLimitsResponseBodyItems
from ._describe_data_masking_run_history_response_body import DescribeDataMaskingRunHistoryResponseBodyItems
from ._describe_data_masking_tasks_response_body import DescribeDataMaskingTasksResponseBodyItems
from ._describe_data_object_column_detail_response_body import DescribeDataObjectColumnDetailResponseBodyItemsModelTags
from ._describe_data_object_column_detail_response_body import DescribeDataObjectColumnDetailResponseBodyItems
from ._describe_data_object_column_detail_v2response_body import DescribeDataObjectColumnDetailV2ResponseBodyItemsModelTags
from ._describe_data_object_column_detail_v2response_body import DescribeDataObjectColumnDetailV2ResponseBodyItems
from ._describe_data_objects_response_body import DescribeDataObjectsResponseBodyItemsModelTags
from ._describe_data_objects_response_body import DescribeDataObjectsResponseBodyItemsRuleList
from ._describe_data_objects_response_body import DescribeDataObjectsResponseBodyItems
from ._describe_doc_types_response_body import DescribeDocTypesResponseBodyDocTypeList
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEventDetailChartData
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEventDetailChart
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEventDetailContent
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEventDetailResourceInfo
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEventDetail
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEventHandleInfoList
from ._describe_event_detail_response_body import DescribeEventDetailResponseBodyEvent
from ._describe_event_types_response_body import DescribeEventTypesResponseBodyEventTypeListSubTypeList
from ._describe_event_types_response_body import DescribeEventTypesResponseBodyEventTypeList
from ._describe_events_response_body import DescribeEventsResponseBodyItems
from ._describe_identify_task_status_response_body import DescribeIdentifyTaskStatusResponseBodyContent
from ._describe_instance_sources_response_body import DescribeInstanceSourcesResponseBodyItems
from ._describe_instances_response_body import DescribeInstancesResponseBodyItemsModelTags
from ._describe_instances_response_body import DescribeInstancesResponseBodyItems
from ._describe_oss_object_detail_response_body import DescribeOssObjectDetailResponseBodyOssObjectDetailRuleListModelTags
from ._describe_oss_object_detail_response_body import DescribeOssObjectDetailResponseBodyOssObjectDetailRuleList
from ._describe_oss_object_detail_response_body import DescribeOssObjectDetailResponseBodyOssObjectDetail
from ._describe_oss_object_detail_v2response_body import DescribeOssObjectDetailV2ResponseBodyOssObjectDetailRuleListModelTags
from ._describe_oss_object_detail_v2response_body import DescribeOssObjectDetailV2ResponseBodyOssObjectDetailRuleList
from ._describe_oss_object_detail_v2response_body import DescribeOssObjectDetailV2ResponseBodyOssObjectDetail
from ._describe_oss_objects_response_body import DescribeOssObjectsResponseBodyItemsRuleList
from ._describe_oss_objects_response_body import DescribeOssObjectsResponseBodyItems
from ._describe_packages_response_body import DescribePackagesResponseBodyItems
from ._describe_parent_instance_response_body import DescribeParentInstanceResponseBodyItems
from ._describe_risk_levels_response_body import DescribeRiskLevelsResponseBodyRiskLevelList
from ._describe_rules_response_body import DescribeRulesResponseBodyItems
from ._describe_tables_response_body import DescribeTablesResponseBodyItemsRuleList
from ._describe_tables_response_body import DescribeTablesResponseBodyItems
from ._describe_template_all_rules_response_body import DescribeTemplateAllRulesResponseBodyRuleList
from ._describe_user_status_response_body import DescribeUserStatusResponseBodyUserStatus

__all__ = [
    CreateConfigRequest,
    CreateConfigResponseBody,
    CreateConfigResponse,
    CreateDataLimitRequest,
    CreateDataLimitResponseBody,
    CreateDataLimitResponse,
    CreateRuleRequest,
    CreateRuleResponseBody,
    CreateRuleResponse,
    CreateScanTaskRequest,
    CreateScanTaskResponseBody,
    CreateScanTaskResponse,
    CreateSlrRoleRequest,
    CreateSlrRoleResponseBody,
    CreateSlrRoleResponse,
    DeleteDataLimitRequest,
    DeleteDataLimitResponseBody,
    DeleteDataLimitResponse,
    DeleteRuleRequest,
    DeleteRuleResponseBody,
    DeleteRuleResponse,
    DescribeAuditLogsRequest,
    DescribeAuditLogsResponseBody,
    DescribeAuditLogsResponse,
    DescribeCategoryTemplateListRequest,
    DescribeCategoryTemplateListResponseBody,
    DescribeCategoryTemplateListResponse,
    DescribeCategoryTemplateRuleListRequest,
    DescribeCategoryTemplateRuleListResponseBody,
    DescribeCategoryTemplateRuleListResponse,
    DescribeColumnsRequest,
    DescribeColumnsResponseBody,
    DescribeColumnsResponse,
    DescribeColumnsV2Request,
    DescribeColumnsV2ResponseBody,
    DescribeColumnsV2Response,
    DescribeConfigsRequest,
    DescribeConfigsResponseBody,
    DescribeConfigsResponse,
    DescribeDataAssetsRequest,
    DescribeDataAssetsResponseBody,
    DescribeDataAssetsResponse,
    DescribeDataLimitDetailRequest,
    DescribeDataLimitDetailResponseBody,
    DescribeDataLimitDetailResponse,
    DescribeDataLimitSetRequest,
    DescribeDataLimitSetResponseBody,
    DescribeDataLimitSetResponse,
    DescribeDataLimitsRequest,
    DescribeDataLimitsResponseBody,
    DescribeDataLimitsResponse,
    DescribeDataMaskingRunHistoryRequest,
    DescribeDataMaskingRunHistoryResponseBody,
    DescribeDataMaskingRunHistoryResponse,
    DescribeDataMaskingTasksRequest,
    DescribeDataMaskingTasksResponseBody,
    DescribeDataMaskingTasksResponse,
    DescribeDataObjectColumnDetailRequest,
    DescribeDataObjectColumnDetailResponseBody,
    DescribeDataObjectColumnDetailResponse,
    DescribeDataObjectColumnDetailV2Request,
    DescribeDataObjectColumnDetailV2ResponseBody,
    DescribeDataObjectColumnDetailV2Response,
    DescribeDataObjectsRequest,
    DescribeDataObjectsResponseBody,
    DescribeDataObjectsResponse,
    DescribeDocTypesRequest,
    DescribeDocTypesResponseBody,
    DescribeDocTypesResponse,
    DescribeEventDetailRequest,
    DescribeEventDetailResponseBody,
    DescribeEventDetailResponse,
    DescribeEventTypesRequest,
    DescribeEventTypesResponseBody,
    DescribeEventTypesResponse,
    DescribeEventsRequest,
    DescribeEventsResponseBody,
    DescribeEventsResponse,
    DescribeIdentifyTaskStatusRequest,
    DescribeIdentifyTaskStatusResponseBody,
    DescribeIdentifyTaskStatusResponse,
    DescribeInstanceSourcesRequest,
    DescribeInstanceSourcesResponseBody,
    DescribeInstanceSourcesResponse,
    DescribeInstancesRequest,
    DescribeInstancesResponseBody,
    DescribeInstancesResponse,
    DescribeOssObjectDetailRequest,
    DescribeOssObjectDetailResponseBody,
    DescribeOssObjectDetailResponse,
    DescribeOssObjectDetailV2Request,
    DescribeOssObjectDetailV2ResponseBody,
    DescribeOssObjectDetailV2Response,
    DescribeOssObjectsRequest,
    DescribeOssObjectsResponseBody,
    DescribeOssObjectsResponse,
    DescribePackagesRequest,
    DescribePackagesResponseBody,
    DescribePackagesResponse,
    DescribeParentInstanceRequest,
    DescribeParentInstanceResponseBody,
    DescribeParentInstanceResponse,
    DescribeRiskLevelsRequest,
    DescribeRiskLevelsResponseBody,
    DescribeRiskLevelsResponse,
    DescribeRulesRequest,
    DescribeRulesResponseBody,
    DescribeRulesResponse,
    DescribeTablesRequest,
    DescribeTablesResponseBody,
    DescribeTablesResponse,
    DescribeTemplateAllRulesRequest,
    DescribeTemplateAllRulesResponseBody,
    DescribeTemplateAllRulesResponse,
    DescribeUserStatusRequest,
    DescribeUserStatusResponseBody,
    DescribeUserStatusResponse,
    DisableUserConfigRequest,
    DisableUserConfigResponseBody,
    DisableUserConfigResponse,
    ExecDatamaskRequest,
    ExecDatamaskResponseBody,
    ExecDatamaskResponse,
    ManualTriggerMaskingProcessRequest,
    ManualTriggerMaskingProcessResponseBody,
    ManualTriggerMaskingProcessResponse,
    MaskOssImageRequest,
    MaskOssImageResponseBody,
    MaskOssImageResponse,
    ModifyDataLimitRequest,
    ModifyDataLimitResponseBody,
    ModifyDataLimitResponse,
    ModifyDefaultLevelRequest,
    ModifyDefaultLevelResponseBody,
    ModifyDefaultLevelResponse,
    ModifyEventStatusRequest,
    ModifyEventStatusResponseBody,
    ModifyEventStatusResponse,
    ModifyEventTypeStatusRequest,
    ModifyEventTypeStatusResponseBody,
    ModifyEventTypeStatusResponse,
    ModifyReportTaskStatusRequest,
    ModifyReportTaskStatusResponseBody,
    ModifyReportTaskStatusResponse,
    ModifyRuleRequest,
    ModifyRuleResponseBody,
    ModifyRuleResponse,
    ModifyRuleStatusRequest,
    ModifyRuleStatusResponseBody,
    ModifyRuleStatusResponse,
    RestoreOssImageRequest,
    RestoreOssImageResponseBody,
    RestoreOssImageResponse,
    ScanOssObjectV1Request,
    ScanOssObjectV1ShrinkRequest,
    ScanOssObjectV1ResponseBody,
    ScanOssObjectV1Response,
    StopMaskingProcessRequest,
    StopMaskingProcessResponseBody,
    StopMaskingProcessResponse,
    DescribeAuditLogsResponseBodyItems,
    DescribeCategoryTemplateListResponseBodyItems,
    DescribeCategoryTemplateRuleListResponseBodyItems,
    DescribeColumnsResponseBodyItemsModelTags,
    DescribeColumnsResponseBodyItems,
    DescribeColumnsV2ResponseBodyItemsModelTags,
    DescribeColumnsV2ResponseBodyItems,
    DescribeConfigsResponseBodyConfigList,
    DescribeDataAssetsResponseBodyItems,
    DescribeDataLimitDetailResponseBodyDataLimit,
    DescribeDataLimitSetResponseBodyDataLimitSetDataLimitList,
    DescribeDataLimitSetResponseBodyDataLimitSetOssBucketList,
    DescribeDataLimitSetResponseBodyDataLimitSetRegionList,
    DescribeDataLimitSetResponseBodyDataLimitSet,
    DescribeDataLimitsResponseBodyItems,
    DescribeDataMaskingRunHistoryResponseBodyItems,
    DescribeDataMaskingTasksResponseBodyItems,
    DescribeDataObjectColumnDetailResponseBodyItemsModelTags,
    DescribeDataObjectColumnDetailResponseBodyItems,
    DescribeDataObjectColumnDetailV2ResponseBodyItemsModelTags,
    DescribeDataObjectColumnDetailV2ResponseBodyItems,
    DescribeDataObjectsResponseBodyItemsModelTags,
    DescribeDataObjectsResponseBodyItemsRuleList,
    DescribeDataObjectsResponseBodyItems,
    DescribeDocTypesResponseBodyDocTypeList,
    DescribeEventDetailResponseBodyEventDetailChartData,
    DescribeEventDetailResponseBodyEventDetailChart,
    DescribeEventDetailResponseBodyEventDetailContent,
    DescribeEventDetailResponseBodyEventDetailResourceInfo,
    DescribeEventDetailResponseBodyEventDetail,
    DescribeEventDetailResponseBodyEventHandleInfoList,
    DescribeEventDetailResponseBodyEvent,
    DescribeEventTypesResponseBodyEventTypeListSubTypeList,
    DescribeEventTypesResponseBodyEventTypeList,
    DescribeEventsResponseBodyItems,
    DescribeIdentifyTaskStatusResponseBodyContent,
    DescribeInstanceSourcesResponseBodyItems,
    DescribeInstancesResponseBodyItemsModelTags,
    DescribeInstancesResponseBodyItems,
    DescribeOssObjectDetailResponseBodyOssObjectDetailRuleListModelTags,
    DescribeOssObjectDetailResponseBodyOssObjectDetailRuleList,
    DescribeOssObjectDetailResponseBodyOssObjectDetail,
    DescribeOssObjectDetailV2ResponseBodyOssObjectDetailRuleListModelTags,
    DescribeOssObjectDetailV2ResponseBodyOssObjectDetailRuleList,
    DescribeOssObjectDetailV2ResponseBodyOssObjectDetail,
    DescribeOssObjectsResponseBodyItemsRuleList,
    DescribeOssObjectsResponseBodyItems,
    DescribePackagesResponseBodyItems,
    DescribeParentInstanceResponseBodyItems,
    DescribeRiskLevelsResponseBodyRiskLevelList,
    DescribeRulesResponseBodyItems,
    DescribeTablesResponseBodyItemsRuleList,
    DescribeTablesResponseBodyItems,
    DescribeTemplateAllRulesResponseBodyRuleList,
    DescribeUserStatusResponseBodyUserStatus
]
