# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List, Dict

from alibabacloud_polardbx20200202 import models as main_models
from darabonba.model import DaraModel

class QueryColumnarLogSSEResponseBody(DaraModel):
    def __init__(
        self,
        access_denied_detail: main_models.QueryColumnarLogSSEResponseBodyAccessDeniedDetail = None,
        applied_offset: int = None,
        applied_row_limit: int = None,
        code: str = None,
        has_more: bool = None,
        message: str = None,
        partial: bool = None,
        query_elapsed_time_milliseconds: int = None,
        query_id: str = None,
        records: List[Dict[str, str]] = None,
        records_size_bytes: int = None,
        request_id: str = None,
        retryable: bool = None,
        returned_row_count: int = None,
        sequence: int = None,
        type: str = None,
    ):
        # The details of the access denial.
        self.access_denied_detail = access_denied_detail
        # Returned only when Type is EOF. The top-level SQL LIMIT offset actually applied by the service. The value is 0 if the SQL statement does not specify an offset.
        self.applied_offset = applied_offset
        # Returned only when Type is EOF. The maximum number of rows actually applied by the service after combining the top-level SQL LIMIT, MaxResultRows, and the current service policy. This value does not include the extra row used to detect HasMore.
        self.applied_row_limit = applied_row_limit
        # The stable error code. This field is returned only when Type is ERROR. Handle errors based on this field instead of relying on the Message text.
        self.code = code
        # Returned only when Type is EOF. Indicates whether the service or API row limit truncated the SQL submitted by the caller. A value of false when the SQL statement has a smaller LIMIT that was fully executed does not indicate that no more data exists in the underlying table.
        self.has_more = has_more
        # The error summary. This field is returned only when Type is ERROR.
        self.message = message
        # Indicates whether at least one RECORD event was sent before the ERROR occurred. A value of true indicates that the results already received by the caller are incomplete and must not be treated as complete query results.
        self.partial = partial
        # Returned only when Type is EOF. The elapsed time from the start of JDBC statement execution to the completion of reading the last result row or probe row. Unit: milliseconds.
        self.query_elapsed_time_milliseconds = query_elapsed_time_milliseconds
        # The unique identifier generated by the service for this JDBC query. All events in the same SSE stream share the same QueryId.
        self.query_id = query_id
        # Returned only when Type is RECORD. A batch of query results carried by this event. Each row is a JSON key-value object that maps column names to text values. SQL NULL values are encoded as the string null.
        self.records = records
        # Returned only when Type is EOF. The sum of UTF-8 bytes of the JSON objects for all returned rows. This value does not include arrays, SSE frames, or fixed response fields.
        self.records_size_bytes = records_size_bytes
        # The request ID. The same ID is used across all stages of the request, including access, authentication, routing, query execution, and all SSE events, to facilitate end-to-end troubleshooting.
        self.request_id = request_id
        # Indicates whether the current ERROR is suitable for retry. A value of true indicates that you can retry the request based on the suggestion returned with the error. A value of false indicates that you need to modify the request or contact the service team for troubleshooting.
        self.retryable = retryable
        # Returned only when Type is EOF. The total number of result rows actually returned in this SSE stream.
        self.returned_row_count = returned_row_count
        # The sequence number of the RECORD event, starting from 1 and incrementing. This field indicates the event order and does not represent the result row offset.
        self.sequence = sequence
        # The SSE event type. RECORD indicates a batch of query results. EOF indicates that the query has completed. ERROR indicates that the query ended abnormally.
        self.type = type

    def validate(self):
        if self.access_denied_detail:
            self.access_denied_detail.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.access_denied_detail is not None:
            result['AccessDeniedDetail'] = self.access_denied_detail.to_map()

        if self.applied_offset is not None:
            result['AppliedOffset'] = self.applied_offset

        if self.applied_row_limit is not None:
            result['AppliedRowLimit'] = self.applied_row_limit

        if self.code is not None:
            result['Code'] = self.code

        if self.has_more is not None:
            result['HasMore'] = self.has_more

        if self.message is not None:
            result['Message'] = self.message

        if self.partial is not None:
            result['Partial'] = self.partial

        if self.query_elapsed_time_milliseconds is not None:
            result['QueryElapsedTimeMilliseconds'] = self.query_elapsed_time_milliseconds

        if self.query_id is not None:
            result['QueryId'] = self.query_id

        if self.records is not None:
            result['Records'] = self.records

        if self.records_size_bytes is not None:
            result['RecordsSizeBytes'] = self.records_size_bytes

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.retryable is not None:
            result['Retryable'] = self.retryable

        if self.returned_row_count is not None:
            result['ReturnedRowCount'] = self.returned_row_count

        if self.sequence is not None:
            result['Sequence'] = self.sequence

        if self.type is not None:
            result['Type'] = self.type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AccessDeniedDetail') is not None:
            temp_model = main_models.QueryColumnarLogSSEResponseBodyAccessDeniedDetail()
            self.access_denied_detail = temp_model.from_map(m.get('AccessDeniedDetail'))

        if m.get('AppliedOffset') is not None:
            self.applied_offset = m.get('AppliedOffset')

        if m.get('AppliedRowLimit') is not None:
            self.applied_row_limit = m.get('AppliedRowLimit')

        if m.get('Code') is not None:
            self.code = m.get('Code')

        if m.get('HasMore') is not None:
            self.has_more = m.get('HasMore')

        if m.get('Message') is not None:
            self.message = m.get('Message')

        if m.get('Partial') is not None:
            self.partial = m.get('Partial')

        if m.get('QueryElapsedTimeMilliseconds') is not None:
            self.query_elapsed_time_milliseconds = m.get('QueryElapsedTimeMilliseconds')

        if m.get('QueryId') is not None:
            self.query_id = m.get('QueryId')

        if m.get('Records') is not None:
            self.records = m.get('Records')

        if m.get('RecordsSizeBytes') is not None:
            self.records_size_bytes = m.get('RecordsSizeBytes')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Retryable') is not None:
            self.retryable = m.get('Retryable')

        if m.get('ReturnedRowCount') is not None:
            self.returned_row_count = m.get('ReturnedRowCount')

        if m.get('Sequence') is not None:
            self.sequence = m.get('Sequence')

        if m.get('Type') is not None:
            self.type = m.get('Type')

        return self

class QueryColumnarLogSSEResponseBodyAccessDeniedDetail(DaraModel):
    def __init__(
        self,
        auth_action: str = None,
        auth_principal_display_name: str = None,
        auth_principal_owner_id: str = None,
        auth_principal_type: str = None,
        encoded_diagnostic_message: str = None,
        no_permission_type: str = None,
        policy_type: str = None,
    ):
        # As described above.
        self.auth_action = auth_action
        # The display name of the authentication principal.
        self.auth_principal_display_name = auth_principal_display_name
        # The owner ID of the authentication principal.
        self.auth_principal_owner_id = auth_principal_owner_id
        # The identity type used for authentication in the request. Valid values:
        # - SubUser: RAM user.
        # - AssumedRoleUser: RAM role.
        # - Federated: SSO federated identity.
        self.auth_principal_type = auth_principal_type
        # The encoded diagnostic message.
        self.encoded_diagnostic_message = encoded_diagnostic_message
        # NoPermissionType
        self.no_permission_type = no_permission_type
        # The policy type.
        self.policy_type = policy_type

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.auth_action is not None:
            result['AuthAction'] = self.auth_action

        if self.auth_principal_display_name is not None:
            result['AuthPrincipalDisplayName'] = self.auth_principal_display_name

        if self.auth_principal_owner_id is not None:
            result['AuthPrincipalOwnerId'] = self.auth_principal_owner_id

        if self.auth_principal_type is not None:
            result['AuthPrincipalType'] = self.auth_principal_type

        if self.encoded_diagnostic_message is not None:
            result['EncodedDiagnosticMessage'] = self.encoded_diagnostic_message

        if self.no_permission_type is not None:
            result['NoPermissionType'] = self.no_permission_type

        if self.policy_type is not None:
            result['PolicyType'] = self.policy_type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AuthAction') is not None:
            self.auth_action = m.get('AuthAction')

        if m.get('AuthPrincipalDisplayName') is not None:
            self.auth_principal_display_name = m.get('AuthPrincipalDisplayName')

        if m.get('AuthPrincipalOwnerId') is not None:
            self.auth_principal_owner_id = m.get('AuthPrincipalOwnerId')

        if m.get('AuthPrincipalType') is not None:
            self.auth_principal_type = m.get('AuthPrincipalType')

        if m.get('EncodedDiagnosticMessage') is not None:
            self.encoded_diagnostic_message = m.get('EncodedDiagnosticMessage')

        if m.get('NoPermissionType') is not None:
            self.no_permission_type = m.get('NoPermissionType')

        if m.get('PolicyType') is not None:
            self.policy_type = m.get('PolicyType')

        return self

