# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_mns_open20220119 import models as main_models
from darabonba.model import DaraModel

class GetEventRuleResponseBody(DaraModel):
    def __init__(
        self,
        code: int = None,
        data: main_models.GetEventRuleResponseBodyData = None,
        message: str = None,
        request_id: str = None,
        status: str = None,
        success: bool = None,
    ):
        # The response code.
        self.code = code
        # The query results.
        self.data = data
        # The response message.
        self.message = message
        # The unique ID generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.
        self.request_id = request_id
        # The status of the response.
        self.status = status
        # Indicates whether the request was successful.
        self.success = success

    def validate(self):
        if self.data:
            self.data.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.code is not None:
            result['Code'] = self.code

        if self.data is not None:
            result['Data'] = self.data.to_map()

        if self.message is not None:
            result['Message'] = self.message

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.status is not None:
            result['Status'] = self.status

        if self.success is not None:
            result['Success'] = self.success

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Code') is not None:
            self.code = m.get('Code')

        if m.get('Data') is not None:
            temp_model = main_models.GetEventRuleResponseBodyData()
            self.data = temp_model.from_map(m.get('Data'))

        if m.get('Message') is not None:
            self.message = m.get('Message')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('Success') is not None:
            self.success = m.get('Success')

        return self

class GetEventRuleResponseBodyData(DaraModel):
    def __init__(
        self,
        delivery_mode: str = None,
        endpoint: main_models.GetEventRuleResponseBodyDataEndpoint = None,
        event_types: List[str] = None,
        match_rules: List[List[main_models.EventMatchRule]] = None,
        rule_name: str = None,
        subscriptions: List[main_models.GetEventRuleResponseBodyDataSubscriptions] = None,
        topic_name: str = None,
    ):
        # This field is deprecated.
        self.delivery_mode = delivery_mode
        # The endpoint address.
        self.endpoint = endpoint
        # A list of event types.
        self.event_types = event_types
        # The event matching rules. The rules have an OR relationship.
        self.match_rules = match_rules
        # The name of the event notification rule.
        self.rule_name = rule_name
        # Subscription endpoints.
        self.subscriptions = subscriptions
        # The name of the topic.
        self.topic_name = topic_name

    def validate(self):
        if self.endpoint:
            self.endpoint.validate()
        if self.match_rules:
            for v1 in self.match_rules:
                for v2 in v1:
                     if v2:
                        v2.validate()
        if self.subscriptions:
            for v1 in self.subscriptions:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.delivery_mode is not None:
            result['DeliveryMode'] = self.delivery_mode

        if self.endpoint is not None:
            result['Endpoint'] = self.endpoint.to_map()

        if self.event_types is not None:
            result['EventTypes'] = self.event_types

        result['MatchRules'] = []
        if self.match_rules is not None:
            for k1 in self.match_rules:
                l1 = []
                for k2 in k1:
                    l1.append(k2.to_map() if k2 else None)
                result['MatchRules'].append(l1)

        if self.rule_name is not None:
            result['RuleName'] = self.rule_name

        result['Subscriptions'] = []
        if self.subscriptions is not None:
            for k1 in self.subscriptions:
                result['Subscriptions'].append(k1.to_map() if k1 else None)

        if self.topic_name is not None:
            result['TopicName'] = self.topic_name

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('DeliveryMode') is not None:
            self.delivery_mode = m.get('DeliveryMode')

        if m.get('Endpoint') is not None:
            temp_model = main_models.GetEventRuleResponseBodyDataEndpoint()
            self.endpoint = temp_model.from_map(m.get('Endpoint'))

        if m.get('EventTypes') is not None:
            self.event_types = m.get('EventTypes')

        self.match_rules = []
        if m.get('MatchRules') is not None:
            for k1 in m.get('MatchRules'):
                l1 = []
                for k2 in k1:
                    temp_model = main_models.EventMatchRule()
                    l1.append(temp_model.from_map(k2))
                self.match_rules.append(l1)

        if m.get('RuleName') is not None:
            self.rule_name = m.get('RuleName')

        self.subscriptions = []
        if m.get('Subscriptions') is not None:
            for k1 in m.get('Subscriptions'):
                temp_model = main_models.GetEventRuleResponseBodyDataSubscriptions()
                self.subscriptions.append(temp_model.from_map(k1))

        if m.get('TopicName') is not None:
            self.topic_name = m.get('TopicName')

        return self

class GetEventRuleResponseBodyDataSubscriptions(DaraModel):
    def __init__(
        self,
        endpoint_type: str = None,
        endpoint_value: str = None,
    ):
        # The endpoint type. Valid values:
        # 
        # - **queue**: A queue.
        # 
        # - **topic**: A topic.
        self.endpoint_type = endpoint_type
        # The value of the endpoint.
        self.endpoint_value = endpoint_value

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.endpoint_type is not None:
            result['EndpointType'] = self.endpoint_type

        if self.endpoint_value is not None:
            result['EndpointValue'] = self.endpoint_value

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('EndpointType') is not None:
            self.endpoint_type = m.get('EndpointType')

        if m.get('EndpointValue') is not None:
            self.endpoint_value = m.get('EndpointValue')

        return self

class GetEventRuleResponseBodyDataEndpoint(DaraModel):
    def __init__(
        self,
        endpoint_type: str = None,
        endpoint_value: str = None,
    ):
        # The endpoint type. Valid values:
        # 
        # - **queue**: A queue.
        # 
        # - **topic**: A topic.
        self.endpoint_type = endpoint_type
        # The value of the endpoint.
        self.endpoint_value = endpoint_value

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.endpoint_type is not None:
            result['EndpointType'] = self.endpoint_type

        if self.endpoint_value is not None:
            result['EndpointValue'] = self.endpoint_value

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('EndpointType') is not None:
            self.endpoint_type = m.get('EndpointType')

        if m.get('EndpointValue') is not None:
            self.endpoint_value = m.get('EndpointValue')

        return self

