# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_alidns20150109 import models as main_models
from darabonba.model import DaraModel

class DescribeAtiAgentRegisterInfoResponseBody(DaraModel):
    def __init__(
        self,
        access_denied_detail: main_models.DescribeAtiAgentRegisterInfoResponseBodyAccessDeniedDetail = None,
        agent_description: str = None,
        agent_display_name: str = None,
        agent_host: str = None,
        agent_id: str = None,
        agent_register_info_id: str = None,
        agent_sub_host: str = None,
        agent_version: str = None,
        ati_name: str = None,
        create_timestamp: int = None,
        domain_mode: str = None,
        endpoints: main_models.DescribeAtiAgentRegisterInfoResponseBodyEndpoints = None,
        identity_cert_serial_number: str = None,
        registrant_id: str = None,
        registrant_name: str = None,
        reject_reason: main_models.DescribeAtiAgentRegisterInfoResponseBodyRejectReason = None,
        request_id: str = None,
        server_cert_serial_number: str = None,
        status: str = None,
        trust_card: str = None,
        trust_card_url: str = None,
        trust_level: str = None,
        update_timestamp: int = None,
    ):
        # The details about the access denial. This field is returned only when RAM authentication fails.
        self.access_denied_detail = access_denied_detail
        # The capability description of the Agent.
        self.agent_description = agent_description
        # The display name of the Agent.
        self.agent_display_name = agent_display_name
        # The endpoint domain name through which the Agent provides external services.
        self.agent_host = agent_host
        # The Agent ID, which is uniformly assigned by CNNIC after real-name authentication. The Agent ID serves as the unique identifier that binds the Agent to the authenticated registrant.
        self.agent_id = agent_id
        # The Agent registration ID. This ID is automatically generated by the Alibaba Cloud ATS platform and is globally unique within the platform. It is automatically generated during the Agent registration process. In the multi-step registration process through the API, this ID must be carried throughout all steps to ensure that each step is associated with the same Agent and the complete registration process is completed.
        self.agent_register_info_id = agent_register_info_id
        self.agent_sub_host = agent_sub_host
        # The version of the Agent.
        self.agent_version = agent_version
        # The ATI name, which is a globally unique identifier in the ATI trust system. Example: ati://v1.0.0.www.example.com
        # - ati:// — The protocol prefix that identifies this as a resource in the ATI system.
        # - v1.0.0 — The Agent version number.
        # - www.example.com — The domain name (FQDN) bound to the Agent.
        self.ati_name = ati_name
        # The creation time (timestamp).
        self.create_timestamp = create_timestamp
        self.domain_mode = domain_mode
        self.endpoints = endpoints
        # Ignore.
        self.identity_cert_serial_number = identity_cert_serial_number
        # The ID of the authenticated registrant.
        self.registrant_id = registrant_id
        # The name of the registrant.
        self.registrant_name = registrant_name
        # The reason for Agent registration review failure.
        self.reject_reason = reject_reason
        # The request ID.
        self.request_id = request_id
        # Ignore.
        self.server_cert_serial_number = server_cert_serial_number
        # The Agent status. Valid values:
        # 
        # - Draft: The Agent registration form is being filled out and has not been formally submitted. In draft status, only modification and detail viewing operations are supported.
        # - Private CA Pending Issuance: The Agent registration has been formally submitted. Alibaba Cloud has completed the ACME DNS-01 pre-check and submitted the registration information and generated DNS records to CNNIC. Currently waiting for CNNIC to approve and issue the Private CA and complete TL sealing.
        # - DNS Pending Verification: CNNIC has approved and issued the Private CA certificate and completed TL sealing, but the DNS records of the user have not been verified. Waiting for the user to add the corresponding DNS records in domain name resolution and complete verification.
        # - Active: All processes are complete. The Private CA certificate has been issued, TL has been sealed, and DNS records have been verified. The Agent is activated and can be discovered and trust-verified across the network.
        # - Expired: The Agent identity certificate has expired, and the user did not complete certificate renewal within the validity period.
        # - Revoked: The Agent certificate has been revoked, DNS records have been cleaned up, and the Agent cannot be discovered or trust-verified. It cannot be restored to active status.
        self.status = status
        # Ignore.
        self.trust_card = trust_card
        # **[Deprecated]**
        self.trust_card_url = trust_card_url
        self.trust_level = trust_level
        # The update time (timestamp).
        self.update_timestamp = update_timestamp

    def validate(self):
        if self.access_denied_detail:
            self.access_denied_detail.validate()
        if self.endpoints:
            self.endpoints.validate()
        if self.reject_reason:
            self.reject_reason.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.access_denied_detail is not None:
            result['AccessDeniedDetail'] = self.access_denied_detail.to_map()

        if self.agent_description is not None:
            result['AgentDescription'] = self.agent_description

        if self.agent_display_name is not None:
            result['AgentDisplayName'] = self.agent_display_name

        if self.agent_host is not None:
            result['AgentHost'] = self.agent_host

        if self.agent_id is not None:
            result['AgentId'] = self.agent_id

        if self.agent_register_info_id is not None:
            result['AgentRegisterInfoId'] = self.agent_register_info_id

        if self.agent_sub_host is not None:
            result['AgentSubHost'] = self.agent_sub_host

        if self.agent_version is not None:
            result['AgentVersion'] = self.agent_version

        if self.ati_name is not None:
            result['AtiName'] = self.ati_name

        if self.create_timestamp is not None:
            result['CreateTimestamp'] = self.create_timestamp

        if self.domain_mode is not None:
            result['DomainMode'] = self.domain_mode

        if self.endpoints is not None:
            result['Endpoints'] = self.endpoints.to_map()

        if self.identity_cert_serial_number is not None:
            result['IdentityCertSerialNumber'] = self.identity_cert_serial_number

        if self.registrant_id is not None:
            result['RegistrantId'] = self.registrant_id

        if self.registrant_name is not None:
            result['RegistrantName'] = self.registrant_name

        if self.reject_reason is not None:
            result['RejectReason'] = self.reject_reason.to_map()

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.server_cert_serial_number is not None:
            result['ServerCertSerialNumber'] = self.server_cert_serial_number

        if self.status is not None:
            result['Status'] = self.status

        if self.trust_card is not None:
            result['TrustCard'] = self.trust_card

        if self.trust_card_url is not None:
            result['TrustCardUrl'] = self.trust_card_url

        if self.trust_level is not None:
            result['TrustLevel'] = self.trust_level

        if self.update_timestamp is not None:
            result['UpdateTimestamp'] = self.update_timestamp

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AccessDeniedDetail') is not None:
            temp_model = main_models.DescribeAtiAgentRegisterInfoResponseBodyAccessDeniedDetail()
            self.access_denied_detail = temp_model.from_map(m.get('AccessDeniedDetail'))

        if m.get('AgentDescription') is not None:
            self.agent_description = m.get('AgentDescription')

        if m.get('AgentDisplayName') is not None:
            self.agent_display_name = m.get('AgentDisplayName')

        if m.get('AgentHost') is not None:
            self.agent_host = m.get('AgentHost')

        if m.get('AgentId') is not None:
            self.agent_id = m.get('AgentId')

        if m.get('AgentRegisterInfoId') is not None:
            self.agent_register_info_id = m.get('AgentRegisterInfoId')

        if m.get('AgentSubHost') is not None:
            self.agent_sub_host = m.get('AgentSubHost')

        if m.get('AgentVersion') is not None:
            self.agent_version = m.get('AgentVersion')

        if m.get('AtiName') is not None:
            self.ati_name = m.get('AtiName')

        if m.get('CreateTimestamp') is not None:
            self.create_timestamp = m.get('CreateTimestamp')

        if m.get('DomainMode') is not None:
            self.domain_mode = m.get('DomainMode')

        if m.get('Endpoints') is not None:
            temp_model = main_models.DescribeAtiAgentRegisterInfoResponseBodyEndpoints()
            self.endpoints = temp_model.from_map(m.get('Endpoints'))

        if m.get('IdentityCertSerialNumber') is not None:
            self.identity_cert_serial_number = m.get('IdentityCertSerialNumber')

        if m.get('RegistrantId') is not None:
            self.registrant_id = m.get('RegistrantId')

        if m.get('RegistrantName') is not None:
            self.registrant_name = m.get('RegistrantName')

        if m.get('RejectReason') is not None:
            temp_model = main_models.DescribeAtiAgentRegisterInfoResponseBodyRejectReason()
            self.reject_reason = temp_model.from_map(m.get('RejectReason'))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('ServerCertSerialNumber') is not None:
            self.server_cert_serial_number = m.get('ServerCertSerialNumber')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('TrustCard') is not None:
            self.trust_card = m.get('TrustCard')

        if m.get('TrustCardUrl') is not None:
            self.trust_card_url = m.get('TrustCardUrl')

        if m.get('TrustLevel') is not None:
            self.trust_level = m.get('TrustLevel')

        if m.get('UpdateTimestamp') is not None:
            self.update_timestamp = m.get('UpdateTimestamp')

        return self

class DescribeAtiAgentRegisterInfoResponseBodyRejectReason(DaraModel):
    def __init__(
        self,
        message: str = None,
        type: str = None,
    ):
        # The detailed information about the Agent registration failure.
        self.message = message
        # The type of review failure. Valid values:
        # - ACME_VERIFY_FAILED: ACME verification failed.  
        # - INFO_AUDIT_FAILED: Agent information review failed.
        self.type = type

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.message is not None:
            result['Message'] = self.message

        if self.type is not None:
            result['Type'] = self.type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Message') is not None:
            self.message = m.get('Message')

        if m.get('Type') is not None:
            self.type = m.get('Type')

        return self

class DescribeAtiAgentRegisterInfoResponseBodyEndpoints(DaraModel):
    def __init__(
        self,
        endpoint: List[main_models.DescribeAtiAgentRegisterInfoResponseBodyEndpointsEndpoint] = None,
    ):
        self.endpoint = endpoint

    def validate(self):
        if self.endpoint:
            for v1 in self.endpoint:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['Endpoint'] = []
        if self.endpoint is not None:
            for k1 in self.endpoint:
                result['Endpoint'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.endpoint = []
        if m.get('Endpoint') is not None:
            for k1 in m.get('Endpoint'):
                temp_model = main_models.DescribeAtiAgentRegisterInfoResponseBodyEndpointsEndpoint()
                self.endpoint.append(temp_model.from_map(k1))

        return self

class DescribeAtiAgentRegisterInfoResponseBodyEndpointsEndpoint(DaraModel):
    def __init__(
        self,
        agent_url: str = None,
        metadata_url: str = None,
        protocol: str = None,
        transports: main_models.DescribeAtiAgentRegisterInfoResponseBodyEndpointsEndpointTransports = None,
    ):
        self.agent_url = agent_url
        self.metadata_url = metadata_url
        self.protocol = protocol
        self.transports = transports

    def validate(self):
        if self.transports:
            self.transports.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.agent_url is not None:
            result['AgentUrl'] = self.agent_url

        if self.metadata_url is not None:
            result['MetadataUrl'] = self.metadata_url

        if self.protocol is not None:
            result['Protocol'] = self.protocol

        if self.transports is not None:
            result['Transports'] = self.transports.to_map()

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AgentUrl') is not None:
            self.agent_url = m.get('AgentUrl')

        if m.get('MetadataUrl') is not None:
            self.metadata_url = m.get('MetadataUrl')

        if m.get('Protocol') is not None:
            self.protocol = m.get('Protocol')

        if m.get('Transports') is not None:
            temp_model = main_models.DescribeAtiAgentRegisterInfoResponseBodyEndpointsEndpointTransports()
            self.transports = temp_model.from_map(m.get('Transports'))

        return self

class DescribeAtiAgentRegisterInfoResponseBodyEndpointsEndpointTransports(DaraModel):
    def __init__(
        self,
        transport: List[str] = None,
    ):
        self.transport = transport

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.transport is not None:
            result['Transport'] = self.transport

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Transport') is not None:
            self.transport = m.get('Transport')

        return self

class DescribeAtiAgentRegisterInfoResponseBodyAccessDeniedDetail(DaraModel):
    def __init__(
        self,
        auth_action: str = None,
        auth_principal_display_name: str = None,
        auth_principal_owner_id: str = None,
        auth_principal_type: str = None,
        encoded_diagnostic_message: str = None,
        no_permission_type: str = None,
        policy_type: str = None,
    ):
        # The unauthorized operation that was attempted.
        self.auth_action = auth_action
        # The display name of the authorization principal.
        self.auth_principal_display_name = auth_principal_display_name
        # The owner ID of the authorization principal.
        self.auth_principal_owner_id = auth_principal_owner_id
        # The identity type.
        self.auth_principal_type = auth_principal_type
        # The encrypted complete diagnostic message.
        self.encoded_diagnostic_message = encoded_diagnostic_message
        # The reason for the authentication failure. Valid values:
        # - ExplicitDeny: Explicit deny.
        # - ImplicitDeny: Implicit deny.
        self.no_permission_type = no_permission_type
        # The policy type.
        self.policy_type = policy_type

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.auth_action is not None:
            result['AuthAction'] = self.auth_action

        if self.auth_principal_display_name is not None:
            result['AuthPrincipalDisplayName'] = self.auth_principal_display_name

        if self.auth_principal_owner_id is not None:
            result['AuthPrincipalOwnerId'] = self.auth_principal_owner_id

        if self.auth_principal_type is not None:
            result['AuthPrincipalType'] = self.auth_principal_type

        if self.encoded_diagnostic_message is not None:
            result['EncodedDiagnosticMessage'] = self.encoded_diagnostic_message

        if self.no_permission_type is not None:
            result['NoPermissionType'] = self.no_permission_type

        if self.policy_type is not None:
            result['PolicyType'] = self.policy_type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AuthAction') is not None:
            self.auth_action = m.get('AuthAction')

        if m.get('AuthPrincipalDisplayName') is not None:
            self.auth_principal_display_name = m.get('AuthPrincipalDisplayName')

        if m.get('AuthPrincipalOwnerId') is not None:
            self.auth_principal_owner_id = m.get('AuthPrincipalOwnerId')

        if m.get('AuthPrincipalType') is not None:
            self.auth_principal_type = m.get('AuthPrincipalType')

        if m.get('EncodedDiagnosticMessage') is not None:
            self.encoded_diagnostic_message = m.get('EncodedDiagnosticMessage')

        if m.get('NoPermissionType') is not None:
            self.no_permission_type = m.get('NoPermissionType')

        if m.get('PolicyType') is not None:
            self.policy_type = m.get('PolicyType')

        return self

