# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_alidns20150109 import models as main_models
from darabonba.model import DaraModel

class VerifyAtiAgentDnsRecordsResponseBody(DaraModel):
    def __init__(
        self,
        access_denied_detail: main_models.VerifyAtiAgentDnsRecordsResponseBodyAccessDeniedDetail = None,
        agent_register_info_id: str = None,
        agent_status: str = None,
        all_verified: bool = None,
        request_id: str = None,
        results: main_models.VerifyAtiAgentDnsRecordsResponseBodyResults = None,
        success: bool = None,
    ):
        # The details about the access denial. This field is returned only when RAM authentication fails.
        self.access_denied_detail = access_denied_detail
        # The Agent registration ID. This ID is automatically generated by the Alibaba Cloud ATS platform and is globally unique within the platform.
        self.agent_register_info_id = agent_register_info_id
        # The Agent status.
        self.agent_status = agent_status
        # Indicates whether all DNS records have been verified.
        self.all_verified = all_verified
        # The request ID.
        self.request_id = request_id
        self.results = results
        # Indicates whether the operation to delete the domain name instance configuration is successful. Valid values:
        # 
        # - true: The operation is successful.
        # 
        # - false: The operation failed.
        self.success = success

    def validate(self):
        if self.access_denied_detail:
            self.access_denied_detail.validate()
        if self.results:
            self.results.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.access_denied_detail is not None:
            result['AccessDeniedDetail'] = self.access_denied_detail.to_map()

        if self.agent_register_info_id is not None:
            result['AgentRegisterInfoId'] = self.agent_register_info_id

        if self.agent_status is not None:
            result['AgentStatus'] = self.agent_status

        if self.all_verified is not None:
            result['AllVerified'] = self.all_verified

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.results is not None:
            result['Results'] = self.results.to_map()

        if self.success is not None:
            result['Success'] = self.success

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AccessDeniedDetail') is not None:
            temp_model = main_models.VerifyAtiAgentDnsRecordsResponseBodyAccessDeniedDetail()
            self.access_denied_detail = temp_model.from_map(m.get('AccessDeniedDetail'))

        if m.get('AgentRegisterInfoId') is not None:
            self.agent_register_info_id = m.get('AgentRegisterInfoId')

        if m.get('AgentStatus') is not None:
            self.agent_status = m.get('AgentStatus')

        if m.get('AllVerified') is not None:
            self.all_verified = m.get('AllVerified')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Results') is not None:
            temp_model = main_models.VerifyAtiAgentDnsRecordsResponseBodyResults()
            self.results = temp_model.from_map(m.get('Results'))

        if m.get('Success') is not None:
            self.success = m.get('Success')

        return self

class VerifyAtiAgentDnsRecordsResponseBodyResults(DaraModel):
    def __init__(
        self,
        result: List[main_models.VerifyAtiAgentDnsRecordsResponseBodyResultsResult] = None,
    ):
        self.result = result

    def validate(self):
        if self.result:
            for v1 in self.result:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['Result'] = []
        if self.result is not None:
            for k1 in self.result:
                result['Result'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.result = []
        if m.get('Result') is not None:
            for k1 in m.get('Result'):
                temp_model = main_models.VerifyAtiAgentDnsRecordsResponseBodyResultsResult()
                self.result.append(temp_model.from_map(k1))

        return self

class VerifyAtiAgentDnsRecordsResponseBodyResultsResult(DaraModel):
    def __init__(
        self,
        fail_reason: str = None,
        record_name: str = None,
        record_type: str = None,
        verify_status: str = None,
    ):
        self.fail_reason = fail_reason
        self.record_name = record_name
        self.record_type = record_type
        self.verify_status = verify_status

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.fail_reason is not None:
            result['FailReason'] = self.fail_reason

        if self.record_name is not None:
            result['RecordName'] = self.record_name

        if self.record_type is not None:
            result['RecordType'] = self.record_type

        if self.verify_status is not None:
            result['VerifyStatus'] = self.verify_status

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('FailReason') is not None:
            self.fail_reason = m.get('FailReason')

        if m.get('RecordName') is not None:
            self.record_name = m.get('RecordName')

        if m.get('RecordType') is not None:
            self.record_type = m.get('RecordType')

        if m.get('VerifyStatus') is not None:
            self.verify_status = m.get('VerifyStatus')

        return self

class VerifyAtiAgentDnsRecordsResponseBodyAccessDeniedDetail(DaraModel):
    def __init__(
        self,
        auth_action: str = None,
        auth_principal_display_name: str = None,
        auth_principal_owner_id: str = None,
        auth_principal_type: str = None,
        encoded_diagnostic_message: str = None,
        no_permission_type: str = None,
        policy_type: str = None,
    ):
        # The unauthorized operation that was attempted.
        self.auth_action = auth_action
        # The display name of the authorization principal.
        self.auth_principal_display_name = auth_principal_display_name
        # The owner ID of the authorization principal.
        self.auth_principal_owner_id = auth_principal_owner_id
        # The identity type.
        self.auth_principal_type = auth_principal_type
        # The encoded complete diagnostic message.
        self.encoded_diagnostic_message = encoded_diagnostic_message
        # The reason for the authentication failure. Valid values:
        # - ExplicitDeny: explicit deny.
        # - ImplicitDeny: implicit deny.
        self.no_permission_type = no_permission_type
        # The policy type.
        self.policy_type = policy_type

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.auth_action is not None:
            result['AuthAction'] = self.auth_action

        if self.auth_principal_display_name is not None:
            result['AuthPrincipalDisplayName'] = self.auth_principal_display_name

        if self.auth_principal_owner_id is not None:
            result['AuthPrincipalOwnerId'] = self.auth_principal_owner_id

        if self.auth_principal_type is not None:
            result['AuthPrincipalType'] = self.auth_principal_type

        if self.encoded_diagnostic_message is not None:
            result['EncodedDiagnosticMessage'] = self.encoded_diagnostic_message

        if self.no_permission_type is not None:
            result['NoPermissionType'] = self.no_permission_type

        if self.policy_type is not None:
            result['PolicyType'] = self.policy_type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AuthAction') is not None:
            self.auth_action = m.get('AuthAction')

        if m.get('AuthPrincipalDisplayName') is not None:
            self.auth_principal_display_name = m.get('AuthPrincipalDisplayName')

        if m.get('AuthPrincipalOwnerId') is not None:
            self.auth_principal_owner_id = m.get('AuthPrincipalOwnerId')

        if m.get('AuthPrincipalType') is not None:
            self.auth_principal_type = m.get('AuthPrincipalType')

        if m.get('EncodedDiagnosticMessage') is not None:
            self.encoded_diagnostic_message = m.get('EncodedDiagnosticMessage')

        if m.get('NoPermissionType') is not None:
            self.no_permission_type = m.get('NoPermissionType')

        if m.get('PolicyType') is not None:
            self.policy_type = m.get('PolicyType')

        return self

