# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class CreateAttackPathSensitiveAssetConfigResponseBody(DaraModel):
    def __init__(
        self,
        attack_path_sensitive_asset_config: main_models.CreateAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig = None,
        request_id: str = None,
    ):
        # Data of the attack path sensitive asset settings.
        self.attack_path_sensitive_asset_config = attack_path_sensitive_asset_config
        # The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
        self.request_id = request_id

    def validate(self):
        if self.attack_path_sensitive_asset_config:
            self.attack_path_sensitive_asset_config.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.attack_path_sensitive_asset_config is not None:
            result['AttackPathSensitiveAssetConfig'] = self.attack_path_sensitive_asset_config.to_map()

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AttackPathSensitiveAssetConfig') is not None:
            temp_model = main_models.CreateAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig()
            self.attack_path_sensitive_asset_config = temp_model.from_map(m.get('AttackPathSensitiveAssetConfig'))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class CreateAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig(DaraModel):
    def __init__(
        self,
        attack_path_sensitive_asset_config_id: str = None,
    ):
        # ID for setting sensitive assets in the attack path.
        self.attack_path_sensitive_asset_config_id = attack_path_sensitive_asset_config_id

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.attack_path_sensitive_asset_config_id is not None:
            result['AttackPathSensitiveAssetConfigId'] = self.attack_path_sensitive_asset_config_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AttackPathSensitiveAssetConfigId') is not None:
            self.attack_path_sensitive_asset_config_id = m.get('AttackPathSensitiveAssetConfigId')

        return self

