# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class DescribeClusterScannerListResponseBody(DaraModel):
    def __init__(
        self,
        installed_count: int = None,
        list: List[main_models.DescribeClusterScannerListResponseBodyList] = None,
        request_id: str = None,
    ):
        # Number of clusters with installed scanners.
        self.installed_count = installed_count
        # List of clusters.
        self.list = list
        # The ID of this request, generated by Alibaba Cloud as a unique identifier, which can be used for troubleshooting and problem localization.
        self.request_id = request_id

    def validate(self):
        if self.list:
            for v1 in self.list:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.installed_count is not None:
            result['InstalledCount'] = self.installed_count

        result['List'] = []
        if self.list is not None:
            for k1 in self.list:
                result['List'].append(k1.to_map() if k1 else None)

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('InstalledCount') is not None:
            self.installed_count = m.get('InstalledCount')

        self.list = []
        if m.get('List') is not None:
            for k1 in m.get('List'):
                temp_model = main_models.DescribeClusterScannerListResponseBodyList()
                self.list.append(temp_model.from_map(k1))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class DescribeClusterScannerListResponseBodyList(DaraModel):
    def __init__(
        self,
        last_time: int = None,
        need_update: bool = None,
        status: str = None,
        version: str = None,
        webhook_open: int = None,
        webhook_status: str = None,
    ):
        # Latest heartbeat time.
        self.last_time = last_time
        # Whether an update is needed.
        self.need_update = need_update
        # Scanner status. Values:
        # - **online**: Running
        # - **offline**: Offline
        # - **not_installed**: Not Installed
        self.status = status
        # Version number.
        self.version = version
        # Whether the incremental scan switch is enabled. Values: 
        # - **0**: Not enabled
        #  - **1**: Enabled
        self.webhook_open = webhook_open
        # The incremental scan component status. Values: 
        # - **n**: Not deployed 
        # - **y**: Deployed
        self.webhook_status = webhook_status

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.last_time is not None:
            result['LastTime'] = self.last_time

        if self.need_update is not None:
            result['NeedUpdate'] = self.need_update

        if self.status is not None:
            result['Status'] = self.status

        if self.version is not None:
            result['Version'] = self.version

        if self.webhook_open is not None:
            result['WebhookOpen'] = self.webhook_open

        if self.webhook_status is not None:
            result['WebhookStatus'] = self.webhook_status

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('LastTime') is not None:
            self.last_time = m.get('LastTime')

        if m.get('NeedUpdate') is not None:
            self.need_update = m.get('NeedUpdate')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('Version') is not None:
            self.version = m.get('Version')

        if m.get('WebhookOpen') is not None:
            self.webhook_open = m.get('WebhookOpen')

        if m.get('WebhookStatus') is not None:
            self.webhook_status = m.get('WebhookStatus')

        return self

