# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class DescribeInstanceStatisticsResponseBody(DaraModel):
    def __init__(
        self,
        data: List[main_models.DescribeInstanceStatisticsResponseBodyData] = None,
        request_id: str = None,
    ):
        # The risk information about assets.
        self.data = data
        # The ID of the request, which is used to locate and troubleshoot issues.
        self.request_id = request_id

    def validate(self):
        if self.data:
            for v1 in self.data:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['Data'] = []
        if self.data is not None:
            for k1 in self.data:
                result['Data'].append(k1.to_map() if k1 else None)

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.data = []
        if m.get('Data') is not None:
            for k1 in m.get('Data'):
                temp_model = main_models.DescribeInstanceStatisticsResponseBodyData()
                self.data.append(temp_model.from_map(k1))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class DescribeInstanceStatisticsResponseBodyData(DaraModel):
    def __init__(
        self,
        account: int = None,
        agentless_all: int = None,
        agentless_baseline: int = None,
        agentless_malicious: int = None,
        agentless_sensitive_file: int = None,
        agentless_vul_cve: int = None,
        agentless_vul_sca: int = None,
        agentless_vul_sys: int = None,
        app_num: int = None,
        cms_num: int = None,
        cspm_high_risk_num: str = None,
        cspm_num: int = None,
        cve_num: int = None,
        emg_num: int = None,
        health: int = None,
        remind_suspicious_num: str = None,
        sca_num: int = None,
        serious_suspicious_num: str = None,
        suspect_suspicious_num: str = None,
        suspicious: int = None,
        sys_asap_vul_count: str = None,
        sys_num: int = None,
        trojan: int = None,
        uuid: str = None,
        vul: int = None,
        weak_pwnum: int = None,
    ):
        # The number of unusual logons to the asset.
        self.account = account
        # The number of alerts generated by the agentless detection feature.
        self.agentless_all = agentless_all
        # The number of baseline risks detected by the agentless detection feature.
        self.agentless_baseline = agentless_baseline
        # The number of malicious samples detected by the agentless detection feature.
        self.agentless_malicious = agentless_malicious
        # The number of sensitive file alerts generated by the agentless detection feature.
        self.agentless_sensitive_file = agentless_sensitive_file
        # The number of system vulnerabilities detected by the agentless detection feature.
        self.agentless_vul_cve = agentless_vul_cve
        # The number of application vulnerabilities detected by the agentless detection feature.
        self.agentless_vul_sca = agentless_vul_sca
        # The number of Windows vulnerabilities detected by using agentless detection.
        self.agentless_vul_sys = agentless_vul_sys
        # The number of application vulnerabilities detected on the asset.
        self.app_num = app_num
        # The number of Web-CMS vulnerabilities detected on the asset.
        self.cms_num = cms_num
        # Number of high-risk CSPM issues in the system
        self.cspm_high_risk_num = cspm_high_risk_num
        # The number of configuration risks detected on the asset.
        self.cspm_num = cspm_num
        # The number of common vulnerabilities detected on the asset.
        self.cve_num = cve_num
        # The number of urgent vulnerabilities detected on the asset.
        self.emg_num = emg_num
        # The number of baseline risks detected on the asset.
        self.health = health
        # Number of security alerts for asset existence reminders.
        self.remind_suspicious_num = remind_suspicious_num
        # The number of middleware vulnerabilities detected on the asset.
        self.sca_num = sca_num
        # Number of high-risk security alerts for the asset.
        self.serious_suspicious_num = serious_suspicious_num
        # Number of suspicious security alerts for the asset.
        self.suspect_suspicious_num = suspect_suspicious_num
        # The number of alerts generated for the asset.
        self.suspicious = suspicious
        # Number of system vulnerabilities in the asset.
        self.sys_asap_vul_count = sys_asap_vul_count
        # The number of Windows system vulnerabilities detected on the asset.
        self.sys_num = sys_num
        # The number of trojans detected on the asset.
        self.trojan = trojan
        # The UUID of the asset.
        self.uuid = uuid
        # The total number of vulnerabilities detected on the asset.
        self.vul = vul
        # The number of weak passwords.
        self.weak_pwnum = weak_pwnum

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.account is not None:
            result['Account'] = self.account

        if self.agentless_all is not None:
            result['AgentlessAll'] = self.agentless_all

        if self.agentless_baseline is not None:
            result['AgentlessBaseline'] = self.agentless_baseline

        if self.agentless_malicious is not None:
            result['AgentlessMalicious'] = self.agentless_malicious

        if self.agentless_sensitive_file is not None:
            result['AgentlessSensitiveFile'] = self.agentless_sensitive_file

        if self.agentless_vul_cve is not None:
            result['AgentlessVulCve'] = self.agentless_vul_cve

        if self.agentless_vul_sca is not None:
            result['AgentlessVulSca'] = self.agentless_vul_sca

        if self.agentless_vul_sys is not None:
            result['AgentlessVulSys'] = self.agentless_vul_sys

        if self.app_num is not None:
            result['AppNum'] = self.app_num

        if self.cms_num is not None:
            result['CmsNum'] = self.cms_num

        if self.cspm_high_risk_num is not None:
            result['CspmHighRiskNum'] = self.cspm_high_risk_num

        if self.cspm_num is not None:
            result['CspmNum'] = self.cspm_num

        if self.cve_num is not None:
            result['CveNum'] = self.cve_num

        if self.emg_num is not None:
            result['EmgNum'] = self.emg_num

        if self.health is not None:
            result['Health'] = self.health

        if self.remind_suspicious_num is not None:
            result['RemindSuspiciousNum'] = self.remind_suspicious_num

        if self.sca_num is not None:
            result['ScaNum'] = self.sca_num

        if self.serious_suspicious_num is not None:
            result['SeriousSuspiciousNum'] = self.serious_suspicious_num

        if self.suspect_suspicious_num is not None:
            result['SuspectSuspiciousNum'] = self.suspect_suspicious_num

        if self.suspicious is not None:
            result['Suspicious'] = self.suspicious

        if self.sys_asap_vul_count is not None:
            result['SysAsapVulCount'] = self.sys_asap_vul_count

        if self.sys_num is not None:
            result['SysNum'] = self.sys_num

        if self.trojan is not None:
            result['Trojan'] = self.trojan

        if self.uuid is not None:
            result['Uuid'] = self.uuid

        if self.vul is not None:
            result['Vul'] = self.vul

        if self.weak_pwnum is not None:
            result['WeakPWNum'] = self.weak_pwnum

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Account') is not None:
            self.account = m.get('Account')

        if m.get('AgentlessAll') is not None:
            self.agentless_all = m.get('AgentlessAll')

        if m.get('AgentlessBaseline') is not None:
            self.agentless_baseline = m.get('AgentlessBaseline')

        if m.get('AgentlessMalicious') is not None:
            self.agentless_malicious = m.get('AgentlessMalicious')

        if m.get('AgentlessSensitiveFile') is not None:
            self.agentless_sensitive_file = m.get('AgentlessSensitiveFile')

        if m.get('AgentlessVulCve') is not None:
            self.agentless_vul_cve = m.get('AgentlessVulCve')

        if m.get('AgentlessVulSca') is not None:
            self.agentless_vul_sca = m.get('AgentlessVulSca')

        if m.get('AgentlessVulSys') is not None:
            self.agentless_vul_sys = m.get('AgentlessVulSys')

        if m.get('AppNum') is not None:
            self.app_num = m.get('AppNum')

        if m.get('CmsNum') is not None:
            self.cms_num = m.get('CmsNum')

        if m.get('CspmHighRiskNum') is not None:
            self.cspm_high_risk_num = m.get('CspmHighRiskNum')

        if m.get('CspmNum') is not None:
            self.cspm_num = m.get('CspmNum')

        if m.get('CveNum') is not None:
            self.cve_num = m.get('CveNum')

        if m.get('EmgNum') is not None:
            self.emg_num = m.get('EmgNum')

        if m.get('Health') is not None:
            self.health = m.get('Health')

        if m.get('RemindSuspiciousNum') is not None:
            self.remind_suspicious_num = m.get('RemindSuspiciousNum')

        if m.get('ScaNum') is not None:
            self.sca_num = m.get('ScaNum')

        if m.get('SeriousSuspiciousNum') is not None:
            self.serious_suspicious_num = m.get('SeriousSuspiciousNum')

        if m.get('SuspectSuspiciousNum') is not None:
            self.suspect_suspicious_num = m.get('SuspectSuspiciousNum')

        if m.get('Suspicious') is not None:
            self.suspicious = m.get('Suspicious')

        if m.get('SysAsapVulCount') is not None:
            self.sys_asap_vul_count = m.get('SysAsapVulCount')

        if m.get('SysNum') is not None:
            self.sys_num = m.get('SysNum')

        if m.get('Trojan') is not None:
            self.trojan = m.get('Trojan')

        if m.get('Uuid') is not None:
            self.uuid = m.get('Uuid')

        if m.get('Vul') is not None:
            self.vul = m.get('Vul')

        if m.get('WeakPWNum') is not None:
            self.weak_pwnum = m.get('WeakPWNum')

        return self

