# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class GetValidDeductInstancesResponseBody(DaraModel):
    def __init__(
        self,
        data: main_models.GetValidDeductInstancesResponseBodyData = None,
        request_id: str = None,
    ):
        # Returned data.
        self.data = data
        # The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and locate issues.
        self.request_id = request_id

    def validate(self):
        if self.data:
            self.data.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.data is not None:
            result['Data'] = self.data.to_map()

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Data') is not None:
            temp_model = main_models.GetValidDeductInstancesResponseBodyData()
            self.data = temp_model.from_map(m.get('Data'))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class GetValidDeductInstancesResponseBodyData(DaraModel):
    def __init__(
        self,
        can_try: bool = None,
        deduct_package_list: List[main_models.GetValidDeductInstancesResponseBodyDataDeductPackageList] = None,
    ):
        # Whether eligible for trial. Values:
        # - **true**: Eligible
        # - **false**: Not eligible
        self.can_try = can_try
        # List of resource package usage details.
        self.deduct_package_list = deduct_package_list

    def validate(self):
        if self.deduct_package_list:
            for v1 in self.deduct_package_list:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.can_try is not None:
            result['CanTry'] = self.can_try

        result['DeductPackageList'] = []
        if self.deduct_package_list is not None:
            for k1 in self.deduct_package_list:
                result['DeductPackageList'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('CanTry') is not None:
            self.can_try = m.get('CanTry')

        self.deduct_package_list = []
        if m.get('DeductPackageList') is not None:
            for k1 in m.get('DeductPackageList'):
                temp_model = main_models.GetValidDeductInstancesResponseBodyDataDeductPackageList()
                self.deduct_package_list.append(temp_model.from_map(k1))

        return self

class GetValidDeductInstancesResponseBodyDataDeductPackageList(DaraModel):
    def __init__(
        self,
        current_period_used: int = None,
        end_time: int = None,
        init_capacity: float = None,
        instance_id: str = None,
        module: str = None,
        period_capacity: float = None,
        start_time: int = None,
        status: str = None,
    ):
        # Authorized consumption in the current billing cycle.
        self.current_period_used = current_period_used
        # End time.
        self.end_time = end_time
        # Total amount of the resource package.
        self.init_capacity = init_capacity
        # Resource package instance ID.
        self.instance_id = instance_id
        # Module code. Values:
        # - **POST_HOST**: Host and container protection
        # - **CSPM**: Cloud product configuration check
        # - **VUL**: Vulnerability scan
        self.module = module
        # Authorized consumption up to the previous billing cycle.
        self.period_capacity = period_capacity
        # Start timestamp (milliseconds).
        self.start_time = start_time
        # Resource package status. Values:
        # - **valid**: Valid
        # - **invalid**: Invalid
        self.status = status

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.current_period_used is not None:
            result['CurrentPeriodUsed'] = self.current_period_used

        if self.end_time is not None:
            result['EndTime'] = self.end_time

        if self.init_capacity is not None:
            result['InitCapacity'] = self.init_capacity

        if self.instance_id is not None:
            result['InstanceId'] = self.instance_id

        if self.module is not None:
            result['Module'] = self.module

        if self.period_capacity is not None:
            result['PeriodCapacity'] = self.period_capacity

        if self.start_time is not None:
            result['StartTime'] = self.start_time

        if self.status is not None:
            result['Status'] = self.status

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('CurrentPeriodUsed') is not None:
            self.current_period_used = m.get('CurrentPeriodUsed')

        if m.get('EndTime') is not None:
            self.end_time = m.get('EndTime')

        if m.get('InitCapacity') is not None:
            self.init_capacity = m.get('InitCapacity')

        if m.get('InstanceId') is not None:
            self.instance_id = m.get('InstanceId')

        if m.get('Module') is not None:
            self.module = m.get('Module')

        if m.get('PeriodCapacity') is not None:
            self.period_capacity = m.get('PeriodCapacity')

        if m.get('StartTime') is not None:
            self.start_time = m.get('StartTime')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        return self

