# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class ListSupportAttackPathAssetResponseBody(DaraModel):
    def __init__(
        self,
        attack_path_asset_type_list: List[main_models.ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList] = None,
        request_id: str = None,
    ):
        # List of cloud product asset types for the attack path.
        self.attack_path_asset_type_list = attack_path_asset_type_list
        # The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.
        self.request_id = request_id

    def validate(self):
        if self.attack_path_asset_type_list:
            for v1 in self.attack_path_asset_type_list:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['AttackPathAssetTypeList'] = []
        if self.attack_path_asset_type_list is not None:
            for k1 in self.attack_path_asset_type_list:
                result['AttackPathAssetTypeList'].append(k1.to_map() if k1 else None)

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.attack_path_asset_type_list = []
        if m.get('AttackPathAssetTypeList') is not None:
            for k1 in m.get('AttackPathAssetTypeList'):
                temp_model = main_models.ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList()
                self.attack_path_asset_type_list.append(temp_model.from_map(k1))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class ListSupportAttackPathAssetResponseBodyAttackPathAssetTypeList(DaraModel):
    def __init__(
        self,
        asset_sub_type: int = None,
        asset_type: int = None,
        vendor: int = None,
    ):
        # Subtype of the cloud product asset.
        self.asset_sub_type = asset_sub_type
        # Type of the cloud product asset.
        self.asset_type = asset_type
        # Vendor of the cloud product asset.
        self.vendor = vendor

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.asset_sub_type is not None:
            result['AssetSubType'] = self.asset_sub_type

        if self.asset_type is not None:
            result['AssetType'] = self.asset_type

        if self.vendor is not None:
            result['Vendor'] = self.vendor

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AssetSubType') is not None:
            self.asset_sub_type = m.get('AssetSubType')

        if m.get('AssetType') is not None:
            self.asset_type = m.get('AssetType')

        if m.get('Vendor') is not None:
            self.vendor = m.get('Vendor')

        return self

