# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class ListAvailableAttackPathResponseBody(DaraModel):
    def __init__(
        self,
        attack_path_list: List[main_models.ListAvailableAttackPathResponseBodyAttackPathList] = None,
        request_id: str = None,
    ):
        # List of attack paths.
        self.attack_path_list = attack_path_list
        # The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and locate issues.
        self.request_id = request_id

    def validate(self):
        if self.attack_path_list:
            for v1 in self.attack_path_list:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['AttackPathList'] = []
        if self.attack_path_list is not None:
            for k1 in self.attack_path_list:
                result['AttackPathList'].append(k1.to_map() if k1 else None)

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.attack_path_list = []
        if m.get('AttackPathList') is not None:
            for k1 in m.get('AttackPathList'):
                temp_model = main_models.ListAvailableAttackPathResponseBodyAttackPathList()
                self.attack_path_list.append(temp_model.from_map(k1))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class ListAvailableAttackPathResponseBodyAttackPathList(DaraModel):
    def __init__(
        self,
        path_name: str = None,
        path_name_desc: str = None,
        path_type: str = None,
        path_type_desc: str = None,
    ):
        # Path name.
        self.path_name = path_name
        # Description of the path name.
        self.path_name_desc = path_name_desc
        # Path type.
        self.path_type = path_type
        # Description of the path type.
        self.path_type_desc = path_type_desc

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.path_name is not None:
            result['PathName'] = self.path_name

        if self.path_name_desc is not None:
            result['PathNameDesc'] = self.path_name_desc

        if self.path_type is not None:
            result['PathType'] = self.path_type

        if self.path_type_desc is not None:
            result['PathTypeDesc'] = self.path_type_desc

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('PathName') is not None:
            self.path_name = m.get('PathName')

        if m.get('PathNameDesc') is not None:
            self.path_name_desc = m.get('PathNameDesc')

        if m.get('PathType') is not None:
            self.path_type = m.get('PathType')

        if m.get('PathTypeDesc') is not None:
            self.path_type_desc = m.get('PathTypeDesc')

        return self

