# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sas20181203 import models as main_models
from darabonba.model import DaraModel

class UpdateMultiUserInstancesResponseBody(DaraModel):
    def __init__(
        self,
        request_id: str = None,
        result: List[main_models.UpdateMultiUserInstancesResponseBodyResult] = None,
    ):
        # The ID of this call request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem location.
        self.request_id = request_id
        # Request processing result.
        self.result = result

    def validate(self):
        if self.result:
            for v1 in self.result:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.request_id is not None:
            result['RequestId'] = self.request_id

        result['Result'] = []
        if self.result is not None:
            for k1 in self.result:
                result['Result'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        self.result = []
        if m.get('Result') is not None:
            for k1 in m.get('Result'):
                temp_model = main_models.UpdateMultiUserInstancesResponseBodyResult()
                self.result.append(temp_model.from_map(k1))

        return self

class UpdateMultiUserInstancesResponseBodyResult(DaraModel):
    def __init__(
        self,
        ali_uid: int = None,
        error_message: str = None,
        instance_id: str = None,
        update_status: str = None,
    ):
        # User UID.
        self.ali_uid = ali_uid
        # Error message returned when the call fails.
        self.error_message = error_message
        # The Cloud Security Center instance ID purchased by the member account.
        self.instance_id = instance_id
        # Update status. Values:  
        # - **1**：Success 
        # - **2**：Failure
        self.update_status = update_status

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.ali_uid is not None:
            result['AliUid'] = self.ali_uid

        if self.error_message is not None:
            result['ErrorMessage'] = self.error_message

        if self.instance_id is not None:
            result['InstanceId'] = self.instance_id

        if self.update_status is not None:
            result['UpdateStatus'] = self.update_status

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AliUid') is not None:
            self.ali_uid = m.get('AliUid')

        if m.get('ErrorMessage') is not None:
            self.error_message = m.get('ErrorMessage')

        if m.get('InstanceId') is not None:
            self.instance_id = m.get('InstanceId')

        if m.get('UpdateStatus') is not None:
            self.update_status = m.get('UpdateStatus')

        return self

