# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class ImageModerationRequest(DaraModel):
    def __init__(
        self,
        service: str = None,
        service_parameters: str = None,
    ):
        # The detection types supported by the enhanced image moderation feature. Valid values:
        # 
        # - baselineCheck: general baseline check
        # 
        # - baselineCheck_pro: general baseline check (Professional Edition)
        # 
        # - baselineCheck_cb: general baseline check (outside China)
        # 
        # - tonalityImprove: content administration check
        # 
        # - aigcCheck: AIGC image check
        # 
        # - aigcViolationDetection: AIGC image infringement detection
        # 
        # - aigcDetector: determines whether an image is generated by AIGC
        # 
        # - profilePhotoCheck: profile picture check
        # 
        # - postImageCheck: image check for posts and comments
        # 
        # - advertisingCheck: marketing material check
        # 
        # - liveStreamCheck: video/livestream screenshot check
        # 
        # - generalOcr: general image and text OCR
        # 
        # - generalRecognition: image object recognition
        # 
        # - postImageCheckByVL: image moderation service with large and small models
        # 
        # - postImageCheckByVL_cb: image moderation service with large and small models (outside China)
        # 
        # - baselineCheckByVL: general image moderation service with a large model
        self.service = service
        # The parameters for the content to detect. The value is a JSON string.
        # 
        # - imageUrl: The URL of the object to detect. This parameter is required.
        # 
        # - dataId: The data ID of the object to detect. This parameter is optional.
        # 
        # - referer: The referer request header. This parameter is used for scenarios such as hotlink protection and is optional.
        self.service_parameters = service_parameters

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.service is not None:
            result['Service'] = self.service

        if self.service_parameters is not None:
            result['ServiceParameters'] = self.service_parameters

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Service') is not None:
            self.service = m.get('Service')

        if m.get('ServiceParameters') is not None:
            self.service_parameters = m.get('ServiceParameters')

        return self

