# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from darabonba.model import DaraModel

class DescribeGlobalDesktopsRequest(DaraModel):
    def __init__(
        self,
        client_id: str = None,
        desktop_access_type: str = None,
        desktop_id: List[str] = None,
        desktop_name: str = None,
        desktop_status: str = None,
        directory_id: str = None,
        keyword: str = None,
        language: str = None,
        login_region_id: str = None,
        login_token: str = None,
        max_results: int = None,
        next_token: str = None,
        office_site_id: str = None,
        order_by: str = None,
        query_fota_update: bool = None,
        region_id: str = None,
        search_region_id: str = None,
        session_id: str = None,
        sort_type: str = None,
        without_latency: bool = None,
    ):
        # A unique ID generated by the client.
        # 
        # This parameter is required.
        self.client_id = client_id
        # Connection type allowed when connecting to the cloud desktop.
        # 
        # > VPC connections depend on Alibaba Cloud PrivateLink, which incurs no additional charges. When you set this parameter to VPC or Any, PrivateLink is automatically enabled for you.
        self.desktop_access_type = desktop_access_type
        # Cloud desktop ID. You can specify one or more IDs. Valid values: 1 to 20.
        self.desktop_id = desktop_id
        # Cloud desktop name.
        self.desktop_name = desktop_name
        # Cloud desktop status.
        self.desktop_status = desktop_status
        # Office site ID.
        # 
        # > This parameter is deprecated. Use `OfficeSiteId` instead.
        self.directory_id = directory_id
        # Keyword. Supports fuzzy search on cloud desktop ID, cloud desktop name, and end-user-defined cloud desktop names.
        self.keyword = keyword
        self.language = language
        # Region ID of the office site. Leave this blank if you log on using an organization ID.
        # 
        # - Required if you log on using an office site ID.
        # 
        # - Optional if you log on using an organization ID.
        self.login_region_id = login_region_id
        # Login token. Get it by calling GetLoginToken, or refresh it by calling RefreshLoginToken. The response includes the LoginToken parameter.
        # 
        # This parameter is required.
        self.login_token = login_token
        # Number of entries per page for paged queries.
        # 
        # - Maximum: 500
        # 
        # - Default: 10
        self.max_results = max_results
        # Token that marks the start of the next query. If NextToken is empty, no more results are available.
        self.next_token = next_token
        # Office site ID.
        # 
        # > Use this field instead of `DirectoryId`, which is deprecated.
        self.office_site_id = office_site_id
        # Field to sort by. If not specified, results are sorted by creation time in descending order.
        self.order_by = order_by
        # Whether to query image update information.
        self.query_fota_update = query_fota_update
        # Region ID.
        self.region_id = region_id
        # Region ID used to filter cloud desktops by region.
        self.search_region_id = search_region_id
        # Session ID. Get it by calling the GetLoginToken operation. The response includes the SessionId parameter.
        self.session_id = session_id
        # Sorting order.
        self.sort_type = sort_type
        # Whether to query real-time cloud desktop information. Because cloud desktop status has a 1–3 second delay, set this value to `true` for accurate information.
        self.without_latency = without_latency

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.client_id is not None:
            result['ClientId'] = self.client_id

        if self.desktop_access_type is not None:
            result['DesktopAccessType'] = self.desktop_access_type

        if self.desktop_id is not None:
            result['DesktopId'] = self.desktop_id

        if self.desktop_name is not None:
            result['DesktopName'] = self.desktop_name

        if self.desktop_status is not None:
            result['DesktopStatus'] = self.desktop_status

        if self.directory_id is not None:
            result['DirectoryId'] = self.directory_id

        if self.keyword is not None:
            result['Keyword'] = self.keyword

        if self.language is not None:
            result['Language'] = self.language

        if self.login_region_id is not None:
            result['LoginRegionId'] = self.login_region_id

        if self.login_token is not None:
            result['LoginToken'] = self.login_token

        if self.max_results is not None:
            result['MaxResults'] = self.max_results

        if self.next_token is not None:
            result['NextToken'] = self.next_token

        if self.office_site_id is not None:
            result['OfficeSiteId'] = self.office_site_id

        if self.order_by is not None:
            result['OrderBy'] = self.order_by

        if self.query_fota_update is not None:
            result['QueryFotaUpdate'] = self.query_fota_update

        if self.region_id is not None:
            result['RegionId'] = self.region_id

        if self.search_region_id is not None:
            result['SearchRegionId'] = self.search_region_id

        if self.session_id is not None:
            result['SessionId'] = self.session_id

        if self.sort_type is not None:
            result['SortType'] = self.sort_type

        if self.without_latency is not None:
            result['WithoutLatency'] = self.without_latency

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ClientId') is not None:
            self.client_id = m.get('ClientId')

        if m.get('DesktopAccessType') is not None:
            self.desktop_access_type = m.get('DesktopAccessType')

        if m.get('DesktopId') is not None:
            self.desktop_id = m.get('DesktopId')

        if m.get('DesktopName') is not None:
            self.desktop_name = m.get('DesktopName')

        if m.get('DesktopStatus') is not None:
            self.desktop_status = m.get('DesktopStatus')

        if m.get('DirectoryId') is not None:
            self.directory_id = m.get('DirectoryId')

        if m.get('Keyword') is not None:
            self.keyword = m.get('Keyword')

        if m.get('Language') is not None:
            self.language = m.get('Language')

        if m.get('LoginRegionId') is not None:
            self.login_region_id = m.get('LoginRegionId')

        if m.get('LoginToken') is not None:
            self.login_token = m.get('LoginToken')

        if m.get('MaxResults') is not None:
            self.max_results = m.get('MaxResults')

        if m.get('NextToken') is not None:
            self.next_token = m.get('NextToken')

        if m.get('OfficeSiteId') is not None:
            self.office_site_id = m.get('OfficeSiteId')

        if m.get('OrderBy') is not None:
            self.order_by = m.get('OrderBy')

        if m.get('QueryFotaUpdate') is not None:
            self.query_fota_update = m.get('QueryFotaUpdate')

        if m.get('RegionId') is not None:
            self.region_id = m.get('RegionId')

        if m.get('SearchRegionId') is not None:
            self.search_region_id = m.get('SearchRegionId')

        if m.get('SessionId') is not None:
            self.session_id = m.get('SessionId')

        if m.get('SortType') is not None:
            self.sort_type = m.get('SortType')

        if m.get('WithoutLatency') is not None:
            self.without_latency = m.get('WithoutLatency')

        return self

