# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from darabonba.model import DaraModel

class DescribeGlobalDesktopsRequest(DaraModel):
    def __init__(
        self,
        client_id: str = None,
        desktop_access_type: str = None,
        desktop_id: List[str] = None,
        desktop_name: str = None,
        desktop_status: str = None,
        directory_id: str = None,
        keyword: str = None,
        language: str = None,
        login_region_id: str = None,
        login_token: str = None,
        max_results: int = None,
        next_token: str = None,
        office_site_id: str = None,
        order_by: str = None,
        query_fota_update: bool = None,
        region_id: str = None,
        search_region_id: str = None,
        session_id: str = None,
        sort_type: str = None,
        without_latency: bool = None,
    ):
        # The unique ID generated by the client.
        # 
        # This parameter is required.
        self.client_id = client_id
        # The method that is used to connect cloud computers that reside in the office network from WUYING clients.
        # 
        # >  The VPC connection method depends on Alibaba Cloud PrivateLink. You can use PrivateLink for free. If you set this parameter to VPC or Any, the system automatically enables PrivateLink.
        # 
        # Valid values:
        # 
        # *   INTERNET (default): End users connect to cloud computers from clients over the Internet.
        # *   VPC: End users connect to cloud computers from clients over a virtual private cloud (VPC).
        # *   Any: End users connect to cloud computers from clients over the Internet or a VPC.
        self.desktop_access_type = desktop_access_type
        # The cloud computer ID. You can specify one or more cloud computer IDs. Valid values: 1 to 20.
        self.desktop_id = desktop_id
        # The cloud computer name.
        self.desktop_name = desktop_name
        # The cloud computer status.
        # 
        # Valid value:
        # 
        # *   Stopped
        # *   Starting.
        # *   Rebuilding
        # *   Running:.
        # *   Stopping:.
        # *   Expired
        # *   Deleted
        # *   Pending: The resource is still being prepared.
        self.desktop_status = desktop_status
        # The office network IDs.
        # 
        # >  This parameter is about to be disabled. Use `OfficeSiteId`.
        self.directory_id = directory_id
        # The keyword. Fuzzy search is supported for cloud computer IDs, cloud computer names, and end user custom cloud computer names.
        self.keyword = keyword
        self.language = language
        # The ID of the region where the office network resides. This parameter is left empty when you log on with an organization ID.
        # 
        # *   This parameter is required when you log on by using the office network ID.
        # *   If you log on by using an organization ID, this parameter can be left empty.
        self.login_region_id = login_region_id
        # The logon token. You can call the GetLoginToken operation to obtain the token. You can also call the UpdateToken operation to obtain the token RefreshLoginToken. Response parameter: LoginToken.
        # 
        # This parameter is required.
        self.login_token = login_token
        # The number of entries per page.
        # 
        # *   Maximum value: 500.
        # *   and the default value is 10.
        self.max_results = max_results
        # The token used to start the next query. If NextToken is empty, it indicates that there is no next query.
        self.next_token = next_token
        # The office network IDs.
        # 
        # >  `DirectoryId` the parameter is about to be retired, use this field.
        self.office_site_id = office_site_id
        # The field used for sorting. If you do not specify this option, the system is sorted in descending order of creation time.
        # 
        # Valid values:
        # 
        # *   AssignTime: sort by allocation time.
        self.order_by = order_by
        # Specifies whether to query information about the image update.
        self.query_fota_update = query_fota_update
        # The region ID.
        # 
        # Valid value:
        # 
        # *   cn-shanghai: China (Shanghai)
        self.region_id = region_id
        # The ID of the searched region. You can specify this parameter to filter cloud computers in specific regions.
        self.search_region_id = search_region_id
        # The session ID. You can call the GetLoginToken operation to query the value of the SessionId parameter.
        self.session_id = session_id
        # The sorting method.
        # 
        # Valid values:
        # 
        # *   ASC (default): the ascending order.
        # *   DESC: the descending order.
        self.sort_type = sort_type
        # Whether to query real-time cloud computer information. The cloud computer status information in the current interface has a delay of 1 to 3 seconds. If you need accurate information, set this value to `true`.
        self.without_latency = without_latency

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.client_id is not None:
            result['ClientId'] = self.client_id

        if self.desktop_access_type is not None:
            result['DesktopAccessType'] = self.desktop_access_type

        if self.desktop_id is not None:
            result['DesktopId'] = self.desktop_id

        if self.desktop_name is not None:
            result['DesktopName'] = self.desktop_name

        if self.desktop_status is not None:
            result['DesktopStatus'] = self.desktop_status

        if self.directory_id is not None:
            result['DirectoryId'] = self.directory_id

        if self.keyword is not None:
            result['Keyword'] = self.keyword

        if self.language is not None:
            result['Language'] = self.language

        if self.login_region_id is not None:
            result['LoginRegionId'] = self.login_region_id

        if self.login_token is not None:
            result['LoginToken'] = self.login_token

        if self.max_results is not None:
            result['MaxResults'] = self.max_results

        if self.next_token is not None:
            result['NextToken'] = self.next_token

        if self.office_site_id is not None:
            result['OfficeSiteId'] = self.office_site_id

        if self.order_by is not None:
            result['OrderBy'] = self.order_by

        if self.query_fota_update is not None:
            result['QueryFotaUpdate'] = self.query_fota_update

        if self.region_id is not None:
            result['RegionId'] = self.region_id

        if self.search_region_id is not None:
            result['SearchRegionId'] = self.search_region_id

        if self.session_id is not None:
            result['SessionId'] = self.session_id

        if self.sort_type is not None:
            result['SortType'] = self.sort_type

        if self.without_latency is not None:
            result['WithoutLatency'] = self.without_latency

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ClientId') is not None:
            self.client_id = m.get('ClientId')

        if m.get('DesktopAccessType') is not None:
            self.desktop_access_type = m.get('DesktopAccessType')

        if m.get('DesktopId') is not None:
            self.desktop_id = m.get('DesktopId')

        if m.get('DesktopName') is not None:
            self.desktop_name = m.get('DesktopName')

        if m.get('DesktopStatus') is not None:
            self.desktop_status = m.get('DesktopStatus')

        if m.get('DirectoryId') is not None:
            self.directory_id = m.get('DirectoryId')

        if m.get('Keyword') is not None:
            self.keyword = m.get('Keyword')

        if m.get('Language') is not None:
            self.language = m.get('Language')

        if m.get('LoginRegionId') is not None:
            self.login_region_id = m.get('LoginRegionId')

        if m.get('LoginToken') is not None:
            self.login_token = m.get('LoginToken')

        if m.get('MaxResults') is not None:
            self.max_results = m.get('MaxResults')

        if m.get('NextToken') is not None:
            self.next_token = m.get('NextToken')

        if m.get('OfficeSiteId') is not None:
            self.office_site_id = m.get('OfficeSiteId')

        if m.get('OrderBy') is not None:
            self.order_by = m.get('OrderBy')

        if m.get('QueryFotaUpdate') is not None:
            self.query_fota_update = m.get('QueryFotaUpdate')

        if m.get('RegionId') is not None:
            self.region_id = m.get('RegionId')

        if m.get('SearchRegionId') is not None:
            self.search_region_id = m.get('SearchRegionId')

        if m.get('SessionId') is not None:
            self.session_id = m.get('SessionId')

        if m.get('SortType') is not None:
            self.sort_type = m.get('SortType')

        if m.get('WithoutLatency') is not None:
            self.without_latency = m.get('WithoutLatency')

        return self

