# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class GetLoginTokenShrinkRequest(DaraModel):
    def __init__(
        self,
        authentication_code: str = None,
        available_features_shrink: str = None,
        client_id: str = None,
        client_name: str = None,
        client_os: str = None,
        client_type: str = None,
        client_version: str = None,
        current_stage: str = None,
        directory_id: str = None,
        end_user_id: str = None,
        keep_alive: bool = None,
        keep_alive_token: str = None,
        new_password: str = None,
        office_site_id: str = None,
        old_password: str = None,
        password: str = None,
        region_id: str = None,
        session_id: str = None,
        token_code: str = None,
        uuid: str = None,
    ):
        # The security code generated by the virtual MFA device. This parameter is required when `CurrentStage` is set to `MFAVerify`.
        self.authentication_code = authentication_code
        self.available_features_shrink = available_features_shrink
        # The unique ID generated by the client.
        # 
        # This parameter is required.
        self.client_id = client_id
        self.client_name = client_name
        # The operating system of the device on which the client runs.
        self.client_os = client_os
        # The type of the Elastic Desktop Service software client.
        self.client_type = client_type
        # The client version. If you use the Elastic Desktop Service client, you can view this parameter in the **About** dialog box on the client logon page.
        self.client_version = client_version
        # The current logon authentication stage. The stages are as follows:
        # 
        # - `ADPassword`: verifies user information. Specify this value when authenticating with the credentials of a convenience account or an AD account.
        # - `MFABind`: binds a virtual MFA device.
        # - `MFAVerify`: verifies the security code generated by the virtual MFA device.
        # - `TokenVerify`: performs client secondary authentication.
        # - `ChangePassword`: changes the user password.
        # - `KeepAliveVerify`: exchanges a valid KeepAliveToken for a LoginToken.
        self.current_stage = current_stage
        # The office network ID, which has the same meaning as `OfficeSiteId`. We recommend that you stop using `DirectoryId` and use `OfficeSiteId` instead. You can specify only one of `DirectoryId` and `OfficeSiteId`, not both.
        self.directory_id = directory_id
        # The username of the convenience user or AD user. This parameter is required when `CurrentStage` is set to `ADPassword`.
        self.end_user_id = end_user_id
        # Specifies whether to keep the logon session alive.
        self.keep_alive = keep_alive
        # The token used to keep the logon session alive. After a successful logon with the keep-alive option enabled, the operation returns a `KeepAliveToken`. While the `KeepAliveToken` is valid, you can call the `GetLoginToken` operation with `CurrentStage` set to `KeepAliveVerify` to exchange it for a logon credential (LoginToken). This parameter is required when `CurrentStage` is set to `KeepAliveVerify`.
        self.keep_alive_token = keep_alive_token
        # The new password. This parameter is required when `CurrentStage` is set to `ChangePassword`.
        self.new_password = new_password
        # The office network ID.
        self.office_site_id = office_site_id
        # The old password. This parameter is required when `CurrentStage` is set to `ChangePassword`.
        self.old_password = old_password
        # The password of the convenience user or AD user. This parameter is required when `CurrentStage` is set to `ADPassword`.
        self.password = password
        # The region ID. You can call [DescribeRegions](https://help.aliyun.com/document_detail/196646.html) to query the regions supported by Elastic Desktop Service.
        # 
        # This parameter is required.
        self.region_id = region_id
        # The session ID for logon.
        # 
        # - If no virtual MFA device is bound or client secondary authentication is not enabled, you do not need to specify `SessionId`.
        # - If a virtual MFA device is bound or client secondary authentication is enabled, you must specify `SessionId` for the authentication stages after `ADPassword`. You can obtain `SessionId` from the response of the convenience account verification (when the `GetLoginToken` request is in the `ADPassword` stage).
        self.session_id = session_id
        # If client secondary authentication is enabled in the Elastic Desktop Service console and the current logon user is identified as risky, a secondary authentication verification code is sent to the end user\\"s email address. This parameter is required when `CurrentStage` is set to `TokenVerify`.
        self.token_code = token_code
        # The unique identifier of the client. If you use the Elastic Desktop Service client, you can view this parameter in the **About** dialog box on the client logon page.
        self.uuid = uuid

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.authentication_code is not None:
            result['AuthenticationCode'] = self.authentication_code

        if self.available_features_shrink is not None:
            result['AvailableFeatures'] = self.available_features_shrink

        if self.client_id is not None:
            result['ClientId'] = self.client_id

        if self.client_name is not None:
            result['ClientName'] = self.client_name

        if self.client_os is not None:
            result['ClientOS'] = self.client_os

        if self.client_type is not None:
            result['ClientType'] = self.client_type

        if self.client_version is not None:
            result['ClientVersion'] = self.client_version

        if self.current_stage is not None:
            result['CurrentStage'] = self.current_stage

        if self.directory_id is not None:
            result['DirectoryId'] = self.directory_id

        if self.end_user_id is not None:
            result['EndUserId'] = self.end_user_id

        if self.keep_alive is not None:
            result['KeepAlive'] = self.keep_alive

        if self.keep_alive_token is not None:
            result['KeepAliveToken'] = self.keep_alive_token

        if self.new_password is not None:
            result['NewPassword'] = self.new_password

        if self.office_site_id is not None:
            result['OfficeSiteId'] = self.office_site_id

        if self.old_password is not None:
            result['OldPassword'] = self.old_password

        if self.password is not None:
            result['Password'] = self.password

        if self.region_id is not None:
            result['RegionId'] = self.region_id

        if self.session_id is not None:
            result['SessionId'] = self.session_id

        if self.token_code is not None:
            result['TokenCode'] = self.token_code

        if self.uuid is not None:
            result['Uuid'] = self.uuid

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AuthenticationCode') is not None:
            self.authentication_code = m.get('AuthenticationCode')

        if m.get('AvailableFeatures') is not None:
            self.available_features_shrink = m.get('AvailableFeatures')

        if m.get('ClientId') is not None:
            self.client_id = m.get('ClientId')

        if m.get('ClientName') is not None:
            self.client_name = m.get('ClientName')

        if m.get('ClientOS') is not None:
            self.client_os = m.get('ClientOS')

        if m.get('ClientType') is not None:
            self.client_type = m.get('ClientType')

        if m.get('ClientVersion') is not None:
            self.client_version = m.get('ClientVersion')

        if m.get('CurrentStage') is not None:
            self.current_stage = m.get('CurrentStage')

        if m.get('DirectoryId') is not None:
            self.directory_id = m.get('DirectoryId')

        if m.get('EndUserId') is not None:
            self.end_user_id = m.get('EndUserId')

        if m.get('KeepAlive') is not None:
            self.keep_alive = m.get('KeepAlive')

        if m.get('KeepAliveToken') is not None:
            self.keep_alive_token = m.get('KeepAliveToken')

        if m.get('NewPassword') is not None:
            self.new_password = m.get('NewPassword')

        if m.get('OfficeSiteId') is not None:
            self.office_site_id = m.get('OfficeSiteId')

        if m.get('OldPassword') is not None:
            self.old_password = m.get('OldPassword')

        if m.get('Password') is not None:
            self.password = m.get('Password')

        if m.get('RegionId') is not None:
            self.region_id = m.get('RegionId')

        if m.get('SessionId') is not None:
            self.session_id = m.get('SessionId')

        if m.get('TokenCode') is not None:
            self.token_code = m.get('TokenCode')

        if m.get('Uuid') is not None:
            self.uuid = m.get('Uuid')

        return self

