# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from ._add_mds_mini_config_request import AddMdsMiniConfigRequest
from ._add_mds_mini_config_response_body import AddMdsMiniConfigResponseBody
from ._add_mds_mini_config_response import AddMdsMiniConfigResponse
from ._cancel_push_scheduler_request import CancelPushSchedulerRequest
from ._cancel_push_scheduler_response_body import CancelPushSchedulerResponseBody
from ._cancel_push_scheduler_response import CancelPushSchedulerResponse
from ._change_mcube_mini_task_status_request import ChangeMcubeMiniTaskStatusRequest
from ._change_mcube_mini_task_status_response_body import ChangeMcubeMiniTaskStatusResponseBody
from ._change_mcube_mini_task_status_response import ChangeMcubeMiniTaskStatusResponse
from ._change_mcube_nebula_task_status_request import ChangeMcubeNebulaTaskStatusRequest
from ._change_mcube_nebula_task_status_response_body import ChangeMcubeNebulaTaskStatusResponseBody
from ._change_mcube_nebula_task_status_response import ChangeMcubeNebulaTaskStatusResponse
from ._change_mcube_public_task_status_request import ChangeMcubePublicTaskStatusRequest
from ._change_mcube_public_task_status_response_body import ChangeMcubePublicTaskStatusResponseBody
from ._change_mcube_public_task_status_response import ChangeMcubePublicTaskStatusResponse
from ._change_mds_cube_task_status_request import ChangeMdsCubeTaskStatusRequest
from ._change_mds_cube_task_status_response_body import ChangeMdsCubeTaskStatusResponseBody
from ._change_mds_cube_task_status_response import ChangeMdsCubeTaskStatusResponse
from ._copy_mcdp_group_request import CopyMcdpGroupRequest
from ._copy_mcdp_group_response_body import CopyMcdpGroupResponseBody
from ._copy_mcdp_group_response import CopyMcdpGroupResponse
from ._create_link_request import CreateLinkRequest
from ._create_link_response_body import CreateLinkResponseBody
from ._create_link_response import CreateLinkResponse
from ._create_mcdp_group_request import CreateMcdpGroupRequest
from ._create_mcdp_group_response_body import CreateMcdpGroupResponseBody
from ._create_mcdp_group_response import CreateMcdpGroupResponse
from ._create_mcdp_material_request import CreateMcdpMaterialRequest
from ._create_mcdp_material_response_body import CreateMcdpMaterialResponseBody
from ._create_mcdp_material_response import CreateMcdpMaterialResponse
from ._create_mcdp_zone_request import CreateMcdpZoneRequest
from ._create_mcdp_zone_response_body import CreateMcdpZoneResponseBody
from ._create_mcdp_zone_response import CreateMcdpZoneResponse
from ._create_mcube_hotpatch_resource_request import CreateMcubeHotpatchResourceRequest
from ._create_mcube_hotpatch_resource_response_body import CreateMcubeHotpatchResourceResponseBody
from ._create_mcube_hotpatch_resource_response import CreateMcubeHotpatchResourceResponse
from ._create_mcube_hotpatch_rollback_task_request import CreateMcubeHotpatchRollbackTaskRequest
from ._create_mcube_hotpatch_rollback_task_response_body import CreateMcubeHotpatchRollbackTaskResponseBody
from ._create_mcube_hotpatch_rollback_task_response import CreateMcubeHotpatchRollbackTaskResponse
from ._create_mcube_hotpatch_task_request import CreateMcubeHotpatchTaskRequest
from ._create_mcube_hotpatch_task_response_body import CreateMcubeHotpatchTaskResponseBody
from ._create_mcube_hotpatch_task_response import CreateMcubeHotpatchTaskResponse
from ._create_mcube_mini_app_request import CreateMcubeMiniAppRequest
from ._create_mcube_mini_app_response_body import CreateMcubeMiniAppResponseBody
from ._create_mcube_mini_app_response import CreateMcubeMiniAppResponse
from ._create_mcube_mini_task_request import CreateMcubeMiniTaskRequest
from ._create_mcube_mini_task_response_body import CreateMcubeMiniTaskResponseBody
from ._create_mcube_mini_task_response import CreateMcubeMiniTaskResponse
from ._create_mcube_nebula_app_request import CreateMcubeNebulaAppRequest
from ._create_mcube_nebula_app_response_body import CreateMcubeNebulaAppResponseBody
from ._create_mcube_nebula_app_response import CreateMcubeNebulaAppResponse
from ._create_mcube_nebula_resource_request import CreateMcubeNebulaResourceRequest
from ._create_mcube_nebula_resource_response_body import CreateMcubeNebulaResourceResponseBody
from ._create_mcube_nebula_resource_response import CreateMcubeNebulaResourceResponse
from ._create_mcube_nebula_task_request import CreateMcubeNebulaTaskRequest
from ._create_mcube_nebula_task_response_body import CreateMcubeNebulaTaskResponseBody
from ._create_mcube_nebula_task_response import CreateMcubeNebulaTaskResponse
from ._create_mcube_upgrade_package_request import CreateMcubeUpgradePackageRequest
from ._create_mcube_upgrade_package_response_body import CreateMcubeUpgradePackageResponseBody
from ._create_mcube_upgrade_package_response import CreateMcubeUpgradePackageResponse
from ._create_mcube_upgrade_task_request import CreateMcubeUpgradeTaskRequest
from ._create_mcube_upgrade_task_response_body import CreateMcubeUpgradeTaskResponseBody
from ._create_mcube_upgrade_task_response import CreateMcubeUpgradeTaskResponse
from ._create_mcube_vhost_request import CreateMcubeVhostRequest
from ._create_mcube_vhost_response_body import CreateMcubeVhostResponseBody
from ._create_mcube_vhost_response import CreateMcubeVhostResponse
from ._create_mcube_whitelist_request import CreateMcubeWhitelistRequest
from ._create_mcube_whitelist_response_body import CreateMcubeWhitelistResponseBody
from ._create_mcube_whitelist_response import CreateMcubeWhitelistResponse
from ._create_mcube_whitelist_for_ide_request import CreateMcubeWhitelistForIdeRequest
from ._create_mcube_whitelist_for_ide_response_body import CreateMcubeWhitelistForIdeResponseBody
from ._create_mcube_whitelist_for_ide_response import CreateMcubeWhitelistForIdeResponse
from ._create_mds_cube_resource_request import CreateMdsCubeResourceRequest
from ._create_mds_cube_resource_response_body import CreateMdsCubeResourceResponseBody
from ._create_mds_cube_resource_response import CreateMdsCubeResourceResponse
from ._create_mds_cube_task_request import CreateMdsCubeTaskRequest
from ._create_mds_cube_task_response_body import CreateMdsCubeTaskResponseBody
from ._create_mds_cube_task_response import CreateMdsCubeTaskResponse
from ._create_mds_cube_template_request import CreateMdsCubeTemplateRequest
from ._create_mds_cube_template_response_body import CreateMdsCubeTemplateResponseBody
from ._create_mds_cube_template_response import CreateMdsCubeTemplateResponse
from ._create_mds_miniprogram_task_request import CreateMdsMiniprogramTaskRequest
from ._create_mds_miniprogram_task_response_body import CreateMdsMiniprogramTaskResponseBody
from ._create_mds_miniprogram_task_response import CreateMdsMiniprogramTaskResponse
from ._create_open_global_data_request import CreateOpenGlobalDataRequest
from ._create_open_global_data_response_body import CreateOpenGlobalDataResponseBody
from ._create_open_global_data_response import CreateOpenGlobalDataResponse
from ._create_open_single_data_request import CreateOpenSingleDataRequest
from ._create_open_single_data_response_body import CreateOpenSingleDataResponseBody
from ._create_open_single_data_response import CreateOpenSingleDataResponse
from ._create_pay_order_to_msence_request import CreatePayOrderToMsenceRequest
from ._create_pay_order_to_msence_shrink_request import CreatePayOrderToMsenceShrinkRequest
from ._create_pay_order_to_msence_response_body import CreatePayOrderToMsenceResponseBody
from ._create_pay_order_to_msence_response import CreatePayOrderToMsenceResponse
from ._create_template_request import CreateTemplateRequest
from ._create_template_response_body import CreateTemplateResponseBody
from ._create_template_response import CreateTemplateResponse
from ._delete_cubecard_whitelist_content_request import DeleteCubecardWhitelistContentRequest
from ._delete_cubecard_whitelist_content_response_body import DeleteCubecardWhitelistContentResponseBody
from ._delete_cubecard_whitelist_content_response import DeleteCubecardWhitelistContentResponse
from ._delete_mcdp_aim_request import DeleteMcdpAimRequest
from ._delete_mcdp_aim_response_body import DeleteMcdpAimResponseBody
from ._delete_mcdp_aim_response import DeleteMcdpAimResponse
from ._delete_mcdp_crowd_request import DeleteMcdpCrowdRequest
from ._delete_mcdp_crowd_response_body import DeleteMcdpCrowdResponseBody
from ._delete_mcdp_crowd_response import DeleteMcdpCrowdResponse
from ._delete_mcdp_zone_request import DeleteMcdpZoneRequest
from ._delete_mcdp_zone_response_body import DeleteMcdpZoneResponseBody
from ._delete_mcdp_zone_response import DeleteMcdpZoneResponse
from ._delete_mcube_hotpatch_resource_request import DeleteMcubeHotpatchResourceRequest
from ._delete_mcube_hotpatch_resource_response_body import DeleteMcubeHotpatchResourceResponseBody
from ._delete_mcube_hotpatch_resource_response import DeleteMcubeHotpatchResourceResponse
from ._delete_mcube_mini_app_request import DeleteMcubeMiniAppRequest
from ._delete_mcube_mini_app_response_body import DeleteMcubeMiniAppResponseBody
from ._delete_mcube_mini_app_response import DeleteMcubeMiniAppResponse
from ._delete_mcube_nebula_app_request import DeleteMcubeNebulaAppRequest
from ._delete_mcube_nebula_app_response_body import DeleteMcubeNebulaAppResponseBody
from ._delete_mcube_nebula_app_response import DeleteMcubeNebulaAppResponse
from ._delete_mcube_upgrade_resource_request import DeleteMcubeUpgradeResourceRequest
from ._delete_mcube_upgrade_resource_response_body import DeleteMcubeUpgradeResourceResponseBody
from ._delete_mcube_upgrade_resource_response import DeleteMcubeUpgradeResourceResponse
from ._delete_mcube_whitelist_request import DeleteMcubeWhitelistRequest
from ._delete_mcube_whitelist_response_body import DeleteMcubeWhitelistResponseBody
from ._delete_mcube_whitelist_response import DeleteMcubeWhitelistResponse
from ._delete_mds_cube_template_request import DeleteMdsCubeTemplateRequest
from ._delete_mds_cube_template_response_body import DeleteMdsCubeTemplateResponseBody
from ._delete_mds_cube_template_response import DeleteMdsCubeTemplateResponse
from ._delete_mds_whitelist_content_request import DeleteMdsWhitelistContentRequest
from ._delete_mds_whitelist_content_response_body import DeleteMdsWhitelistContentResponseBody
from ._delete_mds_whitelist_content_response import DeleteMdsWhitelistContentResponse
from ._delete_template_request import DeleteTemplateRequest
from ._delete_template_response_body import DeleteTemplateResponseBody
from ._delete_template_response import DeleteTemplateResponse
from ._exist_mcube_rsa_key_request import ExistMcubeRsaKeyRequest
from ._exist_mcube_rsa_key_response_body import ExistMcubeRsaKeyResponseBody
from ._exist_mcube_rsa_key_response import ExistMcubeRsaKeyResponse
from ._export_mapp_center_app_config_request import ExportMappCenterAppConfigRequest
from ._export_mapp_center_app_config_response_body import ExportMappCenterAppConfigResponseBody
from ._export_mapp_center_app_config_response import ExportMappCenterAppConfigResponse
from ._get_auth_token_to_msence_request import GetAuthTokenToMsenceRequest
from ._get_auth_token_to_msence_response_body import GetAuthTokenToMsenceResponseBody
from ._get_auth_token_to_msence_response import GetAuthTokenToMsenceResponse
from ._get_file_token_for_upload_to_msa_request import GetFileTokenForUploadToMsaRequest
from ._get_file_token_for_upload_to_msa_response_body import GetFileTokenForUploadToMsaResponseBody
from ._get_file_token_for_upload_to_msa_response import GetFileTokenForUploadToMsaResponse
from ._get_game_review_by_status_request import GetGameReviewByStatusRequest
from ._get_game_review_by_status_response_body import GetGameReviewByStatusResponseBody
from ._get_game_review_by_status_response import GetGameReviewByStatusResponse
from ._get_log_url_in_msa_request import GetLogUrlInMsaRequest
from ._get_log_url_in_msa_response_body import GetLogUrlInMsaResponseBody
from ._get_log_url_in_msa_response import GetLogUrlInMsaResponse
from ._get_mcube_file_token_request import GetMcubeFileTokenRequest
from ._get_mcube_file_token_response_body import GetMcubeFileTokenResponseBody
from ._get_mcube_file_token_response import GetMcubeFileTokenResponse
from ._get_mcube_nebula_resource_request import GetMcubeNebulaResourceRequest
from ._get_mcube_nebula_resource_response_body import GetMcubeNebulaResourceResponseBody
from ._get_mcube_nebula_resource_response import GetMcubeNebulaResourceResponse
from ._get_mcube_nebula_task_detail_request import GetMcubeNebulaTaskDetailRequest
from ._get_mcube_nebula_task_detail_response_body import GetMcubeNebulaTaskDetailResponseBody
from ._get_mcube_nebula_task_detail_response import GetMcubeNebulaTaskDetailResponse
from ._get_mcube_upgrade_package_info_request import GetMcubeUpgradePackageInfoRequest
from ._get_mcube_upgrade_package_info_response_body import GetMcubeUpgradePackageInfoResponseBody
from ._get_mcube_upgrade_package_info_response import GetMcubeUpgradePackageInfoResponse
from ._get_mcube_upgrade_task_info_request import GetMcubeUpgradeTaskInfoRequest
from ._get_mcube_upgrade_task_info_response_body import GetMcubeUpgradeTaskInfoResponseBody
from ._get_mcube_upgrade_task_info_response import GetMcubeUpgradeTaskInfoResponse
from ._get_mds_mini_config_request import GetMdsMiniConfigRequest
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBody
from ._get_mds_mini_config_response import GetMdsMiniConfigResponse
from ._get_template_request import GetTemplateRequest
from ._get_template_response_body import GetTemplateResponseBody
from ._get_template_response import GetTemplateResponse
from ._get_user_app_donwload_url_in_msa_request import GetUserAppDonwloadUrlInMsaRequest
from ._get_user_app_donwload_url_in_msa_response_body import GetUserAppDonwloadUrlInMsaResponseBody
from ._get_user_app_donwload_url_in_msa_response import GetUserAppDonwloadUrlInMsaResponse
from ._get_user_app_enhance_process_in_msa_request import GetUserAppEnhanceProcessInMsaRequest
from ._get_user_app_enhance_process_in_msa_response_body import GetUserAppEnhanceProcessInMsaResponseBody
from ._get_user_app_enhance_process_in_msa_response import GetUserAppEnhanceProcessInMsaResponse
from ._get_user_app_upload_process_in_msa_request import GetUserAppUploadProcessInMsaRequest
from ._get_user_app_upload_process_in_msa_response_body import GetUserAppUploadProcessInMsaResponseBody
from ._get_user_app_upload_process_in_msa_response import GetUserAppUploadProcessInMsaResponse
from ._list_analysis_core_index_request import ListAnalysisCoreIndexRequest
from ._list_analysis_core_index_response_body import ListAnalysisCoreIndexResponseBody
from ._list_analysis_core_index_response import ListAnalysisCoreIndexResponse
from ._list_cubecard_apps_request import ListCubecardAppsRequest
from ._list_cubecard_apps_response_body import ListCubecardAppsResponseBody
from ._list_cubecard_apps_response import ListCubecardAppsResponse
from ._list_mapp_center_apps_response_body import ListMappCenterAppsResponseBody
from ._list_mapp_center_apps_response import ListMappCenterAppsResponse
from ._list_mapp_center_workspaces_response_body import ListMappCenterWorkspacesResponseBody
from ._list_mapp_center_workspaces_response import ListMappCenterWorkspacesResponse
from ._list_mcdp_aim_request import ListMcdpAimRequest
from ._list_mcdp_aim_response_body import ListMcdpAimResponseBody
from ._list_mcdp_aim_response import ListMcdpAimResponse
from ._list_mcube_hotpatch_resources_request import ListMcubeHotpatchResourcesRequest
from ._list_mcube_hotpatch_resources_response_body import ListMcubeHotpatchResourcesResponseBody
from ._list_mcube_hotpatch_resources_response import ListMcubeHotpatchResourcesResponse
from ._list_mcube_hotpatch_tasks_request import ListMcubeHotpatchTasksRequest
from ._list_mcube_hotpatch_tasks_response_body import ListMcubeHotpatchTasksResponseBody
from ._list_mcube_hotpatch_tasks_response import ListMcubeHotpatchTasksResponse
from ._list_mcube_mini_apps_request import ListMcubeMiniAppsRequest
from ._list_mcube_mini_apps_response_body import ListMcubeMiniAppsResponseBody
from ._list_mcube_mini_apps_response import ListMcubeMiniAppsResponse
from ._list_mcube_mini_packages_request import ListMcubeMiniPackagesRequest
from ._list_mcube_mini_packages_response_body import ListMcubeMiniPackagesResponseBody
from ._list_mcube_mini_packages_response import ListMcubeMiniPackagesResponse
from ._list_mcube_mini_tasks_request import ListMcubeMiniTasksRequest
from ._list_mcube_mini_tasks_response_body import ListMcubeMiniTasksResponseBody
from ._list_mcube_mini_tasks_response import ListMcubeMiniTasksResponse
from ._list_mcube_nebula_apps_request import ListMcubeNebulaAppsRequest
from ._list_mcube_nebula_apps_response_body import ListMcubeNebulaAppsResponseBody
from ._list_mcube_nebula_apps_response import ListMcubeNebulaAppsResponse
from ._list_mcube_nebula_resources_request import ListMcubeNebulaResourcesRequest
from ._list_mcube_nebula_resources_response_body import ListMcubeNebulaResourcesResponseBody
from ._list_mcube_nebula_resources_response import ListMcubeNebulaResourcesResponse
from ._list_mcube_nebula_tasks_request import ListMcubeNebulaTasksRequest
from ._list_mcube_nebula_tasks_response_body import ListMcubeNebulaTasksResponseBody
from ._list_mcube_nebula_tasks_response import ListMcubeNebulaTasksResponse
from ._list_mcube_upgrade_packages_request import ListMcubeUpgradePackagesRequest
from ._list_mcube_upgrade_packages_response_body import ListMcubeUpgradePackagesResponseBody
from ._list_mcube_upgrade_packages_response import ListMcubeUpgradePackagesResponse
from ._list_mcube_upgrade_tasks_request import ListMcubeUpgradeTasksRequest
from ._list_mcube_upgrade_tasks_response_body import ListMcubeUpgradeTasksResponseBody
from ._list_mcube_upgrade_tasks_response import ListMcubeUpgradeTasksResponse
from ._list_mcube_whitelists_request import ListMcubeWhitelistsRequest
from ._list_mcube_whitelists_response_body import ListMcubeWhitelistsResponseBody
from ._list_mcube_whitelists_response import ListMcubeWhitelistsResponse
from ._list_mds_cube_resources_request import ListMdsCubeResourcesRequest
from ._list_mds_cube_resources_response_body import ListMdsCubeResourcesResponseBody
from ._list_mds_cube_resources_response import ListMdsCubeResourcesResponse
from ._list_mds_cube_tasks_request import ListMdsCubeTasksRequest
from ._list_mds_cube_tasks_response_body import ListMdsCubeTasksResponseBody
from ._list_mds_cube_tasks_response import ListMdsCubeTasksResponse
from ._list_mds_cube_templates_request import ListMdsCubeTemplatesRequest
from ._list_mds_cube_templates_response_body import ListMdsCubeTemplatesResponseBody
from ._list_mds_cube_templates_response import ListMdsCubeTemplatesResponse
from ._list_mgs_api_request import ListMgsApiRequest
from ._list_mgs_api_response_body import ListMgsApiResponseBody
from ._list_mgs_api_response import ListMgsApiResponse
from ._list_template_page_request import ListTemplatePageRequest
from ._list_template_page_response_body import ListTemplatePageResponseBody
from ._list_template_page_response import ListTemplatePageResponse
from ._mtrsocrservice_request import MTRSOCRServiceRequest
from ._mtrsocrservice_response_body import MTRSOCRServiceResponseBody
from ._mtrsocrservice_response import MTRSOCRServiceResponse
from ._push_bind_request import PushBindRequest
from ._push_bind_response_body import PushBindResponseBody
from ._push_bind_response import PushBindResponse
from ._push_broadcast_request import PushBroadcastRequest
from ._push_broadcast_shrink_request import PushBroadcastShrinkRequest
from ._push_broadcast_response_body import PushBroadcastResponseBody
from ._push_broadcast_response import PushBroadcastResponse
from ._push_multiple_request import PushMultipleRequest
from ._push_multiple_shrink_request import PushMultipleShrinkRequest
from ._push_multiple_response_body import PushMultipleResponseBody
from ._push_multiple_response import PushMultipleResponse
from ._push_query_device_state_request import PushQueryDeviceStateRequest
from ._push_query_device_state_response_body import PushQueryDeviceStateResponseBody
from ._push_query_device_state_response import PushQueryDeviceStateResponse
from ._push_report_request import PushReportRequest
from ._push_report_response_body import PushReportResponseBody
from ._push_report_response import PushReportResponse
from ._push_simple_request import PushSimpleRequest
from ._push_simple_shrink_request import PushSimpleShrinkRequest
from ._push_simple_response_body import PushSimpleResponseBody
from ._push_simple_response import PushSimpleResponse
from ._push_template_request import PushTemplateRequest
from ._push_template_shrink_request import PushTemplateShrinkRequest
from ._push_template_response_body import PushTemplateResponseBody
from ._push_template_response import PushTemplateResponse
from ._push_un_bind_request import PushUnBindRequest
from ._push_un_bind_response_body import PushUnBindResponseBody
from ._push_un_bind_response import PushUnBindResponse
from ._query_cubecard_filetoken_request import QueryCubecardFiletokenRequest
from ._query_cubecard_filetoken_response_body import QueryCubecardFiletokenResponseBody
from ._query_cubecard_filetoken_response import QueryCubecardFiletokenResponse
from ._query_info_from_mdp_request import QueryInfoFromMdpRequest
from ._query_info_from_mdp_response_body import QueryInfoFromMdpResponseBody
from ._query_info_from_mdp_response import QueryInfoFromMdpResponse
from ._query_link_request import QueryLinkRequest
from ._query_link_response_body import QueryLinkResponseBody
from ._query_link_response import QueryLinkResponse
from ._query_mapp_center_app_request import QueryMappCenterAppRequest
from ._query_mapp_center_app_response_body import QueryMappCenterAppResponseBody
from ._query_mapp_center_app_response import QueryMappCenterAppResponse
from ._query_mcdp_aim_request import QueryMcdpAimRequest
from ._query_mcdp_aim_response_body import QueryMcdpAimResponseBody
from ._query_mcdp_aim_response import QueryMcdpAimResponse
from ._query_mcdp_zone_request import QueryMcdpZoneRequest
from ._query_mcdp_zone_response_body import QueryMcdpZoneResponseBody
from ._query_mcdp_zone_response import QueryMcdpZoneResponse
from ._query_mcube_hotpatch_task_detail_request import QueryMcubeHotpatchTaskDetailRequest
from ._query_mcube_hotpatch_task_detail_response_body import QueryMcubeHotpatchTaskDetailResponseBody
from ._query_mcube_hotpatch_task_detail_response import QueryMcubeHotpatchTaskDetailResponse
from ._query_mcube_mini_package_request import QueryMcubeMiniPackageRequest
from ._query_mcube_mini_package_response_body import QueryMcubeMiniPackageResponseBody
from ._query_mcube_mini_package_response import QueryMcubeMiniPackageResponse
from ._query_mcube_mini_task_request import QueryMcubeMiniTaskRequest
from ._query_mcube_mini_task_response_body import QueryMcubeMiniTaskResponseBody
from ._query_mcube_mini_task_response import QueryMcubeMiniTaskResponse
from ._query_mcube_vhost_request import QueryMcubeVhostRequest
from ._query_mcube_vhost_response_body import QueryMcubeVhostResponseBody
from ._query_mcube_vhost_response import QueryMcubeVhostResponse
from ._query_mds_upgrade_task_detail_request import QueryMdsUpgradeTaskDetailRequest
from ._query_mds_upgrade_task_detail_response_body import QueryMdsUpgradeTaskDetailResponseBody
from ._query_mds_upgrade_task_detail_response import QueryMdsUpgradeTaskDetailResponse
from ._query_mgs_apipage_request import QueryMgsApipageRequest
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBody
from ._query_mgs_apipage_response import QueryMgsApipageResponse
from ._query_mgs_apirest_request import QueryMgsApirestRequest
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBody
from ._query_mgs_apirest_response import QueryMgsApirestResponse
from ._query_mgs_testreqbodyautogen_request import QueryMgsTestreqbodyautogenRequest
from ._query_mgs_testreqbodyautogen_response_body import QueryMgsTestreqbodyautogenResponseBody
from ._query_mgs_testreqbodyautogen_response import QueryMgsTestreqbodyautogenResponse
from ._query_mps_scheduler_list_request import QueryMpsSchedulerListRequest
from ._query_mps_scheduler_list_response_body import QueryMpsSchedulerListResponseBody
from ._query_mps_scheduler_list_response import QueryMpsSchedulerListResponse
from ._query_mscp_risk_info_request import QueryMscpRiskInfoRequest
from ._query_mscp_risk_info_response_body import QueryMscpRiskInfoResponseBody
from ._query_mscp_risk_info_response import QueryMscpRiskInfoResponse
from ._query_pay_order_to_msence_request import QueryPayOrderToMsenceRequest
from ._query_pay_order_to_msence_response_body import QueryPayOrderToMsenceResponseBody
from ._query_pay_order_to_msence_response import QueryPayOrderToMsenceResponse
from ._query_push_analysis_core_index_request import QueryPushAnalysisCoreIndexRequest
from ._query_push_analysis_core_index_response_body import QueryPushAnalysisCoreIndexResponseBody
from ._query_push_analysis_core_index_response import QueryPushAnalysisCoreIndexResponse
from ._query_push_analysis_task_detail_request import QueryPushAnalysisTaskDetailRequest
from ._query_push_analysis_task_detail_response_body import QueryPushAnalysisTaskDetailResponseBody
from ._query_push_analysis_task_detail_response import QueryPushAnalysisTaskDetailResponse
from ._query_push_analysis_task_list_request import QueryPushAnalysisTaskListRequest
from ._query_push_analysis_task_list_response_body import QueryPushAnalysisTaskListResponseBody
from ._query_push_analysis_task_list_response import QueryPushAnalysisTaskListResponse
from ._query_push_scheduler_list_request import QueryPushSchedulerListRequest
from ._query_push_scheduler_list_response_body import QueryPushSchedulerListResponseBody
from ._query_push_scheduler_list_response import QueryPushSchedulerListResponse
from ._query_user_info_to_msence_request import QueryUserInfoToMsenceRequest
from ._query_user_info_to_msence_response_body import QueryUserInfoToMsenceResponseBody
from ._query_user_info_to_msence_response import QueryUserInfoToMsenceResponse
from ._revoke_push_message_request import RevokePushMessageRequest
from ._revoke_push_message_response_body import RevokePushMessageResponseBody
from ._revoke_push_message_response import RevokePushMessageResponse
from ._revoke_push_task_request import RevokePushTaskRequest
from ._revoke_push_task_response_body import RevokePushTaskResponseBody
from ._revoke_push_task_response import RevokePushTaskResponse
from ._run_msa_diff_request import RunMsaDiffRequest
from ._run_msa_diff_response_body import RunMsaDiffResponseBody
from ._run_msa_diff_response import RunMsaDiffResponse
from ._save_mgs_apirest_request import SaveMgsApirestRequest
from ._save_mgs_apirest_response_body import SaveMgsApirestResponseBody
from ._save_mgs_apirest_response import SaveMgsApirestResponse
from ._save_order_relation_info_to_msence_request import SaveOrderRelationInfoToMsenceRequest
from ._save_order_relation_info_to_msence_response_body import SaveOrderRelationInfoToMsenceResponseBody
from ._save_order_relation_info_to_msence_response import SaveOrderRelationInfoToMsenceResponse
from ._start_user_app_async_enhance_in_msa_request import StartUserAppAsyncEnhanceInMsaRequest
from ._start_user_app_async_enhance_in_msa_response_body import StartUserAppAsyncEnhanceInMsaResponseBody
from ._start_user_app_async_enhance_in_msa_response import StartUserAppAsyncEnhanceInMsaResponse
from ._update_link_request import UpdateLinkRequest
from ._update_link_response_body import UpdateLinkResponseBody
from ._update_link_response import UpdateLinkResponse
from ._update_mcube_hotpatch_task_status_request import UpdateMcubeHotpatchTaskStatusRequest
from ._update_mcube_hotpatch_task_status_response_body import UpdateMcubeHotpatchTaskStatusResponseBody
from ._update_mcube_hotpatch_task_status_response import UpdateMcubeHotpatchTaskStatusResponse
from ._update_mcube_whitelist_request import UpdateMcubeWhitelistRequest
from ._update_mcube_whitelist_response_body import UpdateMcubeWhitelistResponseBody
from ._update_mcube_whitelist_response import UpdateMcubeWhitelistResponse
from ._update_mds_cube_resource_request import UpdateMdsCubeResourceRequest
from ._update_mds_cube_resource_response_body import UpdateMdsCubeResourceResponseBody
from ._update_mds_cube_resource_response import UpdateMdsCubeResourceResponse
from ._update_mpaas_app_info_request import UpdateMpaasAppInfoRequest
from ._update_mpaas_app_info_response_body import UpdateMpaasAppInfoResponseBody
from ._update_mpaas_app_info_response import UpdateMpaasAppInfoResponse
from ._upload_bitcode_to_msa_request import UploadBitcodeToMsaRequest
from ._upload_bitcode_to_msa_response_body import UploadBitcodeToMsaResponseBody
from ._upload_bitcode_to_msa_response import UploadBitcodeToMsaResponse
from ._upload_mcube_mini_package_request import UploadMcubeMiniPackageRequest
from ._upload_mcube_mini_package_response_body import UploadMcubeMiniPackageResponseBody
from ._upload_mcube_mini_package_response import UploadMcubeMiniPackageResponse
from ._upload_mcube_rsa_key_request import UploadMcubeRsaKeyRequest
from ._upload_mcube_rsa_key_response_body import UploadMcubeRsaKeyResponseBody
from ._upload_mcube_rsa_key_response import UploadMcubeRsaKeyResponse
from ._upload_user_app_to_msa_request import UploadUserAppToMsaRequest
from ._upload_user_app_to_msa_response_body import UploadUserAppToMsaResponseBody
from ._upload_user_app_to_msa_response import UploadUserAppToMsaResponse
from ._virtual_delivery_to_mscene_request import VirtualDeliveryToMsceneRequest
from ._virtual_delivery_to_mscene_response_body import VirtualDeliveryToMsceneResponseBody
from ._virtual_delivery_to_mscene_response import VirtualDeliveryToMsceneResponse
from ._add_mds_mini_config_response_body import AddMdsMiniConfigResponseBodyResultContentData
from ._add_mds_mini_config_response_body import AddMdsMiniConfigResponseBodyResultContent
from ._change_mcube_mini_task_status_response_body import ChangeMcubeMiniTaskStatusResponseBodyChangeMiniTaskStatusResult
from ._change_mcube_nebula_task_status_response_body import ChangeMcubeNebulaTaskStatusResponseBodyChangeMcubeNebulaTaskStatusResult
from ._change_mcube_public_task_status_response_body import ChangeMcubePublicTaskStatusResponseBodyResultContent
from ._change_mds_cube_task_status_response_body import ChangeMdsCubeTaskStatusResponseBodyResultContentData
from ._change_mds_cube_task_status_response_body import ChangeMdsCubeTaskStatusResponseBodyResultContent
from ._copy_mcdp_group_response_body import CopyMcdpGroupResponseBodyResultContent
from ._create_link_response_body import CreateLinkResponseBodyResultContent
from ._create_mcdp_group_response_body import CreateMcdpGroupResponseBodyResultContent
from ._create_mcdp_material_response_body import CreateMcdpMaterialResponseBodyResultContent
from ._create_mcdp_zone_response_body import CreateMcdpZoneResponseBodyResultContent
from ._create_mcube_hotpatch_resource_response_body import CreateMcubeHotpatchResourceResponseBodyCreateHotpatchResourceResult
from ._create_mcube_hotpatch_rollback_task_response_body import CreateMcubeHotpatchRollbackTaskResponseBodyCreateHotpatchRollbackTaskResult
from ._create_mcube_hotpatch_task_response_body import CreateMcubeHotpatchTaskResponseBodyCreateHotpatchTaskResult
from ._create_mcube_mini_app_response_body import CreateMcubeMiniAppResponseBodyCreateMiniResult
from ._create_mcube_mini_task_response_body import CreateMcubeMiniTaskResponseBodyCreateMiniTaskResult
from ._create_mcube_nebula_app_response_body import CreateMcubeNebulaAppResponseBodyCreateNebulaAppResult
from ._create_mcube_nebula_resource_response_body import CreateMcubeNebulaResourceResponseBodyCreateMcubeNebulaResourceReslult
from ._create_mcube_nebula_task_response_body import CreateMcubeNebulaTaskResponseBodyCreateMcubeNebulaTaskResult
from ._create_mcube_upgrade_package_response_body import CreateMcubeUpgradePackageResponseBodyResultContent
from ._create_mcube_upgrade_task_response_body import CreateMcubeUpgradeTaskResponseBodyCreateTaskResult
from ._create_mcube_vhost_response_body import CreateMcubeVhostResponseBodyCreateVhostResult
from ._create_mcube_whitelist_response_body import CreateMcubeWhitelistResponseBodyCreateWhitelistResult
from ._create_mcube_whitelist_for_ide_response_body import CreateMcubeWhitelistForIdeResponseBodyCreateWhitelistForIdeResult
from ._create_mds_cube_resource_response_body import CreateMdsCubeResourceResponseBodyResultContentData
from ._create_mds_cube_resource_response_body import CreateMdsCubeResourceResponseBodyResultContent
from ._create_mds_cube_task_response_body import CreateMdsCubeTaskResponseBodyResultContentData
from ._create_mds_cube_task_response_body import CreateMdsCubeTaskResponseBodyResultContent
from ._create_mds_cube_template_response_body import CreateMdsCubeTemplateResponseBodyResultContentData
from ._create_mds_cube_template_response_body import CreateMdsCubeTemplateResponseBodyResultContent
from ._create_mds_miniprogram_task_response_body import CreateMdsMiniprogramTaskResponseBodyResultContentData
from ._create_mds_miniprogram_task_response_body import CreateMdsMiniprogramTaskResponseBodyResultContent
from ._create_pay_order_to_msence_response_body import CreatePayOrderToMsenceResponseBodyMpaasOrderCreateResponse
from ._delete_cubecard_whitelist_content_response_body import DeleteCubecardWhitelistContentResponseBodyResultContentData
from ._delete_cubecard_whitelist_content_response_body import DeleteCubecardWhitelistContentResponseBodyResultContent
from ._delete_mcdp_aim_response_body import DeleteMcdpAimResponseBodyResultContent
from ._delete_mcdp_crowd_response_body import DeleteMcdpCrowdResponseBodyResultContent
from ._delete_mcdp_zone_response_body import DeleteMcdpZoneResponseBodyResultContent
from ._delete_mcube_hotpatch_resource_response_body import DeleteMcubeHotpatchResourceResponseBodyDeleteHotpatchResourceResult
from ._delete_mcube_mini_app_response_body import DeleteMcubeMiniAppResponseBodyDeleteMiniResult
from ._delete_mcube_nebula_app_response_body import DeleteMcubeNebulaAppResponseBodyDeleteMcubeNebulaAppResult
from ._delete_mcube_upgrade_resource_response_body import DeleteMcubeUpgradeResourceResponseBodyDeleteResult
from ._delete_mcube_whitelist_response_body import DeleteMcubeWhitelistResponseBodyDeleteWhitelistResult
from ._delete_mds_cube_template_response_body import DeleteMdsCubeTemplateResponseBodyResultContentData
from ._delete_mds_cube_template_response_body import DeleteMdsCubeTemplateResponseBodyResultContent
from ._delete_mds_whitelist_content_response_body import DeleteMdsWhitelistContentResponseBodyResultContentData
from ._delete_mds_whitelist_content_response_body import DeleteMdsWhitelistContentResponseBodyResultContent
from ._exist_mcube_rsa_key_response_body import ExistMcubeRsaKeyResponseBodyCheckRsaKeyResult
from ._export_mapp_center_app_config_response_body import ExportMappCenterAppConfigResponseBodyExportMappCenterAppConfigResult
from ._get_auth_token_to_msence_response_body import GetAuthTokenToMsenceResponseBodyMpaasSystemOauthTokenResponse
from ._get_file_token_for_upload_to_msa_response_body import GetFileTokenForUploadToMsaResponseBodyResultContentContent
from ._get_file_token_for_upload_to_msa_response_body import GetFileTokenForUploadToMsaResponseBodyResultContent
from ._get_game_review_by_status_response_body import GetGameReviewByStatusResponseBodyResultContentContentReviewProgress
from ._get_game_review_by_status_response_body import GetGameReviewByStatusResponseBodyResultContentContentTargetDetail
from ._get_game_review_by_status_response_body import GetGameReviewByStatusResponseBodyResultContentContent
from ._get_game_review_by_status_response_body import GetGameReviewByStatusResponseBodyResultContent
from ._get_log_url_in_msa_response_body import GetLogUrlInMsaResponseBodyResultContent
from ._get_mcube_file_token_response_body import GetMcubeFileTokenResponseBodyGetFileTokenResultFileToken
from ._get_mcube_file_token_response_body import GetMcubeFileTokenResponseBodyGetFileTokenResult
from ._get_mcube_nebula_resource_response_body import GetMcubeNebulaResourceResponseBodyGetNebulaResourceResultNebulaResourceInfo
from ._get_mcube_nebula_resource_response_body import GetMcubeNebulaResourceResponseBodyGetNebulaResourceResult
from ._get_mcube_nebula_task_detail_response_body import GetMcubeNebulaTaskDetailResponseBodyGetMcubeNebulaTaskDetailResultNebulaTaskDetailRuleJsonList
from ._get_mcube_nebula_task_detail_response_body import GetMcubeNebulaTaskDetailResponseBodyGetMcubeNebulaTaskDetailResultNebulaTaskDetail
from ._get_mcube_nebula_task_detail_response_body import GetMcubeNebulaTaskDetailResponseBodyGetMcubeNebulaTaskDetailResult
from ._get_mcube_upgrade_package_info_response_body import GetMcubeUpgradePackageInfoResponseBodyGetPackageResultPackageInfoMobileTestFlightConfigDO
from ._get_mcube_upgrade_package_info_response_body import GetMcubeUpgradePackageInfoResponseBodyGetPackageResultPackageInfoUpgradeBaseInfoDO
from ._get_mcube_upgrade_package_info_response_body import GetMcubeUpgradePackageInfoResponseBodyGetPackageResultPackageInfo
from ._get_mcube_upgrade_package_info_response_body import GetMcubeUpgradePackageInfoResponseBodyGetPackageResult
from ._get_mcube_upgrade_task_info_response_body import GetMcubeUpgradeTaskInfoResponseBodyGetTaskResultTaskInfoRuleJsonList
from ._get_mcube_upgrade_task_info_response_body import GetMcubeUpgradeTaskInfoResponseBodyGetTaskResultTaskInfoWhitelist
from ._get_mcube_upgrade_task_info_response_body import GetMcubeUpgradeTaskInfoResponseBodyGetTaskResultTaskInfo
from ._get_mcube_upgrade_task_info_response_body import GetMcubeUpgradeTaskInfoResponseBodyGetTaskResult
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContentDataContentApiConfigList
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContentDataContentPrivilegeSwitch
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContentDataContentServerDomainConfigList
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContentDataContentWebviewDomainConfigList
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContentDataContent
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContentData
from ._get_mds_mini_config_response_body import GetMdsMiniConfigResponseBodyResultContent
from ._get_template_response_body import GetTemplateResponseBodyData
from ._get_user_app_donwload_url_in_msa_response_body import GetUserAppDonwloadUrlInMsaResponseBodyResultContentData
from ._get_user_app_donwload_url_in_msa_response_body import GetUserAppDonwloadUrlInMsaResponseBodyResultContent
from ._get_user_app_enhance_process_in_msa_response_body import GetUserAppEnhanceProcessInMsaResponseBodyResultContentDataEnhanceMapping
from ._get_user_app_enhance_process_in_msa_response_body import GetUserAppEnhanceProcessInMsaResponseBodyResultContentData
from ._get_user_app_enhance_process_in_msa_response_body import GetUserAppEnhanceProcessInMsaResponseBodyResultContent
from ._get_user_app_upload_process_in_msa_response_body import GetUserAppUploadProcessInMsaResponseBodyResultContentDataApkInfoEnhanceMapping
from ._get_user_app_upload_process_in_msa_response_body import GetUserAppUploadProcessInMsaResponseBodyResultContentDataApkInfo
from ._get_user_app_upload_process_in_msa_response_body import GetUserAppUploadProcessInMsaResponseBodyResultContentData
from ._get_user_app_upload_process_in_msa_response_body import GetUserAppUploadProcessInMsaResponseBodyResultContent
from ._list_analysis_core_index_response_body import ListAnalysisCoreIndexResponseBodyResultContentData
from ._list_analysis_core_index_response_body import ListAnalysisCoreIndexResponseBodyResultContent
from ._list_cubecard_apps_response_body import ListCubecardAppsResponseBodyResultContentDataContent
from ._list_cubecard_apps_response_body import ListCubecardAppsResponseBodyResultContentData
from ._list_cubecard_apps_response_body import ListCubecardAppsResponseBodyResultContent
from ._list_mapp_center_apps_response_body import ListMappCenterAppsResponseBodyListMappCenterAppResultMappCenterAppListAndroidConfig
from ._list_mapp_center_apps_response_body import ListMappCenterAppsResponseBodyListMappCenterAppResultMappCenterAppListIosConfig
from ._list_mapp_center_apps_response_body import ListMappCenterAppsResponseBodyListMappCenterAppResultMappCenterAppList
from ._list_mapp_center_apps_response_body import ListMappCenterAppsResponseBodyListMappCenterAppResult
from ._list_mapp_center_workspaces_response_body import ListMappCenterWorkspacesResponseBodyListMappCenterWorkspaceResultMappCenterWorkspaceList
from ._list_mapp_center_workspaces_response_body import ListMappCenterWorkspacesResponseBodyListMappCenterWorkspaceResult
from ._list_mcdp_aim_response_body import ListMcdpAimResponseBodyResultContent
from ._list_mcube_hotpatch_resources_response_body import ListMcubeHotpatchResourcesResponseBodyListHotpatchResourceResultHotpatchResourceInfo
from ._list_mcube_hotpatch_resources_response_body import ListMcubeHotpatchResourcesResponseBodyListHotpatchResourceResult
from ._list_mcube_hotpatch_tasks_response_body import ListMcubeHotpatchTasksResponseBodyListHotpatchTasksResultHotpatchTaskInfo
from ._list_mcube_hotpatch_tasks_response_body import ListMcubeHotpatchTasksResponseBodyListHotpatchTasksResult
from ._list_mcube_mini_apps_response_body import ListMcubeMiniAppsResponseBodyListMiniResultMiniProgramList
from ._list_mcube_mini_apps_response_body import ListMcubeMiniAppsResponseBodyListMiniResult
from ._list_mcube_mini_packages_response_body import ListMcubeMiniPackagesResponseBodyListMiniPackageResultMiniPackageList
from ._list_mcube_mini_packages_response_body import ListMcubeMiniPackagesResponseBodyListMiniPackageResult
from ._list_mcube_mini_tasks_response_body import ListMcubeMiniTasksResponseBodyListMiniTaskResultMiniTaskList
from ._list_mcube_mini_tasks_response_body import ListMcubeMiniTasksResponseBodyListMiniTaskResult
from ._list_mcube_nebula_apps_response_body import ListMcubeNebulaAppsResponseBodyListMcubeNebulaAppsResultNebulaAppInfos
from ._list_mcube_nebula_apps_response_body import ListMcubeNebulaAppsResponseBodyListMcubeNebulaAppsResult
from ._list_mcube_nebula_resources_response_body import ListMcubeNebulaResourcesResponseBodyListMcubeNebulaResourceResultNebulaResourceInfo
from ._list_mcube_nebula_resources_response_body import ListMcubeNebulaResourcesResponseBodyListMcubeNebulaResourceResult
from ._list_mcube_nebula_tasks_response_body import ListMcubeNebulaTasksResponseBodyListMcubeNebulaTaskResultNebulaTaskInfo
from ._list_mcube_nebula_tasks_response_body import ListMcubeNebulaTasksResponseBodyListMcubeNebulaTaskResult
from ._list_mcube_upgrade_packages_response_body import ListMcubeUpgradePackagesResponseBodyListPackagesResultPackages
from ._list_mcube_upgrade_packages_response_body import ListMcubeUpgradePackagesResponseBodyListPackagesResult
from ._list_mcube_upgrade_tasks_response_body import ListMcubeUpgradeTasksResponseBodyListTaskResultTaskInfo
from ._list_mcube_upgrade_tasks_response_body import ListMcubeUpgradeTasksResponseBodyListTaskResult
from ._list_mcube_whitelists_response_body import ListMcubeWhitelistsResponseBodyListWhitelistResultWhitelists
from ._list_mcube_whitelists_response_body import ListMcubeWhitelistsResponseBodyListWhitelistResult
from ._list_mds_cube_resources_response_body import ListMdsCubeResourcesResponseBodyResultContentDataContentList
from ._list_mds_cube_resources_response_body import ListMdsCubeResourcesResponseBodyResultContentDataContent
from ._list_mds_cube_resources_response_body import ListMdsCubeResourcesResponseBodyResultContentData
from ._list_mds_cube_resources_response_body import ListMdsCubeResourcesResponseBodyResultContent
from ._list_mds_cube_tasks_response_body import ListMdsCubeTasksResponseBodyResultContentDataContent
from ._list_mds_cube_tasks_response_body import ListMdsCubeTasksResponseBodyResultContentData
from ._list_mds_cube_tasks_response_body import ListMdsCubeTasksResponseBodyResultContent
from ._list_mds_cube_templates_response_body import ListMdsCubeTemplatesResponseBodyResultContentDataContentList
from ._list_mds_cube_templates_response_body import ListMdsCubeTemplatesResponseBodyResultContentDataContent
from ._list_mds_cube_templates_response_body import ListMdsCubeTemplatesResponseBodyResultContentData
from ._list_mds_cube_templates_response_body import ListMdsCubeTemplatesResponseBodyResultContent
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueApiInvokerHttpInvoker
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueApiInvoker
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueCacheRule
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueCircuitBreakerRule
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueHeaderRule
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueHeaderRules
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueLimitRule
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueMigrateRule
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueMockRule
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValueRequestParams
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContentValue
from ._list_mgs_api_response_body import ListMgsApiResponseBodyResultContent
from ._list_template_page_response_body import ListTemplatePageResponseBodyData
from ._push_bind_response_body import PushBindResponseBodyPushResult
from ._push_broadcast_response_body import PushBroadcastResponseBodyPushResult
from ._push_multiple_request import PushMultipleRequestTargetMsg
from ._push_multiple_shrink_request import PushMultipleShrinkRequestTargetMsg
from ._push_multiple_response_body import PushMultipleResponseBodyPushResult
from ._push_query_device_state_response_body import PushQueryDeviceStateResponseBodyData
from ._push_report_response_body import PushReportResponseBodyPushResult
from ._push_simple_response_body import PushSimpleResponseBodyPushResult
from ._push_template_response_body import PushTemplateResponseBodyPushResult
from ._push_un_bind_response_body import PushUnBindResponseBodyPushResult
from ._query_cubecard_filetoken_response_body import QueryCubecardFiletokenResponseBodyResultContentDataContent
from ._query_cubecard_filetoken_response_body import QueryCubecardFiletokenResponseBodyResultContentData
from ._query_cubecard_filetoken_response_body import QueryCubecardFiletokenResponseBodyResultContent
from ._query_link_response_body import QueryLinkResponseBodyResultContent
from ._query_mapp_center_app_response_body import QueryMappCenterAppResponseBodyQueryMappCenterAppResultMappCenterAppAndroidConfig
from ._query_mapp_center_app_response_body import QueryMappCenterAppResponseBodyQueryMappCenterAppResultMappCenterAppIosConfig
from ._query_mapp_center_app_response_body import QueryMappCenterAppResponseBodyQueryMappCenterAppResultMappCenterApp
from ._query_mapp_center_app_response_body import QueryMappCenterAppResponseBodyQueryMappCenterAppResult
from ._query_mcdp_aim_response_body import QueryMcdpAimResponseBodyResultContent
from ._query_mcdp_zone_response_body import QueryMcdpZoneResponseBodyResultContent
from ._query_mcube_hotpatch_task_detail_response_body import QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResultHotpatchTaskDetailRuleJsonList
from ._query_mcube_hotpatch_task_detail_response_body import QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResultHotpatchTaskDetailWhitelist
from ._query_mcube_hotpatch_task_detail_response_body import QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResultHotpatchTaskDetail
from ._query_mcube_hotpatch_task_detail_response_body import QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResult
from ._query_mcube_mini_package_response_body import QueryMcubeMiniPackageResponseBodyQueryMiniPackageResultMiniPackageInfo
from ._query_mcube_mini_package_response_body import QueryMcubeMiniPackageResponseBodyQueryMiniPackageResult
from ._query_mcube_mini_task_response_body import QueryMcubeMiniTaskResponseBodyQueryMiniTaskResultMiniTaskInfo
from ._query_mcube_mini_task_response_body import QueryMcubeMiniTaskResponseBodyQueryMiniTaskResult
from ._query_mcube_vhost_response_body import QueryMcubeVhostResponseBodyQueryVhostResult
from ._query_mds_upgrade_task_detail_response_body import QueryMdsUpgradeTaskDetailResponseBodyResultContentDataContentRuleJsonList
from ._query_mds_upgrade_task_detail_response_body import QueryMdsUpgradeTaskDetailResponseBodyResultContentDataContentWhitelist
from ._query_mds_upgrade_task_detail_response_body import QueryMdsUpgradeTaskDetailResponseBodyResultContentDataContent
from ._query_mds_upgrade_task_detail_response_body import QueryMdsUpgradeTaskDetailResponseBodyResultContentData
from ._query_mds_upgrade_task_detail_response_body import QueryMdsUpgradeTaskDetailResponseBodyResultContent
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListApiInvokerHttpInvoker
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListApiInvoker
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListCacheRule
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListCircuitBreakerRule
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListHeaderRule
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListHeaderRules
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListLimitRule
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListMigrateRule
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListMockRule
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentListRequestParams
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContentList
from ._query_mgs_apipage_response_body import QueryMgsApipageResponseBodyResultContent
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueApiInvokerHttpInvoker
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueApiInvoker
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueCacheRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueCircuitBreakerRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueDefaultLimitRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueHeaderRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueHeaderRules
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueLimitRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueMigrateRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueMockRule
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValueRequestParams
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContentValue
from ._query_mgs_apirest_response_body import QueryMgsApirestResponseBodyResultContent
from ._query_mps_scheduler_list_response_body import QueryMpsSchedulerListResponseBodyResultContentDataList
from ._query_mps_scheduler_list_response_body import QueryMpsSchedulerListResponseBodyResultContentData
from ._query_mps_scheduler_list_response_body import QueryMpsSchedulerListResponseBodyResultContent
from ._query_pay_order_to_msence_response_body import QueryPayOrderToMsenceResponseBodyMpaasUserGamecenterPaymentQuerystatusResponse
from ._query_push_analysis_core_index_response_body import QueryPushAnalysisCoreIndexResponseBodyResultContentData
from ._query_push_analysis_core_index_response_body import QueryPushAnalysisCoreIndexResponseBodyResultContent
from ._query_push_analysis_task_detail_response_body import QueryPushAnalysisTaskDetailResponseBodyResultContentData
from ._query_push_analysis_task_detail_response_body import QueryPushAnalysisTaskDetailResponseBodyResultContent
from ._query_push_analysis_task_list_response_body import QueryPushAnalysisTaskListResponseBodyResultContentDataList
from ._query_push_analysis_task_list_response_body import QueryPushAnalysisTaskListResponseBodyResultContentData
from ._query_push_analysis_task_list_response_body import QueryPushAnalysisTaskListResponseBodyResultContent
from ._query_push_scheduler_list_response_body import QueryPushSchedulerListResponseBodyResultContentDataList
from ._query_push_scheduler_list_response_body import QueryPushSchedulerListResponseBodyResultContentData
from ._query_push_scheduler_list_response_body import QueryPushSchedulerListResponseBodyResultContent
from ._query_user_info_to_msence_response_body import QueryUserInfoToMsenceResponseBodyMpaasUserInfoShareResponse
from ._revoke_push_message_response_body import RevokePushMessageResponseBodyPushResult
from ._revoke_push_task_response_body import RevokePushTaskResponseBodyPushResult
from ._run_msa_diff_response_body import RunMsaDiffResponseBodyResultContent
from ._save_mgs_apirest_response_body import SaveMgsApirestResponseBodyResultContent
from ._save_order_relation_info_to_msence_response_body import SaveOrderRelationInfoToMsenceResponseBodyMpaasSaveOrderRelationResponse
from ._start_user_app_async_enhance_in_msa_response_body import StartUserAppAsyncEnhanceInMsaResponseBodyResultContentDataEnhanceMapping
from ._start_user_app_async_enhance_in_msa_response_body import StartUserAppAsyncEnhanceInMsaResponseBodyResultContentData
from ._start_user_app_async_enhance_in_msa_response_body import StartUserAppAsyncEnhanceInMsaResponseBodyResultContent
from ._update_link_response_body import UpdateLinkResponseBodyResultContent
from ._update_mcube_hotpatch_task_status_response_body import UpdateMcubeHotpatchTaskStatusResponseBodyUpdateHotpatchTaskStatusResult
from ._update_mcube_whitelist_response_body import UpdateMcubeWhitelistResponseBodyAddWhitelistResultAddWhitelistInfo
from ._update_mcube_whitelist_response_body import UpdateMcubeWhitelistResponseBodyAddWhitelistResult
from ._update_mds_cube_resource_response_body import UpdateMdsCubeResourceResponseBodyResultContentData
from ._update_mds_cube_resource_response_body import UpdateMdsCubeResourceResponseBodyResultContent
from ._update_mpaas_app_info_response_body import UpdateMpaasAppInfoResponseBodyResultContentData
from ._update_mpaas_app_info_response_body import UpdateMpaasAppInfoResponseBodyResultContent
from ._upload_bitcode_to_msa_response_body import UploadBitcodeToMsaResponseBodyResultContent
from ._upload_mcube_mini_package_response_body import UploadMcubeMiniPackageResponseBodyUploadMiniPackageResultReturnPackageResult
from ._upload_mcube_mini_package_response_body import UploadMcubeMiniPackageResponseBodyUploadMiniPackageResult
from ._upload_mcube_rsa_key_response_body import UploadMcubeRsaKeyResponseBodyUploadRsaResult
from ._upload_user_app_to_msa_response_body import UploadUserAppToMsaResponseBodyResultContentDataApkInfoEnhanceMapping
from ._upload_user_app_to_msa_response_body import UploadUserAppToMsaResponseBodyResultContentDataApkInfo
from ._upload_user_app_to_msa_response_body import UploadUserAppToMsaResponseBodyResultContentData
from ._upload_user_app_to_msa_response_body import UploadUserAppToMsaResponseBodyResultContent
from ._virtual_delivery_to_mscene_response_body import VirtualDeliveryToMsceneResponseBodyMpaasUserGamecenterPaymentVirtualdeliveryResponse

__all__ = [
    AddMdsMiniConfigRequest,
    AddMdsMiniConfigResponseBody,
    AddMdsMiniConfigResponse,
    CancelPushSchedulerRequest,
    CancelPushSchedulerResponseBody,
    CancelPushSchedulerResponse,
    ChangeMcubeMiniTaskStatusRequest,
    ChangeMcubeMiniTaskStatusResponseBody,
    ChangeMcubeMiniTaskStatusResponse,
    ChangeMcubeNebulaTaskStatusRequest,
    ChangeMcubeNebulaTaskStatusResponseBody,
    ChangeMcubeNebulaTaskStatusResponse,
    ChangeMcubePublicTaskStatusRequest,
    ChangeMcubePublicTaskStatusResponseBody,
    ChangeMcubePublicTaskStatusResponse,
    ChangeMdsCubeTaskStatusRequest,
    ChangeMdsCubeTaskStatusResponseBody,
    ChangeMdsCubeTaskStatusResponse,
    CopyMcdpGroupRequest,
    CopyMcdpGroupResponseBody,
    CopyMcdpGroupResponse,
    CreateLinkRequest,
    CreateLinkResponseBody,
    CreateLinkResponse,
    CreateMcdpGroupRequest,
    CreateMcdpGroupResponseBody,
    CreateMcdpGroupResponse,
    CreateMcdpMaterialRequest,
    CreateMcdpMaterialResponseBody,
    CreateMcdpMaterialResponse,
    CreateMcdpZoneRequest,
    CreateMcdpZoneResponseBody,
    CreateMcdpZoneResponse,
    CreateMcubeHotpatchResourceRequest,
    CreateMcubeHotpatchResourceResponseBody,
    CreateMcubeHotpatchResourceResponse,
    CreateMcubeHotpatchRollbackTaskRequest,
    CreateMcubeHotpatchRollbackTaskResponseBody,
    CreateMcubeHotpatchRollbackTaskResponse,
    CreateMcubeHotpatchTaskRequest,
    CreateMcubeHotpatchTaskResponseBody,
    CreateMcubeHotpatchTaskResponse,
    CreateMcubeMiniAppRequest,
    CreateMcubeMiniAppResponseBody,
    CreateMcubeMiniAppResponse,
    CreateMcubeMiniTaskRequest,
    CreateMcubeMiniTaskResponseBody,
    CreateMcubeMiniTaskResponse,
    CreateMcubeNebulaAppRequest,
    CreateMcubeNebulaAppResponseBody,
    CreateMcubeNebulaAppResponse,
    CreateMcubeNebulaResourceRequest,
    CreateMcubeNebulaResourceResponseBody,
    CreateMcubeNebulaResourceResponse,
    CreateMcubeNebulaTaskRequest,
    CreateMcubeNebulaTaskResponseBody,
    CreateMcubeNebulaTaskResponse,
    CreateMcubeUpgradePackageRequest,
    CreateMcubeUpgradePackageResponseBody,
    CreateMcubeUpgradePackageResponse,
    CreateMcubeUpgradeTaskRequest,
    CreateMcubeUpgradeTaskResponseBody,
    CreateMcubeUpgradeTaskResponse,
    CreateMcubeVhostRequest,
    CreateMcubeVhostResponseBody,
    CreateMcubeVhostResponse,
    CreateMcubeWhitelistRequest,
    CreateMcubeWhitelistResponseBody,
    CreateMcubeWhitelistResponse,
    CreateMcubeWhitelistForIdeRequest,
    CreateMcubeWhitelistForIdeResponseBody,
    CreateMcubeWhitelistForIdeResponse,
    CreateMdsCubeResourceRequest,
    CreateMdsCubeResourceResponseBody,
    CreateMdsCubeResourceResponse,
    CreateMdsCubeTaskRequest,
    CreateMdsCubeTaskResponseBody,
    CreateMdsCubeTaskResponse,
    CreateMdsCubeTemplateRequest,
    CreateMdsCubeTemplateResponseBody,
    CreateMdsCubeTemplateResponse,
    CreateMdsMiniprogramTaskRequest,
    CreateMdsMiniprogramTaskResponseBody,
    CreateMdsMiniprogramTaskResponse,
    CreateOpenGlobalDataRequest,
    CreateOpenGlobalDataResponseBody,
    CreateOpenGlobalDataResponse,
    CreateOpenSingleDataRequest,
    CreateOpenSingleDataResponseBody,
    CreateOpenSingleDataResponse,
    CreatePayOrderToMsenceRequest,
    CreatePayOrderToMsenceShrinkRequest,
    CreatePayOrderToMsenceResponseBody,
    CreatePayOrderToMsenceResponse,
    CreateTemplateRequest,
    CreateTemplateResponseBody,
    CreateTemplateResponse,
    DeleteCubecardWhitelistContentRequest,
    DeleteCubecardWhitelistContentResponseBody,
    DeleteCubecardWhitelistContentResponse,
    DeleteMcdpAimRequest,
    DeleteMcdpAimResponseBody,
    DeleteMcdpAimResponse,
    DeleteMcdpCrowdRequest,
    DeleteMcdpCrowdResponseBody,
    DeleteMcdpCrowdResponse,
    DeleteMcdpZoneRequest,
    DeleteMcdpZoneResponseBody,
    DeleteMcdpZoneResponse,
    DeleteMcubeHotpatchResourceRequest,
    DeleteMcubeHotpatchResourceResponseBody,
    DeleteMcubeHotpatchResourceResponse,
    DeleteMcubeMiniAppRequest,
    DeleteMcubeMiniAppResponseBody,
    DeleteMcubeMiniAppResponse,
    DeleteMcubeNebulaAppRequest,
    DeleteMcubeNebulaAppResponseBody,
    DeleteMcubeNebulaAppResponse,
    DeleteMcubeUpgradeResourceRequest,
    DeleteMcubeUpgradeResourceResponseBody,
    DeleteMcubeUpgradeResourceResponse,
    DeleteMcubeWhitelistRequest,
    DeleteMcubeWhitelistResponseBody,
    DeleteMcubeWhitelistResponse,
    DeleteMdsCubeTemplateRequest,
    DeleteMdsCubeTemplateResponseBody,
    DeleteMdsCubeTemplateResponse,
    DeleteMdsWhitelistContentRequest,
    DeleteMdsWhitelistContentResponseBody,
    DeleteMdsWhitelistContentResponse,
    DeleteTemplateRequest,
    DeleteTemplateResponseBody,
    DeleteTemplateResponse,
    ExistMcubeRsaKeyRequest,
    ExistMcubeRsaKeyResponseBody,
    ExistMcubeRsaKeyResponse,
    ExportMappCenterAppConfigRequest,
    ExportMappCenterAppConfigResponseBody,
    ExportMappCenterAppConfigResponse,
    GetAuthTokenToMsenceRequest,
    GetAuthTokenToMsenceResponseBody,
    GetAuthTokenToMsenceResponse,
    GetFileTokenForUploadToMsaRequest,
    GetFileTokenForUploadToMsaResponseBody,
    GetFileTokenForUploadToMsaResponse,
    GetGameReviewByStatusRequest,
    GetGameReviewByStatusResponseBody,
    GetGameReviewByStatusResponse,
    GetLogUrlInMsaRequest,
    GetLogUrlInMsaResponseBody,
    GetLogUrlInMsaResponse,
    GetMcubeFileTokenRequest,
    GetMcubeFileTokenResponseBody,
    GetMcubeFileTokenResponse,
    GetMcubeNebulaResourceRequest,
    GetMcubeNebulaResourceResponseBody,
    GetMcubeNebulaResourceResponse,
    GetMcubeNebulaTaskDetailRequest,
    GetMcubeNebulaTaskDetailResponseBody,
    GetMcubeNebulaTaskDetailResponse,
    GetMcubeUpgradePackageInfoRequest,
    GetMcubeUpgradePackageInfoResponseBody,
    GetMcubeUpgradePackageInfoResponse,
    GetMcubeUpgradeTaskInfoRequest,
    GetMcubeUpgradeTaskInfoResponseBody,
    GetMcubeUpgradeTaskInfoResponse,
    GetMdsMiniConfigRequest,
    GetMdsMiniConfigResponseBody,
    GetMdsMiniConfigResponse,
    GetTemplateRequest,
    GetTemplateResponseBody,
    GetTemplateResponse,
    GetUserAppDonwloadUrlInMsaRequest,
    GetUserAppDonwloadUrlInMsaResponseBody,
    GetUserAppDonwloadUrlInMsaResponse,
    GetUserAppEnhanceProcessInMsaRequest,
    GetUserAppEnhanceProcessInMsaResponseBody,
    GetUserAppEnhanceProcessInMsaResponse,
    GetUserAppUploadProcessInMsaRequest,
    GetUserAppUploadProcessInMsaResponseBody,
    GetUserAppUploadProcessInMsaResponse,
    ListAnalysisCoreIndexRequest,
    ListAnalysisCoreIndexResponseBody,
    ListAnalysisCoreIndexResponse,
    ListCubecardAppsRequest,
    ListCubecardAppsResponseBody,
    ListCubecardAppsResponse,
    ListMappCenterAppsResponseBody,
    ListMappCenterAppsResponse,
    ListMappCenterWorkspacesResponseBody,
    ListMappCenterWorkspacesResponse,
    ListMcdpAimRequest,
    ListMcdpAimResponseBody,
    ListMcdpAimResponse,
    ListMcubeHotpatchResourcesRequest,
    ListMcubeHotpatchResourcesResponseBody,
    ListMcubeHotpatchResourcesResponse,
    ListMcubeHotpatchTasksRequest,
    ListMcubeHotpatchTasksResponseBody,
    ListMcubeHotpatchTasksResponse,
    ListMcubeMiniAppsRequest,
    ListMcubeMiniAppsResponseBody,
    ListMcubeMiniAppsResponse,
    ListMcubeMiniPackagesRequest,
    ListMcubeMiniPackagesResponseBody,
    ListMcubeMiniPackagesResponse,
    ListMcubeMiniTasksRequest,
    ListMcubeMiniTasksResponseBody,
    ListMcubeMiniTasksResponse,
    ListMcubeNebulaAppsRequest,
    ListMcubeNebulaAppsResponseBody,
    ListMcubeNebulaAppsResponse,
    ListMcubeNebulaResourcesRequest,
    ListMcubeNebulaResourcesResponseBody,
    ListMcubeNebulaResourcesResponse,
    ListMcubeNebulaTasksRequest,
    ListMcubeNebulaTasksResponseBody,
    ListMcubeNebulaTasksResponse,
    ListMcubeUpgradePackagesRequest,
    ListMcubeUpgradePackagesResponseBody,
    ListMcubeUpgradePackagesResponse,
    ListMcubeUpgradeTasksRequest,
    ListMcubeUpgradeTasksResponseBody,
    ListMcubeUpgradeTasksResponse,
    ListMcubeWhitelistsRequest,
    ListMcubeWhitelistsResponseBody,
    ListMcubeWhitelistsResponse,
    ListMdsCubeResourcesRequest,
    ListMdsCubeResourcesResponseBody,
    ListMdsCubeResourcesResponse,
    ListMdsCubeTasksRequest,
    ListMdsCubeTasksResponseBody,
    ListMdsCubeTasksResponse,
    ListMdsCubeTemplatesRequest,
    ListMdsCubeTemplatesResponseBody,
    ListMdsCubeTemplatesResponse,
    ListMgsApiRequest,
    ListMgsApiResponseBody,
    ListMgsApiResponse,
    ListTemplatePageRequest,
    ListTemplatePageResponseBody,
    ListTemplatePageResponse,
    MTRSOCRServiceRequest,
    MTRSOCRServiceResponseBody,
    MTRSOCRServiceResponse,
    PushBindRequest,
    PushBindResponseBody,
    PushBindResponse,
    PushBroadcastRequest,
    PushBroadcastShrinkRequest,
    PushBroadcastResponseBody,
    PushBroadcastResponse,
    PushMultipleRequest,
    PushMultipleShrinkRequest,
    PushMultipleResponseBody,
    PushMultipleResponse,
    PushQueryDeviceStateRequest,
    PushQueryDeviceStateResponseBody,
    PushQueryDeviceStateResponse,
    PushReportRequest,
    PushReportResponseBody,
    PushReportResponse,
    PushSimpleRequest,
    PushSimpleShrinkRequest,
    PushSimpleResponseBody,
    PushSimpleResponse,
    PushTemplateRequest,
    PushTemplateShrinkRequest,
    PushTemplateResponseBody,
    PushTemplateResponse,
    PushUnBindRequest,
    PushUnBindResponseBody,
    PushUnBindResponse,
    QueryCubecardFiletokenRequest,
    QueryCubecardFiletokenResponseBody,
    QueryCubecardFiletokenResponse,
    QueryInfoFromMdpRequest,
    QueryInfoFromMdpResponseBody,
    QueryInfoFromMdpResponse,
    QueryLinkRequest,
    QueryLinkResponseBody,
    QueryLinkResponse,
    QueryMappCenterAppRequest,
    QueryMappCenterAppResponseBody,
    QueryMappCenterAppResponse,
    QueryMcdpAimRequest,
    QueryMcdpAimResponseBody,
    QueryMcdpAimResponse,
    QueryMcdpZoneRequest,
    QueryMcdpZoneResponseBody,
    QueryMcdpZoneResponse,
    QueryMcubeHotpatchTaskDetailRequest,
    QueryMcubeHotpatchTaskDetailResponseBody,
    QueryMcubeHotpatchTaskDetailResponse,
    QueryMcubeMiniPackageRequest,
    QueryMcubeMiniPackageResponseBody,
    QueryMcubeMiniPackageResponse,
    QueryMcubeMiniTaskRequest,
    QueryMcubeMiniTaskResponseBody,
    QueryMcubeMiniTaskResponse,
    QueryMcubeVhostRequest,
    QueryMcubeVhostResponseBody,
    QueryMcubeVhostResponse,
    QueryMdsUpgradeTaskDetailRequest,
    QueryMdsUpgradeTaskDetailResponseBody,
    QueryMdsUpgradeTaskDetailResponse,
    QueryMgsApipageRequest,
    QueryMgsApipageResponseBody,
    QueryMgsApipageResponse,
    QueryMgsApirestRequest,
    QueryMgsApirestResponseBody,
    QueryMgsApirestResponse,
    QueryMgsTestreqbodyautogenRequest,
    QueryMgsTestreqbodyautogenResponseBody,
    QueryMgsTestreqbodyautogenResponse,
    QueryMpsSchedulerListRequest,
    QueryMpsSchedulerListResponseBody,
    QueryMpsSchedulerListResponse,
    QueryMscpRiskInfoRequest,
    QueryMscpRiskInfoResponseBody,
    QueryMscpRiskInfoResponse,
    QueryPayOrderToMsenceRequest,
    QueryPayOrderToMsenceResponseBody,
    QueryPayOrderToMsenceResponse,
    QueryPushAnalysisCoreIndexRequest,
    QueryPushAnalysisCoreIndexResponseBody,
    QueryPushAnalysisCoreIndexResponse,
    QueryPushAnalysisTaskDetailRequest,
    QueryPushAnalysisTaskDetailResponseBody,
    QueryPushAnalysisTaskDetailResponse,
    QueryPushAnalysisTaskListRequest,
    QueryPushAnalysisTaskListResponseBody,
    QueryPushAnalysisTaskListResponse,
    QueryPushSchedulerListRequest,
    QueryPushSchedulerListResponseBody,
    QueryPushSchedulerListResponse,
    QueryUserInfoToMsenceRequest,
    QueryUserInfoToMsenceResponseBody,
    QueryUserInfoToMsenceResponse,
    RevokePushMessageRequest,
    RevokePushMessageResponseBody,
    RevokePushMessageResponse,
    RevokePushTaskRequest,
    RevokePushTaskResponseBody,
    RevokePushTaskResponse,
    RunMsaDiffRequest,
    RunMsaDiffResponseBody,
    RunMsaDiffResponse,
    SaveMgsApirestRequest,
    SaveMgsApirestResponseBody,
    SaveMgsApirestResponse,
    SaveOrderRelationInfoToMsenceRequest,
    SaveOrderRelationInfoToMsenceResponseBody,
    SaveOrderRelationInfoToMsenceResponse,
    StartUserAppAsyncEnhanceInMsaRequest,
    StartUserAppAsyncEnhanceInMsaResponseBody,
    StartUserAppAsyncEnhanceInMsaResponse,
    UpdateLinkRequest,
    UpdateLinkResponseBody,
    UpdateLinkResponse,
    UpdateMcubeHotpatchTaskStatusRequest,
    UpdateMcubeHotpatchTaskStatusResponseBody,
    UpdateMcubeHotpatchTaskStatusResponse,
    UpdateMcubeWhitelistRequest,
    UpdateMcubeWhitelistResponseBody,
    UpdateMcubeWhitelistResponse,
    UpdateMdsCubeResourceRequest,
    UpdateMdsCubeResourceResponseBody,
    UpdateMdsCubeResourceResponse,
    UpdateMpaasAppInfoRequest,
    UpdateMpaasAppInfoResponseBody,
    UpdateMpaasAppInfoResponse,
    UploadBitcodeToMsaRequest,
    UploadBitcodeToMsaResponseBody,
    UploadBitcodeToMsaResponse,
    UploadMcubeMiniPackageRequest,
    UploadMcubeMiniPackageResponseBody,
    UploadMcubeMiniPackageResponse,
    UploadMcubeRsaKeyRequest,
    UploadMcubeRsaKeyResponseBody,
    UploadMcubeRsaKeyResponse,
    UploadUserAppToMsaRequest,
    UploadUserAppToMsaResponseBody,
    UploadUserAppToMsaResponse,
    VirtualDeliveryToMsceneRequest,
    VirtualDeliveryToMsceneResponseBody,
    VirtualDeliveryToMsceneResponse,
    AddMdsMiniConfigResponseBodyResultContentData,
    AddMdsMiniConfigResponseBodyResultContent,
    ChangeMcubeMiniTaskStatusResponseBodyChangeMiniTaskStatusResult,
    ChangeMcubeNebulaTaskStatusResponseBodyChangeMcubeNebulaTaskStatusResult,
    ChangeMcubePublicTaskStatusResponseBodyResultContent,
    ChangeMdsCubeTaskStatusResponseBodyResultContentData,
    ChangeMdsCubeTaskStatusResponseBodyResultContent,
    CopyMcdpGroupResponseBodyResultContent,
    CreateLinkResponseBodyResultContent,
    CreateMcdpGroupResponseBodyResultContent,
    CreateMcdpMaterialResponseBodyResultContent,
    CreateMcdpZoneResponseBodyResultContent,
    CreateMcubeHotpatchResourceResponseBodyCreateHotpatchResourceResult,
    CreateMcubeHotpatchRollbackTaskResponseBodyCreateHotpatchRollbackTaskResult,
    CreateMcubeHotpatchTaskResponseBodyCreateHotpatchTaskResult,
    CreateMcubeMiniAppResponseBodyCreateMiniResult,
    CreateMcubeMiniTaskResponseBodyCreateMiniTaskResult,
    CreateMcubeNebulaAppResponseBodyCreateNebulaAppResult,
    CreateMcubeNebulaResourceResponseBodyCreateMcubeNebulaResourceReslult,
    CreateMcubeNebulaTaskResponseBodyCreateMcubeNebulaTaskResult,
    CreateMcubeUpgradePackageResponseBodyResultContent,
    CreateMcubeUpgradeTaskResponseBodyCreateTaskResult,
    CreateMcubeVhostResponseBodyCreateVhostResult,
    CreateMcubeWhitelistResponseBodyCreateWhitelistResult,
    CreateMcubeWhitelistForIdeResponseBodyCreateWhitelistForIdeResult,
    CreateMdsCubeResourceResponseBodyResultContentData,
    CreateMdsCubeResourceResponseBodyResultContent,
    CreateMdsCubeTaskResponseBodyResultContentData,
    CreateMdsCubeTaskResponseBodyResultContent,
    CreateMdsCubeTemplateResponseBodyResultContentData,
    CreateMdsCubeTemplateResponseBodyResultContent,
    CreateMdsMiniprogramTaskResponseBodyResultContentData,
    CreateMdsMiniprogramTaskResponseBodyResultContent,
    CreatePayOrderToMsenceResponseBodyMpaasOrderCreateResponse,
    DeleteCubecardWhitelistContentResponseBodyResultContentData,
    DeleteCubecardWhitelistContentResponseBodyResultContent,
    DeleteMcdpAimResponseBodyResultContent,
    DeleteMcdpCrowdResponseBodyResultContent,
    DeleteMcdpZoneResponseBodyResultContent,
    DeleteMcubeHotpatchResourceResponseBodyDeleteHotpatchResourceResult,
    DeleteMcubeMiniAppResponseBodyDeleteMiniResult,
    DeleteMcubeNebulaAppResponseBodyDeleteMcubeNebulaAppResult,
    DeleteMcubeUpgradeResourceResponseBodyDeleteResult,
    DeleteMcubeWhitelistResponseBodyDeleteWhitelistResult,
    DeleteMdsCubeTemplateResponseBodyResultContentData,
    DeleteMdsCubeTemplateResponseBodyResultContent,
    DeleteMdsWhitelistContentResponseBodyResultContentData,
    DeleteMdsWhitelistContentResponseBodyResultContent,
    ExistMcubeRsaKeyResponseBodyCheckRsaKeyResult,
    ExportMappCenterAppConfigResponseBodyExportMappCenterAppConfigResult,
    GetAuthTokenToMsenceResponseBodyMpaasSystemOauthTokenResponse,
    GetFileTokenForUploadToMsaResponseBodyResultContentContent,
    GetFileTokenForUploadToMsaResponseBodyResultContent,
    GetGameReviewByStatusResponseBodyResultContentContentReviewProgress,
    GetGameReviewByStatusResponseBodyResultContentContentTargetDetail,
    GetGameReviewByStatusResponseBodyResultContentContent,
    GetGameReviewByStatusResponseBodyResultContent,
    GetLogUrlInMsaResponseBodyResultContent,
    GetMcubeFileTokenResponseBodyGetFileTokenResultFileToken,
    GetMcubeFileTokenResponseBodyGetFileTokenResult,
    GetMcubeNebulaResourceResponseBodyGetNebulaResourceResultNebulaResourceInfo,
    GetMcubeNebulaResourceResponseBodyGetNebulaResourceResult,
    GetMcubeNebulaTaskDetailResponseBodyGetMcubeNebulaTaskDetailResultNebulaTaskDetailRuleJsonList,
    GetMcubeNebulaTaskDetailResponseBodyGetMcubeNebulaTaskDetailResultNebulaTaskDetail,
    GetMcubeNebulaTaskDetailResponseBodyGetMcubeNebulaTaskDetailResult,
    GetMcubeUpgradePackageInfoResponseBodyGetPackageResultPackageInfoMobileTestFlightConfigDO,
    GetMcubeUpgradePackageInfoResponseBodyGetPackageResultPackageInfoUpgradeBaseInfoDO,
    GetMcubeUpgradePackageInfoResponseBodyGetPackageResultPackageInfo,
    GetMcubeUpgradePackageInfoResponseBodyGetPackageResult,
    GetMcubeUpgradeTaskInfoResponseBodyGetTaskResultTaskInfoRuleJsonList,
    GetMcubeUpgradeTaskInfoResponseBodyGetTaskResultTaskInfoWhitelist,
    GetMcubeUpgradeTaskInfoResponseBodyGetTaskResultTaskInfo,
    GetMcubeUpgradeTaskInfoResponseBodyGetTaskResult,
    GetMdsMiniConfigResponseBodyResultContentDataContentApiConfigList,
    GetMdsMiniConfigResponseBodyResultContentDataContentPrivilegeSwitch,
    GetMdsMiniConfigResponseBodyResultContentDataContentServerDomainConfigList,
    GetMdsMiniConfigResponseBodyResultContentDataContentWebviewDomainConfigList,
    GetMdsMiniConfigResponseBodyResultContentDataContent,
    GetMdsMiniConfigResponseBodyResultContentData,
    GetMdsMiniConfigResponseBodyResultContent,
    GetTemplateResponseBodyData,
    GetUserAppDonwloadUrlInMsaResponseBodyResultContentData,
    GetUserAppDonwloadUrlInMsaResponseBodyResultContent,
    GetUserAppEnhanceProcessInMsaResponseBodyResultContentDataEnhanceMapping,
    GetUserAppEnhanceProcessInMsaResponseBodyResultContentData,
    GetUserAppEnhanceProcessInMsaResponseBodyResultContent,
    GetUserAppUploadProcessInMsaResponseBodyResultContentDataApkInfoEnhanceMapping,
    GetUserAppUploadProcessInMsaResponseBodyResultContentDataApkInfo,
    GetUserAppUploadProcessInMsaResponseBodyResultContentData,
    GetUserAppUploadProcessInMsaResponseBodyResultContent,
    ListAnalysisCoreIndexResponseBodyResultContentData,
    ListAnalysisCoreIndexResponseBodyResultContent,
    ListCubecardAppsResponseBodyResultContentDataContent,
    ListCubecardAppsResponseBodyResultContentData,
    ListCubecardAppsResponseBodyResultContent,
    ListMappCenterAppsResponseBodyListMappCenterAppResultMappCenterAppListAndroidConfig,
    ListMappCenterAppsResponseBodyListMappCenterAppResultMappCenterAppListIosConfig,
    ListMappCenterAppsResponseBodyListMappCenterAppResultMappCenterAppList,
    ListMappCenterAppsResponseBodyListMappCenterAppResult,
    ListMappCenterWorkspacesResponseBodyListMappCenterWorkspaceResultMappCenterWorkspaceList,
    ListMappCenterWorkspacesResponseBodyListMappCenterWorkspaceResult,
    ListMcdpAimResponseBodyResultContent,
    ListMcubeHotpatchResourcesResponseBodyListHotpatchResourceResultHotpatchResourceInfo,
    ListMcubeHotpatchResourcesResponseBodyListHotpatchResourceResult,
    ListMcubeHotpatchTasksResponseBodyListHotpatchTasksResultHotpatchTaskInfo,
    ListMcubeHotpatchTasksResponseBodyListHotpatchTasksResult,
    ListMcubeMiniAppsResponseBodyListMiniResultMiniProgramList,
    ListMcubeMiniAppsResponseBodyListMiniResult,
    ListMcubeMiniPackagesResponseBodyListMiniPackageResultMiniPackageList,
    ListMcubeMiniPackagesResponseBodyListMiniPackageResult,
    ListMcubeMiniTasksResponseBodyListMiniTaskResultMiniTaskList,
    ListMcubeMiniTasksResponseBodyListMiniTaskResult,
    ListMcubeNebulaAppsResponseBodyListMcubeNebulaAppsResultNebulaAppInfos,
    ListMcubeNebulaAppsResponseBodyListMcubeNebulaAppsResult,
    ListMcubeNebulaResourcesResponseBodyListMcubeNebulaResourceResultNebulaResourceInfo,
    ListMcubeNebulaResourcesResponseBodyListMcubeNebulaResourceResult,
    ListMcubeNebulaTasksResponseBodyListMcubeNebulaTaskResultNebulaTaskInfo,
    ListMcubeNebulaTasksResponseBodyListMcubeNebulaTaskResult,
    ListMcubeUpgradePackagesResponseBodyListPackagesResultPackages,
    ListMcubeUpgradePackagesResponseBodyListPackagesResult,
    ListMcubeUpgradeTasksResponseBodyListTaskResultTaskInfo,
    ListMcubeUpgradeTasksResponseBodyListTaskResult,
    ListMcubeWhitelistsResponseBodyListWhitelistResultWhitelists,
    ListMcubeWhitelistsResponseBodyListWhitelistResult,
    ListMdsCubeResourcesResponseBodyResultContentDataContentList,
    ListMdsCubeResourcesResponseBodyResultContentDataContent,
    ListMdsCubeResourcesResponseBodyResultContentData,
    ListMdsCubeResourcesResponseBodyResultContent,
    ListMdsCubeTasksResponseBodyResultContentDataContent,
    ListMdsCubeTasksResponseBodyResultContentData,
    ListMdsCubeTasksResponseBodyResultContent,
    ListMdsCubeTemplatesResponseBodyResultContentDataContentList,
    ListMdsCubeTemplatesResponseBodyResultContentDataContent,
    ListMdsCubeTemplatesResponseBodyResultContentData,
    ListMdsCubeTemplatesResponseBodyResultContent,
    ListMgsApiResponseBodyResultContentValueApiInvokerHttpInvoker,
    ListMgsApiResponseBodyResultContentValueApiInvoker,
    ListMgsApiResponseBodyResultContentValueCacheRule,
    ListMgsApiResponseBodyResultContentValueCircuitBreakerRule,
    ListMgsApiResponseBodyResultContentValueHeaderRule,
    ListMgsApiResponseBodyResultContentValueHeaderRules,
    ListMgsApiResponseBodyResultContentValueLimitRule,
    ListMgsApiResponseBodyResultContentValueMigrateRule,
    ListMgsApiResponseBodyResultContentValueMockRule,
    ListMgsApiResponseBodyResultContentValueRequestParams,
    ListMgsApiResponseBodyResultContentValue,
    ListMgsApiResponseBodyResultContent,
    ListTemplatePageResponseBodyData,
    PushBindResponseBodyPushResult,
    PushBroadcastResponseBodyPushResult,
    PushMultipleRequestTargetMsg,
    PushMultipleShrinkRequestTargetMsg,
    PushMultipleResponseBodyPushResult,
    PushQueryDeviceStateResponseBodyData,
    PushReportResponseBodyPushResult,
    PushSimpleResponseBodyPushResult,
    PushTemplateResponseBodyPushResult,
    PushUnBindResponseBodyPushResult,
    QueryCubecardFiletokenResponseBodyResultContentDataContent,
    QueryCubecardFiletokenResponseBodyResultContentData,
    QueryCubecardFiletokenResponseBodyResultContent,
    QueryLinkResponseBodyResultContent,
    QueryMappCenterAppResponseBodyQueryMappCenterAppResultMappCenterAppAndroidConfig,
    QueryMappCenterAppResponseBodyQueryMappCenterAppResultMappCenterAppIosConfig,
    QueryMappCenterAppResponseBodyQueryMappCenterAppResultMappCenterApp,
    QueryMappCenterAppResponseBodyQueryMappCenterAppResult,
    QueryMcdpAimResponseBodyResultContent,
    QueryMcdpZoneResponseBodyResultContent,
    QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResultHotpatchTaskDetailRuleJsonList,
    QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResultHotpatchTaskDetailWhitelist,
    QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResultHotpatchTaskDetail,
    QueryMcubeHotpatchTaskDetailResponseBodyQueryHotpatchTaskDetailResult,
    QueryMcubeMiniPackageResponseBodyQueryMiniPackageResultMiniPackageInfo,
    QueryMcubeMiniPackageResponseBodyQueryMiniPackageResult,
    QueryMcubeMiniTaskResponseBodyQueryMiniTaskResultMiniTaskInfo,
    QueryMcubeMiniTaskResponseBodyQueryMiniTaskResult,
    QueryMcubeVhostResponseBodyQueryVhostResult,
    QueryMdsUpgradeTaskDetailResponseBodyResultContentDataContentRuleJsonList,
    QueryMdsUpgradeTaskDetailResponseBodyResultContentDataContentWhitelist,
    QueryMdsUpgradeTaskDetailResponseBodyResultContentDataContent,
    QueryMdsUpgradeTaskDetailResponseBodyResultContentData,
    QueryMdsUpgradeTaskDetailResponseBodyResultContent,
    QueryMgsApipageResponseBodyResultContentListApiInvokerHttpInvoker,
    QueryMgsApipageResponseBodyResultContentListApiInvoker,
    QueryMgsApipageResponseBodyResultContentListCacheRule,
    QueryMgsApipageResponseBodyResultContentListCircuitBreakerRule,
    QueryMgsApipageResponseBodyResultContentListHeaderRule,
    QueryMgsApipageResponseBodyResultContentListHeaderRules,
    QueryMgsApipageResponseBodyResultContentListLimitRule,
    QueryMgsApipageResponseBodyResultContentListMigrateRule,
    QueryMgsApipageResponseBodyResultContentListMockRule,
    QueryMgsApipageResponseBodyResultContentListRequestParams,
    QueryMgsApipageResponseBodyResultContentList,
    QueryMgsApipageResponseBodyResultContent,
    QueryMgsApirestResponseBodyResultContentValueApiInvokerHttpInvoker,
    QueryMgsApirestResponseBodyResultContentValueApiInvoker,
    QueryMgsApirestResponseBodyResultContentValueCacheRule,
    QueryMgsApirestResponseBodyResultContentValueCircuitBreakerRule,
    QueryMgsApirestResponseBodyResultContentValueDefaultLimitRule,
    QueryMgsApirestResponseBodyResultContentValueHeaderRule,
    QueryMgsApirestResponseBodyResultContentValueHeaderRules,
    QueryMgsApirestResponseBodyResultContentValueLimitRule,
    QueryMgsApirestResponseBodyResultContentValueMigrateRule,
    QueryMgsApirestResponseBodyResultContentValueMockRule,
    QueryMgsApirestResponseBodyResultContentValueRequestParams,
    QueryMgsApirestResponseBodyResultContentValue,
    QueryMgsApirestResponseBodyResultContent,
    QueryMpsSchedulerListResponseBodyResultContentDataList,
    QueryMpsSchedulerListResponseBodyResultContentData,
    QueryMpsSchedulerListResponseBodyResultContent,
    QueryPayOrderToMsenceResponseBodyMpaasUserGamecenterPaymentQuerystatusResponse,
    QueryPushAnalysisCoreIndexResponseBodyResultContentData,
    QueryPushAnalysisCoreIndexResponseBodyResultContent,
    QueryPushAnalysisTaskDetailResponseBodyResultContentData,
    QueryPushAnalysisTaskDetailResponseBodyResultContent,
    QueryPushAnalysisTaskListResponseBodyResultContentDataList,
    QueryPushAnalysisTaskListResponseBodyResultContentData,
    QueryPushAnalysisTaskListResponseBodyResultContent,
    QueryPushSchedulerListResponseBodyResultContentDataList,
    QueryPushSchedulerListResponseBodyResultContentData,
    QueryPushSchedulerListResponseBodyResultContent,
    QueryUserInfoToMsenceResponseBodyMpaasUserInfoShareResponse,
    RevokePushMessageResponseBodyPushResult,
    RevokePushTaskResponseBodyPushResult,
    RunMsaDiffResponseBodyResultContent,
    SaveMgsApirestResponseBodyResultContent,
    SaveOrderRelationInfoToMsenceResponseBodyMpaasSaveOrderRelationResponse,
    StartUserAppAsyncEnhanceInMsaResponseBodyResultContentDataEnhanceMapping,
    StartUserAppAsyncEnhanceInMsaResponseBodyResultContentData,
    StartUserAppAsyncEnhanceInMsaResponseBodyResultContent,
    UpdateLinkResponseBodyResultContent,
    UpdateMcubeHotpatchTaskStatusResponseBodyUpdateHotpatchTaskStatusResult,
    UpdateMcubeWhitelistResponseBodyAddWhitelistResultAddWhitelistInfo,
    UpdateMcubeWhitelistResponseBodyAddWhitelistResult,
    UpdateMdsCubeResourceResponseBodyResultContentData,
    UpdateMdsCubeResourceResponseBodyResultContent,
    UpdateMpaasAppInfoResponseBodyResultContentData,
    UpdateMpaasAppInfoResponseBodyResultContent,
    UploadBitcodeToMsaResponseBodyResultContent,
    UploadMcubeMiniPackageResponseBodyUploadMiniPackageResultReturnPackageResult,
    UploadMcubeMiniPackageResponseBodyUploadMiniPackageResult,
    UploadMcubeRsaKeyResponseBodyUploadRsaResult,
    UploadUserAppToMsaResponseBodyResultContentDataApkInfoEnhanceMapping,
    UploadUserAppToMsaResponseBodyResultContentDataApkInfo,
    UploadUserAppToMsaResponseBodyResultContentData,
    UploadUserAppToMsaResponseBodyResultContent,
    VirtualDeliveryToMsceneResponseBodyMpaasUserGamecenterPaymentVirtualdeliveryResponse
]
