# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_cbn20170912 import models as main_models
from darabonba.model import DaraModel

class ListTransitRouterRouteEntriesResponseBody(DaraModel):
    def __init__(
        self,
        max_results: int = None,
        next_token: str = None,
        request_id: str = None,
        total_count: int = None,
        transit_router_route_entries: List[main_models.ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries] = None,
    ):
        # The number of entries per page when entries are returned in pages.
        self.max_results = max_results
        # The token that determines the start point of the next query. Valid values:
        # 
        # - If **NextToken** is empty, no subsequent query is to be sent.
        # - If **NextToken** is returned, the value indicates the token for the next query.
        self.next_token = next_token
        # The request ID.
        self.request_id = request_id
        # The total number of entries.
        self.total_count = total_count
        # The list of route entries.
        self.transit_router_route_entries = transit_router_route_entries

    def validate(self):
        if self.transit_router_route_entries:
            for v1 in self.transit_router_route_entries:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.max_results is not None:
            result['MaxResults'] = self.max_results

        if self.next_token is not None:
            result['NextToken'] = self.next_token

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.total_count is not None:
            result['TotalCount'] = self.total_count

        result['TransitRouterRouteEntries'] = []
        if self.transit_router_route_entries is not None:
            for k1 in self.transit_router_route_entries:
                result['TransitRouterRouteEntries'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('MaxResults') is not None:
            self.max_results = m.get('MaxResults')

        if m.get('NextToken') is not None:
            self.next_token = m.get('NextToken')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('TotalCount') is not None:
            self.total_count = m.get('TotalCount')

        self.transit_router_route_entries = []
        if m.get('TransitRouterRouteEntries') is not None:
            for k1 in m.get('TransitRouterRouteEntries'):
                temp_model = main_models.ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries()
                self.transit_router_route_entries.append(temp_model.from_map(k1))

        return self

class ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntries(DaraModel):
    def __init__(
        self,
        create_time: str = None,
        operational_mode: bool = None,
        path_attributes: main_models.ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes = None,
        prefix_list_id: str = None,
        tag: str = None,
        transit_router_route_entry_description: str = None,
        transit_router_route_entry_destination_cidr_block: str = None,
        transit_router_route_entry_id: str = None,
        transit_router_route_entry_name: str = None,
        transit_router_route_entry_next_hop_id: str = None,
        transit_router_route_entry_next_hop_resource_id: str = None,
        transit_router_route_entry_next_hop_resource_type: str = None,
        transit_router_route_entry_next_hop_type: str = None,
        transit_router_route_entry_origin_resource_id: str = None,
        transit_router_route_entry_origin_resource_type: str = None,
        transit_router_route_entry_status: str = None,
        transit_router_route_entry_type: str = None,
    ):
        # The time when the route entry was created.
        # 
        # The time is displayed in UTC in the YYYY-MM-DDThh:mmZ format.
        # 
        # > This parameter is returned only for statically configured routes.
        self.create_time = create_time
        # Indicates whether the current route entry can be modified.
        # 
        # - **true**: the route entry can be modified. You can delete the route entry.
        # - **false**: the route entry cannot be modified. The route entry is automatically generated by the system and does not support editing.
        self.operational_mode = operational_mode
        # The path attributes of the route.
        self.path_attributes = path_attributes
        # The ID of the prefix list.
        self.prefix_list_id = prefix_list_id
        # The tag of the route entry.
        # 
        # The only valid value is **PermitVbr**, which indicates that the current route entry is propagated only to the route tables of VBR instances under the transit router instance.
        # 
        # > This parameter is returned only for system-generated routes for transit router CIDR blocks.
        self.tag = tag
        # The description of the route entry.
        # 
        # > This parameter is returned only for statically configured routes.
        self.transit_router_route_entry_description = transit_router_route_entry_description
        # The destination CIDR block of the route entry. An IPv4 CIDR block or an IPv6 CIDR block is returned.
        self.transit_router_route_entry_destination_cidr_block = transit_router_route_entry_destination_cidr_block
        # The ID of the route entry.
        # 
        # > This parameter is returned only for statically configured routes.
        self.transit_router_route_entry_id = transit_router_route_entry_id
        # The name of the route entry.
        # 
        # > This parameter is returned only for statically configured routes.
        self.transit_router_route_entry_name = transit_router_route_entry_name
        # The next hop ID of the route entry. This parameter is not returned for blackhole routes.
        self.transit_router_route_entry_next_hop_id = transit_router_route_entry_next_hop_id
        # The instance ID of the next hop of the route entry.
        self.transit_router_route_entry_next_hop_resource_id = transit_router_route_entry_next_hop_resource_id
        # The type of the next hop instance of the route entry.
        # 
        # - **VPC**: Virtual Private Cloud (VPC) instance.
        # - **VBR**: Virtual Border Router (VBR) instance.
        # - **TR**: transit router instance.
        # - **VPN**: IPsec connection instance.
        self.transit_router_route_entry_next_hop_resource_type = transit_router_route_entry_next_hop_resource_type
        # The next hop type of the route entry.
        # 
        # - **BlackHole**: the route entry is a blackhole route. All traffic destined for the destination CIDR block is dropped.
        # - **Attachment**: the next hop of the route entry is a network instance connection. All traffic destined for the destination CIDR block is forwarded to the specified network instance connection.
        self.transit_router_route_entry_next_hop_type = transit_router_route_entry_next_hop_type
        # The instance ID of the origin of the route entry.
        self.transit_router_route_entry_origin_resource_id = transit_router_route_entry_origin_resource_id
        # The type of the origin instance of the route entry.
        # 
        # - **VPC**: Virtual Private Cloud (VPC) instance.
        # - **VBR**: Virtual Border Router (VBR) instance.
        # - **TR**: transit router instance.
        # - **VPN**: IPsec connection instance.
        self.transit_router_route_entry_origin_resource_type = transit_router_route_entry_origin_resource_type
        # The status of the route entry.
        # 
        # - **Active**: active.
        # - **Rejected**: rejected due to a route conflict.
        # - **Prohibited**: prohibited by a routing policy.
        # - **Standby**: standby.
        # - **Candidate**: candidate.
        # - **Creating**: being created.
        # - **Deleting**: being deleted.
        self.transit_router_route_entry_status = transit_router_route_entry_status
        # The type of the route entry.
        # 
        # - **Static**: a statically configured route entry.
        # - **Propagated**: a route entry generated by automatic learning.
        self.transit_router_route_entry_type = transit_router_route_entry_type

    def validate(self):
        if self.path_attributes:
            self.path_attributes.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.create_time is not None:
            result['CreateTime'] = self.create_time

        if self.operational_mode is not None:
            result['OperationalMode'] = self.operational_mode

        if self.path_attributes is not None:
            result['PathAttributes'] = self.path_attributes.to_map()

        if self.prefix_list_id is not None:
            result['PrefixListId'] = self.prefix_list_id

        if self.tag is not None:
            result['Tag'] = self.tag

        if self.transit_router_route_entry_description is not None:
            result['TransitRouterRouteEntryDescription'] = self.transit_router_route_entry_description

        if self.transit_router_route_entry_destination_cidr_block is not None:
            result['TransitRouterRouteEntryDestinationCidrBlock'] = self.transit_router_route_entry_destination_cidr_block

        if self.transit_router_route_entry_id is not None:
            result['TransitRouterRouteEntryId'] = self.transit_router_route_entry_id

        if self.transit_router_route_entry_name is not None:
            result['TransitRouterRouteEntryName'] = self.transit_router_route_entry_name

        if self.transit_router_route_entry_next_hop_id is not None:
            result['TransitRouterRouteEntryNextHopId'] = self.transit_router_route_entry_next_hop_id

        if self.transit_router_route_entry_next_hop_resource_id is not None:
            result['TransitRouterRouteEntryNextHopResourceId'] = self.transit_router_route_entry_next_hop_resource_id

        if self.transit_router_route_entry_next_hop_resource_type is not None:
            result['TransitRouterRouteEntryNextHopResourceType'] = self.transit_router_route_entry_next_hop_resource_type

        if self.transit_router_route_entry_next_hop_type is not None:
            result['TransitRouterRouteEntryNextHopType'] = self.transit_router_route_entry_next_hop_type

        if self.transit_router_route_entry_origin_resource_id is not None:
            result['TransitRouterRouteEntryOriginResourceId'] = self.transit_router_route_entry_origin_resource_id

        if self.transit_router_route_entry_origin_resource_type is not None:
            result['TransitRouterRouteEntryOriginResourceType'] = self.transit_router_route_entry_origin_resource_type

        if self.transit_router_route_entry_status is not None:
            result['TransitRouterRouteEntryStatus'] = self.transit_router_route_entry_status

        if self.transit_router_route_entry_type is not None:
            result['TransitRouterRouteEntryType'] = self.transit_router_route_entry_type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('CreateTime') is not None:
            self.create_time = m.get('CreateTime')

        if m.get('OperationalMode') is not None:
            self.operational_mode = m.get('OperationalMode')

        if m.get('PathAttributes') is not None:
            temp_model = main_models.ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes()
            self.path_attributes = temp_model.from_map(m.get('PathAttributes'))

        if m.get('PrefixListId') is not None:
            self.prefix_list_id = m.get('PrefixListId')

        if m.get('Tag') is not None:
            self.tag = m.get('Tag')

        if m.get('TransitRouterRouteEntryDescription') is not None:
            self.transit_router_route_entry_description = m.get('TransitRouterRouteEntryDescription')

        if m.get('TransitRouterRouteEntryDestinationCidrBlock') is not None:
            self.transit_router_route_entry_destination_cidr_block = m.get('TransitRouterRouteEntryDestinationCidrBlock')

        if m.get('TransitRouterRouteEntryId') is not None:
            self.transit_router_route_entry_id = m.get('TransitRouterRouteEntryId')

        if m.get('TransitRouterRouteEntryName') is not None:
            self.transit_router_route_entry_name = m.get('TransitRouterRouteEntryName')

        if m.get('TransitRouterRouteEntryNextHopId') is not None:
            self.transit_router_route_entry_next_hop_id = m.get('TransitRouterRouteEntryNextHopId')

        if m.get('TransitRouterRouteEntryNextHopResourceId') is not None:
            self.transit_router_route_entry_next_hop_resource_id = m.get('TransitRouterRouteEntryNextHopResourceId')

        if m.get('TransitRouterRouteEntryNextHopResourceType') is not None:
            self.transit_router_route_entry_next_hop_resource_type = m.get('TransitRouterRouteEntryNextHopResourceType')

        if m.get('TransitRouterRouteEntryNextHopType') is not None:
            self.transit_router_route_entry_next_hop_type = m.get('TransitRouterRouteEntryNextHopType')

        if m.get('TransitRouterRouteEntryOriginResourceId') is not None:
            self.transit_router_route_entry_origin_resource_id = m.get('TransitRouterRouteEntryOriginResourceId')

        if m.get('TransitRouterRouteEntryOriginResourceType') is not None:
            self.transit_router_route_entry_origin_resource_type = m.get('TransitRouterRouteEntryOriginResourceType')

        if m.get('TransitRouterRouteEntryStatus') is not None:
            self.transit_router_route_entry_status = m.get('TransitRouterRouteEntryStatus')

        if m.get('TransitRouterRouteEntryType') is not None:
            self.transit_router_route_entry_type = m.get('TransitRouterRouteEntryType')

        return self

class ListTransitRouterRouteEntriesResponseBodyTransitRouterRouteEntriesPathAttributes(DaraModel):
    def __init__(
        self,
        as_paths: List[str] = None,
        communities: List[str] = None,
        origin_instance_id: str = None,
        origin_instance_type: str = None,
        origin_route_type: str = None,
        preference: int = None,
    ):
        # The list of AS Path attributes of the route entry.
        self.as_paths = as_paths
        # The list of Community attributes of the route entry.
        self.communities = communities
        # The instance ID of the original instance from which the route entry originates.
        self.origin_instance_id = origin_instance_id
        # The type of the instance from which the route originates.
        # 
        # - **VPC**: Virtual Private Cloud (VPC) instance.
        # - **VBR**: Virtual Border Router (VBR) instance.
        # - **TR**: transit router instance.
        # - **VPN**: IPsec connection instance.
        # - **CCN**: Cloud Connect Network (CCN) instance.
        self.origin_instance_type = origin_instance_type
        # The original route type when the route was generated.
        # 
        # - **System**: system route.
        # - **Custom**: custom route.
        # - **Static**: static route.
        # - **BGP**: BGP route.
        # - **BlackHole**: blackhole route.
        self.origin_route_type = origin_route_type
        # The priority of the route entry.
        # 
        # A smaller value indicates a higher priority.
        self.preference = preference

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.as_paths is not None:
            result['AsPaths'] = self.as_paths

        if self.communities is not None:
            result['Communities'] = self.communities

        if self.origin_instance_id is not None:
            result['OriginInstanceId'] = self.origin_instance_id

        if self.origin_instance_type is not None:
            result['OriginInstanceType'] = self.origin_instance_type

        if self.origin_route_type is not None:
            result['OriginRouteType'] = self.origin_route_type

        if self.preference is not None:
            result['Preference'] = self.preference

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AsPaths') is not None:
            self.as_paths = m.get('AsPaths')

        if m.get('Communities') is not None:
            self.communities = m.get('Communities')

        if m.get('OriginInstanceId') is not None:
            self.origin_instance_id = m.get('OriginInstanceId')

        if m.get('OriginInstanceType') is not None:
            self.origin_instance_type = m.get('OriginInstanceType')

        if m.get('OriginRouteType') is not None:
            self.origin_route_type = m.get('OriginRouteType')

        if m.get('Preference') is not None:
            self.preference = m.get('Preference')

        return self

