# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from ._attach_kvcache_store_request import AttachKVCacheStoreRequest
from ._attach_kvcache_store_response_body import AttachKVCacheStoreResponseBody
from ._attach_kvcache_store_response import AttachKVCacheStoreResponse
from ._create_kvcache_store_request import CreateKVCacheStoreRequest
from ._create_kvcache_store_response_body import CreateKVCacheStoreResponseBody
from ._create_kvcache_store_response import CreateKVCacheStoreResponse
from ._delete_kvcache_store_request import DeleteKVCacheStoreRequest
from ._delete_kvcache_store_response_body import DeleteKVCacheStoreResponseBody
from ._delete_kvcache_store_response import DeleteKVCacheStoreResponse
from ._describe_regions_request import DescribeRegionsRequest
from ._describe_regions_response_body import DescribeRegionsResponseBody
from ._describe_regions_response import DescribeRegionsResponse
from ._describe_zones_request import DescribeZonesRequest
from ._describe_zones_response_body import DescribeZonesResponseBody
from ._describe_zones_response import DescribeZonesResponse
from ._detach_kvcache_store_request import DetachKVCacheStoreRequest
from ._detach_kvcache_store_response_body import DetachKVCacheStoreResponseBody
from ._detach_kvcache_store_response import DetachKVCacheStoreResponse
from ._get_kvcache_store_request import GetKVCacheStoreRequest
from ._get_kvcache_store_response_body import GetKVCacheStoreResponseBody
from ._get_kvcache_store_response import GetKVCacheStoreResponse
from ._list_kvcache_store_attach_info_request import ListKVCacheStoreAttachInfoRequest
from ._list_kvcache_store_attach_info_response_body import ListKVCacheStoreAttachInfoResponseBody
from ._list_kvcache_store_attach_info_response import ListKVCacheStoreAttachInfoResponse
from ._list_kvcache_store_available_hpn_zones_request import ListKVCacheStoreAvailableHpnZonesRequest
from ._list_kvcache_store_available_hpn_zones_response_body import ListKVCacheStoreAvailableHpnZonesResponseBody
from ._list_kvcache_store_available_hpn_zones_response import ListKVCacheStoreAvailableHpnZonesResponse
from ._list_kvcache_stores_request import ListKVCacheStoresRequest
from ._list_kvcache_stores_response_body import ListKVCacheStoresResponseBody
from ._list_kvcache_stores_response import ListKVCacheStoresResponse
from ._update_kvcache_store_request import UpdateKVCacheStoreRequest
from ._update_kvcache_store_response_body import UpdateKVCacheStoreResponseBody
from ._update_kvcache_store_response import UpdateKVCacheStoreResponse
from ._attach_kvcache_store_request import AttachKVCacheStoreRequestArns
from ._attach_kvcache_store_request import AttachKVCacheStoreRequestResourceIds
from ._attach_kvcache_store_response_body import AttachKVCacheStoreResponseBodyAttachResults
from ._create_kvcache_store_request import CreateKVCacheStoreRequestTag
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegions
from ._describe_zones_response_body import DescribeZonesResponseBodyZones
from ._detach_kvcache_store_request import DetachKVCacheStoreRequestResourceIds
from ._detach_kvcache_store_response_body import DetachKVCacheStoreResponseBodyDetachResults
from ._get_kvcache_store_response_body import GetKVCacheStoreResponseBodyKvCacheStoreTags
from ._get_kvcache_store_response_body import GetKVCacheStoreResponseBodyKvCacheStore
from ._list_kvcache_store_attach_info_response_body import ListKVCacheStoreAttachInfoResponseBodyAttachInfos
from ._list_kvcache_store_available_hpn_zones_response_body import ListKVCacheStoreAvailableHpnZonesResponseBodyInstanceHpnZonesAvailableHpnZones
from ._list_kvcache_store_available_hpn_zones_response_body import ListKVCacheStoreAvailableHpnZonesResponseBodyInstanceHpnZones
from ._list_kvcache_stores_response_body import ListKVCacheStoresResponseBodyKVCacheStoresTags
from ._list_kvcache_stores_response_body import ListKVCacheStoresResponseBodyKVCacheStores
from ._update_kvcache_store_request import UpdateKVCacheStoreRequestTag

__all__ = [
    AttachKVCacheStoreRequest,
    AttachKVCacheStoreResponseBody,
    AttachKVCacheStoreResponse,
    CreateKVCacheStoreRequest,
    CreateKVCacheStoreResponseBody,
    CreateKVCacheStoreResponse,
    DeleteKVCacheStoreRequest,
    DeleteKVCacheStoreResponseBody,
    DeleteKVCacheStoreResponse,
    DescribeRegionsRequest,
    DescribeRegionsResponseBody,
    DescribeRegionsResponse,
    DescribeZonesRequest,
    DescribeZonesResponseBody,
    DescribeZonesResponse,
    DetachKVCacheStoreRequest,
    DetachKVCacheStoreResponseBody,
    DetachKVCacheStoreResponse,
    GetKVCacheStoreRequest,
    GetKVCacheStoreResponseBody,
    GetKVCacheStoreResponse,
    ListKVCacheStoreAttachInfoRequest,
    ListKVCacheStoreAttachInfoResponseBody,
    ListKVCacheStoreAttachInfoResponse,
    ListKVCacheStoreAvailableHpnZonesRequest,
    ListKVCacheStoreAvailableHpnZonesResponseBody,
    ListKVCacheStoreAvailableHpnZonesResponse,
    ListKVCacheStoresRequest,
    ListKVCacheStoresResponseBody,
    ListKVCacheStoresResponse,
    UpdateKVCacheStoreRequest,
    UpdateKVCacheStoreResponseBody,
    UpdateKVCacheStoreResponse,
    AttachKVCacheStoreRequestArns,
    AttachKVCacheStoreRequestResourceIds,
    AttachKVCacheStoreResponseBodyAttachResults,
    CreateKVCacheStoreRequestTag,
    DescribeRegionsResponseBodyRegions,
    DescribeZonesResponseBodyZones,
    DetachKVCacheStoreRequestResourceIds,
    DetachKVCacheStoreResponseBodyDetachResults,
    GetKVCacheStoreResponseBodyKvCacheStoreTags,
    GetKVCacheStoreResponseBodyKvCacheStore,
    ListKVCacheStoreAttachInfoResponseBodyAttachInfos,
    ListKVCacheStoreAvailableHpnZonesResponseBodyInstanceHpnZonesAvailableHpnZones,
    ListKVCacheStoreAvailableHpnZonesResponseBodyInstanceHpnZones,
    ListKVCacheStoresResponseBodyKVCacheStoresTags,
    ListKVCacheStoresResponseBodyKVCacheStores,
    UpdateKVCacheStoreRequestTag
]
