# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from ._ots_detail import OtsDetail
from ._ots_table_restore_detail import OtsTableRestoreDetail
from ._report import Report
from ._rule import Rule
from ._add_container_cluster_request import AddContainerClusterRequest
from ._add_container_cluster_response_body import AddContainerClusterResponseBody
from ._add_container_cluster_response import AddContainerClusterResponse
from ._cancel_backup_job_request import CancelBackupJobRequest
from ._cancel_backup_job_response_body import CancelBackupJobResponseBody
from ._cancel_backup_job_response import CancelBackupJobResponse
from ._cancel_restore_job_request import CancelRestoreJobRequest
from ._cancel_restore_job_response_body import CancelRestoreJobResponseBody
from ._cancel_restore_job_response import CancelRestoreJobResponse
from ._change_resource_group_request import ChangeResourceGroupRequest
from ._change_resource_group_response_body import ChangeResourceGroupResponseBody
from ._change_resource_group_response import ChangeResourceGroupResponse
from ._check_role_request import CheckRoleRequest
from ._check_role_response_body import CheckRoleResponseBody
from ._check_role_response import CheckRoleResponse
from ._create_backup_job_request import CreateBackupJobRequest
from ._create_backup_job_shrink_request import CreateBackupJobShrinkRequest
from ._create_backup_job_response_body import CreateBackupJobResponseBody
from ._create_backup_job_response import CreateBackupJobResponse
from ._create_backup_plan_request import CreateBackupPlanRequest
from ._create_backup_plan_shrink_request import CreateBackupPlanShrinkRequest
from ._create_backup_plan_response_body import CreateBackupPlanResponseBody
from ._create_backup_plan_response import CreateBackupPlanResponse
from ._create_clients_request import CreateClientsRequest
from ._create_clients_response_body import CreateClientsResponseBody
from ._create_clients_response import CreateClientsResponse
from ._create_hana_backup_plan_request import CreateHanaBackupPlanRequest
from ._create_hana_backup_plan_response_body import CreateHanaBackupPlanResponseBody
from ._create_hana_backup_plan_response import CreateHanaBackupPlanResponse
from ._create_hana_instance_request import CreateHanaInstanceRequest
from ._create_hana_instance_response_body import CreateHanaInstanceResponseBody
from ._create_hana_instance_response import CreateHanaInstanceResponse
from ._create_hana_restore_request import CreateHanaRestoreRequest
from ._create_hana_restore_response_body import CreateHanaRestoreResponseBody
from ._create_hana_restore_response import CreateHanaRestoreResponse
from ._create_policy_bindings_request import CreatePolicyBindingsRequest
from ._create_policy_bindings_shrink_request import CreatePolicyBindingsShrinkRequest
from ._create_policy_bindings_response_body import CreatePolicyBindingsResponseBody
from ._create_policy_bindings_response import CreatePolicyBindingsResponse
from ._create_policy_v2request import CreatePolicyV2Request
from ._create_policy_v2shrink_request import CreatePolicyV2ShrinkRequest
from ._create_policy_v2response_body import CreatePolicyV2ResponseBody
from ._create_policy_v2response import CreatePolicyV2Response
from ._create_replication_vault_request import CreateReplicationVaultRequest
from ._create_replication_vault_response_body import CreateReplicationVaultResponseBody
from ._create_replication_vault_response import CreateReplicationVaultResponse
from ._create_restore_job_request import CreateRestoreJobRequest
from ._create_restore_job_shrink_request import CreateRestoreJobShrinkRequest
from ._create_restore_job_response_body import CreateRestoreJobResponseBody
from ._create_restore_job_response import CreateRestoreJobResponse
from ._create_temp_file_upload_url_request import CreateTempFileUploadUrlRequest
from ._create_temp_file_upload_url_response_body import CreateTempFileUploadUrlResponseBody
from ._create_temp_file_upload_url_response import CreateTempFileUploadUrlResponse
from ._create_vault_request import CreateVaultRequest
from ._create_vault_response_body import CreateVaultResponseBody
from ._create_vault_response import CreateVaultResponse
from ._create_vault_replication_request import CreateVaultReplicationRequest
from ._create_vault_replication_response_body import CreateVaultReplicationResponseBody
from ._create_vault_replication_response import CreateVaultReplicationResponse
from ._delete_air_ecs_instance_request import DeleteAirEcsInstanceRequest
from ._delete_air_ecs_instance_shrink_request import DeleteAirEcsInstanceShrinkRequest
from ._delete_air_ecs_instance_response_body import DeleteAirEcsInstanceResponseBody
from ._delete_air_ecs_instance_response import DeleteAirEcsInstanceResponse
from ._delete_backup_client_request import DeleteBackupClientRequest
from ._delete_backup_client_response_body import DeleteBackupClientResponseBody
from ._delete_backup_client_response import DeleteBackupClientResponse
from ._delete_backup_client_resource_request import DeleteBackupClientResourceRequest
from ._delete_backup_client_resource_shrink_request import DeleteBackupClientResourceShrinkRequest
from ._delete_backup_client_resource_response_body import DeleteBackupClientResourceResponseBody
from ._delete_backup_client_resource_response import DeleteBackupClientResourceResponse
from ._delete_backup_plan_request import DeleteBackupPlanRequest
from ._delete_backup_plan_response_body import DeleteBackupPlanResponseBody
from ._delete_backup_plan_response import DeleteBackupPlanResponse
from ._delete_client_request import DeleteClientRequest
from ._delete_client_response_body import DeleteClientResponseBody
from ._delete_client_response import DeleteClientResponse
from ._delete_hana_backup_plan_request import DeleteHanaBackupPlanRequest
from ._delete_hana_backup_plan_response_body import DeleteHanaBackupPlanResponseBody
from ._delete_hana_backup_plan_response import DeleteHanaBackupPlanResponse
from ._delete_hana_instance_request import DeleteHanaInstanceRequest
from ._delete_hana_instance_response_body import DeleteHanaInstanceResponseBody
from ._delete_hana_instance_response import DeleteHanaInstanceResponse
from ._delete_policy_binding_request import DeletePolicyBindingRequest
from ._delete_policy_binding_shrink_request import DeletePolicyBindingShrinkRequest
from ._delete_policy_binding_response_body import DeletePolicyBindingResponseBody
from ._delete_policy_binding_response import DeletePolicyBindingResponse
from ._delete_policy_v2request import DeletePolicyV2Request
from ._delete_policy_v2response_body import DeletePolicyV2ResponseBody
from ._delete_policy_v2response import DeletePolicyV2Response
from ._delete_snapshot_request import DeleteSnapshotRequest
from ._delete_snapshot_response_body import DeleteSnapshotResponseBody
from ._delete_snapshot_response import DeleteSnapshotResponse
from ._delete_udm_disk_request import DeleteUdmDiskRequest
from ._delete_udm_disk_response_body import DeleteUdmDiskResponseBody
from ._delete_udm_disk_response import DeleteUdmDiskResponse
from ._delete_udm_ecs_instance_request import DeleteUdmEcsInstanceRequest
from ._delete_udm_ecs_instance_response_body import DeleteUdmEcsInstanceResponseBody
from ._delete_udm_ecs_instance_response import DeleteUdmEcsInstanceResponse
from ._delete_vault_request import DeleteVaultRequest
from ._delete_vault_response_body import DeleteVaultResponseBody
from ._delete_vault_response import DeleteVaultResponse
from ._delete_vault_replication_request import DeleteVaultReplicationRequest
from ._delete_vault_replication_response_body import DeleteVaultReplicationResponseBody
from ._delete_vault_replication_response import DeleteVaultReplicationResponse
from ._describe_backup_clients_request import DescribeBackupClientsRequest
from ._describe_backup_clients_shrink_request import DescribeBackupClientsShrinkRequest
from ._describe_backup_clients_response_body import DescribeBackupClientsResponseBody
from ._describe_backup_clients_response import DescribeBackupClientsResponse
from ._describe_backup_jobs_2request import DescribeBackupJobs2Request
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBody
from ._describe_backup_jobs_2response import DescribeBackupJobs2Response
from ._describe_backup_plans_request import DescribeBackupPlansRequest
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBody
from ._describe_backup_plans_response import DescribeBackupPlansResponse
from ._describe_clients_request import DescribeClientsRequest
from ._describe_clients_response_body import DescribeClientsResponseBody
from ._describe_clients_response import DescribeClientsResponse
from ._describe_container_cluster_request import DescribeContainerClusterRequest
from ._describe_container_cluster_response_body import DescribeContainerClusterResponseBody
from ._describe_container_cluster_response import DescribeContainerClusterResponse
from ._describe_cross_accounts_request import DescribeCrossAccountsRequest
from ._describe_cross_accounts_response_body import DescribeCrossAccountsResponseBody
from ._describe_cross_accounts_response import DescribeCrossAccountsResponse
from ._describe_hana_backup_plans_request import DescribeHanaBackupPlansRequest
from ._describe_hana_backup_plans_response_body import DescribeHanaBackupPlansResponseBody
from ._describe_hana_backup_plans_response import DescribeHanaBackupPlansResponse
from ._describe_hana_backup_setting_request import DescribeHanaBackupSettingRequest
from ._describe_hana_backup_setting_response_body import DescribeHanaBackupSettingResponseBody
from ._describe_hana_backup_setting_response import DescribeHanaBackupSettingResponse
from ._describe_hana_backups_async_request import DescribeHanaBackupsAsyncRequest
from ._describe_hana_backups_async_response_body import DescribeHanaBackupsAsyncResponseBody
from ._describe_hana_backups_async_response import DescribeHanaBackupsAsyncResponse
from ._describe_hana_databases_request import DescribeHanaDatabasesRequest
from ._describe_hana_databases_response_body import DescribeHanaDatabasesResponseBody
from ._describe_hana_databases_response import DescribeHanaDatabasesResponse
from ._describe_hana_instances_request import DescribeHanaInstancesRequest
from ._describe_hana_instances_response_body import DescribeHanaInstancesResponseBody
from ._describe_hana_instances_response import DescribeHanaInstancesResponse
from ._describe_hana_restores_request import DescribeHanaRestoresRequest
from ._describe_hana_restores_response_body import DescribeHanaRestoresResponseBody
from ._describe_hana_restores_response import DescribeHanaRestoresResponse
from ._describe_hana_retention_setting_request import DescribeHanaRetentionSettingRequest
from ._describe_hana_retention_setting_response_body import DescribeHanaRetentionSettingResponseBody
from ._describe_hana_retention_setting_response import DescribeHanaRetentionSettingResponse
from ._describe_ots_table_snapshots_request import DescribeOtsTableSnapshotsRequest
from ._describe_ots_table_snapshots_response_body import DescribeOtsTableSnapshotsResponseBody
from ._describe_ots_table_snapshots_response import DescribeOtsTableSnapshotsResponse
from ._describe_policies_v2request import DescribePoliciesV2Request
from ._describe_policies_v2response_body import DescribePoliciesV2ResponseBody
from ._describe_policies_v2response import DescribePoliciesV2Response
from ._describe_policy_bindings_request import DescribePolicyBindingsRequest
from ._describe_policy_bindings_shrink_request import DescribePolicyBindingsShrinkRequest
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBody
from ._describe_policy_bindings_response import DescribePolicyBindingsResponse
from ._describe_recoverable_ots_instances_request import DescribeRecoverableOtsInstancesRequest
from ._describe_recoverable_ots_instances_response_body import DescribeRecoverableOtsInstancesResponseBody
from ._describe_recoverable_ots_instances_response import DescribeRecoverableOtsInstancesResponse
from ._describe_regions_response_body import DescribeRegionsResponseBody
from ._describe_regions_response import DescribeRegionsResponse
from ._describe_restore_jobs_2request import DescribeRestoreJobs2Request
from ._describe_restore_jobs_2response_body import DescribeRestoreJobs2ResponseBody
from ._describe_restore_jobs_2response import DescribeRestoreJobs2Response
from ._describe_task_request import DescribeTaskRequest
from ._describe_task_response_body import DescribeTaskResponseBody
from ._describe_task_response import DescribeTaskResponse
from ._describe_udm_snapshots_request import DescribeUdmSnapshotsRequest
from ._describe_udm_snapshots_shrink_request import DescribeUdmSnapshotsShrinkRequest
from ._describe_udm_snapshots_response_body import DescribeUdmSnapshotsResponseBody
from ._describe_udm_snapshots_response import DescribeUdmSnapshotsResponse
from ._describe_vault_replication_regions_request import DescribeVaultReplicationRegionsRequest
from ._describe_vault_replication_regions_response_body import DescribeVaultReplicationRegionsResponseBody
from ._describe_vault_replication_regions_response import DescribeVaultReplicationRegionsResponse
from ._describe_vaults_request import DescribeVaultsRequest
from ._describe_vaults_response_body import DescribeVaultsResponseBody
from ._describe_vaults_response import DescribeVaultsResponse
from ._detach_nas_file_system_request import DetachNasFileSystemRequest
from ._detach_nas_file_system_response_body import DetachNasFileSystemResponseBody
from ._detach_nas_file_system_response import DetachNasFileSystemResponse
from ._disable_backup_plan_request import DisableBackupPlanRequest
from ._disable_backup_plan_response_body import DisableBackupPlanResponseBody
from ._disable_backup_plan_response import DisableBackupPlanResponse
from ._disable_hana_backup_plan_request import DisableHanaBackupPlanRequest
from ._disable_hana_backup_plan_response_body import DisableHanaBackupPlanResponseBody
from ._disable_hana_backup_plan_response import DisableHanaBackupPlanResponse
from ._enable_backup_plan_request import EnableBackupPlanRequest
from ._enable_backup_plan_response_body import EnableBackupPlanResponseBody
from ._enable_backup_plan_response import EnableBackupPlanResponse
from ._enable_hana_backup_plan_request import EnableHanaBackupPlanRequest
from ._enable_hana_backup_plan_response_body import EnableHanaBackupPlanResponseBody
from ._enable_hana_backup_plan_response import EnableHanaBackupPlanResponse
from ._execute_backup_plan_request import ExecuteBackupPlanRequest
from ._execute_backup_plan_response_body import ExecuteBackupPlanResponseBody
from ._execute_backup_plan_response import ExecuteBackupPlanResponse
from ._execute_policy_v2request import ExecutePolicyV2Request
from ._execute_policy_v2response_body import ExecutePolicyV2ResponseBody
from ._execute_policy_v2response import ExecutePolicyV2Response
from ._generate_ram_policy_request import GenerateRamPolicyRequest
from ._generate_ram_policy_response_body import GenerateRamPolicyResponseBody
from ._generate_ram_policy_response import GenerateRamPolicyResponse
from ._get_temp_file_download_link_request import GetTempFileDownloadLinkRequest
from ._get_temp_file_download_link_response_body import GetTempFileDownloadLinkResponseBody
from ._get_temp_file_download_link_response import GetTempFileDownloadLinkResponse
from ._install_backup_clients_request import InstallBackupClientsRequest
from ._install_backup_clients_shrink_request import InstallBackupClientsShrinkRequest
from ._install_backup_clients_response_body import InstallBackupClientsResponseBody
from ._install_backup_clients_response import InstallBackupClientsResponse
from ._list_protected_resources_request import ListProtectedResourcesRequest
from ._list_protected_resources_response_body import ListProtectedResourcesResponseBody
from ._list_protected_resources_response import ListProtectedResourcesResponse
from ._open_hbr_service_response_body import OpenHbrServiceResponseBody
from ._open_hbr_service_response import OpenHbrServiceResponse
from ._search_historical_snapshots_request import SearchHistoricalSnapshotsRequest
from ._search_historical_snapshots_shrink_request import SearchHistoricalSnapshotsShrinkRequest
from ._search_historical_snapshots_response_body import SearchHistoricalSnapshotsResponseBody
from ._search_historical_snapshots_response import SearchHistoricalSnapshotsResponse
from ._start_hana_database_async_request import StartHanaDatabaseAsyncRequest
from ._start_hana_database_async_response_body import StartHanaDatabaseAsyncResponseBody
from ._start_hana_database_async_response import StartHanaDatabaseAsyncResponse
from ._stop_hana_database_async_request import StopHanaDatabaseAsyncRequest
from ._stop_hana_database_async_response_body import StopHanaDatabaseAsyncResponseBody
from ._stop_hana_database_async_response import StopHanaDatabaseAsyncResponse
from ._uninstall_backup_clients_request import UninstallBackupClientsRequest
from ._uninstall_backup_clients_shrink_request import UninstallBackupClientsShrinkRequest
from ._uninstall_backup_clients_response_body import UninstallBackupClientsResponseBody
from ._uninstall_backup_clients_response import UninstallBackupClientsResponse
from ._uninstall_client_request import UninstallClientRequest
from ._uninstall_client_response_body import UninstallClientResponseBody
from ._uninstall_client_response import UninstallClientResponse
from ._update_backup_plan_request import UpdateBackupPlanRequest
from ._update_backup_plan_shrink_request import UpdateBackupPlanShrinkRequest
from ._update_backup_plan_response_body import UpdateBackupPlanResponseBody
from ._update_backup_plan_response import UpdateBackupPlanResponse
from ._update_client_settings_request import UpdateClientSettingsRequest
from ._update_client_settings_response_body import UpdateClientSettingsResponseBody
from ._update_client_settings_response import UpdateClientSettingsResponse
from ._update_container_cluster_request import UpdateContainerClusterRequest
from ._update_container_cluster_response_body import UpdateContainerClusterResponseBody
from ._update_container_cluster_response import UpdateContainerClusterResponse
from ._update_hana_backup_plan_request import UpdateHanaBackupPlanRequest
from ._update_hana_backup_plan_response_body import UpdateHanaBackupPlanResponseBody
from ._update_hana_backup_plan_response import UpdateHanaBackupPlanResponse
from ._update_hana_backup_setting_request import UpdateHanaBackupSettingRequest
from ._update_hana_backup_setting_response_body import UpdateHanaBackupSettingResponseBody
from ._update_hana_backup_setting_response import UpdateHanaBackupSettingResponse
from ._update_hana_instance_request import UpdateHanaInstanceRequest
from ._update_hana_instance_response_body import UpdateHanaInstanceResponseBody
from ._update_hana_instance_response import UpdateHanaInstanceResponse
from ._update_hana_retention_setting_request import UpdateHanaRetentionSettingRequest
from ._update_hana_retention_setting_response_body import UpdateHanaRetentionSettingResponseBody
from ._update_hana_retention_setting_response import UpdateHanaRetentionSettingResponse
from ._update_policy_binding_request import UpdatePolicyBindingRequest
from ._update_policy_binding_shrink_request import UpdatePolicyBindingShrinkRequest
from ._update_policy_binding_response_body import UpdatePolicyBindingResponseBody
from ._update_policy_binding_response import UpdatePolicyBindingResponse
from ._update_policy_v2request import UpdatePolicyV2Request
from ._update_policy_v2shrink_request import UpdatePolicyV2ShrinkRequest
from ._update_policy_v2response_body import UpdatePolicyV2ResponseBody
from ._update_policy_v2response import UpdatePolicyV2Response
from ._update_vault_request import UpdateVaultRequest
from ._update_vault_response_body import UpdateVaultResponseBody
from ._update_vault_response import UpdateVaultResponse
from ._upgrade_backup_clients_request import UpgradeBackupClientsRequest
from ._upgrade_backup_clients_shrink_request import UpgradeBackupClientsShrinkRequest
from ._upgrade_backup_clients_response_body import UpgradeBackupClientsResponseBody
from ._upgrade_backup_clients_response import UpgradeBackupClientsResponse
from ._upgrade_client_request import UpgradeClientRequest
from ._upgrade_client_response_body import UpgradeClientResponseBody
from ._upgrade_client_response import UpgradeClientResponse
from ._create_backup_plan_request import CreateBackupPlanRequestRule
from ._create_backup_plan_shrink_request import CreateBackupPlanShrinkRequestRule
from ._create_clients_response_body import CreateClientsResponseBodyInstanceStatusesInstanceStatus
from ._create_clients_response_body import CreateClientsResponseBodyInstanceStatuses
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsCommonFileSystemDetail
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsCommonNasDetail
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsFileDetail
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsOssDetail
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsUdmDetail
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingListAdvancedOptions
from ._create_policy_bindings_request import CreatePolicyBindingsRequestPolicyBindingList
from ._create_policy_v2request import CreatePolicyV2RequestRulesDataSourceFilters
from ._create_policy_v2request import CreatePolicyV2RequestRulesRetentionRules
from ._create_policy_v2request import CreatePolicyV2RequestRulesTagFilters
from ._create_policy_v2request import CreatePolicyV2RequestRules
from ._describe_backup_clients_request import DescribeBackupClientsRequestFilters
from ._describe_backup_clients_request import DescribeBackupClientsRequestTag
from ._describe_backup_clients_shrink_request import DescribeBackupClientsShrinkRequestFilters
from ._describe_backup_clients_shrink_request import DescribeBackupClientsShrinkRequestTag
from ._describe_backup_clients_response_body import DescribeBackupClientsResponseBodyClientsSettings
from ._describe_backup_clients_response_body import DescribeBackupClientsResponseBodyClientsTags
from ._describe_backup_clients_response_body import DescribeBackupClientsResponseBodyClients
from ._describe_backup_jobs_2request import DescribeBackupJobs2RequestFilters
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJobDetailDiskNativeSnapshotIdList
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJobDetail
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJobOtsDetailTableNames
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJobOtsDetail
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJobPaths
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJobReport
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobsBackupJob
from ._describe_backup_jobs_2response_body import DescribeBackupJobs2ResponseBodyBackupJobs
from ._describe_backup_plans_request import DescribeBackupPlansRequestFilters
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanHitTagsHitTag
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanHitTags
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanOtsDetailTableNames
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanOtsDetail
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanPaths
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanResourcesResource
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanResources
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanRulesRule
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanRules
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlanTrialInfo
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlansBackupPlan
from ._describe_backup_plans_response_body import DescribeBackupPlansResponseBodyBackupPlans
from ._describe_clients_response_body import DescribeClientsResponseBodyClientsClient
from ._describe_clients_response_body import DescribeClientsResponseBodyClients
from ._describe_container_cluster_response_body import DescribeContainerClusterResponseBodyClusters
from ._describe_cross_accounts_response_body import DescribeCrossAccountsResponseBodyCrossAccountsCrossAccount
from ._describe_cross_accounts_response_body import DescribeCrossAccountsResponseBodyCrossAccounts
from ._describe_hana_backup_plans_response_body import DescribeHanaBackupPlansResponseBodyHanaBackupPlansHanaBackupPlan
from ._describe_hana_backup_plans_response_body import DescribeHanaBackupPlansResponseBodyHanaBackupPlans
from ._describe_hana_backup_setting_response_body import DescribeHanaBackupSettingResponseBodyHanaBackupSetting
from ._describe_hana_databases_response_body import DescribeHanaDatabasesResponseBodyHanaDatabasesHanaDatabase
from ._describe_hana_databases_response_body import DescribeHanaDatabasesResponseBodyHanaDatabases
from ._describe_hana_instances_request import DescribeHanaInstancesRequestTag
from ._describe_hana_instances_response_body import DescribeHanaInstancesResponseBodyHanasHanaTagsTag
from ._describe_hana_instances_response_body import DescribeHanaInstancesResponseBodyHanasHanaTags
from ._describe_hana_instances_response_body import DescribeHanaInstancesResponseBodyHanasHana
from ._describe_hana_instances_response_body import DescribeHanaInstancesResponseBodyHanas
from ._describe_hana_restores_response_body import DescribeHanaRestoresResponseBodyHanaRestoreHanaRestores
from ._describe_hana_restores_response_body import DescribeHanaRestoresResponseBodyHanaRestore
from ._describe_ots_table_snapshots_request import DescribeOtsTableSnapshotsRequestOtsInstances
from ._describe_ots_table_snapshots_response_body import DescribeOtsTableSnapshotsResponseBodySnapshots
from ._describe_policies_v2response_body import DescribePoliciesV2ResponseBodyPoliciesRulesDataSourceFilters
from ._describe_policies_v2response_body import DescribePoliciesV2ResponseBodyPoliciesRulesRetentionRules
from ._describe_policies_v2response_body import DescribePoliciesV2ResponseBodyPoliciesRulesTagFilters
from ._describe_policies_v2response_body import DescribePoliciesV2ResponseBodyPoliciesRules
from ._describe_policies_v2response_body import DescribePoliciesV2ResponseBodyPolicies
from ._describe_policy_bindings_request import DescribePolicyBindingsRequestFilters
from ._describe_policy_bindings_shrink_request import DescribePolicyBindingsShrinkRequestFilters
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsCommonFileSystemDetail
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsCommonNasDetail
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsFileDetail
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsOssDetail
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsUdmDetail
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptions
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindingsHitTags
from ._describe_policy_bindings_response_body import DescribePolicyBindingsResponseBodyPolicyBindings
from ._describe_recoverable_ots_instances_response_body import DescribeRecoverableOtsInstancesResponseBodyOtsInstances
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegionsRegion
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegions
from ._describe_restore_jobs_2request import DescribeRestoreJobs2RequestFilters
from ._describe_restore_jobs_2response_body import DescribeRestoreJobs2ResponseBodyRestoreJobsRestoreJobOtsDetail
from ._describe_restore_jobs_2response_body import DescribeRestoreJobs2ResponseBodyRestoreJobsRestoreJobReport
from ._describe_restore_jobs_2response_body import DescribeRestoreJobs2ResponseBodyRestoreJobsRestoreJob
from ._describe_restore_jobs_2response_body import DescribeRestoreJobs2ResponseBodyRestoreJobs
from ._describe_udm_snapshots_response_body import DescribeUdmSnapshotsResponseBodySnapshotsDetail
from ._describe_udm_snapshots_response_body import DescribeUdmSnapshotsResponseBodySnapshots
from ._describe_vault_replication_regions_response_body import DescribeVaultReplicationRegionsResponseBodyRegions
from ._describe_vaults_request import DescribeVaultsRequestTag
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultBackupPlanStatistics
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultReplicationProgress
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultRsTargetAccountIds
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultSourceTypes
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultTagsTag
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultTags
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVaultTrialInfo
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaultsVault
from ._describe_vaults_response_body import DescribeVaultsResponseBodyVaults
from ._install_backup_clients_response_body import InstallBackupClientsResponseBodyInstanceStatuses
from ._list_protected_resources_response_body import ListProtectedResourcesResponseBodyProtectedResources
from ._search_historical_snapshots_response_body import SearchHistoricalSnapshotsResponseBodySnapshotsSnapshotPaths
from ._search_historical_snapshots_response_body import SearchHistoricalSnapshotsResponseBodySnapshotsSnapshot
from ._search_historical_snapshots_response_body import SearchHistoricalSnapshotsResponseBodySnapshots
from ._uninstall_backup_clients_response_body import UninstallBackupClientsResponseBodyInstanceStatuses
from ._update_backup_plan_request import UpdateBackupPlanRequestRule
from ._update_backup_plan_shrink_request import UpdateBackupPlanShrinkRequestRule
from ._update_policy_binding_request import UpdatePolicyBindingRequestAdvancedOptionsCommonFileSystemDetail
from ._update_policy_binding_request import UpdatePolicyBindingRequestAdvancedOptionsOssDetail
from ._update_policy_binding_request import UpdatePolicyBindingRequestAdvancedOptionsUdmDetail
from ._update_policy_binding_request import UpdatePolicyBindingRequestAdvancedOptions
from ._update_policy_v2request import UpdatePolicyV2RequestRulesDataSourceFilters
from ._update_policy_v2request import UpdatePolicyV2RequestRulesRetentionRules
from ._update_policy_v2request import UpdatePolicyV2RequestRulesTagFilters
from ._update_policy_v2request import UpdatePolicyV2RequestRules
from ._upgrade_backup_clients_response_body import UpgradeBackupClientsResponseBodyInstanceStatuses

__all__ = [
    OtsDetail,
    OtsTableRestoreDetail,
    Report,
    Rule,
    AddContainerClusterRequest,
    AddContainerClusterResponseBody,
    AddContainerClusterResponse,
    CancelBackupJobRequest,
    CancelBackupJobResponseBody,
    CancelBackupJobResponse,
    CancelRestoreJobRequest,
    CancelRestoreJobResponseBody,
    CancelRestoreJobResponse,
    ChangeResourceGroupRequest,
    ChangeResourceGroupResponseBody,
    ChangeResourceGroupResponse,
    CheckRoleRequest,
    CheckRoleResponseBody,
    CheckRoleResponse,
    CreateBackupJobRequest,
    CreateBackupJobShrinkRequest,
    CreateBackupJobResponseBody,
    CreateBackupJobResponse,
    CreateBackupPlanRequest,
    CreateBackupPlanShrinkRequest,
    CreateBackupPlanResponseBody,
    CreateBackupPlanResponse,
    CreateClientsRequest,
    CreateClientsResponseBody,
    CreateClientsResponse,
    CreateHanaBackupPlanRequest,
    CreateHanaBackupPlanResponseBody,
    CreateHanaBackupPlanResponse,
    CreateHanaInstanceRequest,
    CreateHanaInstanceResponseBody,
    CreateHanaInstanceResponse,
    CreateHanaRestoreRequest,
    CreateHanaRestoreResponseBody,
    CreateHanaRestoreResponse,
    CreatePolicyBindingsRequest,
    CreatePolicyBindingsShrinkRequest,
    CreatePolicyBindingsResponseBody,
    CreatePolicyBindingsResponse,
    CreatePolicyV2Request,
    CreatePolicyV2ShrinkRequest,
    CreatePolicyV2ResponseBody,
    CreatePolicyV2Response,
    CreateReplicationVaultRequest,
    CreateReplicationVaultResponseBody,
    CreateReplicationVaultResponse,
    CreateRestoreJobRequest,
    CreateRestoreJobShrinkRequest,
    CreateRestoreJobResponseBody,
    CreateRestoreJobResponse,
    CreateTempFileUploadUrlRequest,
    CreateTempFileUploadUrlResponseBody,
    CreateTempFileUploadUrlResponse,
    CreateVaultRequest,
    CreateVaultResponseBody,
    CreateVaultResponse,
    CreateVaultReplicationRequest,
    CreateVaultReplicationResponseBody,
    CreateVaultReplicationResponse,
    DeleteAirEcsInstanceRequest,
    DeleteAirEcsInstanceShrinkRequest,
    DeleteAirEcsInstanceResponseBody,
    DeleteAirEcsInstanceResponse,
    DeleteBackupClientRequest,
    DeleteBackupClientResponseBody,
    DeleteBackupClientResponse,
    DeleteBackupClientResourceRequest,
    DeleteBackupClientResourceShrinkRequest,
    DeleteBackupClientResourceResponseBody,
    DeleteBackupClientResourceResponse,
    DeleteBackupPlanRequest,
    DeleteBackupPlanResponseBody,
    DeleteBackupPlanResponse,
    DeleteClientRequest,
    DeleteClientResponseBody,
    DeleteClientResponse,
    DeleteHanaBackupPlanRequest,
    DeleteHanaBackupPlanResponseBody,
    DeleteHanaBackupPlanResponse,
    DeleteHanaInstanceRequest,
    DeleteHanaInstanceResponseBody,
    DeleteHanaInstanceResponse,
    DeletePolicyBindingRequest,
    DeletePolicyBindingShrinkRequest,
    DeletePolicyBindingResponseBody,
    DeletePolicyBindingResponse,
    DeletePolicyV2Request,
    DeletePolicyV2ResponseBody,
    DeletePolicyV2Response,
    DeleteSnapshotRequest,
    DeleteSnapshotResponseBody,
    DeleteSnapshotResponse,
    DeleteUdmDiskRequest,
    DeleteUdmDiskResponseBody,
    DeleteUdmDiskResponse,
    DeleteUdmEcsInstanceRequest,
    DeleteUdmEcsInstanceResponseBody,
    DeleteUdmEcsInstanceResponse,
    DeleteVaultRequest,
    DeleteVaultResponseBody,
    DeleteVaultResponse,
    DeleteVaultReplicationRequest,
    DeleteVaultReplicationResponseBody,
    DeleteVaultReplicationResponse,
    DescribeBackupClientsRequest,
    DescribeBackupClientsShrinkRequest,
    DescribeBackupClientsResponseBody,
    DescribeBackupClientsResponse,
    DescribeBackupJobs2Request,
    DescribeBackupJobs2ResponseBody,
    DescribeBackupJobs2Response,
    DescribeBackupPlansRequest,
    DescribeBackupPlansResponseBody,
    DescribeBackupPlansResponse,
    DescribeClientsRequest,
    DescribeClientsResponseBody,
    DescribeClientsResponse,
    DescribeContainerClusterRequest,
    DescribeContainerClusterResponseBody,
    DescribeContainerClusterResponse,
    DescribeCrossAccountsRequest,
    DescribeCrossAccountsResponseBody,
    DescribeCrossAccountsResponse,
    DescribeHanaBackupPlansRequest,
    DescribeHanaBackupPlansResponseBody,
    DescribeHanaBackupPlansResponse,
    DescribeHanaBackupSettingRequest,
    DescribeHanaBackupSettingResponseBody,
    DescribeHanaBackupSettingResponse,
    DescribeHanaBackupsAsyncRequest,
    DescribeHanaBackupsAsyncResponseBody,
    DescribeHanaBackupsAsyncResponse,
    DescribeHanaDatabasesRequest,
    DescribeHanaDatabasesResponseBody,
    DescribeHanaDatabasesResponse,
    DescribeHanaInstancesRequest,
    DescribeHanaInstancesResponseBody,
    DescribeHanaInstancesResponse,
    DescribeHanaRestoresRequest,
    DescribeHanaRestoresResponseBody,
    DescribeHanaRestoresResponse,
    DescribeHanaRetentionSettingRequest,
    DescribeHanaRetentionSettingResponseBody,
    DescribeHanaRetentionSettingResponse,
    DescribeOtsTableSnapshotsRequest,
    DescribeOtsTableSnapshotsResponseBody,
    DescribeOtsTableSnapshotsResponse,
    DescribePoliciesV2Request,
    DescribePoliciesV2ResponseBody,
    DescribePoliciesV2Response,
    DescribePolicyBindingsRequest,
    DescribePolicyBindingsShrinkRequest,
    DescribePolicyBindingsResponseBody,
    DescribePolicyBindingsResponse,
    DescribeRecoverableOtsInstancesRequest,
    DescribeRecoverableOtsInstancesResponseBody,
    DescribeRecoverableOtsInstancesResponse,
    DescribeRegionsResponseBody,
    DescribeRegionsResponse,
    DescribeRestoreJobs2Request,
    DescribeRestoreJobs2ResponseBody,
    DescribeRestoreJobs2Response,
    DescribeTaskRequest,
    DescribeTaskResponseBody,
    DescribeTaskResponse,
    DescribeUdmSnapshotsRequest,
    DescribeUdmSnapshotsShrinkRequest,
    DescribeUdmSnapshotsResponseBody,
    DescribeUdmSnapshotsResponse,
    DescribeVaultReplicationRegionsRequest,
    DescribeVaultReplicationRegionsResponseBody,
    DescribeVaultReplicationRegionsResponse,
    DescribeVaultsRequest,
    DescribeVaultsResponseBody,
    DescribeVaultsResponse,
    DetachNasFileSystemRequest,
    DetachNasFileSystemResponseBody,
    DetachNasFileSystemResponse,
    DisableBackupPlanRequest,
    DisableBackupPlanResponseBody,
    DisableBackupPlanResponse,
    DisableHanaBackupPlanRequest,
    DisableHanaBackupPlanResponseBody,
    DisableHanaBackupPlanResponse,
    EnableBackupPlanRequest,
    EnableBackupPlanResponseBody,
    EnableBackupPlanResponse,
    EnableHanaBackupPlanRequest,
    EnableHanaBackupPlanResponseBody,
    EnableHanaBackupPlanResponse,
    ExecuteBackupPlanRequest,
    ExecuteBackupPlanResponseBody,
    ExecuteBackupPlanResponse,
    ExecutePolicyV2Request,
    ExecutePolicyV2ResponseBody,
    ExecutePolicyV2Response,
    GenerateRamPolicyRequest,
    GenerateRamPolicyResponseBody,
    GenerateRamPolicyResponse,
    GetTempFileDownloadLinkRequest,
    GetTempFileDownloadLinkResponseBody,
    GetTempFileDownloadLinkResponse,
    InstallBackupClientsRequest,
    InstallBackupClientsShrinkRequest,
    InstallBackupClientsResponseBody,
    InstallBackupClientsResponse,
    ListProtectedResourcesRequest,
    ListProtectedResourcesResponseBody,
    ListProtectedResourcesResponse,
    OpenHbrServiceResponseBody,
    OpenHbrServiceResponse,
    SearchHistoricalSnapshotsRequest,
    SearchHistoricalSnapshotsShrinkRequest,
    SearchHistoricalSnapshotsResponseBody,
    SearchHistoricalSnapshotsResponse,
    StartHanaDatabaseAsyncRequest,
    StartHanaDatabaseAsyncResponseBody,
    StartHanaDatabaseAsyncResponse,
    StopHanaDatabaseAsyncRequest,
    StopHanaDatabaseAsyncResponseBody,
    StopHanaDatabaseAsyncResponse,
    UninstallBackupClientsRequest,
    UninstallBackupClientsShrinkRequest,
    UninstallBackupClientsResponseBody,
    UninstallBackupClientsResponse,
    UninstallClientRequest,
    UninstallClientResponseBody,
    UninstallClientResponse,
    UpdateBackupPlanRequest,
    UpdateBackupPlanShrinkRequest,
    UpdateBackupPlanResponseBody,
    UpdateBackupPlanResponse,
    UpdateClientSettingsRequest,
    UpdateClientSettingsResponseBody,
    UpdateClientSettingsResponse,
    UpdateContainerClusterRequest,
    UpdateContainerClusterResponseBody,
    UpdateContainerClusterResponse,
    UpdateHanaBackupPlanRequest,
    UpdateHanaBackupPlanResponseBody,
    UpdateHanaBackupPlanResponse,
    UpdateHanaBackupSettingRequest,
    UpdateHanaBackupSettingResponseBody,
    UpdateHanaBackupSettingResponse,
    UpdateHanaInstanceRequest,
    UpdateHanaInstanceResponseBody,
    UpdateHanaInstanceResponse,
    UpdateHanaRetentionSettingRequest,
    UpdateHanaRetentionSettingResponseBody,
    UpdateHanaRetentionSettingResponse,
    UpdatePolicyBindingRequest,
    UpdatePolicyBindingShrinkRequest,
    UpdatePolicyBindingResponseBody,
    UpdatePolicyBindingResponse,
    UpdatePolicyV2Request,
    UpdatePolicyV2ShrinkRequest,
    UpdatePolicyV2ResponseBody,
    UpdatePolicyV2Response,
    UpdateVaultRequest,
    UpdateVaultResponseBody,
    UpdateVaultResponse,
    UpgradeBackupClientsRequest,
    UpgradeBackupClientsShrinkRequest,
    UpgradeBackupClientsResponseBody,
    UpgradeBackupClientsResponse,
    UpgradeClientRequest,
    UpgradeClientResponseBody,
    UpgradeClientResponse,
    CreateBackupPlanRequestRule,
    CreateBackupPlanShrinkRequestRule,
    CreateClientsResponseBodyInstanceStatusesInstanceStatus,
    CreateClientsResponseBodyInstanceStatuses,
    CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsCommonFileSystemDetail,
    CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsCommonNasDetail,
    CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsFileDetail,
    CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsOssDetail,
    CreatePolicyBindingsRequestPolicyBindingListAdvancedOptionsUdmDetail,
    CreatePolicyBindingsRequestPolicyBindingListAdvancedOptions,
    CreatePolicyBindingsRequestPolicyBindingList,
    CreatePolicyV2RequestRulesDataSourceFilters,
    CreatePolicyV2RequestRulesRetentionRules,
    CreatePolicyV2RequestRulesTagFilters,
    CreatePolicyV2RequestRules,
    DescribeBackupClientsRequestFilters,
    DescribeBackupClientsRequestTag,
    DescribeBackupClientsShrinkRequestFilters,
    DescribeBackupClientsShrinkRequestTag,
    DescribeBackupClientsResponseBodyClientsSettings,
    DescribeBackupClientsResponseBodyClientsTags,
    DescribeBackupClientsResponseBodyClients,
    DescribeBackupJobs2RequestFilters,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJobDetailDiskNativeSnapshotIdList,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJobDetail,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJobOtsDetailTableNames,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJobOtsDetail,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJobPaths,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJobReport,
    DescribeBackupJobs2ResponseBodyBackupJobsBackupJob,
    DescribeBackupJobs2ResponseBodyBackupJobs,
    DescribeBackupPlansRequestFilters,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanHitTagsHitTag,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanHitTags,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanOtsDetailTableNames,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanOtsDetail,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanPaths,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanResourcesResource,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanResources,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanRulesRule,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanRules,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlanTrialInfo,
    DescribeBackupPlansResponseBodyBackupPlansBackupPlan,
    DescribeBackupPlansResponseBodyBackupPlans,
    DescribeClientsResponseBodyClientsClient,
    DescribeClientsResponseBodyClients,
    DescribeContainerClusterResponseBodyClusters,
    DescribeCrossAccountsResponseBodyCrossAccountsCrossAccount,
    DescribeCrossAccountsResponseBodyCrossAccounts,
    DescribeHanaBackupPlansResponseBodyHanaBackupPlansHanaBackupPlan,
    DescribeHanaBackupPlansResponseBodyHanaBackupPlans,
    DescribeHanaBackupSettingResponseBodyHanaBackupSetting,
    DescribeHanaDatabasesResponseBodyHanaDatabasesHanaDatabase,
    DescribeHanaDatabasesResponseBodyHanaDatabases,
    DescribeHanaInstancesRequestTag,
    DescribeHanaInstancesResponseBodyHanasHanaTagsTag,
    DescribeHanaInstancesResponseBodyHanasHanaTags,
    DescribeHanaInstancesResponseBodyHanasHana,
    DescribeHanaInstancesResponseBodyHanas,
    DescribeHanaRestoresResponseBodyHanaRestoreHanaRestores,
    DescribeHanaRestoresResponseBodyHanaRestore,
    DescribeOtsTableSnapshotsRequestOtsInstances,
    DescribeOtsTableSnapshotsResponseBodySnapshots,
    DescribePoliciesV2ResponseBodyPoliciesRulesDataSourceFilters,
    DescribePoliciesV2ResponseBodyPoliciesRulesRetentionRules,
    DescribePoliciesV2ResponseBodyPoliciesRulesTagFilters,
    DescribePoliciesV2ResponseBodyPoliciesRules,
    DescribePoliciesV2ResponseBodyPolicies,
    DescribePolicyBindingsRequestFilters,
    DescribePolicyBindingsShrinkRequestFilters,
    DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsCommonFileSystemDetail,
    DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsCommonNasDetail,
    DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsFileDetail,
    DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsOssDetail,
    DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptionsUdmDetail,
    DescribePolicyBindingsResponseBodyPolicyBindingsAdvancedOptions,
    DescribePolicyBindingsResponseBodyPolicyBindingsHitTags,
    DescribePolicyBindingsResponseBodyPolicyBindings,
    DescribeRecoverableOtsInstancesResponseBodyOtsInstances,
    DescribeRegionsResponseBodyRegionsRegion,
    DescribeRegionsResponseBodyRegions,
    DescribeRestoreJobs2RequestFilters,
    DescribeRestoreJobs2ResponseBodyRestoreJobsRestoreJobOtsDetail,
    DescribeRestoreJobs2ResponseBodyRestoreJobsRestoreJobReport,
    DescribeRestoreJobs2ResponseBodyRestoreJobsRestoreJob,
    DescribeRestoreJobs2ResponseBodyRestoreJobs,
    DescribeUdmSnapshotsResponseBodySnapshotsDetail,
    DescribeUdmSnapshotsResponseBodySnapshots,
    DescribeVaultReplicationRegionsResponseBodyRegions,
    DescribeVaultsRequestTag,
    DescribeVaultsResponseBodyVaultsVaultBackupPlanStatistics,
    DescribeVaultsResponseBodyVaultsVaultReplicationProgress,
    DescribeVaultsResponseBodyVaultsVaultRsTargetAccountIds,
    DescribeVaultsResponseBodyVaultsVaultSourceTypes,
    DescribeVaultsResponseBodyVaultsVaultTagsTag,
    DescribeVaultsResponseBodyVaultsVaultTags,
    DescribeVaultsResponseBodyVaultsVaultTrialInfo,
    DescribeVaultsResponseBodyVaultsVault,
    DescribeVaultsResponseBodyVaults,
    InstallBackupClientsResponseBodyInstanceStatuses,
    ListProtectedResourcesResponseBodyProtectedResources,
    SearchHistoricalSnapshotsResponseBodySnapshotsSnapshotPaths,
    SearchHistoricalSnapshotsResponseBodySnapshotsSnapshot,
    SearchHistoricalSnapshotsResponseBodySnapshots,
    UninstallBackupClientsResponseBodyInstanceStatuses,
    UpdateBackupPlanRequestRule,
    UpdateBackupPlanShrinkRequestRule,
    UpdatePolicyBindingRequestAdvancedOptionsCommonFileSystemDetail,
    UpdatePolicyBindingRequestAdvancedOptionsOssDetail,
    UpdatePolicyBindingRequestAdvancedOptionsUdmDetail,
    UpdatePolicyBindingRequestAdvancedOptions,
    UpdatePolicyV2RequestRulesDataSourceFilters,
    UpdatePolicyV2RequestRulesRetentionRules,
    UpdatePolicyV2RequestRulesTagFilters,
    UpdatePolicyV2RequestRules,
    UpgradeBackupClientsResponseBodyInstanceStatuses
]
