# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class RegisterKnowledgeBaseFileResponseBody(DaraModel):
    def __init__(
        self,
        file_id: str = None,
        file_name: str = None,
        file_path: str = None,
        idempotent: bool = None,
        request_id: str = None,
        status: str = None,
    ):
        # The file ID, which is generated by the server based on the ETL rules for native OSS files.
        self.file_id = file_id
        # The file name.
        self.file_name = file_name
        # The OSS object key of the registered file.
        self.file_path = file_path
        # Indicates whether an existing idempotent record is matched. Valid values:
        # - true: An existing idempotent record is matched.
        # - false: No existing idempotent record is matched.
        self.idempotent = idempotent
        # The request ID.
        self.request_id = request_id
        # The file processing status.
        self.status = status

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.file_id is not None:
            result['FileId'] = self.file_id

        if self.file_name is not None:
            result['FileName'] = self.file_name

        if self.file_path is not None:
            result['FilePath'] = self.file_path

        if self.idempotent is not None:
            result['Idempotent'] = self.idempotent

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.status is not None:
            result['Status'] = self.status

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('FileId') is not None:
            self.file_id = m.get('FileId')

        if m.get('FileName') is not None:
            self.file_name = m.get('FileName')

        if m.get('FilePath') is not None:
            self.file_path = m.get('FilePath')

        if m.get('Idempotent') is not None:
            self.idempotent = m.get('Idempotent')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        return self

