# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from ._accept_approve_command_request import AcceptApproveCommandRequest
from ._accept_approve_command_response_body import AcceptApproveCommandResponseBody
from ._accept_approve_command_response import AcceptApproveCommandResponse
from ._accept_operation_ticket_request import AcceptOperationTicketRequest
from ._accept_operation_ticket_response_body import AcceptOperationTicketResponseBody
from ._accept_operation_ticket_response import AcceptOperationTicketResponse
from ._add_databases_to_group_request import AddDatabasesToGroupRequest
from ._add_databases_to_group_response_body import AddDatabasesToGroupResponseBody
from ._add_databases_to_group_response import AddDatabasesToGroupResponse
from ._add_hosts_to_group_request import AddHostsToGroupRequest
from ._add_hosts_to_group_response_body import AddHostsToGroupResponseBody
from ._add_hosts_to_group_response import AddHostsToGroupResponse
from ._add_instance_rd_member_request import AddInstanceRdMemberRequest
from ._add_instance_rd_member_response_body import AddInstanceRdMemberResponseBody
from ._add_instance_rd_member_response import AddInstanceRdMemberResponse
from ._add_users_to_group_request import AddUsersToGroupRequest
from ._add_users_to_group_response_body import AddUsersToGroupResponseBody
from ._add_users_to_group_response import AddUsersToGroupResponse
from ._attach_database_accounts_to_user_request import AttachDatabaseAccountsToUserRequest
from ._attach_database_accounts_to_user_response_body import AttachDatabaseAccountsToUserResponseBody
from ._attach_database_accounts_to_user_response import AttachDatabaseAccountsToUserResponse
from ._attach_database_accounts_to_user_group_request import AttachDatabaseAccountsToUserGroupRequest
from ._attach_database_accounts_to_user_group_response_body import AttachDatabaseAccountsToUserGroupResponseBody
from ._attach_database_accounts_to_user_group_response import AttachDatabaseAccountsToUserGroupResponse
from ._attach_host_accounts_to_host_share_key_request import AttachHostAccountsToHostShareKeyRequest
from ._attach_host_accounts_to_host_share_key_response_body import AttachHostAccountsToHostShareKeyResponseBody
from ._attach_host_accounts_to_host_share_key_response import AttachHostAccountsToHostShareKeyResponse
from ._attach_host_accounts_to_user_request import AttachHostAccountsToUserRequest
from ._attach_host_accounts_to_user_response_body import AttachHostAccountsToUserResponseBody
from ._attach_host_accounts_to_user_response import AttachHostAccountsToUserResponse
from ._attach_host_accounts_to_user_group_request import AttachHostAccountsToUserGroupRequest
from ._attach_host_accounts_to_user_group_response_body import AttachHostAccountsToUserGroupResponseBody
from ._attach_host_accounts_to_user_group_response import AttachHostAccountsToUserGroupResponse
from ._attach_host_group_accounts_to_user_request import AttachHostGroupAccountsToUserRequest
from ._attach_host_group_accounts_to_user_response_body import AttachHostGroupAccountsToUserResponseBody
from ._attach_host_group_accounts_to_user_response import AttachHostGroupAccountsToUserResponse
from ._attach_host_group_accounts_to_user_group_request import AttachHostGroupAccountsToUserGroupRequest
from ._attach_host_group_accounts_to_user_group_response_body import AttachHostGroupAccountsToUserGroupResponseBody
from ._attach_host_group_accounts_to_user_group_response import AttachHostGroupAccountsToUserGroupResponse
from ._config_instance_security_groups_request import ConfigInstanceSecurityGroupsRequest
from ._config_instance_security_groups_response_body import ConfigInstanceSecurityGroupsResponseBody
from ._config_instance_security_groups_response import ConfigInstanceSecurityGroupsResponse
from ._config_instance_white_list_request import ConfigInstanceWhiteListRequest
from ._config_instance_white_list_response_body import ConfigInstanceWhiteListResponseBody
from ._config_instance_white_list_response import ConfigInstanceWhiteListResponse
from ._create_database_request import CreateDatabaseRequest
from ._create_database_response_body import CreateDatabaseResponseBody
from ._create_database_response import CreateDatabaseResponse
from ._create_database_account_request import CreateDatabaseAccountRequest
from ._create_database_account_response_body import CreateDatabaseAccountResponseBody
from ._create_database_account_response import CreateDatabaseAccountResponse
from ._create_export_config_job_request import CreateExportConfigJobRequest
from ._create_export_config_job_response_body import CreateExportConfigJobResponseBody
from ._create_export_config_job_response import CreateExportConfigJobResponse
from ._create_host_request import CreateHostRequest
from ._create_host_response_body import CreateHostResponseBody
from ._create_host_response import CreateHostResponse
from ._create_host_account_request import CreateHostAccountRequest
from ._create_host_account_response_body import CreateHostAccountResponseBody
from ._create_host_account_response import CreateHostAccountResponse
from ._create_host_group_request import CreateHostGroupRequest
from ._create_host_group_response_body import CreateHostGroupResponseBody
from ._create_host_group_response import CreateHostGroupResponse
from ._create_host_share_key_request import CreateHostShareKeyRequest
from ._create_host_share_key_response_body import CreateHostShareKeyResponseBody
from ._create_host_share_key_response import CreateHostShareKeyResponse
from ._create_network_domain_request import CreateNetworkDomainRequest
from ._create_network_domain_response_body import CreateNetworkDomainResponseBody
from ._create_network_domain_response import CreateNetworkDomainResponse
from ._create_operation_ticket_request import CreateOperationTicketRequest
from ._create_operation_ticket_response_body import CreateOperationTicketResponseBody
from ._create_operation_ticket_response import CreateOperationTicketResponse
from ._create_policy_request import CreatePolicyRequest
from ._create_policy_response_body import CreatePolicyResponseBody
from ._create_policy_response import CreatePolicyResponse
from ._create_rule_request import CreateRuleRequest
from ._create_rule_response_body import CreateRuleResponseBody
from ._create_rule_response import CreateRuleResponse
from ._create_user_request import CreateUserRequest
from ._create_user_response_body import CreateUserResponseBody
from ._create_user_response import CreateUserResponse
from ._create_user_group_request import CreateUserGroupRequest
from ._create_user_group_response_body import CreateUserGroupResponseBody
from ._create_user_group_response import CreateUserGroupResponse
from ._create_user_public_key_request import CreateUserPublicKeyRequest
from ._create_user_public_key_response_body import CreateUserPublicKeyResponseBody
from ._create_user_public_key_response import CreateUserPublicKeyResponse
from ._delete_database_request import DeleteDatabaseRequest
from ._delete_database_response_body import DeleteDatabaseResponseBody
from ._delete_database_response import DeleteDatabaseResponse
from ._delete_database_account_request import DeleteDatabaseAccountRequest
from ._delete_database_account_response_body import DeleteDatabaseAccountResponseBody
from ._delete_database_account_response import DeleteDatabaseAccountResponse
from ._delete_host_request import DeleteHostRequest
from ._delete_host_response_body import DeleteHostResponseBody
from ._delete_host_response import DeleteHostResponse
from ._delete_host_account_request import DeleteHostAccountRequest
from ._delete_host_account_response_body import DeleteHostAccountResponseBody
from ._delete_host_account_response import DeleteHostAccountResponse
from ._delete_host_group_request import DeleteHostGroupRequest
from ._delete_host_group_response_body import DeleteHostGroupResponseBody
from ._delete_host_group_response import DeleteHostGroupResponse
from ._delete_host_share_key_request import DeleteHostShareKeyRequest
from ._delete_host_share_key_response_body import DeleteHostShareKeyResponseBody
from ._delete_host_share_key_response import DeleteHostShareKeyResponse
from ._delete_network_domain_request import DeleteNetworkDomainRequest
from ._delete_network_domain_response_body import DeleteNetworkDomainResponseBody
from ._delete_network_domain_response import DeleteNetworkDomainResponse
from ._delete_policy_request import DeletePolicyRequest
from ._delete_policy_response_body import DeletePolicyResponseBody
from ._delete_policy_response import DeletePolicyResponse
from ._delete_rule_request import DeleteRuleRequest
from ._delete_rule_response_body import DeleteRuleResponseBody
from ._delete_rule_response import DeleteRuleResponse
from ._delete_user_request import DeleteUserRequest
from ._delete_user_response_body import DeleteUserResponseBody
from ._delete_user_response import DeleteUserResponse
from ._delete_user_group_request import DeleteUserGroupRequest
from ._delete_user_group_response_body import DeleteUserGroupResponseBody
from ._delete_user_group_response import DeleteUserGroupResponse
from ._delete_user_public_key_request import DeleteUserPublicKeyRequest
from ._delete_user_public_key_response_body import DeleteUserPublicKeyResponseBody
from ._delete_user_public_key_response import DeleteUserPublicKeyResponse
from ._describe_instance_attribute_request import DescribeInstanceAttributeRequest
from ._describe_instance_attribute_response_body import DescribeInstanceAttributeResponseBody
from ._describe_instance_attribute_response import DescribeInstanceAttributeResponse
from ._describe_instances_request import DescribeInstancesRequest
from ._describe_instances_response_body import DescribeInstancesResponseBody
from ._describe_instances_response import DescribeInstancesResponse
from ._describe_regions_request import DescribeRegionsRequest
from ._describe_regions_response_body import DescribeRegionsResponseBody
from ._describe_regions_response import DescribeRegionsResponse
from ._detach_database_accounts_from_user_request import DetachDatabaseAccountsFromUserRequest
from ._detach_database_accounts_from_user_response_body import DetachDatabaseAccountsFromUserResponseBody
from ._detach_database_accounts_from_user_response import DetachDatabaseAccountsFromUserResponse
from ._detach_database_accounts_from_user_group_request import DetachDatabaseAccountsFromUserGroupRequest
from ._detach_database_accounts_from_user_group_response_body import DetachDatabaseAccountsFromUserGroupResponseBody
from ._detach_database_accounts_from_user_group_response import DetachDatabaseAccountsFromUserGroupResponse
from ._detach_host_accounts_from_host_share_key_request import DetachHostAccountsFromHostShareKeyRequest
from ._detach_host_accounts_from_host_share_key_response_body import DetachHostAccountsFromHostShareKeyResponseBody
from ._detach_host_accounts_from_host_share_key_response import DetachHostAccountsFromHostShareKeyResponse
from ._detach_host_accounts_from_user_request import DetachHostAccountsFromUserRequest
from ._detach_host_accounts_from_user_response_body import DetachHostAccountsFromUserResponseBody
from ._detach_host_accounts_from_user_response import DetachHostAccountsFromUserResponse
from ._detach_host_accounts_from_user_group_request import DetachHostAccountsFromUserGroupRequest
from ._detach_host_accounts_from_user_group_response_body import DetachHostAccountsFromUserGroupResponseBody
from ._detach_host_accounts_from_user_group_response import DetachHostAccountsFromUserGroupResponse
from ._detach_host_group_accounts_from_user_request import DetachHostGroupAccountsFromUserRequest
from ._detach_host_group_accounts_from_user_response_body import DetachHostGroupAccountsFromUserResponseBody
from ._detach_host_group_accounts_from_user_response import DetachHostGroupAccountsFromUserResponse
from ._detach_host_group_accounts_from_user_group_request import DetachHostGroupAccountsFromUserGroupRequest
from ._detach_host_group_accounts_from_user_group_response_body import DetachHostGroupAccountsFromUserGroupResponseBody
from ._detach_host_group_accounts_from_user_group_response import DetachHostGroupAccountsFromUserGroupResponse
from ._disable_instance_public_access_request import DisableInstancePublicAccessRequest
from ._disable_instance_public_access_response_body import DisableInstancePublicAccessResponseBody
from ._disable_instance_public_access_response import DisableInstancePublicAccessResponse
from ._disable_rule_request import DisableRuleRequest
from ._disable_rule_response_body import DisableRuleResponseBody
from ._disable_rule_response import DisableRuleResponse
from ._enable_instance_public_access_request import EnableInstancePublicAccessRequest
from ._enable_instance_public_access_response_body import EnableInstancePublicAccessResponseBody
from ._enable_instance_public_access_response import EnableInstancePublicAccessResponse
from ._enable_rule_request import EnableRuleRequest
from ._enable_rule_response_body import EnableRuleResponseBody
from ._enable_rule_response import EnableRuleResponse
from ._generate_asset_operation_token_request import GenerateAssetOperationTokenRequest
from ._generate_asset_operation_token_response_body import GenerateAssetOperationTokenResponseBody
from ._generate_asset_operation_token_response import GenerateAssetOperationTokenResponse
from ._get_database_request import GetDatabaseRequest
from ._get_database_response_body import GetDatabaseResponseBody
from ._get_database_response import GetDatabaseResponse
from ._get_database_account_request import GetDatabaseAccountRequest
from ._get_database_account_response_body import GetDatabaseAccountResponseBody
from ._get_database_account_response import GetDatabaseAccountResponse
from ._get_export_config_job_request import GetExportConfigJobRequest
from ._get_export_config_job_response_body import GetExportConfigJobResponseBody
from ._get_export_config_job_response import GetExportConfigJobResponse
from ._get_host_request import GetHostRequest
from ._get_host_response_body import GetHostResponseBody
from ._get_host_response import GetHostResponse
from ._get_host_account_request import GetHostAccountRequest
from ._get_host_account_response_body import GetHostAccountResponseBody
from ._get_host_account_response import GetHostAccountResponse
from ._get_host_group_request import GetHostGroupRequest
from ._get_host_group_response_body import GetHostGroupResponseBody
from ._get_host_group_response import GetHostGroupResponse
from ._get_host_share_key_request import GetHostShareKeyRequest
from ._get_host_share_key_response_body import GetHostShareKeyResponseBody
from ._get_host_share_key_response import GetHostShareKeyResponse
from ._get_instance_adauth_server_request import GetInstanceADAuthServerRequest
from ._get_instance_adauth_server_response_body import GetInstanceADAuthServerResponseBody
from ._get_instance_adauth_server_response import GetInstanceADAuthServerResponse
from ._get_instance_ldapauth_server_request import GetInstanceLDAPAuthServerRequest
from ._get_instance_ldapauth_server_response_body import GetInstanceLDAPAuthServerResponseBody
from ._get_instance_ldapauth_server_response import GetInstanceLDAPAuthServerResponse
from ._get_instance_store_info_request import GetInstanceStoreInfoRequest
from ._get_instance_store_info_response_body import GetInstanceStoreInfoResponseBody
from ._get_instance_store_info_response import GetInstanceStoreInfoResponse
from ._get_instance_two_factor_request import GetInstanceTwoFactorRequest
from ._get_instance_two_factor_response_body import GetInstanceTwoFactorResponseBody
from ._get_instance_two_factor_response import GetInstanceTwoFactorResponse
from ._get_network_domain_request import GetNetworkDomainRequest
from ._get_network_domain_response_body import GetNetworkDomainResponseBody
from ._get_network_domain_response import GetNetworkDomainResponse
from ._get_policy_request import GetPolicyRequest
from ._get_policy_response_body import GetPolicyResponseBody
from ._get_policy_response import GetPolicyResponse
from ._get_policy_asset_scope_request import GetPolicyAssetScopeRequest
from ._get_policy_asset_scope_response_body import GetPolicyAssetScopeResponseBody
from ._get_policy_asset_scope_response import GetPolicyAssetScopeResponse
from ._get_policy_user_scope_request import GetPolicyUserScopeRequest
from ._get_policy_user_scope_response_body import GetPolicyUserScopeResponseBody
from ._get_policy_user_scope_response import GetPolicyUserScopeResponse
from ._get_rule_request import GetRuleRequest
from ._get_rule_response_body import GetRuleResponseBody
from ._get_rule_response import GetRuleResponse
from ._get_user_request import GetUserRequest
from ._get_user_response_body import GetUserResponseBody
from ._get_user_response import GetUserResponse
from ._get_user_group_request import GetUserGroupRequest
from ._get_user_group_response_body import GetUserGroupResponseBody
from ._get_user_group_response import GetUserGroupResponse
from ._list_approve_commands_request import ListApproveCommandsRequest
from ._list_approve_commands_response_body import ListApproveCommandsResponseBody
from ._list_approve_commands_response import ListApproveCommandsResponse
from ._list_database_accounts_request import ListDatabaseAccountsRequest
from ._list_database_accounts_response_body import ListDatabaseAccountsResponseBody
from ._list_database_accounts_response import ListDatabaseAccountsResponse
from ._list_database_accounts_for_user_request import ListDatabaseAccountsForUserRequest
from ._list_database_accounts_for_user_response_body import ListDatabaseAccountsForUserResponseBody
from ._list_database_accounts_for_user_response import ListDatabaseAccountsForUserResponse
from ._list_database_accounts_for_user_group_request import ListDatabaseAccountsForUserGroupRequest
from ._list_database_accounts_for_user_group_response_body import ListDatabaseAccountsForUserGroupResponseBody
from ._list_database_accounts_for_user_group_response import ListDatabaseAccountsForUserGroupResponse
from ._list_databases_request import ListDatabasesRequest
from ._list_databases_response_body import ListDatabasesResponseBody
from ._list_databases_response import ListDatabasesResponse
from ._list_databases_for_user_request import ListDatabasesForUserRequest
from ._list_databases_for_user_response_body import ListDatabasesForUserResponseBody
from ._list_databases_for_user_response import ListDatabasesForUserResponse
from ._list_databases_for_user_group_request import ListDatabasesForUserGroupRequest
from ._list_databases_for_user_group_response_body import ListDatabasesForUserGroupResponseBody
from ._list_databases_for_user_group_response import ListDatabasesForUserGroupResponse
from ._list_host_accounts_request import ListHostAccountsRequest
from ._list_host_accounts_response_body import ListHostAccountsResponseBody
from ._list_host_accounts_response import ListHostAccountsResponse
from ._list_host_accounts_for_host_share_key_request import ListHostAccountsForHostShareKeyRequest
from ._list_host_accounts_for_host_share_key_response_body import ListHostAccountsForHostShareKeyResponseBody
from ._list_host_accounts_for_host_share_key_response import ListHostAccountsForHostShareKeyResponse
from ._list_host_accounts_for_user_request import ListHostAccountsForUserRequest
from ._list_host_accounts_for_user_response_body import ListHostAccountsForUserResponseBody
from ._list_host_accounts_for_user_response import ListHostAccountsForUserResponse
from ._list_host_accounts_for_user_group_request import ListHostAccountsForUserGroupRequest
from ._list_host_accounts_for_user_group_response_body import ListHostAccountsForUserGroupResponseBody
from ._list_host_accounts_for_user_group_response import ListHostAccountsForUserGroupResponse
from ._list_host_group_account_names_for_user_request import ListHostGroupAccountNamesForUserRequest
from ._list_host_group_account_names_for_user_response_body import ListHostGroupAccountNamesForUserResponseBody
from ._list_host_group_account_names_for_user_response import ListHostGroupAccountNamesForUserResponse
from ._list_host_group_account_names_for_user_group_request import ListHostGroupAccountNamesForUserGroupRequest
from ._list_host_group_account_names_for_user_group_response_body import ListHostGroupAccountNamesForUserGroupResponseBody
from ._list_host_group_account_names_for_user_group_response import ListHostGroupAccountNamesForUserGroupResponse
from ._list_host_groups_request import ListHostGroupsRequest
from ._list_host_groups_response_body import ListHostGroupsResponseBody
from ._list_host_groups_response import ListHostGroupsResponse
from ._list_host_groups_for_user_request import ListHostGroupsForUserRequest
from ._list_host_groups_for_user_response_body import ListHostGroupsForUserResponseBody
from ._list_host_groups_for_user_response import ListHostGroupsForUserResponse
from ._list_host_groups_for_user_group_request import ListHostGroupsForUserGroupRequest
from ._list_host_groups_for_user_group_response_body import ListHostGroupsForUserGroupResponseBody
from ._list_host_groups_for_user_group_response import ListHostGroupsForUserGroupResponse
from ._list_host_share_keys_request import ListHostShareKeysRequest
from ._list_host_share_keys_response_body import ListHostShareKeysResponseBody
from ._list_host_share_keys_response import ListHostShareKeysResponse
from ._list_hosts_request import ListHostsRequest
from ._list_hosts_response_body import ListHostsResponseBody
from ._list_hosts_response import ListHostsResponse
from ._list_hosts_for_user_request import ListHostsForUserRequest
from ._list_hosts_for_user_response_body import ListHostsForUserResponseBody
from ._list_hosts_for_user_response import ListHostsForUserResponse
from ._list_hosts_for_user_group_request import ListHostsForUserGroupRequest
from ._list_hosts_for_user_group_response_body import ListHostsForUserGroupResponseBody
from ._list_hosts_for_user_group_response import ListHostsForUserGroupResponse
from ._list_instance_rd_members_request import ListInstanceRdMembersRequest
from ._list_instance_rd_members_response_body import ListInstanceRdMembersResponseBody
from ._list_instance_rd_members_response import ListInstanceRdMembersResponse
from ._list_network_domains_request import ListNetworkDomainsRequest
from ._list_network_domains_response_body import ListNetworkDomainsResponseBody
from ._list_network_domains_response import ListNetworkDomainsResponse
from ._list_operation_database_accounts_request import ListOperationDatabaseAccountsRequest
from ._list_operation_database_accounts_response_body import ListOperationDatabaseAccountsResponseBody
from ._list_operation_database_accounts_response import ListOperationDatabaseAccountsResponse
from ._list_operation_databases_request import ListOperationDatabasesRequest
from ._list_operation_databases_response_body import ListOperationDatabasesResponseBody
from ._list_operation_databases_response import ListOperationDatabasesResponse
from ._list_operation_host_accounts_request import ListOperationHostAccountsRequest
from ._list_operation_host_accounts_response_body import ListOperationHostAccountsResponseBody
from ._list_operation_host_accounts_response import ListOperationHostAccountsResponse
from ._list_operation_hosts_request import ListOperationHostsRequest
from ._list_operation_hosts_response_body import ListOperationHostsResponseBody
from ._list_operation_hosts_response import ListOperationHostsResponse
from ._list_operation_tickets_request import ListOperationTicketsRequest
from ._list_operation_tickets_response_body import ListOperationTicketsResponseBody
from ._list_operation_tickets_response import ListOperationTicketsResponse
from ._list_policies_request import ListPoliciesRequest
from ._list_policies_response_body import ListPoliciesResponseBody
from ._list_policies_response import ListPoliciesResponse
from ._list_rules_request import ListRulesRequest
from ._list_rules_response_body import ListRulesResponseBody
from ._list_rules_response import ListRulesResponse
from ._list_tag_keys_request import ListTagKeysRequest
from ._list_tag_keys_response_body import ListTagKeysResponseBody
from ._list_tag_keys_response import ListTagKeysResponse
from ._list_tag_resources_request import ListTagResourcesRequest
from ._list_tag_resources_response_body import ListTagResourcesResponseBody
from ._list_tag_resources_response import ListTagResourcesResponse
from ._list_user_groups_request import ListUserGroupsRequest
from ._list_user_groups_response_body import ListUserGroupsResponseBody
from ._list_user_groups_response import ListUserGroupsResponse
from ._list_user_public_keys_request import ListUserPublicKeysRequest
from ._list_user_public_keys_response_body import ListUserPublicKeysResponseBody
from ._list_user_public_keys_response import ListUserPublicKeysResponse
from ._list_users_request import ListUsersRequest
from ._list_users_response_body import ListUsersResponseBody
from ._list_users_response import ListUsersResponse
from ._lock_users_request import LockUsersRequest
from ._lock_users_response_body import LockUsersResponseBody
from ._lock_users_response import LockUsersResponse
from ._modify_database_request import ModifyDatabaseRequest
from ._modify_database_response_body import ModifyDatabaseResponseBody
from ._modify_database_response import ModifyDatabaseResponse
from ._modify_database_account_request import ModifyDatabaseAccountRequest
from ._modify_database_account_response_body import ModifyDatabaseAccountResponseBody
from ._modify_database_account_response import ModifyDatabaseAccountResponse
from ._modify_host_request import ModifyHostRequest
from ._modify_host_response_body import ModifyHostResponseBody
from ._modify_host_response import ModifyHostResponse
from ._modify_host_account_request import ModifyHostAccountRequest
from ._modify_host_account_response_body import ModifyHostAccountResponseBody
from ._modify_host_account_response import ModifyHostAccountResponse
from ._modify_host_group_request import ModifyHostGroupRequest
from ._modify_host_group_response_body import ModifyHostGroupResponseBody
from ._modify_host_group_response import ModifyHostGroupResponse
from ._modify_host_share_key_request import ModifyHostShareKeyRequest
from ._modify_host_share_key_response_body import ModifyHostShareKeyResponseBody
from ._modify_host_share_key_response import ModifyHostShareKeyResponse
from ._modify_hosts_active_address_type_request import ModifyHostsActiveAddressTypeRequest
from ._modify_hosts_active_address_type_response_body import ModifyHostsActiveAddressTypeResponseBody
from ._modify_hosts_active_address_type_response import ModifyHostsActiveAddressTypeResponse
from ._modify_hosts_port_request import ModifyHostsPortRequest
from ._modify_hosts_port_response_body import ModifyHostsPortResponseBody
from ._modify_hosts_port_response import ModifyHostsPortResponse
from ._modify_instance_adauth_server_request import ModifyInstanceADAuthServerRequest
from ._modify_instance_adauth_server_response_body import ModifyInstanceADAuthServerResponseBody
from ._modify_instance_adauth_server_response import ModifyInstanceADAuthServerResponse
from ._modify_instance_attribute_request import ModifyInstanceAttributeRequest
from ._modify_instance_attribute_response_body import ModifyInstanceAttributeResponseBody
from ._modify_instance_attribute_response import ModifyInstanceAttributeResponse
from ._modify_instance_ldapauth_server_request import ModifyInstanceLDAPAuthServerRequest
from ._modify_instance_ldapauth_server_response_body import ModifyInstanceLDAPAuthServerResponseBody
from ._modify_instance_ldapauth_server_response import ModifyInstanceLDAPAuthServerResponse
from ._modify_instance_two_factor_request import ModifyInstanceTwoFactorRequest
from ._modify_instance_two_factor_response_body import ModifyInstanceTwoFactorResponseBody
from ._modify_instance_two_factor_response import ModifyInstanceTwoFactorResponse
from ._modify_network_domain_request import ModifyNetworkDomainRequest
from ._modify_network_domain_response_body import ModifyNetworkDomainResponseBody
from ._modify_network_domain_response import ModifyNetworkDomainResponse
from ._modify_policy_request import ModifyPolicyRequest
from ._modify_policy_response_body import ModifyPolicyResponseBody
from ._modify_policy_response import ModifyPolicyResponse
from ._modify_rule_request import ModifyRuleRequest
from ._modify_rule_response_body import ModifyRuleResponseBody
from ._modify_rule_response import ModifyRuleResponse
from ._modify_user_request import ModifyUserRequest
from ._modify_user_response_body import ModifyUserResponseBody
from ._modify_user_response import ModifyUserResponse
from ._modify_user_group_request import ModifyUserGroupRequest
from ._modify_user_group_response_body import ModifyUserGroupResponseBody
from ._modify_user_group_response import ModifyUserGroupResponse
from ._modify_user_public_key_request import ModifyUserPublicKeyRequest
from ._modify_user_public_key_response_body import ModifyUserPublicKeyResponseBody
from ._modify_user_public_key_response import ModifyUserPublicKeyResponse
from ._move_databases_to_network_domain_request import MoveDatabasesToNetworkDomainRequest
from ._move_databases_to_network_domain_response_body import MoveDatabasesToNetworkDomainResponseBody
from ._move_databases_to_network_domain_response import MoveDatabasesToNetworkDomainResponse
from ._move_hosts_to_network_domain_request import MoveHostsToNetworkDomainRequest
from ._move_hosts_to_network_domain_response_body import MoveHostsToNetworkDomainResponseBody
from ._move_hosts_to_network_domain_response import MoveHostsToNetworkDomainResponse
from ._move_resource_group_request import MoveResourceGroupRequest
from ._move_resource_group_response_body import MoveResourceGroupResponseBody
from ._move_resource_group_response import MoveResourceGroupResponse
from ._reject_approve_command_request import RejectApproveCommandRequest
from ._reject_approve_command_response_body import RejectApproveCommandResponseBody
from ._reject_approve_command_response import RejectApproveCommandResponse
from ._reject_operation_ticket_request import RejectOperationTicketRequest
from ._reject_operation_ticket_response_body import RejectOperationTicketResponseBody
from ._reject_operation_ticket_response import RejectOperationTicketResponse
from ._remove_databases_from_group_request import RemoveDatabasesFromGroupRequest
from ._remove_databases_from_group_response_body import RemoveDatabasesFromGroupResponseBody
from ._remove_databases_from_group_response import RemoveDatabasesFromGroupResponse
from ._remove_hosts_from_group_request import RemoveHostsFromGroupRequest
from ._remove_hosts_from_group_response_body import RemoveHostsFromGroupResponseBody
from ._remove_hosts_from_group_response import RemoveHostsFromGroupResponse
from ._remove_instance_rd_member_request import RemoveInstanceRdMemberRequest
from ._remove_instance_rd_member_response_body import RemoveInstanceRdMemberResponseBody
from ._remove_instance_rd_member_response import RemoveInstanceRdMemberResponse
from ._remove_users_from_group_request import RemoveUsersFromGroupRequest
from ._remove_users_from_group_response_body import RemoveUsersFromGroupResponseBody
from ._remove_users_from_group_response import RemoveUsersFromGroupResponse
from ._renew_asset_operation_token_request import RenewAssetOperationTokenRequest
from ._renew_asset_operation_token_response_body import RenewAssetOperationTokenResponseBody
from ._renew_asset_operation_token_response import RenewAssetOperationTokenResponse
from ._reset_host_account_credential_request import ResetHostAccountCredentialRequest
from ._reset_host_account_credential_response_body import ResetHostAccountCredentialResponseBody
from ._reset_host_account_credential_response import ResetHostAccountCredentialResponse
from ._set_policy_access_time_range_config_request import SetPolicyAccessTimeRangeConfigRequest
from ._set_policy_access_time_range_config_shrink_request import SetPolicyAccessTimeRangeConfigShrinkRequest
from ._set_policy_access_time_range_config_response_body import SetPolicyAccessTimeRangeConfigResponseBody
from ._set_policy_access_time_range_config_response import SetPolicyAccessTimeRangeConfigResponse
from ._set_policy_approval_config_request import SetPolicyApprovalConfigRequest
from ._set_policy_approval_config_shrink_request import SetPolicyApprovalConfigShrinkRequest
from ._set_policy_approval_config_response_body import SetPolicyApprovalConfigResponseBody
from ._set_policy_approval_config_response import SetPolicyApprovalConfigResponse
from ._set_policy_asset_scope_request import SetPolicyAssetScopeRequest
from ._set_policy_asset_scope_response_body import SetPolicyAssetScopeResponseBody
from ._set_policy_asset_scope_response import SetPolicyAssetScopeResponse
from ._set_policy_command_config_request import SetPolicyCommandConfigRequest
from ._set_policy_command_config_shrink_request import SetPolicyCommandConfigShrinkRequest
from ._set_policy_command_config_response_body import SetPolicyCommandConfigResponseBody
from ._set_policy_command_config_response import SetPolicyCommandConfigResponse
from ._set_policy_ipacl_config_request import SetPolicyIPAclConfigRequest
from ._set_policy_ipacl_config_shrink_request import SetPolicyIPAclConfigShrinkRequest
from ._set_policy_ipacl_config_response_body import SetPolicyIPAclConfigResponseBody
from ._set_policy_ipacl_config_response import SetPolicyIPAclConfigResponse
from ._set_policy_protocol_config_request import SetPolicyProtocolConfigRequest
from ._set_policy_protocol_config_shrink_request import SetPolicyProtocolConfigShrinkRequest
from ._set_policy_protocol_config_response_body import SetPolicyProtocolConfigResponseBody
from ._set_policy_protocol_config_response import SetPolicyProtocolConfigResponse
from ._set_policy_user_scope_request import SetPolicyUserScopeRequest
from ._set_policy_user_scope_response_body import SetPolicyUserScopeResponseBody
from ._set_policy_user_scope_response import SetPolicyUserScopeResponse
from ._start_instance_request import StartInstanceRequest
from ._start_instance_response_body import StartInstanceResponseBody
from ._start_instance_response import StartInstanceResponse
from ._tag_resources_request import TagResourcesRequest
from ._tag_resources_response_body import TagResourcesResponseBody
from ._tag_resources_response import TagResourcesResponse
from ._unlock_users_request import UnlockUsersRequest
from ._unlock_users_response_body import UnlockUsersResponseBody
from ._unlock_users_response import UnlockUsersResponse
from ._untag_resources_request import UntagResourcesRequest
from ._untag_resources_response_body import UntagResourcesResponseBody
from ._untag_resources_response import UntagResourcesResponse
from ._verify_instance_adauth_server_request import VerifyInstanceADAuthServerRequest
from ._verify_instance_adauth_server_response_body import VerifyInstanceADAuthServerResponseBody
from ._verify_instance_adauth_server_response import VerifyInstanceADAuthServerResponse
from ._verify_instance_ldapauth_server_request import VerifyInstanceLDAPAuthServerRequest
from ._verify_instance_ldapauth_server_response_body import VerifyInstanceLDAPAuthServerResponseBody
from ._verify_instance_ldapauth_server_response import VerifyInstanceLDAPAuthServerResponse
from ._add_databases_to_group_response_body import AddDatabasesToGroupResponseBodyResults
from ._add_hosts_to_group_response_body import AddHostsToGroupResponseBodyResults
from ._add_users_to_group_response_body import AddUsersToGroupResponseBodyResults
from ._attach_database_accounts_to_user_request import AttachDatabaseAccountsToUserRequestDatabases
from ._attach_database_accounts_to_user_response_body import AttachDatabaseAccountsToUserResponseBodyResultsDatabaseAccounts
from ._attach_database_accounts_to_user_response_body import AttachDatabaseAccountsToUserResponseBodyResults
from ._attach_database_accounts_to_user_group_request import AttachDatabaseAccountsToUserGroupRequestDatabases
from ._attach_database_accounts_to_user_group_response_body import AttachDatabaseAccountsToUserGroupResponseBodyResultsDatabaseAccounts
from ._attach_database_accounts_to_user_group_response_body import AttachDatabaseAccountsToUserGroupResponseBodyResults
from ._attach_host_accounts_to_host_share_key_response_body import AttachHostAccountsToHostShareKeyResponseBodyResults
from ._attach_host_accounts_to_user_response_body import AttachHostAccountsToUserResponseBodyResultsHostAccounts
from ._attach_host_accounts_to_user_response_body import AttachHostAccountsToUserResponseBodyResults
from ._attach_host_accounts_to_user_group_response_body import AttachHostAccountsToUserGroupResponseBodyResultsHostAccounts
from ._attach_host_accounts_to_user_group_response_body import AttachHostAccountsToUserGroupResponseBodyResults
from ._attach_host_group_accounts_to_user_response_body import AttachHostGroupAccountsToUserResponseBodyResultsHostAccountNames
from ._attach_host_group_accounts_to_user_response_body import AttachHostGroupAccountsToUserResponseBodyResults
from ._attach_host_group_accounts_to_user_group_response_body import AttachHostGroupAccountsToUserGroupResponseBodyResultsHostAccountNames
from ._attach_host_group_accounts_to_user_group_response_body import AttachHostGroupAccountsToUserGroupResponseBodyResults
from ._config_instance_white_list_request import ConfigInstanceWhiteListRequestWhiteListPolicies
from ._create_network_domain_request import CreateNetworkDomainRequestProxies
from ._create_rule_request import CreateRuleRequestDatabases
from ._create_rule_request import CreateRuleRequestHostGroups
from ._create_rule_request import CreateRuleRequestHosts
from ._describe_instance_attribute_response_body import DescribeInstanceAttributeResponseBodyInstanceAttributePorts
from ._describe_instance_attribute_response_body import DescribeInstanceAttributeResponseBodyInstanceAttributeWhiteListPolicies
from ._describe_instance_attribute_response_body import DescribeInstanceAttributeResponseBodyInstanceAttribute
from ._describe_instances_request import DescribeInstancesRequestTag
from ._describe_instances_response_body import DescribeInstancesResponseBodyInstances
from ._describe_regions_response_body import DescribeRegionsResponseBodyRegions
from ._detach_database_accounts_from_user_request import DetachDatabaseAccountsFromUserRequestDatabases
from ._detach_database_accounts_from_user_response_body import DetachDatabaseAccountsFromUserResponseBodyResultsDatabaseAccounts
from ._detach_database_accounts_from_user_response_body import DetachDatabaseAccountsFromUserResponseBodyResults
from ._detach_database_accounts_from_user_group_request import DetachDatabaseAccountsFromUserGroupRequestDatabases
from ._detach_database_accounts_from_user_group_response_body import DetachDatabaseAccountsFromUserGroupResponseBodyResultsDatabaseAccounts
from ._detach_database_accounts_from_user_group_response_body import DetachDatabaseAccountsFromUserGroupResponseBodyResults
from ._detach_host_accounts_from_host_share_key_response_body import DetachHostAccountsFromHostShareKeyResponseBodyResults
from ._detach_host_accounts_from_user_response_body import DetachHostAccountsFromUserResponseBodyResultsHostAccounts
from ._detach_host_accounts_from_user_response_body import DetachHostAccountsFromUserResponseBodyResults
from ._detach_host_accounts_from_user_group_response_body import DetachHostAccountsFromUserGroupResponseBodyResultsHostAccounts
from ._detach_host_accounts_from_user_group_response_body import DetachHostAccountsFromUserGroupResponseBodyResults
from ._detach_host_group_accounts_from_user_response_body import DetachHostGroupAccountsFromUserResponseBodyResultsHostAccountNames
from ._detach_host_group_accounts_from_user_response_body import DetachHostGroupAccountsFromUserResponseBodyResults
from ._detach_host_group_accounts_from_user_group_response_body import DetachHostGroupAccountsFromUserGroupResponseBodyResultsHostAccountNames
from ._detach_host_group_accounts_from_user_group_response_body import DetachHostGroupAccountsFromUserGroupResponseBodyResults
from ._generate_asset_operation_token_response_body import GenerateAssetOperationTokenResponseBodyAssetOperationToken
from ._get_database_response_body import GetDatabaseResponseBodyDatabase
from ._get_database_account_response_body import GetDatabaseAccountResponseBodyDatabaseAccount
from ._get_host_response_body import GetHostResponseBodyHostProtocols
from ._get_host_response_body import GetHostResponseBodyHost
from ._get_host_account_response_body import GetHostAccountResponseBodyHostAccount
from ._get_host_group_response_body import GetHostGroupResponseBodyHostGroup
from ._get_host_share_key_response_body import GetHostShareKeyResponseBodyHostShareKey
from ._get_instance_adauth_server_response_body import GetInstanceADAuthServerResponseBodyAD
from ._get_instance_ldapauth_server_response_body import GetInstanceLDAPAuthServerResponseBodyLDAP
from ._get_instance_two_factor_response_body import GetInstanceTwoFactorResponseBodyConfig
from ._get_network_domain_response_body import GetNetworkDomainResponseBodyNetworkDomainProxies
from ._get_network_domain_response_body import GetNetworkDomainResponseBodyNetworkDomain
from ._get_policy_response_body import GetPolicyResponseBodyPolicyAccessTimeRangeConfigEffectiveTime
from ._get_policy_response_body import GetPolicyResponseBodyPolicyAccessTimeRangeConfig
from ._get_policy_response_body import GetPolicyResponseBodyPolicyApprovalConfig
from ._get_policy_response_body import GetPolicyResponseBodyPolicyCommandConfigApproval
from ._get_policy_response_body import GetPolicyResponseBodyPolicyCommandConfigDeny
from ._get_policy_response_body import GetPolicyResponseBodyPolicyCommandConfig
from ._get_policy_response_body import GetPolicyResponseBodyPolicyIPAclConfig
from ._get_policy_response_body import GetPolicyResponseBodyPolicyProtocolConfigRDP
from ._get_policy_response_body import GetPolicyResponseBodyPolicyProtocolConfigSSH
from ._get_policy_response_body import GetPolicyResponseBodyPolicyProtocolConfig
from ._get_policy_response_body import GetPolicyResponseBodyPolicy
from ._get_policy_asset_scope_response_body import GetPolicyAssetScopeResponseBodyAssetScopeDatabases
from ._get_policy_asset_scope_response_body import GetPolicyAssetScopeResponseBodyAssetScopeHostGroups
from ._get_policy_asset_scope_response_body import GetPolicyAssetScopeResponseBodyAssetScopeHosts
from ._get_policy_asset_scope_response_body import GetPolicyAssetScopeResponseBodyAssetScope
from ._get_policy_user_scope_response_body import GetPolicyUserScopeResponseBodyUserScope
from ._get_rule_response_body import GetRuleResponseBodyRuleDatabasesDatabaseAccounts
from ._get_rule_response_body import GetRuleResponseBodyRuleDatabases
from ._get_rule_response_body import GetRuleResponseBodyRuleHostGroups
from ._get_rule_response_body import GetRuleResponseBodyRuleHostsHostAccounts
from ._get_rule_response_body import GetRuleResponseBodyRuleHosts
from ._get_rule_response_body import GetRuleResponseBodyRuleUserGroups
from ._get_rule_response_body import GetRuleResponseBodyRuleUsers
from ._get_rule_response_body import GetRuleResponseBodyRule
from ._get_user_response_body import GetUserResponseBodyUser
from ._get_user_group_response_body import GetUserGroupResponseBodyUserGroup
from ._list_approve_commands_response_body import ListApproveCommandsResponseBodyApproveCommands
from ._list_database_accounts_response_body import ListDatabaseAccountsResponseBodyDatabaseAccounts
from ._list_database_accounts_for_user_response_body import ListDatabaseAccountsForUserResponseBodyDatabaseAccounts
from ._list_database_accounts_for_user_group_response_body import ListDatabaseAccountsForUserGroupResponseBodyDatabaseAccounts
from ._list_databases_response_body import ListDatabasesResponseBodyDatabases
from ._list_databases_for_user_response_body import ListDatabasesForUserResponseBodyDatabases
from ._list_databases_for_user_group_response_body import ListDatabasesForUserGroupResponseBodyDatabases
from ._list_host_accounts_response_body import ListHostAccountsResponseBodyHostAccounts
from ._list_host_accounts_for_host_share_key_response_body import ListHostAccountsForHostShareKeyResponseBodyHostAccounts
from ._list_host_accounts_for_user_response_body import ListHostAccountsForUserResponseBodyHostAccounts
from ._list_host_accounts_for_user_group_response_body import ListHostAccountsForUserGroupResponseBodyHostAccounts
from ._list_host_groups_response_body import ListHostGroupsResponseBodyHostGroups
from ._list_host_groups_for_user_response_body import ListHostGroupsForUserResponseBodyHostGroups
from ._list_host_groups_for_user_group_response_body import ListHostGroupsForUserGroupResponseBodyHostGroups
from ._list_host_share_keys_response_body import ListHostShareKeysResponseBodyHostShareKeys
from ._list_hosts_response_body import ListHostsResponseBodyHosts
from ._list_hosts_for_user_response_body import ListHostsForUserResponseBodyHosts
from ._list_hosts_for_user_group_response_body import ListHostsForUserGroupResponseBodyHosts
from ._list_instance_rd_members_response_body import ListInstanceRdMembersResponseBodyMembers
from ._list_network_domains_response_body import ListNetworkDomainsResponseBodyNetworkDomainsProxiesState
from ._list_network_domains_response_body import ListNetworkDomainsResponseBodyNetworkDomains
from ._list_operation_database_accounts_response_body import ListOperationDatabaseAccountsResponseBodyDatabaseAccounts
from ._list_operation_databases_response_body import ListOperationDatabasesResponseBodyDatabases
from ._list_operation_host_accounts_response_body import ListOperationHostAccountsResponseBodyHostAccountsSSHConfig
from ._list_operation_host_accounts_response_body import ListOperationHostAccountsResponseBodyHostAccounts
from ._list_operation_hosts_response_body import ListOperationHostsResponseBodyHosts
from ._list_operation_tickets_response_body import ListOperationTicketsResponseBodyOperationTickets
from ._list_policies_response_body import ListPoliciesResponseBodyPolicies
from ._list_rules_response_body import ListRulesResponseBodyRules
from ._list_tag_keys_response_body import ListTagKeysResponseBodyTagKeys
from ._list_tag_resources_request import ListTagResourcesRequestTag
from ._list_tag_resources_response_body import ListTagResourcesResponseBodyTagResources
from ._list_user_groups_response_body import ListUserGroupsResponseBodyUserGroups
from ._list_user_public_keys_response_body import ListUserPublicKeysResponseBodyPublicKeys
from ._list_users_response_body import ListUsersResponseBodyUsers
from ._lock_users_response_body import LockUsersResponseBodyResults
from ._modify_hosts_active_address_type_response_body import ModifyHostsActiveAddressTypeResponseBodyResults
from ._modify_hosts_port_response_body import ModifyHostsPortResponseBodyResults
from ._modify_network_domain_request import ModifyNetworkDomainRequestProxies
from ._modify_rule_request import ModifyRuleRequestDatabases
from ._modify_rule_request import ModifyRuleRequestHostGroups
from ._modify_rule_request import ModifyRuleRequestHosts
from ._move_databases_to_network_domain_response_body import MoveDatabasesToNetworkDomainResponseBodyResults
from ._move_hosts_to_network_domain_response_body import MoveHostsToNetworkDomainResponseBodyResults
from ._remove_databases_from_group_response_body import RemoveDatabasesFromGroupResponseBodyResults
from ._remove_hosts_from_group_response_body import RemoveHostsFromGroupResponseBodyResults
from ._remove_users_from_group_response_body import RemoveUsersFromGroupResponseBodyResults
from ._set_policy_access_time_range_config_request import SetPolicyAccessTimeRangeConfigRequestAccessTimeRangeConfigEffectiveTime
from ._set_policy_access_time_range_config_request import SetPolicyAccessTimeRangeConfigRequestAccessTimeRangeConfig
from ._set_policy_approval_config_request import SetPolicyApprovalConfigRequestApprovalConfig
from ._set_policy_asset_scope_request import SetPolicyAssetScopeRequestDatabases
from ._set_policy_asset_scope_request import SetPolicyAssetScopeRequestHostGroups
from ._set_policy_asset_scope_request import SetPolicyAssetScopeRequestHosts
from ._set_policy_command_config_request import SetPolicyCommandConfigRequestCommandConfigApproval
from ._set_policy_command_config_request import SetPolicyCommandConfigRequestCommandConfigDeny
from ._set_policy_command_config_request import SetPolicyCommandConfigRequestCommandConfig
from ._set_policy_ipacl_config_request import SetPolicyIPAclConfigRequestIPAclConfig
from ._set_policy_protocol_config_request import SetPolicyProtocolConfigRequestProtocolConfigRDP
from ._set_policy_protocol_config_request import SetPolicyProtocolConfigRequestProtocolConfigSSH
from ._set_policy_protocol_config_request import SetPolicyProtocolConfigRequestProtocolConfig
from ._tag_resources_request import TagResourcesRequestTag
from ._unlock_users_response_body import UnlockUsersResponseBodyResults

__all__ = [
    AcceptApproveCommandRequest,
    AcceptApproveCommandResponseBody,
    AcceptApproveCommandResponse,
    AcceptOperationTicketRequest,
    AcceptOperationTicketResponseBody,
    AcceptOperationTicketResponse,
    AddDatabasesToGroupRequest,
    AddDatabasesToGroupResponseBody,
    AddDatabasesToGroupResponse,
    AddHostsToGroupRequest,
    AddHostsToGroupResponseBody,
    AddHostsToGroupResponse,
    AddInstanceRdMemberRequest,
    AddInstanceRdMemberResponseBody,
    AddInstanceRdMemberResponse,
    AddUsersToGroupRequest,
    AddUsersToGroupResponseBody,
    AddUsersToGroupResponse,
    AttachDatabaseAccountsToUserRequest,
    AttachDatabaseAccountsToUserResponseBody,
    AttachDatabaseAccountsToUserResponse,
    AttachDatabaseAccountsToUserGroupRequest,
    AttachDatabaseAccountsToUserGroupResponseBody,
    AttachDatabaseAccountsToUserGroupResponse,
    AttachHostAccountsToHostShareKeyRequest,
    AttachHostAccountsToHostShareKeyResponseBody,
    AttachHostAccountsToHostShareKeyResponse,
    AttachHostAccountsToUserRequest,
    AttachHostAccountsToUserResponseBody,
    AttachHostAccountsToUserResponse,
    AttachHostAccountsToUserGroupRequest,
    AttachHostAccountsToUserGroupResponseBody,
    AttachHostAccountsToUserGroupResponse,
    AttachHostGroupAccountsToUserRequest,
    AttachHostGroupAccountsToUserResponseBody,
    AttachHostGroupAccountsToUserResponse,
    AttachHostGroupAccountsToUserGroupRequest,
    AttachHostGroupAccountsToUserGroupResponseBody,
    AttachHostGroupAccountsToUserGroupResponse,
    ConfigInstanceSecurityGroupsRequest,
    ConfigInstanceSecurityGroupsResponseBody,
    ConfigInstanceSecurityGroupsResponse,
    ConfigInstanceWhiteListRequest,
    ConfigInstanceWhiteListResponseBody,
    ConfigInstanceWhiteListResponse,
    CreateDatabaseRequest,
    CreateDatabaseResponseBody,
    CreateDatabaseResponse,
    CreateDatabaseAccountRequest,
    CreateDatabaseAccountResponseBody,
    CreateDatabaseAccountResponse,
    CreateExportConfigJobRequest,
    CreateExportConfigJobResponseBody,
    CreateExportConfigJobResponse,
    CreateHostRequest,
    CreateHostResponseBody,
    CreateHostResponse,
    CreateHostAccountRequest,
    CreateHostAccountResponseBody,
    CreateHostAccountResponse,
    CreateHostGroupRequest,
    CreateHostGroupResponseBody,
    CreateHostGroupResponse,
    CreateHostShareKeyRequest,
    CreateHostShareKeyResponseBody,
    CreateHostShareKeyResponse,
    CreateNetworkDomainRequest,
    CreateNetworkDomainResponseBody,
    CreateNetworkDomainResponse,
    CreateOperationTicketRequest,
    CreateOperationTicketResponseBody,
    CreateOperationTicketResponse,
    CreatePolicyRequest,
    CreatePolicyResponseBody,
    CreatePolicyResponse,
    CreateRuleRequest,
    CreateRuleResponseBody,
    CreateRuleResponse,
    CreateUserRequest,
    CreateUserResponseBody,
    CreateUserResponse,
    CreateUserGroupRequest,
    CreateUserGroupResponseBody,
    CreateUserGroupResponse,
    CreateUserPublicKeyRequest,
    CreateUserPublicKeyResponseBody,
    CreateUserPublicKeyResponse,
    DeleteDatabaseRequest,
    DeleteDatabaseResponseBody,
    DeleteDatabaseResponse,
    DeleteDatabaseAccountRequest,
    DeleteDatabaseAccountResponseBody,
    DeleteDatabaseAccountResponse,
    DeleteHostRequest,
    DeleteHostResponseBody,
    DeleteHostResponse,
    DeleteHostAccountRequest,
    DeleteHostAccountResponseBody,
    DeleteHostAccountResponse,
    DeleteHostGroupRequest,
    DeleteHostGroupResponseBody,
    DeleteHostGroupResponse,
    DeleteHostShareKeyRequest,
    DeleteHostShareKeyResponseBody,
    DeleteHostShareKeyResponse,
    DeleteNetworkDomainRequest,
    DeleteNetworkDomainResponseBody,
    DeleteNetworkDomainResponse,
    DeletePolicyRequest,
    DeletePolicyResponseBody,
    DeletePolicyResponse,
    DeleteRuleRequest,
    DeleteRuleResponseBody,
    DeleteRuleResponse,
    DeleteUserRequest,
    DeleteUserResponseBody,
    DeleteUserResponse,
    DeleteUserGroupRequest,
    DeleteUserGroupResponseBody,
    DeleteUserGroupResponse,
    DeleteUserPublicKeyRequest,
    DeleteUserPublicKeyResponseBody,
    DeleteUserPublicKeyResponse,
    DescribeInstanceAttributeRequest,
    DescribeInstanceAttributeResponseBody,
    DescribeInstanceAttributeResponse,
    DescribeInstancesRequest,
    DescribeInstancesResponseBody,
    DescribeInstancesResponse,
    DescribeRegionsRequest,
    DescribeRegionsResponseBody,
    DescribeRegionsResponse,
    DetachDatabaseAccountsFromUserRequest,
    DetachDatabaseAccountsFromUserResponseBody,
    DetachDatabaseAccountsFromUserResponse,
    DetachDatabaseAccountsFromUserGroupRequest,
    DetachDatabaseAccountsFromUserGroupResponseBody,
    DetachDatabaseAccountsFromUserGroupResponse,
    DetachHostAccountsFromHostShareKeyRequest,
    DetachHostAccountsFromHostShareKeyResponseBody,
    DetachHostAccountsFromHostShareKeyResponse,
    DetachHostAccountsFromUserRequest,
    DetachHostAccountsFromUserResponseBody,
    DetachHostAccountsFromUserResponse,
    DetachHostAccountsFromUserGroupRequest,
    DetachHostAccountsFromUserGroupResponseBody,
    DetachHostAccountsFromUserGroupResponse,
    DetachHostGroupAccountsFromUserRequest,
    DetachHostGroupAccountsFromUserResponseBody,
    DetachHostGroupAccountsFromUserResponse,
    DetachHostGroupAccountsFromUserGroupRequest,
    DetachHostGroupAccountsFromUserGroupResponseBody,
    DetachHostGroupAccountsFromUserGroupResponse,
    DisableInstancePublicAccessRequest,
    DisableInstancePublicAccessResponseBody,
    DisableInstancePublicAccessResponse,
    DisableRuleRequest,
    DisableRuleResponseBody,
    DisableRuleResponse,
    EnableInstancePublicAccessRequest,
    EnableInstancePublicAccessResponseBody,
    EnableInstancePublicAccessResponse,
    EnableRuleRequest,
    EnableRuleResponseBody,
    EnableRuleResponse,
    GenerateAssetOperationTokenRequest,
    GenerateAssetOperationTokenResponseBody,
    GenerateAssetOperationTokenResponse,
    GetDatabaseRequest,
    GetDatabaseResponseBody,
    GetDatabaseResponse,
    GetDatabaseAccountRequest,
    GetDatabaseAccountResponseBody,
    GetDatabaseAccountResponse,
    GetExportConfigJobRequest,
    GetExportConfigJobResponseBody,
    GetExportConfigJobResponse,
    GetHostRequest,
    GetHostResponseBody,
    GetHostResponse,
    GetHostAccountRequest,
    GetHostAccountResponseBody,
    GetHostAccountResponse,
    GetHostGroupRequest,
    GetHostGroupResponseBody,
    GetHostGroupResponse,
    GetHostShareKeyRequest,
    GetHostShareKeyResponseBody,
    GetHostShareKeyResponse,
    GetInstanceADAuthServerRequest,
    GetInstanceADAuthServerResponseBody,
    GetInstanceADAuthServerResponse,
    GetInstanceLDAPAuthServerRequest,
    GetInstanceLDAPAuthServerResponseBody,
    GetInstanceLDAPAuthServerResponse,
    GetInstanceStoreInfoRequest,
    GetInstanceStoreInfoResponseBody,
    GetInstanceStoreInfoResponse,
    GetInstanceTwoFactorRequest,
    GetInstanceTwoFactorResponseBody,
    GetInstanceTwoFactorResponse,
    GetNetworkDomainRequest,
    GetNetworkDomainResponseBody,
    GetNetworkDomainResponse,
    GetPolicyRequest,
    GetPolicyResponseBody,
    GetPolicyResponse,
    GetPolicyAssetScopeRequest,
    GetPolicyAssetScopeResponseBody,
    GetPolicyAssetScopeResponse,
    GetPolicyUserScopeRequest,
    GetPolicyUserScopeResponseBody,
    GetPolicyUserScopeResponse,
    GetRuleRequest,
    GetRuleResponseBody,
    GetRuleResponse,
    GetUserRequest,
    GetUserResponseBody,
    GetUserResponse,
    GetUserGroupRequest,
    GetUserGroupResponseBody,
    GetUserGroupResponse,
    ListApproveCommandsRequest,
    ListApproveCommandsResponseBody,
    ListApproveCommandsResponse,
    ListDatabaseAccountsRequest,
    ListDatabaseAccountsResponseBody,
    ListDatabaseAccountsResponse,
    ListDatabaseAccountsForUserRequest,
    ListDatabaseAccountsForUserResponseBody,
    ListDatabaseAccountsForUserResponse,
    ListDatabaseAccountsForUserGroupRequest,
    ListDatabaseAccountsForUserGroupResponseBody,
    ListDatabaseAccountsForUserGroupResponse,
    ListDatabasesRequest,
    ListDatabasesResponseBody,
    ListDatabasesResponse,
    ListDatabasesForUserRequest,
    ListDatabasesForUserResponseBody,
    ListDatabasesForUserResponse,
    ListDatabasesForUserGroupRequest,
    ListDatabasesForUserGroupResponseBody,
    ListDatabasesForUserGroupResponse,
    ListHostAccountsRequest,
    ListHostAccountsResponseBody,
    ListHostAccountsResponse,
    ListHostAccountsForHostShareKeyRequest,
    ListHostAccountsForHostShareKeyResponseBody,
    ListHostAccountsForHostShareKeyResponse,
    ListHostAccountsForUserRequest,
    ListHostAccountsForUserResponseBody,
    ListHostAccountsForUserResponse,
    ListHostAccountsForUserGroupRequest,
    ListHostAccountsForUserGroupResponseBody,
    ListHostAccountsForUserGroupResponse,
    ListHostGroupAccountNamesForUserRequest,
    ListHostGroupAccountNamesForUserResponseBody,
    ListHostGroupAccountNamesForUserResponse,
    ListHostGroupAccountNamesForUserGroupRequest,
    ListHostGroupAccountNamesForUserGroupResponseBody,
    ListHostGroupAccountNamesForUserGroupResponse,
    ListHostGroupsRequest,
    ListHostGroupsResponseBody,
    ListHostGroupsResponse,
    ListHostGroupsForUserRequest,
    ListHostGroupsForUserResponseBody,
    ListHostGroupsForUserResponse,
    ListHostGroupsForUserGroupRequest,
    ListHostGroupsForUserGroupResponseBody,
    ListHostGroupsForUserGroupResponse,
    ListHostShareKeysRequest,
    ListHostShareKeysResponseBody,
    ListHostShareKeysResponse,
    ListHostsRequest,
    ListHostsResponseBody,
    ListHostsResponse,
    ListHostsForUserRequest,
    ListHostsForUserResponseBody,
    ListHostsForUserResponse,
    ListHostsForUserGroupRequest,
    ListHostsForUserGroupResponseBody,
    ListHostsForUserGroupResponse,
    ListInstanceRdMembersRequest,
    ListInstanceRdMembersResponseBody,
    ListInstanceRdMembersResponse,
    ListNetworkDomainsRequest,
    ListNetworkDomainsResponseBody,
    ListNetworkDomainsResponse,
    ListOperationDatabaseAccountsRequest,
    ListOperationDatabaseAccountsResponseBody,
    ListOperationDatabaseAccountsResponse,
    ListOperationDatabasesRequest,
    ListOperationDatabasesResponseBody,
    ListOperationDatabasesResponse,
    ListOperationHostAccountsRequest,
    ListOperationHostAccountsResponseBody,
    ListOperationHostAccountsResponse,
    ListOperationHostsRequest,
    ListOperationHostsResponseBody,
    ListOperationHostsResponse,
    ListOperationTicketsRequest,
    ListOperationTicketsResponseBody,
    ListOperationTicketsResponse,
    ListPoliciesRequest,
    ListPoliciesResponseBody,
    ListPoliciesResponse,
    ListRulesRequest,
    ListRulesResponseBody,
    ListRulesResponse,
    ListTagKeysRequest,
    ListTagKeysResponseBody,
    ListTagKeysResponse,
    ListTagResourcesRequest,
    ListTagResourcesResponseBody,
    ListTagResourcesResponse,
    ListUserGroupsRequest,
    ListUserGroupsResponseBody,
    ListUserGroupsResponse,
    ListUserPublicKeysRequest,
    ListUserPublicKeysResponseBody,
    ListUserPublicKeysResponse,
    ListUsersRequest,
    ListUsersResponseBody,
    ListUsersResponse,
    LockUsersRequest,
    LockUsersResponseBody,
    LockUsersResponse,
    ModifyDatabaseRequest,
    ModifyDatabaseResponseBody,
    ModifyDatabaseResponse,
    ModifyDatabaseAccountRequest,
    ModifyDatabaseAccountResponseBody,
    ModifyDatabaseAccountResponse,
    ModifyHostRequest,
    ModifyHostResponseBody,
    ModifyHostResponse,
    ModifyHostAccountRequest,
    ModifyHostAccountResponseBody,
    ModifyHostAccountResponse,
    ModifyHostGroupRequest,
    ModifyHostGroupResponseBody,
    ModifyHostGroupResponse,
    ModifyHostShareKeyRequest,
    ModifyHostShareKeyResponseBody,
    ModifyHostShareKeyResponse,
    ModifyHostsActiveAddressTypeRequest,
    ModifyHostsActiveAddressTypeResponseBody,
    ModifyHostsActiveAddressTypeResponse,
    ModifyHostsPortRequest,
    ModifyHostsPortResponseBody,
    ModifyHostsPortResponse,
    ModifyInstanceADAuthServerRequest,
    ModifyInstanceADAuthServerResponseBody,
    ModifyInstanceADAuthServerResponse,
    ModifyInstanceAttributeRequest,
    ModifyInstanceAttributeResponseBody,
    ModifyInstanceAttributeResponse,
    ModifyInstanceLDAPAuthServerRequest,
    ModifyInstanceLDAPAuthServerResponseBody,
    ModifyInstanceLDAPAuthServerResponse,
    ModifyInstanceTwoFactorRequest,
    ModifyInstanceTwoFactorResponseBody,
    ModifyInstanceTwoFactorResponse,
    ModifyNetworkDomainRequest,
    ModifyNetworkDomainResponseBody,
    ModifyNetworkDomainResponse,
    ModifyPolicyRequest,
    ModifyPolicyResponseBody,
    ModifyPolicyResponse,
    ModifyRuleRequest,
    ModifyRuleResponseBody,
    ModifyRuleResponse,
    ModifyUserRequest,
    ModifyUserResponseBody,
    ModifyUserResponse,
    ModifyUserGroupRequest,
    ModifyUserGroupResponseBody,
    ModifyUserGroupResponse,
    ModifyUserPublicKeyRequest,
    ModifyUserPublicKeyResponseBody,
    ModifyUserPublicKeyResponse,
    MoveDatabasesToNetworkDomainRequest,
    MoveDatabasesToNetworkDomainResponseBody,
    MoveDatabasesToNetworkDomainResponse,
    MoveHostsToNetworkDomainRequest,
    MoveHostsToNetworkDomainResponseBody,
    MoveHostsToNetworkDomainResponse,
    MoveResourceGroupRequest,
    MoveResourceGroupResponseBody,
    MoveResourceGroupResponse,
    RejectApproveCommandRequest,
    RejectApproveCommandResponseBody,
    RejectApproveCommandResponse,
    RejectOperationTicketRequest,
    RejectOperationTicketResponseBody,
    RejectOperationTicketResponse,
    RemoveDatabasesFromGroupRequest,
    RemoveDatabasesFromGroupResponseBody,
    RemoveDatabasesFromGroupResponse,
    RemoveHostsFromGroupRequest,
    RemoveHostsFromGroupResponseBody,
    RemoveHostsFromGroupResponse,
    RemoveInstanceRdMemberRequest,
    RemoveInstanceRdMemberResponseBody,
    RemoveInstanceRdMemberResponse,
    RemoveUsersFromGroupRequest,
    RemoveUsersFromGroupResponseBody,
    RemoveUsersFromGroupResponse,
    RenewAssetOperationTokenRequest,
    RenewAssetOperationTokenResponseBody,
    RenewAssetOperationTokenResponse,
    ResetHostAccountCredentialRequest,
    ResetHostAccountCredentialResponseBody,
    ResetHostAccountCredentialResponse,
    SetPolicyAccessTimeRangeConfigRequest,
    SetPolicyAccessTimeRangeConfigShrinkRequest,
    SetPolicyAccessTimeRangeConfigResponseBody,
    SetPolicyAccessTimeRangeConfigResponse,
    SetPolicyApprovalConfigRequest,
    SetPolicyApprovalConfigShrinkRequest,
    SetPolicyApprovalConfigResponseBody,
    SetPolicyApprovalConfigResponse,
    SetPolicyAssetScopeRequest,
    SetPolicyAssetScopeResponseBody,
    SetPolicyAssetScopeResponse,
    SetPolicyCommandConfigRequest,
    SetPolicyCommandConfigShrinkRequest,
    SetPolicyCommandConfigResponseBody,
    SetPolicyCommandConfigResponse,
    SetPolicyIPAclConfigRequest,
    SetPolicyIPAclConfigShrinkRequest,
    SetPolicyIPAclConfigResponseBody,
    SetPolicyIPAclConfigResponse,
    SetPolicyProtocolConfigRequest,
    SetPolicyProtocolConfigShrinkRequest,
    SetPolicyProtocolConfigResponseBody,
    SetPolicyProtocolConfigResponse,
    SetPolicyUserScopeRequest,
    SetPolicyUserScopeResponseBody,
    SetPolicyUserScopeResponse,
    StartInstanceRequest,
    StartInstanceResponseBody,
    StartInstanceResponse,
    TagResourcesRequest,
    TagResourcesResponseBody,
    TagResourcesResponse,
    UnlockUsersRequest,
    UnlockUsersResponseBody,
    UnlockUsersResponse,
    UntagResourcesRequest,
    UntagResourcesResponseBody,
    UntagResourcesResponse,
    VerifyInstanceADAuthServerRequest,
    VerifyInstanceADAuthServerResponseBody,
    VerifyInstanceADAuthServerResponse,
    VerifyInstanceLDAPAuthServerRequest,
    VerifyInstanceLDAPAuthServerResponseBody,
    VerifyInstanceLDAPAuthServerResponse,
    AddDatabasesToGroupResponseBodyResults,
    AddHostsToGroupResponseBodyResults,
    AddUsersToGroupResponseBodyResults,
    AttachDatabaseAccountsToUserRequestDatabases,
    AttachDatabaseAccountsToUserResponseBodyResultsDatabaseAccounts,
    AttachDatabaseAccountsToUserResponseBodyResults,
    AttachDatabaseAccountsToUserGroupRequestDatabases,
    AttachDatabaseAccountsToUserGroupResponseBodyResultsDatabaseAccounts,
    AttachDatabaseAccountsToUserGroupResponseBodyResults,
    AttachHostAccountsToHostShareKeyResponseBodyResults,
    AttachHostAccountsToUserResponseBodyResultsHostAccounts,
    AttachHostAccountsToUserResponseBodyResults,
    AttachHostAccountsToUserGroupResponseBodyResultsHostAccounts,
    AttachHostAccountsToUserGroupResponseBodyResults,
    AttachHostGroupAccountsToUserResponseBodyResultsHostAccountNames,
    AttachHostGroupAccountsToUserResponseBodyResults,
    AttachHostGroupAccountsToUserGroupResponseBodyResultsHostAccountNames,
    AttachHostGroupAccountsToUserGroupResponseBodyResults,
    ConfigInstanceWhiteListRequestWhiteListPolicies,
    CreateNetworkDomainRequestProxies,
    CreateRuleRequestDatabases,
    CreateRuleRequestHostGroups,
    CreateRuleRequestHosts,
    DescribeInstanceAttributeResponseBodyInstanceAttributePorts,
    DescribeInstanceAttributeResponseBodyInstanceAttributeWhiteListPolicies,
    DescribeInstanceAttributeResponseBodyInstanceAttribute,
    DescribeInstancesRequestTag,
    DescribeInstancesResponseBodyInstances,
    DescribeRegionsResponseBodyRegions,
    DetachDatabaseAccountsFromUserRequestDatabases,
    DetachDatabaseAccountsFromUserResponseBodyResultsDatabaseAccounts,
    DetachDatabaseAccountsFromUserResponseBodyResults,
    DetachDatabaseAccountsFromUserGroupRequestDatabases,
    DetachDatabaseAccountsFromUserGroupResponseBodyResultsDatabaseAccounts,
    DetachDatabaseAccountsFromUserGroupResponseBodyResults,
    DetachHostAccountsFromHostShareKeyResponseBodyResults,
    DetachHostAccountsFromUserResponseBodyResultsHostAccounts,
    DetachHostAccountsFromUserResponseBodyResults,
    DetachHostAccountsFromUserGroupResponseBodyResultsHostAccounts,
    DetachHostAccountsFromUserGroupResponseBodyResults,
    DetachHostGroupAccountsFromUserResponseBodyResultsHostAccountNames,
    DetachHostGroupAccountsFromUserResponseBodyResults,
    DetachHostGroupAccountsFromUserGroupResponseBodyResultsHostAccountNames,
    DetachHostGroupAccountsFromUserGroupResponseBodyResults,
    GenerateAssetOperationTokenResponseBodyAssetOperationToken,
    GetDatabaseResponseBodyDatabase,
    GetDatabaseAccountResponseBodyDatabaseAccount,
    GetHostResponseBodyHostProtocols,
    GetHostResponseBodyHost,
    GetHostAccountResponseBodyHostAccount,
    GetHostGroupResponseBodyHostGroup,
    GetHostShareKeyResponseBodyHostShareKey,
    GetInstanceADAuthServerResponseBodyAD,
    GetInstanceLDAPAuthServerResponseBodyLDAP,
    GetInstanceTwoFactorResponseBodyConfig,
    GetNetworkDomainResponseBodyNetworkDomainProxies,
    GetNetworkDomainResponseBodyNetworkDomain,
    GetPolicyResponseBodyPolicyAccessTimeRangeConfigEffectiveTime,
    GetPolicyResponseBodyPolicyAccessTimeRangeConfig,
    GetPolicyResponseBodyPolicyApprovalConfig,
    GetPolicyResponseBodyPolicyCommandConfigApproval,
    GetPolicyResponseBodyPolicyCommandConfigDeny,
    GetPolicyResponseBodyPolicyCommandConfig,
    GetPolicyResponseBodyPolicyIPAclConfig,
    GetPolicyResponseBodyPolicyProtocolConfigRDP,
    GetPolicyResponseBodyPolicyProtocolConfigSSH,
    GetPolicyResponseBodyPolicyProtocolConfig,
    GetPolicyResponseBodyPolicy,
    GetPolicyAssetScopeResponseBodyAssetScopeDatabases,
    GetPolicyAssetScopeResponseBodyAssetScopeHostGroups,
    GetPolicyAssetScopeResponseBodyAssetScopeHosts,
    GetPolicyAssetScopeResponseBodyAssetScope,
    GetPolicyUserScopeResponseBodyUserScope,
    GetRuleResponseBodyRuleDatabasesDatabaseAccounts,
    GetRuleResponseBodyRuleDatabases,
    GetRuleResponseBodyRuleHostGroups,
    GetRuleResponseBodyRuleHostsHostAccounts,
    GetRuleResponseBodyRuleHosts,
    GetRuleResponseBodyRuleUserGroups,
    GetRuleResponseBodyRuleUsers,
    GetRuleResponseBodyRule,
    GetUserResponseBodyUser,
    GetUserGroupResponseBodyUserGroup,
    ListApproveCommandsResponseBodyApproveCommands,
    ListDatabaseAccountsResponseBodyDatabaseAccounts,
    ListDatabaseAccountsForUserResponseBodyDatabaseAccounts,
    ListDatabaseAccountsForUserGroupResponseBodyDatabaseAccounts,
    ListDatabasesResponseBodyDatabases,
    ListDatabasesForUserResponseBodyDatabases,
    ListDatabasesForUserGroupResponseBodyDatabases,
    ListHostAccountsResponseBodyHostAccounts,
    ListHostAccountsForHostShareKeyResponseBodyHostAccounts,
    ListHostAccountsForUserResponseBodyHostAccounts,
    ListHostAccountsForUserGroupResponseBodyHostAccounts,
    ListHostGroupsResponseBodyHostGroups,
    ListHostGroupsForUserResponseBodyHostGroups,
    ListHostGroupsForUserGroupResponseBodyHostGroups,
    ListHostShareKeysResponseBodyHostShareKeys,
    ListHostsResponseBodyHosts,
    ListHostsForUserResponseBodyHosts,
    ListHostsForUserGroupResponseBodyHosts,
    ListInstanceRdMembersResponseBodyMembers,
    ListNetworkDomainsResponseBodyNetworkDomainsProxiesState,
    ListNetworkDomainsResponseBodyNetworkDomains,
    ListOperationDatabaseAccountsResponseBodyDatabaseAccounts,
    ListOperationDatabasesResponseBodyDatabases,
    ListOperationHostAccountsResponseBodyHostAccountsSSHConfig,
    ListOperationHostAccountsResponseBodyHostAccounts,
    ListOperationHostsResponseBodyHosts,
    ListOperationTicketsResponseBodyOperationTickets,
    ListPoliciesResponseBodyPolicies,
    ListRulesResponseBodyRules,
    ListTagKeysResponseBodyTagKeys,
    ListTagResourcesRequestTag,
    ListTagResourcesResponseBodyTagResources,
    ListUserGroupsResponseBodyUserGroups,
    ListUserPublicKeysResponseBodyPublicKeys,
    ListUsersResponseBodyUsers,
    LockUsersResponseBodyResults,
    ModifyHostsActiveAddressTypeResponseBodyResults,
    ModifyHostsPortResponseBodyResults,
    ModifyNetworkDomainRequestProxies,
    ModifyRuleRequestDatabases,
    ModifyRuleRequestHostGroups,
    ModifyRuleRequestHosts,
    MoveDatabasesToNetworkDomainResponseBodyResults,
    MoveHostsToNetworkDomainResponseBodyResults,
    RemoveDatabasesFromGroupResponseBodyResults,
    RemoveHostsFromGroupResponseBodyResults,
    RemoveUsersFromGroupResponseBodyResults,
    SetPolicyAccessTimeRangeConfigRequestAccessTimeRangeConfigEffectiveTime,
    SetPolicyAccessTimeRangeConfigRequestAccessTimeRangeConfig,
    SetPolicyApprovalConfigRequestApprovalConfig,
    SetPolicyAssetScopeRequestDatabases,
    SetPolicyAssetScopeRequestHostGroups,
    SetPolicyAssetScopeRequestHosts,
    SetPolicyCommandConfigRequestCommandConfigApproval,
    SetPolicyCommandConfigRequestCommandConfigDeny,
    SetPolicyCommandConfigRequestCommandConfig,
    SetPolicyIPAclConfigRequestIPAclConfig,
    SetPolicyProtocolConfigRequestProtocolConfigRDP,
    SetPolicyProtocolConfigRequestProtocolConfigSSH,
    SetPolicyProtocolConfigRequestProtocolConfig,
    TagResourcesRequestTag,
    UnlockUsersResponseBodyResults
]
