# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import Dict

from alibabacloud_agentloop20260520 import models as main_models
from darabonba.model import DaraModel

class UpdateContextStoreRequest(DaraModel):
    def __init__(
        self,
        config: main_models.UpdateContextStoreRequestConfig = None,
        context_type: str = None,
        description: str = None,
        client_token: str = None,
    ):
        # The context store configuration. If specified, the entire configuration is overwritten. If not specified, the existing configuration is retained.
        self.config = config
        # The type of the context store. This value typically cannot be changed after creation. This field is provided only for exception correction.
        self.context_type = context_type
        # The description of the context store, which helps the business team understand its purpose.
        self.description = description
        # The idempotency token, which is a unique string generated by the client to ensure that the update operation is idempotent.
        self.client_token = client_token

    def validate(self):
        if self.config:
            self.config.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.config is not None:
            result['config'] = self.config.to_map()

        if self.context_type is not None:
            result['contextType'] = self.context_type

        if self.description is not None:
            result['description'] = self.description

        if self.client_token is not None:
            result['clientToken'] = self.client_token

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('config') is not None:
            temp_model = main_models.UpdateContextStoreRequestConfig()
            self.config = temp_model.from_map(m.get('config'))

        if m.get('contextType') is not None:
            self.context_type = m.get('contextType')

        if m.get('description') is not None:
            self.description = m.get('description')

        if m.get('clientToken') is not None:
            self.client_token = m.get('clientToken')

        return self

class UpdateContextStoreRequestConfig(DaraModel):
    def __init__(
        self,
        metadata_field: Dict[str, str] = None,
        source: main_models.UpdateContextStoreRequestConfigSource = None,
    ):
        # The metadata field mapping. The key is the business field and the value is the storage field.
        self.metadata_field = metadata_field
        # The datasource config, which serves only as the root identifier of the data source.
        self.source = source

    def validate(self):
        if self.source:
            self.source.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.metadata_field is not None:
            result['metadataField'] = self.metadata_field

        if self.source is not None:
            result['source'] = self.source.to_map()

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('metadataField') is not None:
            self.metadata_field = m.get('metadataField')

        if m.get('source') is not None:
            temp_model = main_models.UpdateContextStoreRequestConfigSource()
            self.source = temp_model.from_map(m.get('source'))

        return self

class UpdateContextStoreRequestConfigSource(DaraModel):
    def __init__(
        self,
        agent_space: str = None,
        start_time: str = None,
    ):
        # The AgentSpace where the trace data source resides. Cross-AgentSpace access is not supported. If specified, this value must be the same as the path AgentSpace. Otherwise, a 400 parameter error is returned. The AgentSpace cannot be changed after creation.
        self.agent_space = agent_space
        # The start time for data backfill, in ISO 8601 UTC format.
        self.start_time = start_time

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.agent_space is not None:
            result['agentSpace'] = self.agent_space

        if self.start_time is not None:
            result['startTime'] = self.start_time

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('agentSpace') is not None:
            self.agent_space = m.get('agentSpace')

        if m.get('startTime') is not None:
            self.start_time = m.get('startTime')

        return self

