# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_kms20160120 import models as main_models
from darabonba.model import DaraModel

class ListSecretsResponseBody(DaraModel):
    def __init__(
        self,
        page_number: int = None,
        page_size: int = None,
        request_id: str = None,
        secret_list: main_models.ListSecretsResponseBodySecretList = None,
        total_count: int = None,
    ):
        # The page number.
        self.page_number = page_number
        # The number of entries per page.
        self.page_size = page_size
        # The unique identifier generated by Alibaba Cloud for the request. Use it to locate and troubleshoot issues.
        self.request_id = request_id
        self.secret_list = secret_list
        # The number of secrets.
        self.total_count = total_count

    def validate(self):
        if self.secret_list:
            self.secret_list.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.page_number is not None:
            result['PageNumber'] = self.page_number

        if self.page_size is not None:
            result['PageSize'] = self.page_size

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.secret_list is not None:
            result['SecretList'] = self.secret_list.to_map()

        if self.total_count is not None:
            result['TotalCount'] = self.total_count

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('PageNumber') is not None:
            self.page_number = m.get('PageNumber')

        if m.get('PageSize') is not None:
            self.page_size = m.get('PageSize')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('SecretList') is not None:
            temp_model = main_models.ListSecretsResponseBodySecretList()
            self.secret_list = temp_model.from_map(m.get('SecretList'))

        if m.get('TotalCount') is not None:
            self.total_count = m.get('TotalCount')

        return self

class ListSecretsResponseBodySecretList(DaraModel):
    def __init__(
        self,
        secret: List[main_models.ListSecretsResponseBodySecretListSecret] = None,
    ):
        self.secret = secret

    def validate(self):
        if self.secret:
            for v1 in self.secret:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['Secret'] = []
        if self.secret is not None:
            for k1 in self.secret:
                result['Secret'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.secret = []
        if m.get('Secret') is not None:
            for k1 in m.get('Secret'):
                temp_model = main_models.ListSecretsResponseBodySecretListSecret()
                self.secret.append(temp_model.from_map(k1))

        return self

class ListSecretsResponseBodySecretListSecret(DaraModel):
    def __init__(
        self,
        create_time: str = None,
        owing_service: str = None,
        planned_delete_time: str = None,
        secret_name: str = None,
        secret_type: str = None,
        tags: main_models.ListSecretsResponseBodySecretListSecretTags = None,
        update_time: str = None,
    ):
        self.create_time = create_time
        self.owing_service = owing_service
        self.planned_delete_time = planned_delete_time
        self.secret_name = secret_name
        self.secret_type = secret_type
        self.tags = tags
        self.update_time = update_time

    def validate(self):
        if self.tags:
            self.tags.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.create_time is not None:
            result['CreateTime'] = self.create_time

        if self.owing_service is not None:
            result['OwingService'] = self.owing_service

        if self.planned_delete_time is not None:
            result['PlannedDeleteTime'] = self.planned_delete_time

        if self.secret_name is not None:
            result['SecretName'] = self.secret_name

        if self.secret_type is not None:
            result['SecretType'] = self.secret_type

        if self.tags is not None:
            result['Tags'] = self.tags.to_map()

        if self.update_time is not None:
            result['UpdateTime'] = self.update_time

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('CreateTime') is not None:
            self.create_time = m.get('CreateTime')

        if m.get('OwingService') is not None:
            self.owing_service = m.get('OwingService')

        if m.get('PlannedDeleteTime') is not None:
            self.planned_delete_time = m.get('PlannedDeleteTime')

        if m.get('SecretName') is not None:
            self.secret_name = m.get('SecretName')

        if m.get('SecretType') is not None:
            self.secret_type = m.get('SecretType')

        if m.get('Tags') is not None:
            temp_model = main_models.ListSecretsResponseBodySecretListSecretTags()
            self.tags = temp_model.from_map(m.get('Tags'))

        if m.get('UpdateTime') is not None:
            self.update_time = m.get('UpdateTime')

        return self

class ListSecretsResponseBodySecretListSecretTags(DaraModel):
    def __init__(
        self,
        tag: List[main_models.ListSecretsResponseBodySecretListSecretTagsTag] = None,
    ):
        self.tag = tag

    def validate(self):
        if self.tag:
            for v1 in self.tag:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['Tag'] = []
        if self.tag is not None:
            for k1 in self.tag:
                result['Tag'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.tag = []
        if m.get('Tag') is not None:
            for k1 in m.get('Tag'):
                temp_model = main_models.ListSecretsResponseBodySecretListSecretTagsTag()
                self.tag.append(temp_model.from_map(k1))

        return self

class ListSecretsResponseBodySecretListSecretTagsTag(DaraModel):
    def __init__(
        self,
        tag_key: str = None,
        tag_value: str = None,
    ):
        self.tag_key = tag_key
        self.tag_value = tag_value

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.tag_key is not None:
            result['TagKey'] = self.tag_key

        if self.tag_value is not None:
            result['TagValue'] = self.tag_value

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('TagKey') is not None:
            self.tag_key = m.get('TagKey')

        if m.get('TagValue') is not None:
            self.tag_value = m.get('TagValue')

        return self

