# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_aiccs20191015 import models as main_models
from darabonba.model import DaraModel

class ListAvailableTtsResponseBody(DaraModel):
    def __init__(
        self,
        access_denied_detail: str = None,
        code: str = None,
        data: List[main_models.ListAvailableTtsResponseBodyData] = None,
        message: str = None,
        request_id: str = None,
        success: bool = None,
    ):
        # Details about the access denial. The system returns this parameter only if a RAM permission check fails.
        self.access_denied_detail = access_denied_detail
        # The status code. `OK` indicates that the request was successful.
        self.code = code
        # A list of available TTS voices.
        self.data = data
        # The description of the status code.
        self.message = message
        # The request ID generated by Alibaba Cloud. You can use this ID to troubleshoot issues.
        self.request_id = request_id
        # Indicates whether the request was successful. Valid values:
        # 
        # - **true**: The request was successful.
        # 
        # - **false**: The request failed.
        self.success = success

    def validate(self):
        if self.data:
            for v1 in self.data:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.access_denied_detail is not None:
            result['AccessDeniedDetail'] = self.access_denied_detail

        if self.code is not None:
            result['Code'] = self.code

        result['Data'] = []
        if self.data is not None:
            for k1 in self.data:
                result['Data'].append(k1.to_map() if k1 else None)

        if self.message is not None:
            result['Message'] = self.message

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.success is not None:
            result['Success'] = self.success

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AccessDeniedDetail') is not None:
            self.access_denied_detail = m.get('AccessDeniedDetail')

        if m.get('Code') is not None:
            self.code = m.get('Code')

        self.data = []
        if m.get('Data') is not None:
            for k1 in m.get('Data'):
                temp_model = main_models.ListAvailableTtsResponseBodyData()
                self.data.append(temp_model.from_map(k1))

        if m.get('Message') is not None:
            self.message = m.get('Message')

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('Success') is not None:
            self.success = m.get('Success')

        return self

class ListAvailableTtsResponseBodyData(DaraModel):
    def __init__(
        self,
        tts_audition_file_url: str = None,
        tts_engine: str = None,
        tts_style: str = None,
        tts_voice_code: str = None,
        tts_voice_name: str = None,
        voice_type: str = None,
    ):
        # The URL for the voice audition file.
        self.tts_audition_file_url = tts_audition_file_url
        # The voice engine. Valid values:
        # 
        # - CosyVoice: A custom voice or a system voice.
        # 
        # - Volcano: A Doubao voice.
        self.tts_engine = tts_engine
        # The voice style.
        self.tts_style = tts_style
        # The voice code.
        self.tts_voice_code = tts_voice_code
        # The name of the TTS voice.
        self.tts_voice_name = tts_voice_name
        # The type of the TTS voice. Valid values:
        # 
        # `SYSTEM`: system voice.
        # 
        # `COSYCLONE`: cloned voice.
        # 
        # `BL-CUSTOM`: premium custom voice.
        self.voice_type = voice_type

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.tts_audition_file_url is not None:
            result['TtsAuditionFileUrl'] = self.tts_audition_file_url

        if self.tts_engine is not None:
            result['TtsEngine'] = self.tts_engine

        if self.tts_style is not None:
            result['TtsStyle'] = self.tts_style

        if self.tts_voice_code is not None:
            result['TtsVoiceCode'] = self.tts_voice_code

        if self.tts_voice_name is not None:
            result['TtsVoiceName'] = self.tts_voice_name

        if self.voice_type is not None:
            result['VoiceType'] = self.voice_type

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('TtsAuditionFileUrl') is not None:
            self.tts_audition_file_url = m.get('TtsAuditionFileUrl')

        if m.get('TtsEngine') is not None:
            self.tts_engine = m.get('TtsEngine')

        if m.get('TtsStyle') is not None:
            self.tts_style = m.get('TtsStyle')

        if m.get('TtsVoiceCode') is not None:
            self.tts_voice_code = m.get('TtsVoiceCode')

        if m.get('TtsVoiceName') is not None:
            self.tts_voice_name = m.get('TtsVoiceName')

        if m.get('VoiceType') is not None:
            self.voice_type = m.get('VoiceType')

        return self

