# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sophonsoar20220728 import models as main_models
from darabonba.model import DaraModel

class DescribePlaybooksResponseBody(DaraModel):
    def __init__(
        self,
        page: main_models.DescribePlaybooksResponseBodyPage = None,
        playbooks: List[main_models.DescribePlaybooksResponseBodyPlaybooks] = None,
        request_id: str = None,
    ):
        # The pagination information.
        self.page = page
        # The list of playbooks.
        self.playbooks = playbooks
        # The request ID. This ID is generated by Alibaba Cloud for the request and can be used to troubleshoot issues.
        self.request_id = request_id

    def validate(self):
        if self.page:
            self.page.validate()
        if self.playbooks:
            for v1 in self.playbooks:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.page is not None:
            result['Page'] = self.page.to_map()

        result['Playbooks'] = []
        if self.playbooks is not None:
            for k1 in self.playbooks:
                result['Playbooks'].append(k1.to_map() if k1 else None)

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Page') is not None:
            temp_model = main_models.DescribePlaybooksResponseBodyPage()
            self.page = temp_model.from_map(m.get('Page'))

        self.playbooks = []
        if m.get('Playbooks') is not None:
            for k1 in m.get('Playbooks'):
                temp_model = main_models.DescribePlaybooksResponseBodyPlaybooks()
                self.playbooks.append(temp_model.from_map(k1))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        return self

class DescribePlaybooksResponseBodyPlaybooks(DaraModel):
    def __init__(
        self,
        active: int = None,
        description: str = None,
        display_name: str = None,
        gmt_create: int = None,
        gmt_modified: str = None,
        last_runtime: int = None,
        own_type: str = None,
        param_type: str = None,
        playbook_uuid: str = None,
        tenant_id: str = None,
    ):
        # The status of the playbook. Valid values:
        # 
        # - **1**: The playbook is enabled.
        # 
        # - **0**: The playbook is disabled.
        self.active = active
        # The description of the playbook.
        self.description = description
        # The display name of the playbook.
        self.display_name = display_name
        # The time when the playbook was created. This value is a 13-digit timestamp.
        self.gmt_create = gmt_create
        # The time when the playbook was modified.
        self.gmt_modified = gmt_modified
        # The last time the playbook was run. This value is a 13-digit timestamp.
        self.last_runtime = last_runtime
        # The type of the playbook. Valid values:
        # 
        # - **preset**: predefined playbook.
        # 
        # - **user**: custom playbook.
        self.own_type = own_type
        # The trigger type of the playbook. Valid values:
        # 
        # - **template-incident**: security event.
        # 
        # - **template-ip**: IP entity.
        # 
        # - **template-file**: file entity.
        # 
        # - **template-process**: process entity.
        # 
        # - **template-alert**: security alert.
        # 
        # - **template-domain**: domain name entity.
        # 
        # - **template-container**: container entity.
        # 
        # - **template-host**: host entity.
        self.param_type = param_type
        # The UUID of the playbook.
        self.playbook_uuid = playbook_uuid
        # The ID of the user to which the playbook belongs.
        self.tenant_id = tenant_id

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.active is not None:
            result['Active'] = self.active

        if self.description is not None:
            result['Description'] = self.description

        if self.display_name is not None:
            result['DisplayName'] = self.display_name

        if self.gmt_create is not None:
            result['GmtCreate'] = self.gmt_create

        if self.gmt_modified is not None:
            result['GmtModified'] = self.gmt_modified

        if self.last_runtime is not None:
            result['LastRuntime'] = self.last_runtime

        if self.own_type is not None:
            result['OwnType'] = self.own_type

        if self.param_type is not None:
            result['ParamType'] = self.param_type

        if self.playbook_uuid is not None:
            result['PlaybookUuid'] = self.playbook_uuid

        if self.tenant_id is not None:
            result['TenantId'] = self.tenant_id

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Active') is not None:
            self.active = m.get('Active')

        if m.get('Description') is not None:
            self.description = m.get('Description')

        if m.get('DisplayName') is not None:
            self.display_name = m.get('DisplayName')

        if m.get('GmtCreate') is not None:
            self.gmt_create = m.get('GmtCreate')

        if m.get('GmtModified') is not None:
            self.gmt_modified = m.get('GmtModified')

        if m.get('LastRuntime') is not None:
            self.last_runtime = m.get('LastRuntime')

        if m.get('OwnType') is not None:
            self.own_type = m.get('OwnType')

        if m.get('ParamType') is not None:
            self.param_type = m.get('ParamType')

        if m.get('PlaybookUuid') is not None:
            self.playbook_uuid = m.get('PlaybookUuid')

        if m.get('TenantId') is not None:
            self.tenant_id = m.get('TenantId')

        return self

class DescribePlaybooksResponseBodyPage(DaraModel):
    def __init__(
        self,
        page_number: int = None,
        page_size: int = None,
        total_count: int = None,
    ):
        # The page number of the returned page.
        self.page_number = page_number
        # The number of entries returned per page.
        self.page_size = page_size
        # The total number of entries that match the query.
        self.total_count = total_count

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.page_number is not None:
            result['PageNumber'] = self.page_number

        if self.page_size is not None:
            result['PageSize'] = self.page_size

        if self.total_count is not None:
            result['TotalCount'] = self.total_count

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('PageNumber') is not None:
            self.page_number = m.get('PageNumber')

        if m.get('PageSize') is not None:
            self.page_size = m.get('PageSize')

        if m.get('TotalCount') is not None:
            self.total_count = m.get('TotalCount')

        return self

