# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_sophonsoar20220728 import models as main_models
from darabonba.model import DaraModel

class DescribeSoarRecordsResponseBody(DaraModel):
    def __init__(
        self,
        page: main_models.DescribeSoarRecordsResponseBodyPage = None,
        request_id: str = None,
        soar_execute_records: List[main_models.DescribeSoarRecordsResponseBodySoarExecuteRecords] = None,
    ):
        # Information displayed on the page.
        # 
        # This parameter is required.
        self.page = page
        # The ID of the current request, generated by Alibaba Cloud as a unique identifier for the request, which can be used for troubleshooting and problem localization.
        self.request_id = request_id
        # Execution record result set.
        self.soar_execute_records = soar_execute_records

    def validate(self):
        if self.page:
            self.page.validate()
        if self.soar_execute_records:
            for v1 in self.soar_execute_records:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.page is not None:
            result['Page'] = self.page.to_map()

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        result['SoarExecuteRecords'] = []
        if self.soar_execute_records is not None:
            for k1 in self.soar_execute_records:
                result['SoarExecuteRecords'].append(k1.to_map() if k1 else None)

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Page') is not None:
            temp_model = main_models.DescribeSoarRecordsResponseBodyPage()
            self.page = temp_model.from_map(m.get('Page'))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        self.soar_execute_records = []
        if m.get('SoarExecuteRecords') is not None:
            for k1 in m.get('SoarExecuteRecords'):
                temp_model = main_models.DescribeSoarRecordsResponseBodySoarExecuteRecords()
                self.soar_execute_records.append(temp_model.from_map(k1))

        return self

class DescribeSoarRecordsResponseBodySoarExecuteRecords(DaraModel):
    def __init__(
        self,
        end_time: int = None,
        error_msg: str = None,
        output_list: List[main_models.DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList] = None,
        raw_event_req: str = None,
        request_uuid: str = None,
        start_time: int = None,
        status: str = None,
        task_name: str = None,
        taskflow_md_5: str = None,
        trigger_type: str = None,
        trigger_user: str = None,
    ):
        # The end time of the component execution, in 13-digit timestamp format.
        self.end_time = end_time
        # The error message of the playbook task. This field is empty when the task succeeds.
        self.error_msg = error_msg
        self.output_list = output_list
        # The request parameters of the playbook task.
        self.raw_event_req = raw_event_req
        # The request ID of the playbook task, a unique ID for each task run.
        self.request_uuid = request_uuid
        # The start time of the task execution, in 13-digit timestamp format.
        self.start_time = start_time
        # The status of the playbook task. Values:
        # 
        # - **success**: Indicates successful execution.
        # - **fail**: Indicates failed execution.
        # - **running**: Indicates the task is running
        self.status = status
        # The name of the playbook task, which is the same as the playbook\\"s UUID.
        self.task_name = task_name
        # The MD5 value of the playbook configuration.
        self.taskflow_md_5 = taskflow_md_5
        # The type of the playbook task. Values:
        # 
        # - **debug**: Indicates a debugging task.
        # - **manual**: Indicates a manual task.
        # - **siem**: Indicates a task triggered by an event or alert.
        self.trigger_type = trigger_type
        # The Alibaba Cloud account ID that executes the playbook task.
        self.trigger_user = trigger_user

    def validate(self):
        if self.output_list:
            for v1 in self.output_list:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.end_time is not None:
            result['EndTime'] = self.end_time

        if self.error_msg is not None:
            result['ErrorMsg'] = self.error_msg

        result['OutputList'] = []
        if self.output_list is not None:
            for k1 in self.output_list:
                result['OutputList'].append(k1.to_map() if k1 else None)

        if self.raw_event_req is not None:
            result['RawEventReq'] = self.raw_event_req

        if self.request_uuid is not None:
            result['RequestUuid'] = self.request_uuid

        if self.start_time is not None:
            result['StartTime'] = self.start_time

        if self.status is not None:
            result['Status'] = self.status

        if self.task_name is not None:
            result['TaskName'] = self.task_name

        if self.taskflow_md_5 is not None:
            result['TaskflowMd5'] = self.taskflow_md_5

        if self.trigger_type is not None:
            result['TriggerType'] = self.trigger_type

        if self.trigger_user is not None:
            result['TriggerUser'] = self.trigger_user

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('EndTime') is not None:
            self.end_time = m.get('EndTime')

        if m.get('ErrorMsg') is not None:
            self.error_msg = m.get('ErrorMsg')

        self.output_list = []
        if m.get('OutputList') is not None:
            for k1 in m.get('OutputList'):
                temp_model = main_models.DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList()
                self.output_list.append(temp_model.from_map(k1))

        if m.get('RawEventReq') is not None:
            self.raw_event_req = m.get('RawEventReq')

        if m.get('RequestUuid') is not None:
            self.request_uuid = m.get('RequestUuid')

        if m.get('StartTime') is not None:
            self.start_time = m.get('StartTime')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('TaskName') is not None:
            self.task_name = m.get('TaskName')

        if m.get('TaskflowMd5') is not None:
            self.taskflow_md_5 = m.get('TaskflowMd5')

        if m.get('TriggerType') is not None:
            self.trigger_type = m.get('TriggerType')

        if m.get('TriggerUser') is not None:
            self.trigger_user = m.get('TriggerUser')

        return self

class DescribeSoarRecordsResponseBodySoarExecuteRecordsOutputList(DaraModel):
    def __init__(
        self,
        action_uuid: str = None,
        content: str = None,
        node_name: str = None,
    ):
        self.action_uuid = action_uuid
        self.content = content
        self.node_name = node_name

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.action_uuid is not None:
            result['ActionUuid'] = self.action_uuid

        if self.content is not None:
            result['Content'] = self.content

        if self.node_name is not None:
            result['NodeName'] = self.node_name

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('ActionUuid') is not None:
            self.action_uuid = m.get('ActionUuid')

        if m.get('Content') is not None:
            self.content = m.get('Content')

        if m.get('NodeName') is not None:
            self.node_name = m.get('NodeName')

        return self

class DescribeSoarRecordsResponseBodyPage(DaraModel):
    def __init__(
        self,
        page_number: int = None,
        page_size: int = None,
        total_count: int = None,
    ):
        # The current page number in paginated queries.
        self.page_number = page_number
        # The number of items per page in paginated queries.
        self.page_size = page_size
        # The total number of queried items.
        self.total_count = total_count

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.page_number is not None:
            result['PageNumber'] = self.page_number

        if self.page_size is not None:
            result['PageSize'] = self.page_size

        if self.total_count is not None:
            result['TotalCount'] = self.total_count

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('PageNumber') is not None:
            self.page_number = m.get('PageNumber')

        if m.get('PageSize') is not None:
            self.page_size = m.get('PageSize')

        if m.get('TotalCount') is not None:
            self.total_count = m.get('TotalCount')

        return self

