# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from typing import List

from alibabacloud_waf_openapi20211001 import models as main_models
from darabonba.model import DaraModel

class DescribeCloudResourceAccessPortDetailsResponseBody(DaraModel):
    def __init__(
        self,
        access_port_details: List[main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails] = None,
        request_id: str = None,
        total_count: int = None,
    ):
        # The details of the ports for the cloud service instance that is added to WAF.
        self.access_port_details = access_port_details
        # The request ID.
        self.request_id = request_id
        # The total number of entries returned.
        self.total_count = total_count

    def validate(self):
        if self.access_port_details:
            for v1 in self.access_port_details:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['AccessPortDetails'] = []
        if self.access_port_details is not None:
            for k1 in self.access_port_details:
                result['AccessPortDetails'].append(k1.to_map() if k1 else None)

        if self.request_id is not None:
            result['RequestId'] = self.request_id

        if self.total_count is not None:
            result['TotalCount'] = self.total_count

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.access_port_details = []
        if m.get('AccessPortDetails') is not None:
            for k1 in m.get('AccessPortDetails'):
                temp_model = main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails()
                self.access_port_details.append(temp_model.from_map(k1))

        if m.get('RequestId') is not None:
            self.request_id = m.get('RequestId')

        if m.get('TotalCount') is not None:
            self.total_count = m.get('TotalCount')

        return self

class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetails(DaraModel):
    def __init__(
        self,
        certificates: List[main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates] = None,
        cipher_suite: int = None,
        cloud_resource_id: str = None,
        custom_ciphers: List[str] = None,
        enable_tlsv_3: bool = None,
        http_2enabled: bool = None,
        keepalive: bool = None,
        keepalive_requests: int = None,
        keepalive_timeout: int = None,
        log_headers: List[main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders] = None,
        max_body_size: int = None,
        owner_user_id: str = None,
        port: int = None,
        protocol: str = None,
        read_timeout: int = None,
        status: int = None,
        sub_status: str = None,
        sub_status_details: List[main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails] = None,
        tlsversion: str = None,
        write_timeout: int = None,
        xff_header_mode: int = None,
        xff_headers: List[str] = None,
        xff_proto: bool = None,
    ):
        # The list of certificates for the port of the cloud service instance.
        self.certificates = certificates
        # The type of the cipher suite. Valid values:
        # 
        # - **1**: all cipher suites.
        # 
        # - **2**: strong cipher suites.
        # 
        # - **99**: custom cipher suites.
        self.cipher_suite = cipher_suite
        # The ID of the resource that is added to WAF. The ID is automatically generated by WAF.
        self.cloud_resource_id = cloud_resource_id
        # The custom cipher suites. This parameter is returned only when **CipherSuite** is set to **99**.
        self.custom_ciphers = custom_ciphers
        # Indicates whether TLS 1.3 is supported. Valid values:
        # 
        # - **true**: TLS 1.3 is supported.
        # 
        # - **false**: TLS 1.3 is not supported.
        self.enable_tlsv_3 = enable_tlsv_3
        # Indicates whether HTTP/2 is enabled. Valid values:
        # 
        # - **true**: HTTP/2 is enabled.
        # 
        # - **false**: HTTP/2 is not enabled.
        self.http_2enabled = http_2enabled
        # Indicates whether to enable persistent connections. Valid values:
        # 
        # - **true**: Enables persistent connections. This is the default value.
        # 
        # - **false**: Disables persistent connections.
        self.keepalive = keepalive
        # The number of requests that can be reused in a persistent connection. Valid values: 60 to 1000.
        # 
        # > This parameter specifies the number of requests that can be reused after a persistent connection is established.
        self.keepalive_requests = keepalive_requests
        # The timeout period for an idle persistent connection. Valid values: 10 to 3600. Default value: 15. Unit: seconds.
        # 
        # > This parameter specifies the period of time after which an idle persistent connection is released.
        self.keepalive_timeout = keepalive_timeout
        # The key-value pair that is used to tag the traffic that is processed by WAF.
        # 
        # > This parameter is returned only when the traffic tagging feature is enabled for the domain name.
        self.log_headers = log_headers
        # The maximum size of a request body. Valid values: 2 to 10. Default value: 2. Unit: GB.
        self.max_body_size = max_body_size
        # The ID of the Alibaba Cloud account to which the cloud service belongs.
        self.owner_user_id = owner_user_id
        # The port of the cloud service that is added to WAF.
        self.port = port
        # The protocol. Valid values:
        # 
        # - **http**: HTTP.
        # 
        # - **https**: HTTPS.
        self.protocol = protocol
        # The read timeout period. Unit: seconds. Valid values: 1 to 3600.
        self.read_timeout = read_timeout
        # The status of the domain name. Valid values:
        # 
        # - **1**: The port is in the Normal state.
        # 
        # - **2**: The port is being created.
        # 
        # - **3**: The port is being modified.
        # 
        # - **4**: The port is being released.
        self.status = status
        # The abnormal protection status. Valid values:
        # 
        # - **InvalidCert**: The certificate is invalid.
        # 
        # - **ClientCertOpend**: Mutual authentication is enabled.
        # 
        # - **NetworkConfigLost**: The network configuration of the cloud service is abnormal.
        self.sub_status = sub_status
        # The details of the abnormal protection status. This parameter is returned only when **SubStatus** is set to InvalidCert.
        self.sub_status_details = sub_status_details
        # The version of the Transport Layer Security (TLS) protocol. Valid values:
        # 
        # - **tlsv1**
        # 
        # - **tlsv1.1**
        # 
        # - **tlsv1.2**
        self.tlsversion = tlsversion
        # The write timeout period. Unit: seconds. Valid values: 1 to 3600.
        self.write_timeout = write_timeout
        # The mode that WAF uses to obtain the real IP address of a client. Valid values:
        # 
        # - **0**: WAF is the first Layer 7 proxy before client traffic is forwarded to the origin server.
        # 
        # - **1**: WAF reads the first IP address from the X-Forwarded-For (XFF) header as the client IP address.
        # 
        # - **2**: WAF reads the value of a custom header as the client IP address.
        self.xff_header_mode = xff_header_mode
        # The custom header fields that are used to obtain the client IP address. The value is a string in the `["header1","header2",...]` format.
        # 
        # > This parameter is returned only when **XffHeaderMode** is set to 2.
        self.xff_headers = xff_headers
        # Indicates whether to use the X-Forwarded-For-Proto header to identify the protocol used by WAF. Valid values:
        # 
        # - **true**: Identifies the protocol used by WAF. This is the default value.
        # 
        # - **false**: Does not identify the protocol used by WAF.
        self.xff_proto = xff_proto

    def validate(self):
        if self.certificates:
            for v1 in self.certificates:
                 if v1:
                    v1.validate()
        if self.log_headers:
            for v1 in self.log_headers:
                 if v1:
                    v1.validate()
        if self.sub_status_details:
            for v1 in self.sub_status_details:
                 if v1:
                    v1.validate()

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        result['Certificates'] = []
        if self.certificates is not None:
            for k1 in self.certificates:
                result['Certificates'].append(k1.to_map() if k1 else None)

        if self.cipher_suite is not None:
            result['CipherSuite'] = self.cipher_suite

        if self.cloud_resource_id is not None:
            result['CloudResourceId'] = self.cloud_resource_id

        if self.custom_ciphers is not None:
            result['CustomCiphers'] = self.custom_ciphers

        if self.enable_tlsv_3 is not None:
            result['EnableTLSv3'] = self.enable_tlsv_3

        if self.http_2enabled is not None:
            result['Http2Enabled'] = self.http_2enabled

        if self.keepalive is not None:
            result['Keepalive'] = self.keepalive

        if self.keepalive_requests is not None:
            result['KeepaliveRequests'] = self.keepalive_requests

        if self.keepalive_timeout is not None:
            result['KeepaliveTimeout'] = self.keepalive_timeout

        result['LogHeaders'] = []
        if self.log_headers is not None:
            for k1 in self.log_headers:
                result['LogHeaders'].append(k1.to_map() if k1 else None)

        if self.max_body_size is not None:
            result['MaxBodySize'] = self.max_body_size

        if self.owner_user_id is not None:
            result['OwnerUserId'] = self.owner_user_id

        if self.port is not None:
            result['Port'] = self.port

        if self.protocol is not None:
            result['Protocol'] = self.protocol

        if self.read_timeout is not None:
            result['ReadTimeout'] = self.read_timeout

        if self.status is not None:
            result['Status'] = self.status

        if self.sub_status is not None:
            result['SubStatus'] = self.sub_status

        result['SubStatusDetails'] = []
        if self.sub_status_details is not None:
            for k1 in self.sub_status_details:
                result['SubStatusDetails'].append(k1.to_map() if k1 else None)

        if self.tlsversion is not None:
            result['TLSVersion'] = self.tlsversion

        if self.write_timeout is not None:
            result['WriteTimeout'] = self.write_timeout

        if self.xff_header_mode is not None:
            result['XffHeaderMode'] = self.xff_header_mode

        if self.xff_headers is not None:
            result['XffHeaders'] = self.xff_headers

        if self.xff_proto is not None:
            result['XffProto'] = self.xff_proto

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        self.certificates = []
        if m.get('Certificates') is not None:
            for k1 in m.get('Certificates'):
                temp_model = main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates()
                self.certificates.append(temp_model.from_map(k1))

        if m.get('CipherSuite') is not None:
            self.cipher_suite = m.get('CipherSuite')

        if m.get('CloudResourceId') is not None:
            self.cloud_resource_id = m.get('CloudResourceId')

        if m.get('CustomCiphers') is not None:
            self.custom_ciphers = m.get('CustomCiphers')

        if m.get('EnableTLSv3') is not None:
            self.enable_tlsv_3 = m.get('EnableTLSv3')

        if m.get('Http2Enabled') is not None:
            self.http_2enabled = m.get('Http2Enabled')

        if m.get('Keepalive') is not None:
            self.keepalive = m.get('Keepalive')

        if m.get('KeepaliveRequests') is not None:
            self.keepalive_requests = m.get('KeepaliveRequests')

        if m.get('KeepaliveTimeout') is not None:
            self.keepalive_timeout = m.get('KeepaliveTimeout')

        self.log_headers = []
        if m.get('LogHeaders') is not None:
            for k1 in m.get('LogHeaders'):
                temp_model = main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders()
                self.log_headers.append(temp_model.from_map(k1))

        if m.get('MaxBodySize') is not None:
            self.max_body_size = m.get('MaxBodySize')

        if m.get('OwnerUserId') is not None:
            self.owner_user_id = m.get('OwnerUserId')

        if m.get('Port') is not None:
            self.port = m.get('Port')

        if m.get('Protocol') is not None:
            self.protocol = m.get('Protocol')

        if m.get('ReadTimeout') is not None:
            self.read_timeout = m.get('ReadTimeout')

        if m.get('Status') is not None:
            self.status = m.get('Status')

        if m.get('SubStatus') is not None:
            self.sub_status = m.get('SubStatus')

        self.sub_status_details = []
        if m.get('SubStatusDetails') is not None:
            for k1 in m.get('SubStatusDetails'):
                temp_model = main_models.DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails()
                self.sub_status_details.append(temp_model.from_map(k1))

        if m.get('TLSVersion') is not None:
            self.tlsversion = m.get('TLSVersion')

        if m.get('WriteTimeout') is not None:
            self.write_timeout = m.get('WriteTimeout')

        if m.get('XffHeaderMode') is not None:
            self.xff_header_mode = m.get('XffHeaderMode')

        if m.get('XffHeaders') is not None:
            self.xff_headers = m.get('XffHeaders')

        if m.get('XffProto') is not None:
            self.xff_proto = m.get('XffProto')

        return self

class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsSubStatusDetails(DaraModel):
    def __init__(
        self,
        applied_type: str = None,
        cert_id: str = None,
        cert_name: str = None,
        common_name: str = None,
        domain: str = None,
        expire_time: int = None,
        product_cert_id: str = None,
        product_cert_name: str = None,
        reason_code: str = None,
    ):
        # The type of the certificate for the HTTPS protocol. Valid values:
        # 
        # - **default**: the default certificate.
        # 
        # - **extension**: the additional certificate.
        self.applied_type = applied_type
        # The ID of the certificate in Certificates Management Service.
        self.cert_id = cert_id
        # The name of the certificate in Certificates Management Service.
        self.cert_name = cert_name
        # The common name (CN).
        self.common_name = common_name
        # The domain name that is bound to the certificate.
        self.domain = domain
        # The expiration time of the certificate. The value is a UNIX timestamp. Unit: seconds.
        self.expire_time = expire_time
        # The ID of the certificate that is saved for the cloud service.
        self.product_cert_id = product_cert_id
        # The name of the certificate that is saved for the cloud service.
        self.product_cert_name = product_cert_name
        # The reason for the abnormal protection status. Valid values:
        # 
        # - **UserUploadCert**: The certificate is manually uploaded.
        # 
        # - **CertNotExistInCertCenter**: The certificate does not exist in Certificates Management Service.
        # 
        # - **CertExpired**: The certificate has expired.
        # 
        # - **EmptyCertCN**: The CN of the certificate is empty.
        self.reason_code = reason_code

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.applied_type is not None:
            result['AppliedType'] = self.applied_type

        if self.cert_id is not None:
            result['CertId'] = self.cert_id

        if self.cert_name is not None:
            result['CertName'] = self.cert_name

        if self.common_name is not None:
            result['CommonName'] = self.common_name

        if self.domain is not None:
            result['Domain'] = self.domain

        if self.expire_time is not None:
            result['ExpireTime'] = self.expire_time

        if self.product_cert_id is not None:
            result['ProductCertId'] = self.product_cert_id

        if self.product_cert_name is not None:
            result['ProductCertName'] = self.product_cert_name

        if self.reason_code is not None:
            result['ReasonCode'] = self.reason_code

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AppliedType') is not None:
            self.applied_type = m.get('AppliedType')

        if m.get('CertId') is not None:
            self.cert_id = m.get('CertId')

        if m.get('CertName') is not None:
            self.cert_name = m.get('CertName')

        if m.get('CommonName') is not None:
            self.common_name = m.get('CommonName')

        if m.get('Domain') is not None:
            self.domain = m.get('Domain')

        if m.get('ExpireTime') is not None:
            self.expire_time = m.get('ExpireTime')

        if m.get('ProductCertId') is not None:
            self.product_cert_id = m.get('ProductCertId')

        if m.get('ProductCertName') is not None:
            self.product_cert_name = m.get('ProductCertName')

        if m.get('ReasonCode') is not None:
            self.reason_code = m.get('ReasonCode')

        return self

class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsLogHeaders(DaraModel):
    def __init__(
        self,
        key: str = None,
        value: str = None,
    ):
        # The custom request header field.
        self.key = key
        # The value of the custom request header field.
        self.value = value

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.key is not None:
            result['Key'] = self.key

        if self.value is not None:
            result['Value'] = self.value

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Key') is not None:
            self.key = m.get('Key')

        if m.get('Value') is not None:
            self.value = m.get('Value')

        return self

class DescribeCloudResourceAccessPortDetailsResponseBodyAccessPortDetailsCertificates(DaraModel):
    def __init__(
        self,
        applied_type: str = None,
        certificate_id: str = None,
        certificate_name: str = None,
    ):
        # The type of the certificate for the HTTPS protocol. Valid values:
        # 
        # - **default**: the default certificate.
        # 
        # - **extension**: the additional certificate.
        self.applied_type = applied_type
        # The ID of the added certificate.
        self.certificate_id = certificate_id
        # The name of the certificate.
        self.certificate_name = certificate_name

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.applied_type is not None:
            result['AppliedType'] = self.applied_type

        if self.certificate_id is not None:
            result['CertificateId'] = self.certificate_id

        if self.certificate_name is not None:
            result['CertificateName'] = self.certificate_name

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('AppliedType') is not None:
            self.applied_type = m.get('AppliedType')

        if m.get('CertificateId') is not None:
            self.certificate_id = m.get('CertificateId')

        if m.get('CertificateName') is not None:
            self.certificate_name = m.get('CertificateName')

        return self

