# -*- coding: utf-8 -*-
# This file is auto-generated, don't edit it. Thanks.
from __future__ import annotations

from darabonba.model import DaraModel

class SwitchVariableRequest(DaraModel):
    def __init__(
        self,
        lang: str = None,
        data_version: int = None,
        id: int = None,
        name: str = None,
        reg_id: str = None,
        status: str = None,
    ):
        # The language type for requests and responses. Default value: **zh**. Valid values:
        # - **zh**: Chinese
        # - **en**: English
        self.lang = lang
        # The data version.
        self.data_version = data_version
        # The primary key ID of the cumulative variable.
        self.id = id
        # The name of the cumulative variable, which is generated by the backend.
        self.name = name
        # The region ID.
        self.reg_id = reg_id
        # The status.
        self.status = status

    def validate(self):
        pass

    def to_map(self):
        result = dict()
        _map = super().to_map()
        if _map is not None:
            result = _map
        if self.lang is not None:
            result['Lang'] = self.lang

        if self.data_version is not None:
            result['dataVersion'] = self.data_version

        if self.id is not None:
            result['id'] = self.id

        if self.name is not None:
            result['name'] = self.name

        if self.reg_id is not None:
            result['regId'] = self.reg_id

        if self.status is not None:
            result['status'] = self.status

        return result

    def from_map(self, m: dict = None):
        m = m or dict()
        if m.get('Lang') is not None:
            self.lang = m.get('Lang')

        if m.get('dataVersion') is not None:
            self.data_version = m.get('dataVersion')

        if m.get('id') is not None:
            self.id = m.get('id')

        if m.get('name') is not None:
            self.name = m.get('name')

        if m.get('regId') is not None:
            self.reg_id = m.get('regId')

        if m.get('status') is not None:
            self.status = m.get('status')

        return self

